### PR TITLE
Fix odo log flake

### LINKED ISSUE #3610: odo log -f terminates earlier
/kind bug
/kind flake

## What versions of software are you using?

**Operating System:**
supported
**Output of `odo version`:**
master
## How did you run odo exactly?
This is hit in the CI. You can also reproduce it locally by running the spec (keep trying until you reproduce it)

Spec : https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_log_test.go#L51

CI failure at line : https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/3601/pull-ci-openshift-odo-master-v4.2-integration-e2e/1285441618282811392#1:build-log.txt%3A94332

## Actual behavior
```
 Running odo with args [odo log -f]
[odo] I0721 07:11:31.820487    6939 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
[odo] I0721 07:11:31.820763    6939 preference.go:196] The path for preference file is /tmp/187530165/config.yaml 
```

## Expected behavior
```program=devrun``` should be listed in the log output

## Any logs, error output, etc?
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/3601/pull-ci-openshift-odo-master-v4.2-integration-e2e/1285441618282811392#1:build-log.txt%3A94345

### PR DESCRIPTION
**Pull request by adisky**
**What type of PR is this?**

/kind flake

**What does does this PR do / why we need it**:
Fixes the flag for `odo log -f` test. This PR updates the test to check the log until expected log is printed and timeout if it doesn't gets logged in specified timeout duration.

**Which issue(s) this PR fixes**:

Fixes #3610

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

File: tests/helper/helper_generic.go [hunk 1]
```diff
@@ -177,6 +179,63 @@ func WatchNonRetCmdStdOut(cmdStr string, timeout time.Duration, check func(outpu
 	}
 }
 
+// RunCmdWithMatchOutputFromBuffer starts the command, and command stdout is attached to buffer.
+// we read data from buffer line by line, and if expected string is matched it returns true
+// It is different from WaitforCmdOut which gives stdout in one go using session.Out.Contents()
+// for commands like odo log -f which streams continuous data and does not terminate by their own
+// we need to read the stream data from buffer.
+func RunCmdWithMatchOutputFromBuffer(timeoutAfter time.Duration, matchString, program string, args ...string) (bool, error) {
```
Comment (amitkrout) [inline tests/helper/helper_generic.go:187]: +100

File: tests/integration/devfile/cmd_devfile_log_test.go [hunk 2]
```diff
@@ -58,9 +58,10 @@ var _ = Describe("odo devfile log command tests", func() {
 			output := helper.CmdShouldPass("odo", "log")
 			Expect(output).To(ContainSubstring("ODO_COMMAND_RUN"))
 
-			// test with follow flag
-			output = helper.CmdShouldRunWithTimeout(1*time.Second, "odo", "log", "-f")
-			Expect(output).To(ContainSubstring("program=devrun"))
+			// Test odo log -f
+			match, err := helper.RunCmdWithMatchOutputFromBuffer(30*time.Second, "program=devrun", "odo", "log", "-f")
```
Comment (prietyc123) [inline tests/integration/devfile/cmd_devfile_log_test.go:62]: +1

File: tests/helper/helper_generic.go (hunk 1 above)
Comment (prietyc123) [inline tests/helper/helper_generic.go:187]: I was thinking instead of overloading helper file, Can't we use gingko in-build timeout for this - https://onsi.github.io/ginkgo/#asynchronous-tests

Comment (adisky) [reply tests/helper/helper_generic.go:187]: @prietyc123 I follow the pattern from `odo watch` tests, timeout we are using this way only. I agree with your concern, once you update some other tests with ` gingko in-build` pattern as an example, i would follow the same.

File: tests/helper/helper_generic.go [hunk 3]
```diff
@@ -177,6 +179,63 @@ func WatchNonRetCmdStdOut(cmdStr string, timeout time.Duration, check func(outpu
...
+	var buf bytes.Buffer
+
+	command := exec.Command(program, args...)
+	command.Stdout = &buf
+
```
Comment (mik-dass) [inline tests/helper/helper_generic.go:192]: I think we should also check the StdErr stream. In case of the timeout, we can print the contents from the error buffer. It will help in debugging in case the command fails to stream.

File: tests/helper/helper_generic.go (hunk 1 above)
Comment (mik-dass) [inline tests/helper/helper_generic.go:187]: can we use Eventually instead like in this PR https://github.com/openshift/odo/pull/3619/files#diff-66f499c995fc950f403a939757588820R104?

Comment (adisky) [reply tests/helper/helper_generic.go:187]: as mentioned in comments also, we cannot use `session.Out.Contents()`, it waits for command to run completely then give its all contents, `odo log -f` commands never terminates on its own, to have logs streaming it has to be running so have attached a buffer which streams logs from command output

File: tests/helper/helper_generic.go (hunk 3 above)
Comment (adisky) [reply tests/helper/helper_generic.go:193]: done

File: tests/helper/helper_generic.go (hunk 1 above)
Comment (mik-dass) [reply tests/helper/helper_generic.go:187]: OK :+1:

File: tests/helper/helper_generic.go (hunk 3 above)
Comment (mik-dass) [reply tests/helper/helper_generic.go:193]: I think it's better to use a different buffer for the error stream like in case of the watch test.

Comment (adisky) [reply tests/helper/helper_generic.go:193]: done

**Comment by mik-dass** [comment]
```

• Failure [342.243 seconds]
odo devfile watch command tests
/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:15
  when executing odo watch after odo push with debug flag
  /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:124
    should be able to start a debug session after push with debug flag using odo watch and revert back after normal push [It]
    /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:125
    Timeout after 5.00 minutes
```
/retest

File: tests/helper/helper_generic.go [hunk 4]
```diff
@@ -177,6 +179,66 @@ func WatchNonRetCmdStdOut(cmdStr string, timeout time.Duration, check func(outpu
...
+				}
+			}
+		}
+	}()
+
+	for {
+		select {
+		case <-timeoutCh:
+			fmt.Fprintln(GinkgoWriter, errBuf.String())
+			return false, errors.New("Timeout waiting for the conditon")
```
Comment (cdrage) [inline tests/helper/helper_generic.go:231]: no capitalization on errors

**Comment by adisky** [comment]
/retest
```
odo devfile watch command tests
/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:20
  when executing odo watch after odo push with debug flag
  /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:185
    should be able to start a debug session after push with debug flag using odo watch and revert back after normal push
    /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:186
------------------------------
•••••••••••••••••••••••••••••••••••••••••••••••••
	 -------------------------------------------------------------------
	|                                                                   |
	|  Ginkgo timed out waiting for all parallel nodes to report back!  |
	|                                                                   |
	 -------------------------------------------------------------------
 devfile timed out. path: ./tests/integration/devfile
```
