### PR TITLE
Replace "nightly" tag with "next" in some integration tests devfiles

### LINKED ISSUE #5027: Tests try to pull unknown image
/kind bug

When running integration tests, some devfiles define an image that cannot be found anymore.

## Actual behavior

```
  Warning  Failed          13s                kubelet            Failed to pull image "quay.io/eclipse/che-java11-maven:nightly": rpc error: code = Unknown desc = Error reading manifest nightly in quay.io/eclipse/che-java11-maven: unknown: Tag nightly was deleted or has expired. To pull, revive via time machine
```

### PR DESCRIPTION
**Pull request by feloy**
/kind bug

**What does this PR do / why we need it**:

Some integration tests were using devfiles defining images non existing anymore: `quay.io/eclipse/che-java11-maven:nightly` and `quay.io/eclipse/che-nodejs10-ubi:nightly`.

Also, use JustBeforeEach instead of BeforeSuite to set the Registry preference, as GLOBALODOCONFIG is set on a BeforeEach block, in the `debug` directory`.

It is not possible to use `JustBeforeEach` on the `devfile` directory, as it is not executed fotr the following tests:

```
Context("devfile is modified", func() {
		// Tests https://github.com/openshift/odo/issues/3838
		ensureFilesSyncedTest := func(namespace string, shouldForcePush bool) {
                            [...]
                }

		Context("odo push -f is executed", func() {
			ensureFilesSyncedTest(commonVar.Project, true)
		})
		Context("odo push (without -f) is executed", func() {
			ensureFilesSyncedTest(commonVar.Project, false)
		})
	})
```

**Which issue(s) this PR fixes**:

Fixes #5027 

See https://github.com/devfile/registry/pull/67

See also https://github.com/eclipse/che/issues/19905

### CODE REVIEW

**Comment by valaparthvi** [comment]
/retest-required
Now that https://github.com/devfile/registry/pull/67 is merged, we should stop seeing these failures - 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/5028/pull-ci-openshift-odo-main-v4.8-integration-e2e/1432258149242376192

**Comment by feloy** [comment]
@valaparthvi  we still need to wait for the images to be deployed to the registry, on wednesday 12pm EST (https://github.com/devfile/registry#registry)

**Comment by dharmit** [comment]
> /retest-required

Because all the six failures are due to below error:
```sh
[odo]  NAME                                          COUNT  REASON  MESSAGE                 
[odo] 
[odo]  qwhwor-app-5bd6db66c4-gpgq5.16a06244ab6a97a3  5      Failed  Error: ImagePullBackOff 
[odo] 
[odo] 
```
which is because the images weren't available (https://github.com/openshift/odo/pull/5028#issuecomment-909160571), right?

**Review by dharmit — APPROVED** [review]

**Comment by feloy** [comment]
@prietyc123  When running directly:
```
odo create java-springboot
```

I get the new devfile with the image `quay.io/eclipse/che-java11-maven:next`

But when running with ginkgo:

```
	When("create java-springboot", func() {
		It("should pass", func() {
			helper.Cmd("odo", "create", "java-springboot").ShouldPass()
			helper.Cmd("odo", "push").ShouldPass()
		})
	})
```

I get the old version of the devfile, with the image `quay.io/eclipse/che-java11-maven:nightly`

Do you have an idea what could happen? I cannot see any cache involved.

File: tests/integration/devfile/cmd_devfile_catalog_test.go [hunk 1]
```diff
@@ -22,6 +22,7 @@ var _ = Describe("odo devfile catalog command tests", func() {
 		// odo catalog list components.
 		// TODO: Investigate this more.
 		helper.Cmd("odo", "preference", "set", "registrycachetime", "0").ShouldPass()
+		helper.SetDefaultDevfileRegistryAsStaging()
```
Comment (valaparthvi) [inline tests/integration/devfile/cmd_devfile_catalog_test.go:25]: Why have you explicitly set this for this test and the one below? Why not for all?

Comment (feloy) [reply tests/integration/devfile/cmd_devfile_catalog_test.go:25]: It was originally on the BeforeSuite, but it should be executed after helper.CommonBeforeEach(), because we set GLOBALODOCONFIG in it. 
So we need to execute it in each top level BeforeEach of the `devfile` directory

Comment (feloy) [reply tests/integration/devfile/cmd_devfile_catalog_test.go:25]: Because CommonBeforeEach is called for all tests, not only the ones related to devfiles. There would probably not be a problem, but I would prefer not to.

**Comment by valaparthvi** [comment]
/lgtm
CI is green.
