### PR TITLE
Fixing no such file or directory issue

### LINKED ISSUE #2184: [Flake] component create in a directory with numeric name
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`: master

## How did you run odo exactly?
see CI failure steps - https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2166/pull-ci-openshift-odo-master-v4.2-integration/281#0:build-log.txt%3A5106
```
• Failure [80.116 seconds]
odo sub component command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_sub_test.go:13
  Creating component with numeric named context
  /go/src/github.com/openshift/odo/tests/integration/component.go:579
    should create default named component in a directory with numeric name []
    /go/src/github.com/openshift/odo/tests/integration/component.go:596
     Unexpected error:
      
        <*os.PathError | 0xc0000ad650>: {Op: "chdir", Path: "", Err: 0x2}
        chdir : no such file or directory
    occurred
     /go/src/github.com/openshift/odo/tests/helper/helper_filesystem.go:42
```
## Actual behavior
scenario failing

## Expected behavior
should pass

### PR DESCRIPTION
**Pull request by amitkrout**
## What is the purpose of this change? What does it change?

Fixing ```no such file or directory``` issue for scenario https://github.com/openshift/odo/blob/master/tests/integration/component.go#L579
## Was the change discussed in an issue?
fixes #2184 

## How to test changes?

make test-cmd-cmp

### CODE REVIEW

File: tests/integration/component.go [hunk 1]
```diff
@@ -583,13 +583,10 @@ func componentTests(args ...string) {
 			ts := time.Now().UnixNano()
 			contextNumeric, err = ioutil.TempDir("", fmt.Sprint(ts))
 			Expect(err).ToNot(HaveOccurred())
-			os.Mkdir(context, 0750)
```
Comment (kadel) [inline tests/integration/component.go]: Isn't this source of the original error? Instead of creating `context` dir wasn't this supposed to be `contextNumeric`?

Comment (amitkrout) [reply tests/integration/component.go]: Yes, you are right. 
I thought global ```context``` is misplaced somehow here.

Comment (amitkrout) [reply tests/integration/component.go]: I wrongly interpret your comment i guess.

@kadel ```contextNumeric, err = ioutil.TempDir("", fmt.Sprint(ts))``` is creating the temp dir. So no need to create it again. 
As part of ```os.Mkdir(context, 0750)``` is concerned, global context is misplaced somehow here i guess.

**Comment by amitkrout** [comment]
```
odo component command tests Test odo push with --source and --config flags Using project flag(--project) and current directory 
  create local nodejs component and push source and code separately
  /go/src/github.com/openshift/odo/tests/integration/component.go:185
 Created dir: /tmp/916256747
Creating a new project: kciqnjjmiu
Running odo with args [odo project create kciqnjjmiu -w -v4]
[odo]  •  Waiting for project to come up  ...
[odo]  ✗  Waiting for project to come up [30s]
[odo] I0926 06:59:42.493016   17103 cmdutils.go:48] Error:
[odo] unable to create new project: unable to create new project kciqnjjmiu: Timeout: request did not complete within requested timeout 30s
[odo]  ✗  Timeout: request did not complete within requested timeout 30s
Deleting project: ollzmfgirv
Running odo with args [odo project delete ollzmfgirv -f]
[odo]  ✗  The project ollzmfgirv does not exist. Please check the list of projects using `odo project list`
Deleting dir: /tmp/916256747
 • Failure in Spec Setup (JustBeforeEach) [30.499 seconds]
odo component command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_test.go:13
  Test odo push with --source and --config flags
  /go/src/github.com/openshift/odo/tests/integration/component.go:174
    Using project flag(--project) and current directory [JustBeforeEach]
    /go/src/github.com/openshift/odo/tests/integration/component.go:184
      create local nodejs component and push source and code separately
      /go/src/github.com/openshift/odo/tests/integration/component.go:185
       No future change is possible.  Bailing out early after 30.303s.
      
      Running odo with args [odo project create kciqnjjmiu -w -v4]
      Expected
          <int>: 1
      to match exit code:
          <int>: 0
       /go/src/github.com/openshift/odo/tests/helper/helper_run.go:33
```
/test v4.2-integration

File: tests/integration/component.go [hunk 2]
```diff
@@ -583,13 +583,10 @@ func componentTests(args ...string) {
...
 			project = helper.CreateRandProject()
-			helper.Chdir(contextNumeric)
```
Comment (amitkrout) [inline tests/integration/component.go]: @kadel Issue is coming from here
```
Unexpected error:
      
        <*os.PathError | 0xc0000ad650>: {Op: "chdir", Path: "", Err: 0x2}
        chdir : no such file or directory
    occurred
     /go/src/github.com/openshift/odo/tests/helper/helper_filesystem.go:42
```

File: tests/integration/component.go [hunk 3]
```diff
@@ -583,13 +583,10 @@ func componentTests(args ...string) {
...
 		})
 		JustAfterEach(func() {
 			helper.DeleteProject(project)
-			helper.Chdir(originalDir)
```
Comment (amitkrout) [inline tests/integration/component.go]: @kadel Issue is coming from here
```
Unexpected error:
      
        <*os.PathError | 0xc0000ad650>: {Op: "chdir", Path: "", Err: 0x2}
        chdir : no such file or directory
    occurred
     /go/src/github.com/openshift/odo/tests/helper/helper_filesystem.go:42
```

Comment (amitkrout) [reply tests/integration/component.go]: This is the function where the issue hit - https://github.com/openshift/odo/blob/master/tests/helper/helper_filesystem.go#L39

File: tests/integration/component.go (hunk 1 above)
Comment (amitkrout) [reply tests/integration/component.go]: @kadel https://github.com/openshift/odo/pull/2185#discussion_r328469771

**Comment by amitkrout** [comment]
```
[0modo component command tests[0m [90mCreating component with numeric named context[0m 
  [1mshould create default named component in a directory with numeric name[0m
  [37m/go/src/github.com/openshift/odo/tests/integration/component.go:593[0m

Created dir: /tmp/322401144
Creating a new project: ybeypujunv
[...]
Running odo with args [odo create nodejs --project ybeypujunv --context /tmp/1569480696359993130499387511 --app testing]
[...]
Deleting project: ybeypujunv
Running odo with args [odo project delete ybeypujunv -f]
[...]
Deleting dir: /tmp/1569480696359993130499387511
Deleting dir: /tmp/322401144
```

**Comment by amitkrout** [comment]
ping @kadel

**Comment by kadel** [comment]
/retest
```

• Failure [8.473 seconds]
odo project command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_project_test.go:13
  when running project command app parameter in directory that doesn't contain .odo config directory
  /go/src/github.com/openshift/odo/tests/integration/cmd_project_test.go:41
    should successfully execute list along with machine readable output [It]
    /go/src/github.com/openshift/odo/tests/integration/cmd_project_test.go:42
    Expected
      
        <string>: {"kind":"List","apiVersion":"odo.openshift.io/v1alpha1","metadata":{},"items":[{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"dqifrurwgg","namespace":"dqifrurwgg","creationTimestamp":null},"spec":{},"status":{"active":false}},{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"jnpdcypaqb","namespace":"jnpdcypaqb","creationTimestamp":null},"spec":{},"status":{"active":false}},{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"myproject","namespace":"myproject","creationTimestamp":null},"spec":{},"status":{"active":false}},{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"teejhhfkpa","namespace":"teejhhfkpa","creationTimestamp":null},"spec":{},"status":{"active":true}},{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"zngqztqfjn","namespace":"zngqztqfjn","creationTimestamp":null},"spec":{},"status":{"active":false}}]}
        
    to contain substring
        <string>: {"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"teejhhfkpa","namespace":"teejhhfkpa","creationTimestamp":null},"spec":{},"status":{"active":false}}
    /go/src/github.com/openshift/odo/tests/integration/cmd_project_test.go:50
------------------------------
```
