### PR TITLE
Display warning if env.yaml has urls for another push target but no valid urls for current push target

### LINKED ISSUE #2977: follow up on odo create for docker pushTarget
odo needs to properly handle the situations where the user switches between `pushTarget`s

### URL created for Docker but pushed to Kube
```
▶ odo preference set pushtarget docker
? pushtarget is already set. Do you want to override it in the config Yes
Global preference was successfully updated

▶ odo url create
 ✓  URL backend-8080 created for component: backend with exposed port: 49213

To create the URL on the cluster, please use `odo push`


▶ odo preference set pushtarget kube
? pushtarget is already set. Do you want to override it in the config Yes
Global preference was successfully updated

▶ odo push
 •  Push devfile component backend  ...
 ✓  Waiting for component to start [24s]

Applying URL changes
 ✗  Failed To Update Config To Component Deployed.
Error: unable to create url: unable to create ingress: error creating ingress: Ingress.extensions "backend-8080" is invalid: spec.rules[0].host: Invalid value: "backend-8080.": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a
```

The error message is confusing, it doesn't say anything useful. It should detect what happened, and tell user what to do.
This PR https://github.com/openshift/odo/pull/2885 is adding URL `Kind` to `env.yaml` which might be useful here.

### URL created for Kube but pushed to Docker

```
▶ odo url create  --host apps.testocp4x.psiodo.net
 ✓  URL backend-8080.apps.testocp4x.psiodo.net created for component: backend

To create the URL on the cluster, please use `odo push`

▶ odo preference set pushtarget docker
? pushtarget is already set. Do you want to override it in the config Yes
Global preference was successfully updated

▶ odo push
 •  Push devfile component backend  ...
 ✓  Pulling image quay.io/eclipse/che-java11-maven:nightly [2s]
 ✓  Starting container for quay.io/eclipse/che-java11-maven:nightly [595ms]
 ✓  Push devfile component backend [2s]
 ✓  Changes successfully pushed to component
```

Url was created but it was silently ignored :-/

 

### secure for docker
```
▶ odo url create -h

      --secure             Creates a secure https url
```

How is `--secure` going to work on docker?

_Originally posted by @kadel in https://github.com/openshift/odo/pull/2906#issuecomment-618362722_

### PR DESCRIPTION
**Pull request by yangcao77**
Signed-off-by: Stephanie <stephanie.cao@ibm.com>

**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

/kind bug
/area devfile

**What does does this PR do / why we need it**:

This PR validates urlName during `url create`, and display an error if urlName already exists. (be consistent for route, ingress and docker) 

This PR checks for URL in env.yaml file when executing `odo push`. Displays warning if env.yaml has url(s) for another push target but no valid urls for current push target.

**Which issue(s) this PR fixes**:

Fixes #2977 

**How to test changes / Special notes to the reviewer**:

```
odo preference set experimental true
odo preference set pushtarget docker
odo create java-spring-boot
odo push
odo url create testurl1 --port 8080
```
Check the env.yaml file, should have a url created with a randomly assigned exposed port. 
run the url create command again. should see the error complaining url already exist:
```
odo url create testurl1 --port 8080
 ✗  the url testurl1 already exists
```

**Swicth push target from docker to kube**
Switch push target and run odo push, should successfully create pod&services, should see a warning message indicate there is no valid urls defined in env.yaml for ingress.
```
$ odo preference set pushtarget kube
? pushtarget is already set. Do you want to override it in the config Yes
Global preference was successfully updated

$ odo push
 ⚠  found url(s) defined for docker, but no valid urls for ingress/route defined

Validation
 ✓  Validating the devfile [224302ns]

Creating Kubernetes resources for component java-spring-boot
 ✓  Waiting for component to start [5s]

Applying URL changes

Syncing to component java-spring-boot
 ✓  Checking files for pushing [1ms]
 ✓  Syncing files to the component [3s]

Executing devfile commands for component java-spring-boot
 ✓  Executing devbuild command "/artifacts/bin/build-container-full.sh" [3s]
 ✓  Executing devrun command "/artifacts/bin/start-server.sh" [3s]

Pushing devfile component java-spring-boot
 ✓  Changes successfully pushed to component

```

**Swicth push target from kube to docker**
Delete the old url, create a new url with `pushtarget` set to kube, and then switch push target back to docker and run odo push, should successfully create container, should see a warning message indicate there is no valid urls defined in env.yaml for docker. 
```
$ odo url delete testurl1
? Are you sure you want to delete the testurl1 Yes
 ✓  URL testurl1 removed from the env file

To delete the URL on the cluster, please use `odo push`
$ odo url create --host 1.2.3.4.com
 ✓  URL java-spring-boot-8080.1.2.3.4.com created for component: java-spring-boot

To apply the URL configuration changes, please use `odo push`
$ odo preference set pushtarget docker
? pushtarget is already set. Do you want to override it in the config Yes
Global preference was successfully updated

$ odo push
 ⚠  found url(s) defined for ingress/route, but no valid urls with exposed port defined

Validation
 ✓  Validating the devfile [121135ns]

Creating Docker resources for component java-spring-boot
 ✓  Pulling image maysunfaisal/springbootbuild [943ms]
 ✓  Starting container for maysunfaisal/springbootbuild [432ms]
 ✓  Pulling image maysunfaisal/springbootruntime [682ms]
 ✓  Starting container for maysunfaisal/springbootruntime [429ms]

Syncing to component java-spring-boot
 ✓  Checking files for pushing [1ms]
 ✓  Syncing files to the component [263ms]

Executing devfile commands for component java-spring-boot
 ✓  Executing devbuild command "/artifacts/bin/build-container-full.sh" [2s]
 ✓  Executing devrun command "/artifacts/bin/start-server.sh" [1s]

Pushing devfile component java-spring-boot
 ✓  Changes successfully pushed to component
```
Check no exposed port is assigned: 
```
$ docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
1f5577fba084        maysunfaisal/springbootruntime        "tail -f /dev/null"      7 seconds ago       Up 6 seconds        8080/tcp                                               infallible_cray
337c252426d0        maysunfaisal/springbootbuild          "tail -f /dev/null"      8 seconds ago       Up 7 seconds                                                               wonderful_
```

### CODE REVIEW

**Comment by kadel** [comment]
👍 
/approve
/retest

File: pkg/odo/cli/component/devfile.go [hunk 1]
```diff
@@ -152,3 +153,22 @@ func (do *DeleteOptions) DevfileComponentDelete() error {
 	log.Successf("Successfully deleted component")
 	return nil
 }
+
+func validateURL(url []envinfo.EnvInfoURL) {
```
Comment (cdrage) [inline pkg/odo/cli/component/devfile.go:157]: shouldn't this return err or something instead of just outputting `log.Warningf`?

File: pkg/odo/cli/component/devfile.go [hunk 2]
```diff
@@ -152,3 +153,22 @@ func (do *DeleteOptions) DevfileComponentDelete() error {
...
+	kubeURLExists := false
+	for _, element := range url {
+		if element.Kind == envinfo.DOCKER {
+			dockerURLExists = true
+		} else {
+			kubeURLExists = true
+		}
+	}
+	if pushtarget.IsPushTargetDocker() && !dockerURLExists && kubeURLExists {
+		log.Warningf("found url(s) defined for ingress/route, but no valid urls with exposed port defined")
```
Comment (cdrage) [inline pkg/odo/cli/component/devfile.go:170]: Should be capitalized.

File: pkg/odo/cli/component/devfile.go [hunk 3]
```diff
@@ -152,3 +153,22 @@ func (do *DeleteOptions) DevfileComponentDelete() error {
...
+	} else if !pushtarget.IsPushTargetDocker() && !kubeURLExists && dockerURLExists {
+		log.Warningf("found url(s) defined for docker, but no valid urls for ingress/route defined")
```
Comment (cdrage) [inline pkg/odo/cli/component/devfile.go:172]: Should be capitalized

File: pkg/odo/cli/component/devfile.go (hunk 2 above)
Comment (cdrage) [reply pkg/odo/cli/component/devfile.go:170]: url needs to be capitalized too. 

This may be a better output: `Found URL(s) defined for ingress/route, but no valid URLs with exposed port defined`

File: pkg/odo/cli/component/devfile.go (hunk 3 above)
Comment (cdrage) [reply pkg/odo/cli/component/devfile.go:172]: Also, another thing, is that perhaps you can add a simple `len(urls) > 1` if statement so you can either output `URL` or `URLs` instead of using `(s)`?

File: pkg/odo/cli/component/devfile.go (hunk 1 above)
Comment (cdrage) [reply pkg/odo/cli/component/devfile.go:157]: I believe that for a function called `validateURL` we should be returning bool, or a list of URLs, or something else other than outputting to `warning`

File: pkg/odo/cli/component/devfile.go (hunk 2 above)
Comment (johnmcollier) [reply pkg/odo/cli/component/devfile.go:170]: `Found URL(s) defined for Kubernetes, but no valid URLs for Docker`?

File: pkg/odo/cli/component/devfile.go (hunk 1 above)
Comment (yangcao77) [reply pkg/odo/cli/component/devfile.go:157]: I would prefer not to return an error since it's a warning not an error. 
Why do we want a return value for this function? For test purpose?

File: pkg/odo/cli/component/devfile.go (hunk 3 above)
Comment (yangcao77) [reply pkg/odo/cli/component/devfile.go]: updated

File: pkg/odo/cli/component/devfile.go (hunk 2 above)
Comment (yangcao77) [reply pkg/odo/cli/component/devfile.go]: updated

File: pkg/odo/cli/component/devfile.go (hunk 1 above)
Comment (cdrage) [reply pkg/odo/cli/component/devfile.go:157]: Yes. Test purposes as well as the fact that the name of the function says "validateURL" which is assuming that you're passing in the URL and it's validating it. It would make sense that after validation it'd return a boolean?

Perhaps you can create a separate function that says "validateURL" that validates one URL. And then for this function you can make it as `validateURLS" which will validate all of them?

File: pkg/odo/cli/component/devfile.go [hunk 4]
```diff
@@ -152,3 +153,28 @@ func (do *DeleteOptions) DevfileComponentDelete() error {
...
+			dockerURLExists = true
+		} else {
+			kubeURLExists = true
+		}
+	}
+	var urlOutput string
+	if len(url) > 1 {
+		urlOutput = "URLs"
+	} else {
+		urlOutput = "a URL"
```
Comment (cdrage) [inline pkg/odo/cli/component/devfile.go:173]: :+1:

File: tests/integration/devfile/docker/cmd_docker_devfile_url_test.go [hunk 5]
```diff
@@ -106,4 +97,39 @@ var _ = Describe("odo docker devfile url command tests", func() {
 		})
 	})
 
+	Context("Switching pushtarget", func() {
+		It("swicth from docker to kube, odo push should display warning", func() {
```
Comment (cdrage) [inline tests/integration/devfile/docker/cmd_docker_devfile_url_test.go:101]: switch

File: tests/integration/devfile/docker/cmd_docker_devfile_url_test.go [hunk 6]
```diff
@@ -106,4 +97,39 @@ var _ = Describe("odo docker devfile url command tests", func() {
...
+
+			helper.CmdShouldPass("odo", "preference", "set", "pushtarget", "kube", "-f")
+			session := helper.CmdRunner("odo", "push", "--devfile", "devfile.yaml")
+			stdout = string(session.Wait().Out.Contents())
+			stderr := string(session.Wait().Err.Contents())
+			Expect(stderr).To(ContainSubstring("Found a URL defined for Docker, but no valid URLs for Kubernetes."))
+			Expect(stdout).To(ContainSubstring("Changes successfully pushed to component"))
+		})
+
+		It("swicth from kube to docker, odo push should display warning", func() {
```
Comment (cdrage) [inline tests/integration/devfile/docker/cmd_docker_devfile_url_test.go:117]: switch
