### PR TITLE
Fixing kubeconfig path and login session for 4.x cluster

### LINKED ISSUE #3501: KUBECONFIG somehow reverted back to the original path in CI
/kind bug

## What versions of software are you using?

**Operating System:**
supported

**Output of `odo version`:**
master

## How did you run odo exactly?

Tests running on openshift repo verifies that https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/9431/rehearse-9431-periodic-ci-openshift-odo-master-v4.3-integration-e2e-periodic-steps/1280376323939766272#1:build-log.txt%3A323

Though we are already setting up the `KUBECONFIG` environment var to a [temporary directory](https://github.com/openshift/odo/blob/master/scripts/configure-installer-tests-cluster.sh#L43-L46) which can be seen from [test logs](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/9431/rehearse-9431-periodic-ci-openshift-odo-master-v4.3-integration-e2e-periodic-steps/1280376323939766272#1:build-log.txt%3A72) also.

Not sure whether it is getting reverted back or it is a problem from our odo side. I will send a pr to confirm this weird behaviour on CI.

## Actual behavior

Though `KUBECONFIG` is set to a temporary file but during test run original `KUBECONFIG` getting fetched.

## Expected behavior

`KUBECONFIG` should not get reverted to original one.

## Any logs, error output, etc?

https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/9431/rehearse-9431-periodic-ci-openshift-odo-master-v4.3-integration-e2e-periodic-steps/1280376323939766272#1:build-log.txt%3A323

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind bug
/kind cleanup
/kind feature

**What does does this PR do / why we need it**:

Configuring kubeconfig path and login session for test script running against 4.x cluster

**Which issue(s) this PR fixes**:

Fixes #3501 

**How to test changes / Special notes to the reviewer**:

Test script should use the developer login session and pr https://github.com/openshift/release/pull/9431 should not fail.

### CODE REVIEW

**Comment by prietyc123** [comment]
ping @amitkrout

**Comment by prietyc123** [comment]
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/3528/pull-ci-openshift-odo-master-v4.3-integration-e2e/1281145237829324800#1:build-log.txt%3A496

/retest

**Comment by girishramnani** [comment]
Trusting @amitkrout’s judgement on this

File: scripts/configure-installer-tests-cluster.sh [hunk 1]
```diff
@@ -133,3 +134,9 @@ fi
 oc new-project myproject
 sleep 4
 oc version
+
+# KUBECONFIG cleanup only if CI is set
+if [ ! -f $CI ]; then
+    rm -rf $KUBECONFIG
```
Comment (kadel) [inline scripts/configure-installer-tests-cluster.sh:140]: removing the kubeconfig should happen in the file where it was created (in the test scripts)

Comment (prietyc123) [reply scripts/configure-installer-tests-cluster.sh:140]: > removing the kubeconfig should happen in the file where it was created (in the test scripts)

This kubeconfig will not get used in the test script reason https://github.com/openshift/odo/issues/3501#issuecomment-655883217
