### PR TITLE
Dropping support for service catalog based services

### LINKED ISSUE #4890: Remove code and cli docs related to 3.11 and Service Catalog
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** `main`

## Expected behavior
OCP 3.11 is not supported any more. Service Catalog is not supported on any supported OCP versions. So, we should remove code and docs related to 3.11 and Service Catalog.

### LINKED ISSUE #5004: odo catalog describe service broken
/kind bug

## What versions of software are you using?

**Operating System:** Win10Pro

**Output of `odo version`:**

```
odo v2.2.4 (f12e036b5)

Server: https://api.crc.testing:6443
Kubernetes: v1.20.0+df9c838
```

## How did you run odo exactly?

`odo catalog service describe myoperator`

## Actual behavior

` X  unable to search classes by name (clusterserviceclasses.servicecatalog.k8s.io is forbidden: User "developer" cannot list resource "clusterserviceclasses" in API group "servicecatalog.k8s.io" at the cluster scope)
`
## Expected behavior

operator should be described

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

**What type of PR is this?**
/kind code-refactoring
/kind cleanup

**What does this PR do / why we need it**:
We are dropping support for service catalog based services

**Which issue(s) this PR fixes**:

Fixes #4890 
Fixes #5004

**PR acceptance criteria**:

- [x] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] Update changelog

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
 - `odo catalog list services` should not list service catalog even if it is available in cluster
```bash
> ./odo catalog list services
Services available through Operators
NAME                                CRDs
redis-operator.v0.6.0               RedisCluster, Redis
service-binding-operator.v0.8.0     ServiceBinding

```
 - `odo catalog describe service x/y` should describe operator backed service and fail otherwise
```bash
> odo catalog describe service blah
 ✗  unable to search classes by name (the server could not find the requested resource (get clusterserviceclasses.servicecatalog.k8s.io))
> odo catalog describe service redis-operator.v0.6.0/Redis
Kind: Redis
Version: v1beta1
Description: Redis
Parameters:

 PATH  DISPLAYNAME  DESCRIPTION 




```
 - `odo service create` should successfully create operator backed services and attempts to create service catalog should fail
```bash
> odo service create blah
 ✗  invalid service name, use the format <operator-type>/<crd-name>
> odo service create redis-operator.v0.6.0/Redis
Successfully added service to the configuration; do 'odo push' to create service on the cluster

```
 - `odo service list` should only list operator backed services
 - `odo service delete` should successfully delete operator backed services

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
prow error
/retest

**Comment by mohammedzee1000** [comment]
timeout
/test psi-unit-test-windows

**Comment by mohammedzee1000** [comment]
timeouts
/retest

**Comment by mohammedzee1000** [comment]
timed out 
/retest

**Comment by mohammedzee1000** [comment]
ci error
/retest

**Comment by mohammedzee1000** [comment]
macos machine issue
/test psi-unit-test-mac

File: tests/integration/operatorhub/cmd_service_test.go [hunk 1]
```diff
@@ -28,6 +28,27 @@ var _ = Describe("odo service command tests for OperatorHub", func() {
 		helper.CommonAfterEach(commonVar)
 	})
 
+	Context("user wants to work with services", func() {
+		When("user runs odo service commands with help flag", func() {
+			It("should display the help for odo service -h", func() {
+				appHelp := helper.Cmd("odo", "service", "-h").ShouldPass().Out()
+				Expect(appHelp).To(ContainSubstring("Perform service catalog operations"))
```
Comment (dharmit) [inline tests/integration/operatorhub/cmd_service_test.go:35]: IMO, we sholdn't be showing "service catalog" on CLI. I couldn't find another occurrence of this string being checked with a `Ctrl+F`. We should remove it, IMO.

**Review by dharmit — CHANGES_REQUESTED** [review]

File: pkg/odo/cli/catalog/search/service.go [hunk 2]
```diff
@@ -40,36 +37,16 @@ func (o *SearchServiceOptions) Complete(name string, cmd *cobra.Command, args []
 	o.csvs, err = o.KClient.SearchClusterServiceVersionList(o.searchTerm)
 	if err != nil {
 		// Error only occurs when OperatorHub is not installed/enabled on the
-		// Kubernetes or OpenShift 4.x cluster. It doesn't occur when there are
-		// no operators installed.
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/odo/cli/catalog/search/service.go:44]: I can still see them

[the remark this answers is not in the document]
Comment (dharmit) [reply pkg/odo/cli/catalog/search/service.go:44]: I'm seeing below:
```go
// Error only occurs when OperatorHub is not installed/enabled on the
// Kubernetes or OpenShift 4.x cluster.
// Neither OperatorHub nor Service Catalog is enabled on the cluster
```
IMO, it should be:
```go
// Error only occurs when OperatorHub is not installed/enabled on the
// Kubernetes or OpenShift 4.x cluster. It doesn't occur when there are
// no operators installed.
// OperatorHub is not enabled on the cluster
```

File: pkg/odo/cli/service/ui/ui.go [hunk 3]
```diff
@@ -2,22 +2,18 @@ package ui
...
-	"fmt"
 	"sort"
 	"strings"
 
 	"github.com/openshift/odo/pkg/odo/cli/ui"
 	"github.com/openshift/odo/pkg/odo/util/validation"
-	"github.com/openshift/odo/pkg/service"
 	"k8s.io/klog"
 
+	scv1beta1 "github.com/kubernetes-sigs/service-catalog/pkg/apis/servicecatalog/v1beta1"
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/odo/cli/service/ui/ui.go:12]: removed

File: pkg/odo/cli/service/service_test.go [hunk 4]
```diff
@@ -1,99 +1,15 @@
...
-		return false
-	}
-	for i := range s1 {
-		if s1[i] != s2[i] {
-			return false
-		}
-	}
-	return true
-}
+//func equal(s1, s2 []string) bool {
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/odo/cli/service/service_test.go:3]: removed file as it is last thing remaining

File: pkg/odo/cli/service/list.go [hunk 5]
```diff
@@ -62,48 +56,14 @@ func (o *ServiceListOptions) Complete(name string, cmd *cobra.Command, args []st
 // Validate validates the ServiceListOptions based on completed values
 func (o *ServiceListOptions) Validate() (err error) {
 	if !o.csvSupport {
-		// Throw error if project and application values are not available.
-		// This will most likely be the case when user does odo service list from outside a component directory and
-		// doesn't provide --app and/or --project flags
-		if o.Context.Project == "" || o.Context.Application == "" {
-			return odoutil.ThrowContextError()
-		}
+		return fmt.Errorf("operator backed services not installed and service catalog is no longer supported")
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/odo/cli/service/list.go:59]: removed

File: pkg/odo/cli/component/common_link.go [hunk 6]
```diff
@@ -98,37 +97,20 @@ func (o *commonLinkOptions) complete(name string, cmd *cobra.Command, args []str
...
-	}
-
 	cmpExists, err := component.Exists(o.Client, suppliedName, o.Application)
 	if err != nil {
 		return fmt.Errorf("Unable to determine if component exists:\n%v", err)
 	}
 
-	if !cmpExists && !svcExists {
+	if !cmpExists {
 		return fmt.Errorf("Neither a service nor a component named %s could be located. Please create one of the two before attempting to use 'odo %s'", suppliedName, o.operationName)
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/odo/cli/component/common_link.go:106]: updated

File: pkg/odo/cli/catalog/describe/service.go [hunk 7]
```diff
@@ -55,13 +55,11 @@ func (o *DescribeServiceOptions) Complete(name string, cmd *cobra.Command, args
...
 	}
 
-	// if the argument contains "/" then we assume the user wants to describe a CRD.
-	if _, _, err := service.SplitServiceKindName(args[0]); err == nil {
-		o.backend = NewOperatorBackend()
-	} else {
-		o.backend = NewServiceCatalogBackend()
+	_, _, err = service.IsOperatorServiceNameValid(args[0])
+	if err != nil {
+		return fmt.Errorf("invalid operator name and service catalog not supported %w", err)
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/odo/cli/catalog/describe/service.go:60]: removed

File: pkg/odo/cli/catalog/describe/service.go [hunk 8]
```diff
@@ -31,11 +30,12 @@ var (
...
 type DescribeServiceOptions struct {
+	//go lint complains of unused fields so commenting them out rather than removing as we dont know if we will need them
 	// name of the service to describe, from command arguments
-	serviceName string
+	//	serviceName string
 	// resolved service
-	service svc.ServiceClass
-	plans   []svc.ServicePlan
+	// service svc.ServiceClass
+	// plans   []svc.ServicePlan
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/odo/cli/catalog/describe/service.go:38]: removed

File: tests/integration/operatorhub/cmd_service_test.go (hunk 1 above)
Comment (mohammedzee1000) [reply tests/integration/operatorhub/cmd_service_test.go:35]: updated

File: pkg/odo/cli/catalog/search/service.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/odo/cli/catalog/search/service.go:44]: Updated ptal

**Comment by mohammedzee1000** [comment]
It appears some sort of issue/outage on psi windows is playing havoc with psi tests.
The other fail seems to be a problem with service binding operator

**Comment by mohammedzee1000** [comment]
unrelated fail
/retest

**Comment by dharmit** [comment]
> unrelated fail
> /retest

Can you please add the excerpt before triggering a retest? It helps take up issues with the QE when something fails on infra side. Or track flakes.

**Comment by mohammedzee1000** [comment]
windows timeout

/test psi-unit-test-windows

**Comment by dharmit** [comment]
@mohammedzee1000 please update the changelog.md file with this PR.

**Comment by mohammedzee1000** [comment]
Freezing here, will  break out remainder into new issue

**Comment by mohammedzee1000** [comment]
Flake https://github.com/openshift/odo/issues/4960
/retest

File: pkg/odo/cli/service/create.go [hunk 9]
```diff
@@ -1,62 +1,43 @@
...
 var (
-	createExample = ktemplates.Examples(`
-    # Create new postgresql service from service catalog using dev plan and name my-postgresql-db.
-    %[1]s dh-postgresql-apb my-postgresql-db --plan dev -p postgresql_user=luke -p postgresql_password=secret`)
-
 	createOperatorExample = ktemplates.Examples(`
 	# Create new EtcdCluster service from etcdoperator.v0.9.4 operator.
 	%[1]s etcdoperator.v0.9.4/EtcdCluster`)
 
 	createShortDesc = `Create a new service from Operator Hub or Service Catalog and deploy it on OpenShift.`
```
Comment (valaparthvi) [inline pkg/odo/cli/service/create.go:23]:
```suggestion
    createShortDesc = `Create a new service from Operator Hub and deploy it on OpenShift.`
```

Comment (valaparthvi) [reply pkg/odo/cli/service/create.go:23]: On an unrelated note: Why do we just mention OpenShift, and not K8s in our help docs?

**Review by valaparthvi — CHANGES_REQUESTED** [review]
There is still service description in `odo --help` which refers to catalog services. See https://github.com/openshift/odo/blob/main/pkg/odo/cli/service/service.go#L17 and https://github.com/openshift/odo/blob/main/pkg/odo/cli/service/service.go#L26.

Other than this, I see a mention of `service catalog` in a number of comments. Can you remove them as well?
- https://github.com/openshift/odo/blob/main/pkg/odo/cli/service/create.go#L82
- https://github.com/openshift/odo/blob/main/pkg/odo/cli/service/delete.go#L35
- https://github.com/openshift/odo/blob/main/pkg/odo/cli/service/list.go#L35; Perhaps we no longer need `csvSupport` either, you can remove that too.

File: pkg/odo/cli/service/create.go (hunk 9 above)
Comment (mohammedzee1000) [reply pkg/odo/cli/service/create.go:23]: yea i thought so too. Makes sense to me. We should probably have an issue to update all cli docs to mention kubernetes. Openshift is a kind of kubernetes after all

Comment (mohammedzee1000) [reply pkg/odo/cli/service/create.go:23]: No i think we still need to check if csv is supported. Operator hub is not installed by default on a cluster

Comment (mohammedzee1000) [reply pkg/odo/cli/service/create.go:23]: I believe some of the references to the service catalog can be interpreted as the `odo catalog list services` = a service catalog.

Comment (mohammedzee1000) [reply pkg/odo/cli/service/create.go:23]: @valaparthvi ^ I will go through your links once more and see which of the references makes sense and which does not

**Comment by valaparthvi** [comment]
There are interfaces such as ServiceBackendProvider, do you think we will need to use them now that we no longer have 2 different type of providers? Or do you see a future where we might have more types of provider and this interface would help?

File: pkg/odo/cli/service/create.go (hunk 9 above)
Comment (valaparthvi) [reply pkg/odo/cli/service/create.go:23]: @mohammedzee1000 You missed out on this change.

**Comment by mohammedzee1000** [comment]
> There are interfaces such as ServiceBackendProvider, do you think we will need to use them now that we no longer have 2 different type of providers? Or do you see a future where we might have more types of provider and this interface would help?
> Well, I guess it might become out of scope for this PR.

Yep, that would be out of the scope of this PR. Also having interfaces is not necessarily a bad thing. It would let us expand in the future, if we need to

**Comment by mohammedzee1000** [comment]
Active project error
/retest

**Comment by mohammedzee1000** [comment]
Current project in json issue
/retest

**Comment by dharmit** [comment]
> There are interfaces such as ServiceBackendProvider, do you think we will need to use them now that we no longer have 2 different type of providers? Or do you see a future where we might have more types of provider and this interface would help?

This might come in handy when the scope of Helm task goes beyond just listing Helm backed services. Although I don't expect it to be odo's task to create those services, it's still good to have interfaces. It is one of the powers of Go which we haven't fully utilized in odo code. Thinking in terms of interfaces helps when designing code. Unfortunately, we haven't talked enough about code design in odo ever, AFAIK.

> Well, I guess it might become out of scope for this PR.

Yes.

**Comment by mohammedzee1000** [comment]
> > There are interfaces such as ServiceBackendProvider, do you think we will need to use them now that we no longer have 2 different type of providers? Or do you see a future where we might have more types of provider and this interface would help?
> 
> This might come in handy when the scope of Helm task goes beyond just listing Helm backed services. Although I don't expect it to be odo's task to create those services, it's still good to have interfaces. It is one of the powers of Go which we haven't fully utilized in odo code. Thinking in terms of interfaces helps when designing code. Unfortunately, we haven't talked enough about code design in odo ever, AFAIK.
> 
> > Well, I guess it might become out of scope for this PR.
> 
> Yes.

I think people are confusing `odo catalog service` v/s openshift service catalog v/s Service Catalog Backend. I was confused at first too but the reason why `service catalog` is used here is that openshift service catalog was the only way to create services in the days this code was written. 
In later stages, we got operators and potentially helm in the future. But the name service catalog has stuck

File: Changelog.md [hunk 10]
```diff
@@ -2,6 +2,10 @@
 
 ## Next
 
+### Cleanup
```
Comment (dharmit) [inline Changelog.md:5]: I'd prefer putting "Features/Enhancements" at the top. I'm also thinking if we want to have a separate Cleanup section. I'd like to keep it limited instead of adding too many sections. Items that have been cleaned up can go as "Deprecated xyz" in the "Features/Enhancement" section

Comment (mohammedzee1000) [reply Changelog.md:5]: Makes sense, updating

Comment (dharmit) [reply Changelog.md:5]: Thanks @mohammedzee1000.

**Comment by mohammedzee1000** [comment]
current project in json format error
/retest

**Review by valaparthvi — COMMENTED** [review]
I found the following refefences of service catalog from a quick directory search. But, I understand if you intend  to work on them in another PR.
1. `odo link` help doc 
    1. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/odo/cli/component/link.go#L46
    2. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/odo/cli/component/link.go#L75

2. Do we need this piece of code now?
https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/application/application.go#L53

3. We probably don't need these Make targets now. 
    1. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/Makefile#L170
    2. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/Makefile#L304

4. `odo catalog search service --help` still contains reference to service catalog. Although I am not sure about this one.
https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/odo/cli/catalog/search/service.go#L99

5. There is a https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/kclient/serviceCatalog.go and it's unit test which I am not sure are useful now.

6. We probably don't need this anymore - https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/catalog/catalog.go#L302
7. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/application/doc.go#L4
8. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/odo/cli/application/describe.go#L95
9. `odo catalog list services  --help` still references service catalog. - https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/odo/cli/catalog/list/services.go#L20
10. Maybe some of these types are not required anymore? 
     1. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/service/types.go#L37
     2. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/service/types.go#L62
     3. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/service/types.go#L48
11. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/odo/cli/catalog/util/util.go#L18
12. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/tests/integration/cmd_link_unlink_test.go#L35

**Comment by mohammedzee1000** [comment]
> I found the following refefences of service catalog from a quick directory search. But, I understand if you intend to work on them in another PR.
> 
> 1. `odo link` help doc
>    
>    1. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/odo/cli/component/link.go#L46
>    2. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/odo/cli/component/link.go#L75
> 2. Do we need this piece of code now?
>    https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/application/application.go#L53
> 3. We probably don't need these Make targets now.
>    
>    1. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/Makefile#L170
>    2. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/Makefile#L304
Yea these could be removed
> 4. `odo catalog search service --help` still contains reference to service catalog. Although I am not sure about this one.
>    https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/odo/cli/catalog/search/service.go#L99
> 5. There is a https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/kclient/serviceCatalog.go and it's unit test which I am not sure are useful now.
> 6. We probably don't need this anymore - https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/catalog/catalog.go#L302
> 7. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/application/doc.go#L4
> 8. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/odo/cli/application/describe.go#L95
> 9. `odo catalog list services  --help` still references service catalog. - https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/odo/cli/catalog/list/services.go#L20

This I could fix

> 10. Maybe some of these types are not required anymore?
>     
>     1. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/service/types.go#L37
>     2. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/service/types.go#L62
>     3. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/service/types.go#L48
> 11. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/odo/cli/catalog/util/util.go#L18
> 12. https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/tests/integration/cmd_link_unlink_test.go#L35

@valaparthvi 
Yep, some of the stuff can only be removed once all the refs in link and unlink are removed the I guess it makes sense to add this into the scope of #4978 

For the 2 I have commented, I will push a commit now

**Comment by dharmit** [comment]
>  Yep, some of the stuff can only be removed once all the refs in link and unlink are removed 

What parts are about removing link/unlink of components? If it's about removing linking/unlinking code of service catalog, we should push it in this PR itself.

@valaparthvi that was good https://github.com/openshift/odo/pull/4906#pullrequestreview-728506743! 👍🏾

File: pkg/odo/cli/component/common_link.go [hunk 11]
```diff
@@ -25,7 +25,6 @@ const unlink = "unlink"
 
 type commonLinkOptions struct {
 	wait             bool
-	port             string
```
Comment (valaparthvi) [inline pkg/odo/cli/component/common_link.go:30]: This causes an error during the Make.
```sh
➜  make; make install
go build -mod=vendor -ldflags="-X github.com/openshift/odo/pkg/version.GITCOMMIT=52f9ab91b" cmd/odo/odo.go
# github.com/openshift/odo/pkg/odo/cli/component
pkg/odo/cli/component/unlink.go:101:42: o.port undefined (type *UnlinkOptions has no field or method port)
make: *** [Makefile:57: bin] Error 2
go install -mod=vendor -ldflags="-X github.com/openshift/odo/pkg/version.GITCOMMIT=52f9ab91b" ./cmd/odo/
# github.com/openshift/odo/pkg/odo/cli/component
pkg/odo/cli/component/unlink.go:101:42: o.port undefined (type *UnlinkOptions has no field or method port)
make: *** [Makefile:61: install] Error 2                  
```

Comment (valaparthvi) [reply pkg/odo/cli/component/common_link.go:30]: This PR seems overwhelming. Do you think you should keep the Link cleanup for another PR? For now, you can just remove the references from comments and help docs, do the code cleanup in another PR like you said earlier, WDYT?

File: pkg/odo/cli/component/link.go [hunk 12]
```diff
@@ -24,12 +24,6 @@ var (
 	linkExample = ktemplates.Examples(`# Link the current component to the 'EtcdCluster' named 'myetcd'
 %[1]s EtcdCluster/myetcd
 
-# Link the current component to the 'my-postgresql' service
-%[1]s my-postgresql
-
-# Link component 'nodejs' to the 'my-postgresql' service
-%[1]s my-postgresql --component nodejs
-
```
Comment (valaparthvi) [inline pkg/odo/cli/component/link.go:33]: This should not be deleted, this is still relevant for Operator backed services.

File: tests/integration/operatorhub/cmd_link_test.go [hunk 13]
```diff
@@ -131,7 +131,7 @@ var _ = Describe("odo link command tests for OperatorHub", func() {
 					helper.Cmd("odo", "link", svcFullName, "--bind-as-files", "--name", bindingName, "--context", commonVar.Context).ShouldPass()
 				})
 
-				It("should display the link between the components in odo describe", func() {
+				It("should display component links in odo describe", func() {
```
Comment (valaparthvi) [inline tests/integration/operatorhub/cmd_link_test.go:134]: Did you change this to avoid the duplication report from Sonar Cloud?

Comment (mohammedzee1000) [reply tests/integration/operatorhub/cmd_link_test.go:134]: Yes

Comment (valaparthvi) [reply tests/integration/operatorhub/cmd_link_test.go:134]: Probably don't do that. Rebasing on top of the main branch will mostly make the Sonar cloud duplication error go away.

**Comment by mohammedzee1000** [comment]
reset and rebased, now il ensure some of the docs changes did not disappear

**Comment by mohammedzee1000** [comment]
project json format error
/test v4.8-integration-e2e

**Comment by valaparthvi** [comment]
>I think people are confusing odo catalog <action> service v/s openshift service catalog v/s Service Catalog Backend. I was confused at first too but the reason why service catalog is used here is that openshift service catalog was the only way to create services in the days this code was written.
In later stages, we got operators and potentially helm in the future. But the name service catalog has stuck (https://github.com/openshift/odo/pull/4906#issuecomment-897380534)

Then perhaps we should consider renaming the interface to something like `Service Backend` or something less ambiguous. But again, out of scope for this PR.

File: pkg/odo/cli/component/link.go (hunk 12 above)
Comment (mohammedzee1000) [reply pkg/odo/cli/component/link.go]: change reset

File: pkg/odo/cli/component/common_link.go (hunk 11 above)
Comment (mohammedzee1000) [reply pkg/odo/cli/component/common_link.go]: change reset

File: pkg/odo/cli/catalog/describe/service.go [hunk 14]
```diff
@@ -5,37 +5,25 @@ import (
...
-    %[1]s mysql-persistent
-	
-	# Describe a Operator backed service
+	serviceExample = ktemplates.Examples(`# Describe a Operator backed service
 	%[1]s 
 	`)
 
 	serviceLongDesc = ktemplates.LongDesc(`Describes a service type.
-	This command supports both Service Catalog services and Operator backed services.
+	This command supports both Operator backed services.
```
Comment (feloy) [inline pkg/odo/cli/catalog/describe/service.go:20]:
```suggestion
	This command supports Operator backed services.
```

File: pkg/odo/cli/catalog/describe/service.go [hunk 15]
```diff
@@ -59,7 +47,7 @@ func (o *DescribeServiceOptions) Complete(name string, cmd *cobra.Command, args
 	if _, _, err := service.SplitServiceKindName(args[0]); err == nil {
```
Comment (feloy) [inline pkg/odo/cli/catalog/describe/service.go:47]: You can as usual handle the error case first:

```
	if _, _, err := service.SplitServiceKindName(args[0]); err != nil {
		return fmt.Errorf("no deployable operators found")
	}
	o.backend = NewOperatorBackend()
```

File: pkg/odo/cli/service/list.go [hunk 16]
```diff
@@ -54,56 +48,19 @@ func (o *ServiceListOptions) Complete(name string, cmd *cobra.Command, args []st
 			return err
 		}
 	} else {
-		o.Context, err = genericclioptions.NewContext(cmd)
+		return fmt.Errorf("failed to list operator backed serivices, have you installed operators on the cluseter?")
```
Comment (feloy) [inline pkg/odo/cli/service/list.go:51]:
```suggestion
		return fmt.Errorf("failed to list operator backed services, have you installed operators on the cluseter?")
```

**Review by feloy — COMMENTED** [review]
Some little comments, LGTM otherwise

**Review by valaparthvi — CHANGES_REQUESTED** [review]
I have a few concerns about the deleted unit tests and completion handlers, which still seem relevant, but they definitely need refactoring. Maybe we can comment the tests for now, and refactor them to work with services that we still support, i.e. Operator Backed Services.

Other than that, since the integration tests pass and no other irrelevant integration tests were deleted or modified, I am inclined to do a lgtm.

**Comment by mohammedzee1000** [comment]
@valaparthvi opened issues as per discussion
https://github.com/openshift/odo/issues/4996
https://github.com/openshift/odo/issues/4997

File: pkg/service/service_test.go [hunk 17]
```diff
@@ -1,9 +1,6 @@
 package service
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/service/service_test.go:1]: Recorded in issue before

File: pkg/odo/cli/service/create_test.go [hunk 18]
```diff
@@ -1,124 +0,0 @@
-package service
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/odo/cli/service/create_test.go:1]: Recorded in issue before

File: pkg/odo/util/completion/completionhandlers.go [hunk 19]
```diff
@@ -1,146 +1,20 @@
...
 	"github.com/openshift/odo/pkg/odo/genericclioptions"
-	"github.com/openshift/odo/pkg/service"
 	"github.com/openshift/odo/pkg/storage"
 	"github.com/openshift/odo/pkg/url"
 	"github.com/openshift/odo/pkg/util"
 	"github.com/posener/complete"
 	"github.com/spf13/cobra"
 )
 
-// ServiceCompletionHandler provides service name completion for the current project and application
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/odo/util/completion/completionhandlers.go:22]: Recorded in issue before

File: pkg/odo/util/completion/completionhandlers_test.go [hunk 20]
```diff
@@ -1,748 +0,0 @@
...
-		sort.Strings(completions)
-		sort.Strings(tt.output)
-
-		if !reflect.DeepEqual(tt.output, completions) {
-			t.Errorf("expected output: %#v,got: %#v", tt.output, completions)
-		}
-	}
-}
-
-func TestServiceClassCompletionHandler(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/odo/util/completion/completionhandlers_test.go:665]: Recorded in issue

File: pkg/odo/util/completion/completionhandlers_test.go [hunk 21]
```diff
@@ -1,748 +0,0 @@
...
-		completions := LinkCompletionHandler(nil, parsedArgs, context)
-		sort.Strings(completions)
-
-		if !reflect.DeepEqual(tt.output, completions) {
-			t.Errorf("expected output: %#v,got: %#v", tt.output, completions)
-		}
-	}
-}
-
-func TestUnlinkCompletionHandler(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/odo/util/completion/completionhandlers_test.go:376]: Recorded in issue

File: pkg/odo/util/completion/completionhandlers_test.go [hunk 22]
```diff
@@ -1,748 +0,0 @@
...
-		sort.Strings(completions)
-		sort.Strings(tt.output)
-
-		if !reflect.DeepEqual(tt.output, completions) {
-			t.Errorf("expected output: %#v,got: %#v", tt.output, completions)
-		}
-	}
-}
-
-func TestLinkCompletionHandler(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply pkg/odo/util/completion/completionhandlers_test.go:217]: Recorded an issue

**Comment by valaparthvi** [comment]
@mohammedzee1000 I am curious, why have you not removed the serviceCatalog references from the kclient package?
https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/kclient/serviceCatalog.go
https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/kclient/serviceCatalog_test.go

**Comment by mohammedzee1000** [comment]
> @mohammedzee1000 I am curious, why have you not removed the serviceCatalog references from the kclient package? Are they still relevant or are you planning to take them up in part 2?
> https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/kclient/serviceCatalog.go
> https://github.com/mohammedzee1000/odo/blob/remove_service_catalog/pkg/kclient/serviceCatalog_test.go

Yes, there are still usages in link and unlink and both should be dropped simultanously

**Review by valaparthvi — APPROVED** [review]
No major changes have been made to the integration tests (except that of Service Catalog's) and they are all passing; all the remaining references will be removed in the next PR, hence I'm approving this PR.
