### PR TITLE
Fails if user tries to unset invalid environment variable

### LINKED ISSUE #2274: unsetting of a none existing env var in local config does not report error
[kind/bug]

## What versions of software are you using?
- Operating System: All
- Output of `odo version`: master

## How did you run odo exactly?
```
$ odo component create python
 ✓  Validating component [494ms]
Please use `odo push` command to create the component with source deployed

$ odo config unset --env DB
Environment variables were successfully updated.

```

## Actual behavior
Graceful exit with a message of ```Environment variables were successfully updated.```

## Expected behavior
Should report error. For example 
```
Environment variables not found
```

### PR DESCRIPTION
**Pull request by dharmit**
## What is the purpose of this change? What does it change?

At the moment, there's no check for the scenario where a user tries to unset an environment variable that doesn't exist in the configuration. This PR aims to fix that and fails the execution.

## Was the change discussed in an issue?
fixes #2274 

## How to test changes?

* Create a component
* Try to unset an environment variable that doesn't exist in component's config: `odo config unset --env nosuchvar`.

### CODE REVIEW

File: pkg/config/env_var_test.go [hunk 1]
```diff
@@ -205,15 +206,29 @@ func TestRemoveEnvVarsFromList(t *testing.T) {
 			expected: EnvVarList{},
 			keys:     []string{"foo"},
 		},
+		{
+			envVarList: EnvVarList{},
+			expected:   EnvVarList{},
+			keys:       []string{"nosuchenv"},
```
Comment (girishramnani) [inline pkg/config/env_var_test.go]: In case of an error `nil` is expected @dharmit

Comment (girishramnani) [reply pkg/config/env_var_test.go]: Or you can consider return an empty EnvVarList i.e. `newEnVarList` to retain the behavior

File: pkg/config/env_var_test.go [hunk 2]
```diff
@@ -205,15 +206,29 @@ func TestRemoveEnvVarsFromList(t *testing.T) {
 			expected: EnvVarList{},
 			keys:     []string{"foo"},
 		},
+		{
+			envVarList: EnvVarList{},
+			expected:   EnvVarList{},
```
Comment (girishramnani) [inline pkg/config/env_var_test.go]: This should be `nil`

Comment (girishramnani) [reply pkg/config/env_var_test.go]: 211 line `expected: nil`

File: pkg/config/env_var.go [hunk 3]
```diff
@@ -84,15 +84,20 @@ func NewEnvVarListFromSlice(envList []string) (EnvVarList, error) {
...
 	for _, envVar := range envVarList {
 		// if the env is in the keys we skip it
 		if util.In(keys, envVar.Name) {
+			envVarInList = true
 			continue
 		}
 
 		newEnvVarList = append(newEnvVarList, envVar)
 	}
-	return newEnvVarList
```
Comment (girishramnani) [inline pkg/config/env_var.go]: Check this line, before this function returned a EnvVarList for everycase. Now there is two cases. One where it returns the list and nil error. And another where it returns nil and error

File: pkg/config/env_var.go [hunk 4]
```diff
@@ -84,15 +84,20 @@ func NewEnvVarListFromSlice(envList []string) (EnvVarList, error) {
 
 // RemoveEnvVarsFromList removes the env variables based on the keys provided
 // and returns a new EnvVarList
-func RemoveEnvVarsFromList(envVarList EnvVarList, keys []string) EnvVarList {
+func RemoveEnvVarsFromList(envVarList EnvVarList, keys []string) (EnvVarList, error) {
+	envVarInList := false
```
Comment (girishramnani) [inline pkg/config/env_var.go]: This will stay false if the keys is an empty list and hence throw error

Comment (girishramnani) [reply pkg/config/env_var.go]: @dharmit add a check for the `keys` length. If its 0 then we return the same list without any error

**Comment by girishramnani** [comment]
All of my comments have been addressed - message to whoever reviews this PR

**Comment by dharmit** [comment]
/retest 

All failures related to yum:
```
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again
error: build error: running 'yum -y install make wget gcc git httpd-tools' failed with exit code 1
```

**Comment by girishramnani** [comment]
unit test failure seems like a platform flake [url](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2275/pull-ci-openshift-odo-master-v4.1-unit/454), so rerunning 
/test unit

**Comment by girishramnani** [comment]
v4.1 integration seems to also have the same platform issue

/test v4.1-unit
/test v4.1-integration

**Comment by girishramnani** [comment]
/test v4.1-benchmark 
link - https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2275/pull-ci-openshift-odo-master-v4.1-benchmark/472

/test v4.1-e2e-scenarios
link - https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2275/pull-ci-openshift-odo-master-v4.1-e2e-scenarios/492

 as well show the same error.
But in the v4.2 integration test, odo project command tests, seems to have a flaky test on odo side - the project didn't show up in the list after creation.
```
Running odo with args [odo project delete ikiydcpzex -f]
[odo]  •  Deleting project ikiydcpzex  ...
[odo]  ✓  Deleting project ikiydcpzex [6s]
[odo]  ✓  Deleted project : ikiydcpzex
Deleting dir: /tmp/799583864

[91m[1m• Failure [7.997 seconds][0m
[90m/go/src/github.com/openshift/odo/tests/integration/project/cmd_project_test.go:13[0m
  when running project command app parameter in directory that doesn't contain .odo config directory
  [90m/go/src/github.com/openshift/odo/tests/integration/project/cmd_project_test.go:41[0m
    [91m[1mshould successfully execute list along with machine readable output [It][0m
    [90m/go/src/github.com/openshift/odo/tests/integration/project/cmd_project_test.go:42[0m

    [91mExpected
        <string>: ACTIVE     NAME
                   drsbsxyaju
                   gmktltcicr
                   myproject
        
    to contain substring
        <string>: ikiydcpzex[0m
```

**Comment by girishramnani** [comment]
recorded the flake in the issue, rerunning the v4.2 integration test to check 
/test v4.2-integration

File: pkg/config/env_var.go [hunk 5]
```diff
@@ -84,15 +84,25 @@ func NewEnvVarListFromSlice(envList []string) (EnvVarList, error) {
...
 			continue
 		}
 
 		newEnvVarList = append(newEnvVarList, envVar)
 	}
-	return newEnvVarList
+	if envVarInList {
+		return newEnvVarList, nil
+	}
+	return nil, errors.New(fmt.Sprintf("Cannot find environment variable in the component's configuration.\nCheck `odo config view` to confirm it exists."))
```
Comment (golangcibot) [inline pkg/config/env_var.go]: S1028: should use fmt.Errorf(...) instead of errors.New(fmt.Sprintf(...)) (from `gosimple`)

Comment (dharmit) [reply pkg/config/env_var.go]: Wow, the bot seems really smart! @kadel @girishramnani do you guys think this suggestion is worth implementing? Should I change the code?

Comment (girishramnani) [reply pkg/config/env_var.go]: yes I would say the approach is cleaner

**Comment by dharmit** [comment]
```
[Fail] odo project command tests when running project command app parameter in directory that doesn't contain .odo config directory [It] should successfully execute list along with machine readable output 
/go/src/github.com/openshift/odo/tests/integration/project/cmd_project_test.go:44
Ran 2 of 2 Specs in 13.556 seconds
FAIL! -- 1 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestProject (13.56s)
FAIL
```
looks like a flake
/test v4.1-integration

**Comment by dharmit** [comment]
Looks like one more flake to me. But it's weird - how can I be hitting flakes again and again? 

@amitkrout can you please help? Am I right in judging these issues (also look at past two comments besides this one) to be flakes? :thinking: 

```
• Failure [38.873 seconds]
odo component command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_test.go:13
  Creating component
  /go/src/github.com/openshift/odo/tests/integration/component.go:61
    should create the component from the branch ref when provided [It]
```

**Comment by amitkrout** [comment]
> Looks like one more flake to me. But it's weird - how can I be hitting flakes again and again?
> 
> @amitkrout can you please help? Am I right in judging these issues (also look at past two comments besides this one) to be flakes? 🤔
> 
> ```
> • Failure [38.873 seconds]
> odo component command tests
> /go/src/github.com/openshift/odo/tests/integration/cmd_cmp_test.go:13
>   Creating component
>   /go/src/github.com/openshift/odo/tests/integration/component.go:61
>     should create the component from the branch ref when provided [It]
> ```

#1955 
/retest

**Comment by amitkrout** [comment]
> ```
> [Fail] odo project command tests when running project command app parameter in directory that doesn't contain .odo config directory [It] should successfully execute list along with machine readable output 
> /go/src/github.com/openshift/odo/tests/integration/project/cmd_project_test.go:44
> Ran 2 of 2 Specs in 13.556 seconds
> FAIL! -- 1 Passed | 1 Failed | 0 Pending | 0 Skipped
> --- FAIL: TestProject (13.56s)
> FAIL
> ```
> 
> looks like a flake
> /test v4.1-integration

#2298

**Comment by dharmit** [comment]
@amitkrout thanks for picking that up. It's affecting the `odo config set --env` as well (which is not a part of this PR):
```sh
# when using zsh
$ odo config set --env ""=hello
zsh: hello not found

# now switch to bash
$ bash

$ odo config set --env ""=hello
Environment variables were successfully updated.
Run `odo push --config` command to apply changes to the cluster.
[dshah@think nodejs-ex]$ odo config view
ENVIRONMENT VARIABLES
------------------------------------------------
NAME    VALUE
        hello

COMPONENT SETTINGS
------------------------------------------------
PARAMETER         CURRENT_VALUE
Type              nodejs
Application       app
Project           myproject
SourceType        local
Ref               
SourceLocation    ./
Ports             8080/TCP
Name              nodejs-nodejs-ex-fsfk
MinMemory         
MaxMemory         
DebugPort         
Ignore            
MinCPU            
MaxCPU            
```

**Comment by dharmit** [comment]
@amitkrout I don't think I'll be able to address the empty name for environment variable in this PR. It looks trivial but from code point of view (specifically when adding tests), it's not so trivial. So, if you and the team can review this PR for what it's trying to fix, that would be very helpful. 

I have opened an issue based on what you reported and we can take the discussion forward there, IMO. #2322

**Comment by amitkrout** [comment]
> @amitkrout I don't think I'll be able to address the empty name for environment variable in this PR. It looks trivial but from code point of view (specifically when adding tests), it's not so trivial. So, if you and the team can review this PR for what it's trying to fix, that would be very helpful.
> 
> I have opened an issue based on what you reported and we can take the discussion forward there, IMO. #2322

@dharmit These cases were missing in the UTs of you pr, so i try it out. Anyway will track those missing cases in #2322. The funny part is that you follow the doc [1] unknowingly i guess ;)

[1] https://testing.googleblog.com/2015/04/just-say-no-to-more-end-to-end-tests.html
