### PR TITLE
fix odo compatibility with SBO 0.7.0

### LINKED ISSUE #4612: broken odo link
```
▶ odo service list
NAME                AGE
MariaDB/mariadb     17m10s

▶ odo link MariaDB/mariadb
 ✓  Successfully created link between component "springboot" and service "MariaDB/mariadb"

To apply the link, please use `odo push`

▶ odo push
 ✓  Waiting for component to start [9ms]

Validation
 ✓  Validating the devfile [23800ns]

Creating Kubernetes resources for component springboot
 ✗  Failed to start component with name springboot. Error: Failed to create the component: unable to create or update component: pvc not found for mount path springboot-mariadb-mariadb

```

using SBO  0.7.0

```
▶ odo version
odo v2.1.0 (6040118b0)
```

/priority critical

### PR DESCRIPTION
**Pull request by kadel**
**What type of PR is this?**

/kind bug

**What does this PR do / why we need it**:

see https://github.com/openshift/odo/issues/4612#issuecomment-818805977

**Which issue(s) this PR fixes**:

Fixes #4612

I had to do more changes and stop using SBO types because the new SBO version uses a newer k8s API which is not compatible with the one that we are currently using. 
I switched to generic `k8s.io/apimachinery/pkg/apis/meta/v1/unstructured` for the SeriviceBinding resource in order to avoid vendoring Service Binding source code. 

If we decided that we want to keep using SBO types, we can move back once we update all our dependencies to OpenShift 4.7. This will be done as part of #4553.

This is what you get if you try service-binding-operator@v0.7.0 with the current odo version (6040118b0)

```
▶ go get github.com/redhat-developer/service-binding-operator@v0.7.0
# github.com/redhat-developer/service-binding-operator/pkg/binding
../../../go/pkg/mod/github.com/redhat-developer/service-binding-operator@v0.7.0/pkg/binding/spec.go:63:142: cannot use context.TODO() (type context.Context) as type string in argument to client.Resource(schema.GroupVersionResource{...}).Namespace(namespace).Get
../../../go/pkg/mod/github.com/redhat-developer/service-binding-operator@v0.7.0/pkg/binding/spec.go:63:142: cannot use name (type string) as type v1.GetOptions in argument to client.Resource(schema.GroupVersionResource{...}).Namespace(namespace).Get
../../../go/pkg/mod/github.com/redhat-developer/service-binding-operator@v0.7.0/pkg/binding/spec.go:63:165: cannot use v1.GetOptions{} (type v1.GetOptions) as type string in argument to client.Resource(schema.GroupVersionResource{...}).Namespace(namespace).Get
../../../go/pkg/mod/github.com/redhat-developer/service-binding-operator@v0.7.0/pkg/binding/spec.go:69:139: cannot use context.TODO() (type context.Context) as type string in argument to client.Resource(schema.GroupVersionResource{...}).Namespace(namespace).Get
../../../go/pkg/mod/github.com/redhat-developer/service-binding-operator@v0.7.0/pkg/binding/spec.go:69:139: cannot use name (type string) as type v1.GetOptions in argument to client.Resource(schema.GroupVersionResource{...}).Namespace(namespace).Get
../../../go/pkg/mod/github.com/redhat-developer/service-binding-operator@v0.7.0/pkg/binding/spec.go:69:162: cannot use v1.GetOptions{} (type v1.GetOptions) as type string in argument to client.Resource(schema.GroupVersionResource{...}).Namespace(namespace).Get
# github.com/redhat-developer/service-binding-operator/api/v1alpha1
../../../go/pkg/mod/github.com/redhat-developer/service-binding-operator@v0.7.0/api/v1alpha1/conditions.go:16:44: undefined: v1.Condition
../../../go/pkg/mod/github.com/redhat-developer/service-binding-operator@v0.7.0/api/v1alpha1/conditions.go:17:10: undefined: v1.Condition
../../../go/pkg/mod/github.com/redhat-developer/service-binding-operator@v0.7.0/api/v1alpha1/servicebinding_types.go:118:15: undefined: v1.Condition
../../../go/pkg/mod/github.com/redhat-developer/service-binding-operator@v0.7.0/api/v1alpha1/zz_generated.deepcopy.go:242:17: undefined: v1.Condition
# sigs.k8s.io/controller-runtime/pkg/metrics
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/metrics/client_go_adapter.go:133:25: undefined: metrics.RegisterOpts
# sigs.k8s.io/controller-runtime/pkg/client
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/client/metadata_client.go:68:22: cannot use ctx (type context.Context) as type string in argument to resInt.Delete
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/client/metadata_client.go:68:36: cannot use metadata.ObjectMeta.Name (type string) as type *v1.DeleteOptions in argument to resInt.Delete
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/client/metadata_client.go:68:43: cannot use *deleteOpts.AsDeleteOptions() (type v1.DeleteOptions) as type string in argument to resInt.Delete
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/client/metadata_client.go:86:32: too many arguments in call to resInt.DeleteCollection
        have (context.Context, v1.DeleteOptions, v1.ListOptions)
        want (*v1.DeleteOptions, v1.ListOptions)
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/client/metadata_client.go:108:26: cannot use ctx (type context.Context) as type string in argument to resInt.Patch
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/client/metadata_client.go:108:40: cannot use metadata.ObjectMeta.Name (type string) as type types.PatchType in argument to resInt.Patch
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/client/metadata_client.go:108:57: cannot use patch.Type() (type types.PatchType) as type []byte in argument to resInt.Patch
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/client/metadata_client.go:108:57: cannot use data (type []byte) as type v1.PatchOptions in argument to resInt.Patch
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/client/metadata_client.go:108:67: cannot use *patchOpts.AsPatchOptions() (type v1.PatchOptions) as type string in argument to resInt.Patch
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/client/metadata_client.go:131:24: cannot use ctx (type context.Context) as type string in argument to resInt.Get
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/client/metadata_client.go:131:24: too many errors
````

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

File: pkg/kclient/deployments.go [hunk 1]
```diff
@@ -226,6 +226,9 @@ func (c *Client) CreateDynamicResource(exampleCustomResource map[string]interfac
 		Object: exampleCustomResource,
 	}
 
+	debugOut, _ := json.MarshalIndent(deployment, " ", " ")
```
Comment (dharmit) [inline pkg/kclient/deployments.go:229]: What's the purpose of this code? Can you add a comment?

**Comment by dharmit** [comment]
Looks like infra errors to me - [link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4613/pull-ci-openshift-odo-master-v4.7-integration-e2e/1382024337128689664)

/test v4.7-integration-e2e

File: go.mod [hunk 2]
```diff
@@ -35,14 +38,12 @@ require (
...
 	github.com/openshift/api v3.9.1-0.20190924102528-32369d4db2ad+incompatible
 	github.com/openshift/client-go v0.0.0-20200116152001-92a2713fa240
-	github.com/openshift/custom-resource-status v0.0.0-20200602122900-c002fd1547ca // indirect
 	github.com/openshift/library-go v0.0.0-20200407165825-2e79bd232e72
 	github.com/openshift/oc v0.0.0-alpha.0.0.20200305142246-2576e482bf00
 	github.com/operator-framework/operator-lifecycle-manager v0.0.0-20200422144016-a6acf50218ed
 	github.com/pborman/uuid v1.2.0
 	github.com/pkg/errors v0.9.1
 	github.com/posener/complete v1.1.2
-	github.com/redhat-developer/service-binding-operator v0.3.0
```
Comment (dharmit) [inline go.mod:45]: Instead of removing the dependency, can we try updating this to 0.7.0?

**Comment by dharmit** [comment]
I'm trying to test the changes in this PR using the [node-todo]https://github.com/akashshinde/node-todo) + EtcdCluster example that I have used successfully numerous times in the past. But it's not working out this time.

Even following the steps mentioned on [SBO website](https://github.com/redhat-developer/service-binding-operator/tree/master/examples/nodejs_etcd_operator) don't help me.

How have you tested the changes in this PR? By checking if the `envFrom` is set correctly? That actually works so I think that technically the changes in this PR are successfully doing `odo link`. It's just that I can't play with a real example that I used to play with in the past.

**Comment by dharmit** [comment]
Not sure what the error is about in CI. @anandrkskd @prietyc123 can you help - [link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4613/pull-ci-openshift-odo-master-v4.7-integration-e2e/1382190726212751360) & https://github.com/openshift/odo/pull/4613#issuecomment-819221001

**Comment by prietyc123** [comment]
> Looks like infra errors to me - [link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4613/pull-ci-openshift-odo-master-v4.7-integration-e2e/1382024337128689664)
> 
> /test v4.7-integration-e2e

Yes, its platform error.

File: go.mod (hunk 2 above)
Comment (kadel) [reply go.mod:45]: Check my description of this PR. We can't update to 0.7.0 because it would require updating OpenShift and Kubernetes dependencies which will require larger code change.

File: pkg/kclient/deployments.go (hunk 1 above)
Comment (kadel) [reply pkg/kclient/deployments.go:229]: this is for debugging and verbose output.  I don't think that this needs a comment.

**Comment by kadel** [comment]
> I'm trying to test the changes in this PR using the [node-todo](https://github.com/akashshinde/node-todo) + EtcdCluster example that I have used successfully numerous times in the past. But it's not working out this time.

Why it is not working? Any errors?

**Comment by kadel** [comment]
/retest ci/prow/v4.7-integration-e2e 

Looks like an issue in CI cluster

```
ERRO[2021-04-14T06:56:07Z]   * could not run steps: step integration-e2e failed: "integration-e2e" post steps failed: "integration-e2e" pod "integration-e2e-gather-aws-console" failed: the pod ci-op-jgm36xvy/integration-e2e-gather-aws-console failed after 10s (failed containers: test): ContainerFailed one or more containers exited 
```

**Comment by dharmit** [comment]
> Why it is not working? Any errors?

`(node:27) UnhandledPromiseRejectionWarning: GRPCConnectFailedError: 14 UNAVAILABLE: failed to connect to all addresses`. I guess it's something on the application side.

File: go.mod (hunk 2 above)
Comment (dharmit) [reply go.mod:45]: My concern is that SBO is in alpha stage right now. Till a GA is out, they can break compatibility. And on the odo side, we're playing catch-up game since a long time now.

My understanding is that they would be doing a GA soon. Correct me if I am wrong. When the GA is out, we can make the changes that makes odo compatible with the _**stable**_ version, no?

If it requires a larger code change then let's do that larger code change. But let's do it by following the SB struct provided by the library. In this case, we're adding a bunch of things to the unstructured struct. The problem with that, IMO, is that it requires understanding of different fields in the SB struct and can't rely on IDE.

Also, this would be setting incorrect precedence, IMO. It'll later pop up as more PRs doing things like this. Today to stay compatible with SBO, tomorrow to stay compatible with `devfile/library`.

If my concern sounds like over-thinking, I'm fine by doing lgtm. Let me know. 😄

Comment (kadel) [reply go.mod:45]: We need to fix this ASAP. because more and more clusters will update to 0.7.0 and `odo link` is broken there.
If we release odo without this fixed link will be unusable on new clusters. 
I'm working on a larger code change as part of #4553 because that will require this update as well. But this will take a little bit longer and there are a lot of things that can break while doing this. 
This is why I take this approach so we can merge it before 2.1.0 release

**Review by dharmit — APPROVED** [review]

File: go.mod (hunk 2 above)
Comment (dharmit) [reply go.mod:45]: That makes sense. 👍🏽
LGTM'd.

**Comment by kadel** [comment]
/hold

@dharmit doesn't like this fix. I'm looking into one other option

**Comment by kadel** [comment]
> > Why it is not working? Any errors?
> 
> ```
> (node:27) UnhandledPromiseRejectionWarning: GRPCConnectFailedError: 14 UNAVAILABLE: failed to connect to all addresses
> ```
> 
> I guess it's something on the application side.

`evnFrom` is correctly set in Deployment?

**Comment by dharmit** [comment]
> > > Why it is not working? Any errors?
> > 
> > 
> > ```
> > (node:27) UnhandledPromiseRejectionWarning: GRPCConnectFailedError: 14 UNAVAILABLE: failed to connect to all addresses
> > ```
> > 
> > 
> > I guess it's something on the application side.
> 
> `evnFrom` is correctly set in Deployment?

Yes, I saw it being set correctly in the Pod (not Deployment).

**Comment by kadel** [comment]
> /hold
> 
> @dharmit doesn't like this fix. I'm looking into one other option.
> 
> It could be possible to switch just to SBO v0.4.0 where `bindAsFiles` was first introduced.

Using v0.4.0 doesn't work either. Problem is that `bindAsFiles` has `json` tag `omitempty` so if it is set to `false` it is considered empty and `json.Marshal` won't populate that field. And if `bindAsFiles` is not populated in new SBO version it is considered `true`.
 
Working around this would require changing how `CreateDynamicResource` works right now or using `unstructured` 


@dharmit I'm opened to other suggestions.

**Comment by dharmit** [comment]
> Using v0.4.0 doesn't work either. Problem is that `bindAsFiles` has `json` tag `omitempty` so if it is set to `false` it is considered empty and `json.Marshal` won't populate that field. And if `bindAsFiles` is not populated in new SBO version it is considered `true`.

Can we categorically set it to `false`?
```go
o.serviceBinding.Spec.BindAsFiles = false
```

I'm suggesting this based on what's [proposed in another PR](https://github.com/openshift/odo/pull/4535/files#diff-12f5658caac39ad7a467247dfc3c8ea4d5c08f3f2b9d46a657be8b02c3e50068R125).

**Comment by dharmit** [comment]
/hold cancel

> Can we categorically set it to `false`?
> 
> ```go
> o.serviceBinding.Spec.BindAsFiles = false
> ```
> 
> I'm suggesting this based on what's [proposed in another PR](https://github.com/openshift/odo/pull/4535/files#diff-12f5658caac39ad7a467247dfc3c8ea4d5c08f3f2b9d46a657be8b02c3e50068R125).

This can't be done unless we update SBO library in go.mod and as you mentioned already, it's a large task to do right now. #4614
