### PR TITLE
Fixes odo describe for multiple URLs of unpushed component

### LINKED ISSUE #2776: 'odo describe' fails for component with two URLs with 'panic: runtime error: index out of range' error
/kind bug

## What versions of software are you using?

**Operating System:** 
Windows 10
**Output of `odo version`:**
odo v1.1.1 (02fbd3d08)

## How did you run odo exactly?
Not pushed git component with two URLs.

## Actual behavior
```
> odo.exe" describe
Component Name: nodejs-ex-git
Type: nodejs:10
Source: https://github.com/dgolovin/nodejs-ex
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/openshift/odo/pkg/odo/util.PrintComponentInfo(0xc0007afe00, 0xc0001cfab0, 0xd, 0x1befd6d, 0x9, 0x1c09821, 0x19, 0xc0001cfab0, 0xd, 0x0, ...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/util/cmdutils.go:144 +0x151a
github.com/openshift/odo/pkg/odo/cli/component.(*DescribeOptions).Run(0xc000830300, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/describe.go:86 +0x2f1
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x1f2a920, 0xc000830300, 0xc0008a8900, 0x3285110, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x143
github.com/openshift/odo/pkg/odo/cli/component.NewCmdDescribe.func1(0xc0008a8900, 0x3285110, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/describe.go:104 +0x65
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc0008a8900, 0x3285110, 0x0, 0x0, 0xc0008a8900, 0x3285110)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x290
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0006c9b00, 0x1d1bfd0, 0xc000074b40, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x2d1
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:75 +0x46a
```

## Expected behavior
Prints out two urls.

## Any logs, error output, etc?
N/A

### PR DESCRIPTION
**Pull request by dharmit**
**What type of PR is this?**
/kind bug

**What does does this PR do / why we need it**:
This PR fixes two bugs. One is panic when doing `odo describe` for an unpushed component that has more URLs than number of ports it exposes. Another is the incorrect mapping of URL and port. Refer https://github.com/openshift/odo/issues/2776#issuecomment-620040493 for more detail

**Which issue(s) this PR fixes**:

Fixes #2776 

**How to test changes / Special notes to the reviewer**:
Create more URLs than the number of exposed ports for a component and run `odo describe`.

### CODE REVIEW

File: pkg/component/component.go [hunk 1]
```diff
@@ -963,6 +974,15 @@ func GetComponentFromConfig(localConfig *config.LocalConfigInfo) (Component, err
 	return Component{}, nil
 }
 
+func getPortsProtocol(ports []string) map[string]string {
```
Comment (girishramnani) [inline pkg/component/component.go:977]: maybe a better name for this? `getPortProtocolMapping` and a small comment like `this is a mapping for ports => Protocol`?

**Comment by girishramnani** [comment]
a genuine unit test failure
```
--- FAIL: TestGetComponentFromConfig (0.00s)
    --- FAIL: TestGetComponentFromConfig/case_1:_config_file_exists (0.00s)
        component_test.go:754: the component spec is different, want: {app nodejs file://./ local [example-url-0 example-url-1] [example-storage-0 example-storage-1] [{env-0 value-0 nil} {env-1 value-1 nil}] [8080/TCP,45/UDP]},
             got: {app nodejs file://./ local [example-url-0 example-url-1] [example-storage-0 example-storage-1] [{env-0 value-0 nil} {env-1 value-1 nil}] [8080/TCP,45 45/]}
    --- FAIL: TestGetComponentFromConfig/case_3:_config_file_exists (0.00s)
        component_test.go:754: the component spec is different, want: {app nodejs https://example.com git [example-url-0 example-url-1] [example-storage-0 example-storage-1] [{env-0 value-0 nil} {env-1 value-1 nil}] [8080/TCP,45/UDP]},
             got: {app nodejs https://example.com git [example-url-0 example-url-1] [example-storage-0 example-storage-1] [{env-0 value-0 nil} {env-1 value-1 nil}] [8080/TCP,45 45/]}
FAIL
```

**Comment by girishramnani** [comment]
also can we have a unit test where there are 3 ports defined for a component and we have 2 and 4 urls created for them, essential a more complex unit test targeted to multiple urls?

**Comment by dharmit** [comment]
> a genuine unit test failure
> 
> ```
> --- FAIL: TestGetComponentFromConfig (0.00s)
>     --- FAIL: TestGetComponentFromConfig/case_1:_config_file_exists (0.00s)
>         component_test.go:754: the component spec is different, want: {app nodejs file://./ local [example-url-0 example-url-1] [example-storage-0 example-storage-1] [{env-0 value-0 nil} {env-1 value-1 nil}] [8080/TCP,45/UDP]},
>              got: {app nodejs file://./ local [example-url-0 example-url-1] [example-storage-0 example-storage-1] [{env-0 value-0 nil} {env-1 value-1 nil}] [8080/TCP,45 45/]}
>     --- FAIL: TestGetComponentFromConfig/case_3:_config_file_exists (0.00s)
>         component_test.go:754: the component spec is different, want: {app nodejs https://example.com git [example-url-0 example-url-1] [example-storage-0 example-storage-1] [{env-0 value-0 nil} {env-1 value-1 nil}] [8080/TCP,45/UDP]},
>              got: {app nodejs https://example.com git [example-url-0 example-url-1] [example-storage-0 example-storage-1] [{env-0 value-0 nil} {env-1 value-1 nil}] [8080/TCP,45 45/]}
> FAIL
> ```

Changing the `portsValue := []string{"8080/TCP,45/UDP"}` to `portsValue := []string{"8080/TCP", "45/UDP"}` makes the test pass locally. I'm kind of confused as to what's the expectation here from the tests. :disappointed: 

What should I set the ports value to in `.odo/config.yaml` to play with this?

**Comment by dharmit** [comment]
> also can we have a unit test where there are 3 ports defined for a component and we have 2 and 4 urls created for them, essential a more complex unit test targeted to multiple urls?

Based on our discussion yesterday, I am apprehensive of doing this because we found that there are flaws in this package at a base level and we're not redesigning it only because `.odo/config.yaml` approach is going to be deprecated soon.

I'd try to accommodate what you've suggested/requested but I'm not promising it. More so because I don't understand how to circumvent the existing test failure https://github.com/openshift/odo/pull/3008#issuecomment-620387229.

File: pkg/component/component.go (hunk 1 above)
Comment (dharmit) [reply pkg/component/component.go]: Ack. Makes sense. Done.

File: pkg/component/component.go [hunk 2]
```diff
@@ -970,6 +981,18 @@ func GetComponentFromConfig(localConfig *config.LocalConfigInfo) (Component, err
...
 }
 
+// This function returns a mapping of port and protocol.
+// So for a value of ports {"8080/TCP", "45/UDP"} it will return a map {"8080":
+// "TCP", "45": "UDP"}
+func getPortsProtocolMapping(ports []string) map[string]string {
+	oldPortsProtocol := make(map[string]string, len(ports))
+	for _, port := range ports {
+		portProtocol := strings.Split(port, "/")
+		oldPortsProtocol[portProtocol[0]] = portProtocol[1]
```
Comment (mik-dass) [inline pkg/component/component.go:991]: this will panic if the mappings are incorrect
```
[mrinaldas@localhost nodejs-ex]$ odo config set ports 909,808 -f
 ✓  Local config successfully updated

Run `odo push --config` command to apply changes to the cluster
[mrinaldas@localhost nodejs-ex]$ odo describe 
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/openshift/odo/pkg/component.getPortsProtocolMapping(0xc0006136c0, 0x2, 0x2, 0x0)
        /home/mrinaldas/go/src/github.com/openshift/odo/pkg/component/component.go:991 +0x177
github.com/openshift/odo/pkg/component.GetComponentFromConfig(0xc000ba7500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/mrinaldas/go/src/github.com/openshift/odo/pkg/component/component.go:962 +0x6d6
github.
```

Comment (dharmit) [reply pkg/component/component.go:991]: There never was a check for this in the first place. IMO, we should add it in the documentation of `odo config set -h` so that users don't hit this.

Comment (mik-dass) [reply pkg/component/component.go:991]: Yeah we need to document this and I think should add a check to config set ports too.

Comment (dharmit) [reply pkg/component/component.go:991]: > Yeah we need to document this

Done. I'll push the change. But here's how it looks:
```sh
Examples:

  # Set a configuration value in the local config
  odo config set Type java
  odo config set Name test
  odo config set MinMemory 50M
  odo config set MaxMemory 500M
  odo config set Memory 250M
  odo config set DebugPort 4040
  odo config set Ignore false
  odo config set MinCPU 0.5
  odo config set MaxCPU 2
  odo config set CPU 1
  odo config set Ports 8080/TCP,8443/TCP    <<------- this
  
  # Set a env variable in the local config
  odo config set --env KAFKA_HOST=kafka --env KAFKA_PORT=6639
```

> I think should add a check to config set ports too.

I'd prefer a separate issue to work this out.

Comment (mik-dass) [reply pkg/component/component.go:991]: > I'd prefer a separate issue to work this out.

Cool :+1: Please open a issue so that we don't forget about it

Comment (dharmit) [reply pkg/component/component.go:991]: https://github.com/openshift/odo/issues/3036
