### PR TITLE
Fixes no default build command error.

### LINKED ISSUE #4363: build command should be optional
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?
devfile without default build command

```
▶ odo push

Validation
 ✗  Validating the devfile [222784ns]
 ✗  Failed to start component with name java-jboss-eap-xp. Error: Failed to create the component: failed to validate devfile build and run commands:
there should be exactly one default command for command group build, currently, there is no default command
```

## Expected behavior
Odo should not fail in this case. default build command should be optional. 
In that case, should simply skip the build step. There are valid use cases for this. For example, some of the interpreted languages don't require a build step, or some frameworks with hot reload can handle rebuilds themself.

 
/bug 
/priority high

### PR DESCRIPTION
**Pull request by mik-dass**
**What type of PR is this?**

/kind bug

**What does does this PR do / why we need it**:

It introduces two error types called NoDefaultForGroup and MoreDefaultForGroup.

**Which issue(s) this PR fixes**:

Fixes #4363 

**PR acceptance criteria**:

- [X] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

- Create a component and remove the `build` kind command from the devfile.
- `odo push` should pass.

### CODE REVIEW

File: pkg/devfile/adapters/common/command.go [hunk 1]
```diff
@@ -147,29 +147,42 @@ func validateCommandsForGroup(data data.DevfileData, groupType devfilev1.Command
...
 
 	return nil
 }
 
 // GetBuildCommand iterates through the components in the devfile and returns the build command
 func GetBuildCommand(data data.DevfileData, devfileBuildCmd string) (buildCommand devfilev1.Command, err error) {
+	supportedCommand, err := getCommand(data, devfileBuildCmd, devfilev1.BuildCommandGroupKind)
+	// since build command is not necessary
+	// check if we can ignore it
+	if _, ok := err.(NoDefaultForGroup); ok {
```
Comment (dharmit) [inline pkg/devfile/adapters/common/command.go:169]: Should there be an `else` block covering the case when error is something other than `NoDefaultForGroup`?

File: pkg/devfile/adapters/common/command.go [hunk 2]
```diff
@@ -147,29 +147,42 @@ func validateCommandsForGroup(data data.DevfileData, groupType devfilev1.Command
...
+	return supportedCommand, err
 }
 
 // GetDebugCommand iterates through the components in the devfile and returns the debug command
 func GetDebugCommand(data data.DevfileData, devfileDebugCmd string) (debugCommand devfilev1.Command, err error) {
-	return getCommand(data, devfileDebugCmd, devfilev1.DebugCommandGroupKind)
+	supportedCommand, err := getCommand(data, devfileDebugCmd, devfilev1.DebugCommandGroupKind)
+	// since debug command is not necessary
+	// check if we can ignore it
+	if _, ok := err.(NoDefaultForGroup); ok {
```
Comment (dharmit) [inline pkg/devfile/adapters/common/command.go:181]: Same question - should there be an `else` block?

**Review by dharmit — COMMENTED** [review]
Just a question. Looks good otherwise.

File: pkg/devfile/adapters/common/command.go (hunk 1 above)
Comment (mik-dass) [reply pkg/devfile/adapters/common/command.go]: Updated the logic

File: pkg/devfile/adapters/common/command.go (hunk 2 above)
Comment (mik-dass) [reply pkg/devfile/adapters/common/command.go]: same as https://github.com/openshift/odo/pull/4430#discussion_r576113341

**Review by dharmit — APPROVED** [review]
/approve
/lgtm
