### PR TITLE
Fix odo fake component create on kubernetes cluster

### LINKED ISSUE #2888: Invalid devfile component create fails for devfile feature on kubernetes cluster
/kind bug
/area devfile

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## How did you run odo exactly?
```odo create fakeComponentName```

## Actual behavior

```
Running odo with args [odo create fake-component]
[odo] Experimental mode is enabled, use at your own risk
[odo] 
[odo] Validation
[odo]  •  Checking Devfile compatibility  ...
[odo]  ✗  Checking Devfile compatibility [13703ns]
[odo] 
[odo] Please run 'odo catalog list components' for a list of supported devfile component types
[odo]  ✗  the server could not find the requested resource (get imagestreams.image.openshift.io fake-component)
Deleting project: hywllfifwd
Running kubectl with args [kubectl delete namespaces hywllfifwd]
[kubectl] namespace "hywllfifwd" deleted
Setting current dir to: /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile
Deleting dir: /tmp/392710421
• Failure [3.229 seconds]
odo devfile create command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:13
  When executing odo create with an invalid devfile component
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:96
    should fail with please run 'odo catalog list components' [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:97
    Expected
        <string>:  ✗  the server could not find the requested resource (get imagestreams.image.openshift.io fake-component)
        
    to contain substring
        <string>: "fake-component" not found
```

## Expected behavior

It should reflect ```"fake-component" not found```

## Any logs, error output, etc?

Logs can be found in more detail : https://travis-ci.com/github/openshift/odo/jobs/319523643#L566

### PR DESCRIPTION
**Pull request by adisky**
Signed-off-by: adisky <adsharma@redhat.com>

**What type of PR is this?**
/kind bug

**What does does this PR do / why we need it**:
Do not execute  S2I related code on k8s cluster for .`odo component create` 

**Which issue(s) this PR fixes**:

Fixes  #2888 

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

File: pkg/odo/cli/component/create.go [hunk 1]
```diff
@@ -464,11 +464,17 @@ func (co *CreateOptions) Complete(name string, cmd *cobra.Command, args []string
...
 	// this populates the LocalConfigInfo as well
 	co.Context = genericclioptions.NewContextCreatingAppIfNeeded(cmd)
-
 	if err != nil {
 		return errors.Wrap(err, "failed intiating local config")
 	}
 
+	// Do not execute S2I specific code on Kubernetes Cluster
+	// return from here, if it is not an openshift cluster.
+	openshiftCluster, _ := co.Client.IsRouteSupported()
```
Comment (dharmit) [inline pkg/odo/cli/component/create.go:473]: I know it's not incorrect because k8s doesn't support routes, but we're hitting the bug because k8s doesn't support s2i while OpenShift does. Would it be a better idea to check if the backend cluster supports s2i instead of route?

This might even be a nitpick. :)

Comment (adisky) [reply pkg/odo/cli/component/create.go:473]: I was also skeptical about this , we could check for imagestreams resource, would that be fine??

Comment (dharmit) [reply pkg/odo/cli/component/create.go:473]: Yes, I think that should be a good idea. :+1:

Comment (adisky) [reply pkg/odo/cli/component/create.go]: Done.

File: pkg/occlient/occlient.go [hunk 2]
```diff
@@ -3277,6 +3277,29 @@ func (c *Client) IsRouteSupported() (bool, error) {
 	return false, nil
 }
 
+// IsImageStreamSupported checks if imagestream resource type is present on the cluster
+func (c *Client) IsImageStreamSupported() (bool, error) {
+
+	const ClusterVersionGroup = "image.openshift.io"
```
Comment (girishramnani) [inline pkg/occlient/occlient.go:3283]: can we clean this up by extracting `ClusterVersionGroup`,`Version` and `resourceName` as function parameters and the generalise it for everything?
Maybe even refactor `IsRouteSupported` to use the extracted function?

**Comment by prietyc123** [comment]
> New changes are detected. LGTM label has been removed.

/lgtm
