### PR TITLE
Describe services with multiple plans correctly 

### LINKED ISSUE #2488: "odo catalog describe service" fails for services with more than one plans
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** `master`

## How did you run odo exactly?
```sh
$ odo catalog describe service dh-rhpam-apb
 ✗  json: cannot unmarshal number into Go struct field ServicePlanParameter.Properties.default of type string

$ odo catalog describe service dh-galera-apb
 ✗  json: cannot unmarshal number into Go struct field ServicePlanParameter.Properties.default of type string

$ odo catalog describe service dh-import-vm-apb
 ✗  json: cannot unmarshal number into Go struct field ServicePlanParameter.Properties.default of type string

$ odo catalog describe service dh-hello-world-apb
  Name                           | dh-hello-world-apb                                     
  Bindable                       | false                                                  
  Operated by the broker         | openshift-automation-service-broker                    
  Short Description              | deploys hello-world web                                
                                 | application                                            
  Long Description               | A sample APB which deploys a                           
                                 | containerized Hello World web                          
                                 | application                                            
  Versions Available             | docker.io/ansibleplaybookbundle/hello-world:latest     
  Tags                           |                                                        
                                  
  PLANS                           
  ***********************        | *****************************************************  
  Name                           | default                                                
  -----------------              | -----------------                                      
  Display Name                   | Default                                                
  -----------------              | -----------------                                      
  Short Description              | A sample APB which deploys                             
                                 | Hello World                                            
  -----------------              | -----------------                                      
  Required Params without a      |                                                        
  default value                  |                                                        
  -----------------              | -----------------                                      
  Required Params with a default |                                                        
  value                          |                                                        
  -----------------              | -----------------                                      
  Optional Params                |                                                        
                                 |                                  
```
## Actual behavior
All of the services above, for which we're seeing the `✗  json: cannot unmarshal number into Go struct field ServicePlanParameter.Properties.default of type string` error, have multiple plans. Refer the logs below.

## Expected behavior
odo should successfully describe services with multiple plans.

## Any logs, error output, etc?
```sh
$ odo catalog list services                                                                        
NAME                         PLANS                                                                                                                                          
dh-galera-apb                persistent,ephemeral                                                                      
dh-hello-world-apb           default
dh-import-vm-apb             url,vmware,url-template,vmware-template
dh-rhpam-apb                 managed,immutable-mon,immutable-kie,authoring,trial
```

### PR DESCRIPTION
**Pull request by dharmit**
**What type of PR is this?**

/kind bug

**What does does this PR do / why we need it**:
`odo catalog describe service <service-name>` failed for plans where
value of `default` field was an integer. For example below would cause
the command to fail:

```

"instanceCreateParameterSchema": {
    "$schema": "http://json-schema.org/draft-04/schema",
    "additionalProperties": false,
    "properties": {
        "cluster_size": {
            "default": 1,
            "description": "Number of Elasticsearch instances that the cluster will consist of",
            "title": "Cluster size",
            "type": "integer"
        },
```
This PR fixes that issue.
**Which issue(s) this PR fixes**:

Fixes #2488 

**How to test changes / Special notes to the reviewer**:
Check that `odo catalog describe service <service-name>` works well for the services.

### CODE REVIEW

**Comment by dharmit** [comment]
```
--- FAIL: TestGetServiceClassAndPlans (0.00s)
    service_test.go:180: Different plan parameters value. Expected: [{PLAN_DATABASE_PASSWORD    {true string []}} {PLAN_DATABASE_URI   someuri {true string []}} {PLAN_DATABASE_USERNAME   name {true string []}} {SOME_OTHER   other {false string []}}] , got: [{PLAN_DATABASE_PASSWORD   <nil> {true string []}} {PLAN_DATABASE_URI   someuri {true string []}} {PLAN_DATABASE_USERNAME   name {true string []}} {SOME_OTHER   other {false string []}}]
    service_test.go:180: Different plan parameters value. Expected: [{PLAN_DATABASE_PASSWORD    {true string []}} {PLAN_DATABASE_USERNAME_2   user2 {true string []}}] , got: [{PLAN_DATABASE_PASSWORD   <nil> {true string []}} {PLAN_DATABASE_USERNAME_2   user2 {true string []}}]
FAIL
coverage: 75.6% of statements
FAIL    github.com/openshift/odo/pkg/service    0.094s
make: *** [test-coverage] Error 1
The command "make test-coverage" exited with 2.
```

The difference seems to be in the `PLAN_DATABASE_PASSWORD` (expected:  `PLAN_DATABASE_PASSWORD    {true string []}`, got: `PLAN_DATABASE_PASSWORD   <nil> {true string []`) field to me. But I'm not sure why `""` is converted to `"<nil>"` due to the code change I've made and how to avoid it. :thinking:

**Comment by dharmit** [comment]
@kadel @girishramnani @amitkrout any clue on what I could be doing wrong here? :thinking:

**Comment by dharmit** [comment]
/test unit
```
error: could not run steps: step src failed: could not wait for build: the build src failed after 13s with reason GenericBuildFailed: Generic Build failure - check logs for details.
```
/test v4.1-integration-e2e-benchmark
```
info: Using registry public hostname registry.svc.ci.openshift.org
error: unable to check your credentials - pass --skip-check to bypass this error: Get https://registry.svc.ci.openshift.org/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
/test v4.3-integration-e2e-benchmark
```
error: unable to connect to image repository registry.svc.ci.openshift.org/ci-op-wp5lkfwq/stable@sha256:a6b9e4444877fb0d6fa669dd9e5c3df4ebb7cd9611998489225c9cf76e335159: Get https://registry.svc.ci.openshift.org/v2/: net/http: TLS handshake timeout
```

**Comment by dharmit** [comment]
> @kadel @girishramnani @amitkrout any clue on what I could be doing wrong here? thinking

Never mind. Figured out the fix. Need reviews!

File: pkg/service/types.go [hunk 1]
```diff
@@ -57,3 +60,35 @@ type ServicePlan struct {
 	Description string
 	Parameters  servicePlanParameters
 }
+
+// UnmarshalJSON unmarshals the JSON for ServicePlanParameter instead of using
+// the built in json.Unmarshal
+func (sp *ServicePlanParameter) UnmarshalJSON(data []byte) error {
```
Comment (mohammedzee1000) [inline pkg/service/types.go]: Custom unmarshalling :+1:
