### PR TITLE
Updates test for printSupportedParameters to fix flake

### LINKED ISSUE #3755: UTs fails within env folder
/kind flake

## What versions of software are you using?

**Operating System:**
Windows, Linux

**Output of `odo version`:**
master

## How did you run odo exactly?
make test

## Actual behavior
Observed in travis CI
```
?   	github.com/openshift/odo/pkg/odo/cli/component/ui	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/config	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/debug	[no test files]
--- FAIL: TestPrintSupportedParameters (0.00s)
    --- FAIL: TestPrintSupportedParameters/Case_1:_Test_print_supported_set_parameters (0.00s)
        env_test.go:49: Got Available parameters:
              Namespace: Use this value to set component namespace
              DebugPort: Use this value to set component debug port
              Name: Use this value to set component name, want Available parameters:
              Name: Use this value to set component name
              Namespace: Use this value to set component namespace
              DebugPort: Use this value to set component debug port
FAIL
FAIL	github.com/openshift/odo/pkg/odo/cli/env	0.333s
?   	github.com/openshift/odo/pkg/odo/cli/login	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/logout	[no test files]
?   	github.com/openshift/odo/pkg/odo/cli/plugins	[no test files]
```
## Expected behavior
No such flake should appear

### PR DESCRIPTION
**Pull request by mik-dass**
**What type of PR is this?**

/kind failing-test

**What does does this PR do / why we need it**:

The printing order in printSupportedParameters() is dependent on a for loop over a map which is random in nature. Thus the unit test should not check for a complete match.

**Which issue(s) this PR fixes**:

Fixes #3755

**PR acceptance criteria**:

- [x] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer**:

- Unit test for printSupportedParameters() should pass without flakes.

### CODE REVIEW

File: pkg/odo/cli/env/env_test.go [hunk 1]
```diff
@@ -45,8 +45,20 @@ func TestPrintSupportedParameters(t *testing.T) {
...
+
+			gotStrings := strings.Split(got, "\n")
+			wantStrings := strings.Split(tt.want, "\n")
+
+			gotStringMap := make(map[string]bool)
+			for _, gotString := range gotStrings {
+				gotStringMap[gotString] = true
+			}
+
+			for _, wantString := range wantStrings {
```
Comment (metacosm) [inline pkg/odo/cli/env/env_test.go:57]: Did you try to use `DeepEqual` instead? Because, technically, you should also check that there is no extra strings in `gotStrings`, which would be wrong (i.e. there is a parameter in `gotStrings` that is not supposed to be there, which this doesn't check.

File: pkg/odo/cli/env/env_test.go [hunk 2]
```diff
@@ -45,8 +45,20 @@ func TestPrintSupportedParameters(t *testing.T) {
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
 			got := strings.TrimSpace(printSupportedParameters(tt.supportedParameters))
-			if !reflect.DeepEqual(got, tt.want) {
-				t.Errorf("Got %s, want %s", got, tt.want)
+
```
Comment (metacosm) [inline pkg/odo/cli/env/env_test.go:48]: Here's how I would implement it, which I think is more correct:

```suggestion
			gotSet, gotString := getAsSetAndRecomposedString(got)
			wantedSet, wantedString := getAsSetAndRecomposedString(tt.want)
			if !reflect.DeepEqual(wantedSet, gotSet) {
				t.Errorf("Got %s, want %s", gotString, wantedString)
			}
		})
	}
}

func getAsSetAndRecomposedString(output string) (map[string]bool, string) {
	gotStrings := strings.Split(output, "\n")
	gotSet := make(map[string]bool, len(gotStrings))
	for _, s := range gotStrings {
		gotSet[s] = true
	}
	return gotSet, strings.Join(gotStrings, "\n")
}
```

File: pkg/odo/cli/env/env_test.go (hunk 1 above)
Comment (mik-dass) [reply pkg/odo/cli/env/env_test.go]: Thanks :+1:  I missed that. I have updated the logic to use DeepEqual and sorting.

File: pkg/odo/cli/env/env_test.go (hunk 2 above)
Comment (mik-dass) [reply pkg/odo/cli/env/env_test.go:49]: I have updated the logic to use DeepEqual and sorting instead.

File: pkg/odo/cli/env/env_test.go [hunk 3]
```diff
@@ -45,8 +46,15 @@ func TestPrintSupportedParameters(t *testing.T) {
...
+			gotStrings := strings.Split(got, "\n")
+			wantStrings := strings.Split(tt.want, "\n")
+
+			sort.Strings(gotStrings)
```
Comment (metacosm) [inline pkg/odo/cli/env/env_test.go:53]: That works, too. 👍 
And I was actually thinking that maybe that's what `printSupportedParameters` should do (sort by parameter name) as well to get consistent output.

Comment (mik-dass) [reply pkg/odo/cli/env/env_test.go:53]: I thought about that. But I didn't want to modify the actual function. So left it unchanged for now.
