### PR TITLE
Fix delete context on Windows

### LINKED ISSUE #3534: test-cmd-devfile-debug teardown steps throws error while deleting context on windows platform
/kind bug

## What versions of software are you using?

**Operating System:**
Win10, 3.11 cluster on PSI

**Output of `odo version`:**
master

## How did you run odo exactly?

Run `make test-cmd-devfile-debug` on windows 3.11 cluster PSI

## Actual behavior

```
> make test-cmd-devfile-debug
Running Suite: Debug Suite
==========================
Random Seed: 1594298078
Will run 1 of 1 specs

Created dir: C:\Users\Admin\AppData\Local\Temp\521225239
Running odo.exe with args [odo preference set Experimental true]
[odo] Global preference was successfully updated
Setting KUBECONFIG=C:\Users\Admin\AppData\Local\Temp\521225239\config
Creating a new project: tgqujfptoe
Running odo.exe with args [odo project create tgqujfptoe -w -v4]
[odo]  -  Waiting for project to come up  ...
[odo] I0709 12:34:45.963737    8616 occlient.go:543] Status of creation of project tgqujfptoe is Active
[odo] I0709 12:34:46.017898    8616 occlient.go:548] Project tgqujfptoe now exists
[odo] I0709 12:34:46.024896    8616 occlient.go:583] Status of creation of service account &ServiceAccount{ObjectMeta:{default  tgqujfptoe /api/v1/namespaces/tgqujfptoe/serviceaccounts/default c8751068-c1df-11ea-a594-fa163e9b6334 19246911 0 2020-07-09 12:29:07 +0000 GMT <nil> <nil> map[] map[] [] []  []},Secrets:[]ObjectReference{ObjectReference{Kind:,Namespace:,Name:default-token-mq9c9,UID:,APIVersion:,ResourceVersion:,FieldPath:,},ObjectReference{Kind:,Namespace:,Name:default-dockercfg-n8wcm,UID:,APIVersion:,ResourceVersion:,FieldPath:,},},ImagePullSecrets:[]LocalObjectReference{LocalObjectReference{Name:default-dockercfg-n8wcm,},},AutomountServiceAccountToken:nil,} is ready
 V  Waiting for project to come up [410ms]
[odo]  V  Project 'tgqujfptoe' is ready for use
[odo]  V  New project created and now using project: tgqujfptoe
[odo] I0709 12:34:46.088821    8616 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
Setting current dir to: C:\Users\Admin\AppData\Local\Temp\521225239
Current working dir: C:\Users\Admin\AppData\Local\Temp\521225239
Running odo.exe with args [odo preference set Experimental true -f]
[odo] Global preference was successfully updated
Setting current dir to: C:\Users\Admin\AppData\Local\Temp\521225239/projectDir
Running odo.exe with args [odo create nodejs --project tgqujfptoe quxppn]
[odo] Experimental mode is enabled, use at your own risk
[odo]
[odo] Validation
 V  Checking devfile existence [0ns]
 V  Checking devfile compatibility [0ns]
 V  Creating a devfile component from registry: DefaultDevfileRegistry [0ns]
 V  Validating devfile component [0ns]
[odo]
[odo] Please use `odo push` command to create the component with source deployed
Running odo.exe with args [odo push --debug]
[odo]
[odo] Validation
 V  Validating the devfile [0ns]
[odo]
[odo] Creating Kubernetes resources for component quxppn
 V  Waiting for component to start [5s]
[odo]
[odo] Applying URL changes
[odo]  V  URLs are synced with the cluster, no changes are required.
[odo]
[odo] Syncing to component quxppn
 V  Syncing files to the component [199ms]
[odo]
[odo] Executing devfile commands for component quxppn
 V  Executing devbuild command "npm install" [2s]
 V  Executing debugrun command "npm run debug" [1s]
[odo]
[odo] Pushing devfile component quxppn
[odo]  V  Changes successfully pushed to component
Running odo.exe with args [odo debug port-forward]
[odo]  X  the local debug port 5858 is not free, cause: listen tcp 127.0.0.1:5858: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
[odo] The local port 57404 is auto selected
[odo] Started port forwarding at ports - 57404:5858
Running odo.exe with args [odo debug info]
[odo] Debug is running for the component on the local port : 57404
Checking http://localhost:57404, for WebSockets request was expected
try 0 of 12
Setting current dir to: C:\Users\Admin\AppData\Local\Temp\521225239
Deleting project: tgqujfptoe
Running odo.exe with args [odo project delete tgqujfptoe -f]
[odo]  V  Deleted project : tgqujfptoe
[odo]  !  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project 
may still exist on a different node.
Deleting dir: C:\Users\Admin\AppData\Local\Temp\521225239
+ Failure in Spec Teardown (AfterEach) [13.686 seconds]
odo devfile debug command serial tests
C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/devfile/debug/cmd_devfile_debug_test.go:20
  should auto-select a local debug port when the given local port is occupied for a devfile component [AfterEach]
  C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/devfile/debug/cmd_devfile_debug_test.go:64

  Unexpected error:
      <*os.PathError | 0xc00007d800>: {
          Op: "remove",
          Path: "C:\\Users\\Admin\\AppData\\Local\\Temp\\521225239",
          Err: 0x20,
      }
      remove C:\Users\Admin\AppData\Local\Temp\521225239: The process cannot access the file because it is being used by another process.
  occurred

  C:/Users/Admin/go/src/github.com/openshift/odo/tests/helper/helper_filesystem.go:28
------------------------------


Summarizing 1 Failure:

[Fail] odo devfile debug command serial tests [AfterEach] should auto-select a local debug port when the given local port is occupied for a devfile component
C:/Users/Admin/go/src/github.com/openshift/odo/tests/helper/helper_filesystem.go:28

```

## Expected behavior

Should send the websocket request on autoselected local port.

### PR DESCRIPTION
**Pull request by amitkrout**
**What type of PR is this?**

/kind bug

**Which issue(s) this PR fixes**:

Fixes #3534

**How to test changes / Special notes to the reviewer**:
```make test-cmd-devfile-debug``` should pass on Windows platform too

### CODE REVIEW

File: tests/integration/devfile/debug/cmd_devfile_debug_test.go [hunk 1]
```diff
@@ -62,9 +62,6 @@ var _ = Describe("odo devfile debug command serial tests", func() {
 	})
 
 	It("should auto-select a local debug port when the given local port is occupied for a devfile component", func() {
-		// Devfile push requires experimental mode to be set
-		helper.CmdShouldPass("odo", "preference", "set", "Experimental", "true", "-f")
```
Comment (amitkrout) [inline tests/integration/devfile/debug/cmd_devfile_debug_test.go:66]: It is unnecessary. Already set in the teardown steps

**Comment by amitkrout** [comment]
Verified on Windows
```
PS C:\Users\Admin\go\src\github.com\openshift\odo> make test-cmd-devfile-debug
ginkgo  -randomizeAllSpecs -slowSpecThreshold=120 -timeout 7200s -nodes=2 -focus="odo devfile debug command tests" tests/integration/devfile/
[1] Running Suite: Devfile Suite
[1] ============================
[1] Random Seed: 1594312255 - Will randomize all specs
[1] Parallel test node 1/2.
[1]
[2] Running Suite: Devfile Suite
[2] ============================
[2] Random Seed: 1594312255 - Will randomize all specs
[2] Parallel test node 2/2.
[2]
[1] SSSSSSSSS+SSSSS
SSSS+SSSSSSSSSSSSSS

[1] Ran 2 of 31 Specs in 28.032 seconds
[1] SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 29 Skipped
[1] PASS
[2] SSSSSSSSSSSSSSS
SSSSSSSSSSSSSSSSSSS
SSSSSSSSSSSSSSSSS
SSSSSSSS+SSSS+
[2] Ran 2 of 60 Specs in 31.830 seconds
[2] SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 58 Skipped
[2] PASS

Ginkgo ran 1 suite in 46.5162337s
Test Suite Passed
ginkgo  -randomizeAllSpecs -slowSpecThreshold=120 -timeout 7200s -nodes=1 -focus="odo devfile debug command serial tests" tests/integration/devfile/debug   
Running Suite: Debug Suite
==========================
Random Seed: 1594312302 - Will randomize all specs
Will run 1 of 1 specs

+
Ran 1 of 1 Specs in 13.193 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 19.5567382s
Test Suite Passed
PS C:\Users\Admin\go\src\github.com\openshift\odo>
```
