### PR TITLE
Fix namespace issue for url create --now

### LINKED ISSUE #3122: Unable to start component due to namespace termination
/kind bug

## What versions of software are you using?

**Operating System:**
all supported

**Output of `odo version`:**
master

## How did you run odo exactly?
Running  ```cmd_devfile_url_test``` test on CI

## Actual behavior

```
Running odo with args [odo project create yhzmzsovke -w -v4]
[odo]  •  Waiting for project to come up  ...
[odo] I0507 06:38:17.350862    1571 occlient.go:539] Status of creation of project yhzmzsovke is Active
[odo] I0507 06:38:17.350999    1571 occlient.go:544] Project yhzmzsovke now exists
[odo] I0507 06:38:17.444026    1571 occlient.go:579] Status of creation of service account &ServiceAccount{ObjectMeta:{default  yhzmzsovke /api/v1/namespaces/yhzmzsovke/serviceaccounts/default 833cd7ef-dc12-40b8-a950-0c77961085da 86937 0 2020-05-07 06:38:16 +0000 UTC <nil> <nil> map[] map[] [] []  []},Secrets:[]ObjectReference{ObjectReference{Kind:,Namespace:,Name:default-token-nr8l4,UID:,APIVersion:,ResourceVersion:,FieldPath:,},ObjectReference{Kind:,Namespace:,Name:default-dockercfg-wm67j,UID:,APIVersion:,ResourceVersion:,FieldPath:,},},ImagePullSecrets:[]LocalObjectReference{LocalObjectReference{Name:default-dockercfg-wm67j,},},AutomountServiceAccountToken:nil,} is ready
[odo] 
 ✓  Waiting for project to come up [1s]
[odo]  ✓  Project 'yhzmzsovke' is ready for use
[odo]  ✓  New project created and now using project: yhzmzsovke
Created dir: /tmp/364017334
Current working dir: /go/src/github.com/openshift/odo/tests/integration/devfile
Setting current dir to: /tmp/364017334
Running odo with args [odo preference set Experimental true]
[odo] Global preference was successfully updated
Running git with args [git clone https://github.com/che-samples/web-nodejs-sample.git /tmp/364017334/projectDir]
[git] Cloning into '/tmp/364017334/projectDir'...
Setting current dir to: /tmp/364017334/projectDir
Running odo with args [odo create nodejs --project yhzmzsovke lzelql]
[odo] Experimental mode is enabled, use at your own risk
[odo] 
[odo] Validation
[odo]  •  Checking devfile compatibility  ...
[odo] 
 ✓  Checking devfile compatibility [140679ns]
[odo]  •  Validating devfile component  ...
[odo] 
 ✓  Validating devfile component [269828ns]
[odo] 
[odo] Please use `odo push` command to create the component with source deployed
Running odo with args [odo url create oxuto --port 3000 --host ulwqx.com --now --ingress --devfile devfile.yaml]
[odo]  ✓  URL oxuto created for component: lzelql
[odo] 
[odo] Validation
[odo]  •  Validating the devfile  ...
[odo] 
 ✓  Validating the devfile [90192ns]
[odo] 
[odo] Creating Kubernetes resources for component lzelql
[odo]  ✗  Failed to start component with name lzelql.
[odo] Error: Failed to create the component: unable to create or update component: unable to create Deployment lzelql: deployments.apps "lzelql" is forbidden: unable to create new content in namespace bzcgbcptwl because it is being terminated
Deleting project: yhzmzsovke
Running odo with args [odo project delete yhzmzsovke -f]
[odo]  •  Deleting project yhzmzsovke  ...
[odo] 
 ✓  Deleting project yhzmzsovke [6s]
[odo]  ✓  Deleted project : yhzmzsovke
Setting current dir to: /go/src/github.com/openshift/odo/tests/integration/devfile
Deleting dir: /tmp/364017334
• Failure [11.143 seconds]
odo devfile url command tests
/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_url_test.go:16
  Creating urls
  /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_url_test.go:111
    create with now flag should pass [It]
```

## Expected behavior

namespace should not get terminated  while starting the component and url should get created.

## Any logs, error output, etc?

Logs : https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2913/pull-ci-openshift-odo-master-v4.3-integration-e2e/111#1:build-log.txt%3A454

### PR DESCRIPTION
**Pull request by adisky**
**What type of PR is this?**
/kind bug
/kind failing-test
/kind flake

**What does does this PR do / why we need it**:
fixes use of wrong namespace  while pushing a component via `odo url create --now`

Run 
```
$ odo create nodejs mynodejs --project project1`
$ oc project
Using project "project2" on server "https://api.crc.testing:6443".
$ `odo url create url1  --host "myhost.com" --ingress --now`
```
url create --now, pushes the component and create the url, but it pushes the component in current namespace not in the namespace saved in env.yaml or namespace used while creation.
This causes failure in CI if the current set namespace gets terminated before component deployment.

**Which issue(s) this PR fixes**:

Fixes #3122

**How to test changes / Special notes to the reviewer**:
Component should be pushed into the correct namespace while `odo url create --now`

### CODE REVIEW

File: pkg/odo/cli/component/devfile.go [hunk 1]
```diff
@@ -62,7 +62,7 @@ func (po *PushOptions) DevfilePush() (err error) {
 		platformContext = nil
 	} else {
 		kc := kubernetes.KubernetesContext{
-			Namespace: po.namespace,
+			Namespace: po.KClient.Namespace,
```
Comment (dharmit) [inline pkg/odo/cli/component/devfile.go:65]: Asking based on this description:
> url create --now, pushes the component and create the url, but it pushes the component in current namespace not in the namespace saved in env.yaml or namespace used while creation.

Wouldn't using `KClient.Namespace` still use the namespace that's currently set? To use the namespace set in `env.yaml`, don't we need to use the env specific info?

Comment (adisky) [reply pkg/odo/cli/component/devfile.go:65]: It already gets resolved while creating context.
https://github.com/openshift/odo/blob/c4aa610fddc3f255e82610d232b13ecc634b91c9/pkg/odo/genericclioptions/context.go#L469

The problem here was if we do direct push `odo push`, it goes through this file
https://github.com/openshift/odo/blob/c4aa610fddc3f255e82610d232b13ecc634b91c9/pkg/odo/cli/component/push.go#L78

and we push via `url create --now`, it skips that and directly calls here
https://github.com/openshift/odo/blob/c4aa610fddc3f255e82610d232b13ecc634b91c9/pkg/odo/cli/component/devfile.go#L36

So po.namespace does not get updated correctly, however we initialize context in `odo url create --now` too, so po.Kclient.namespace always have correct value.

Comment (dharmit) [reply pkg/odo/cli/component/devfile.go:65]: OK. So using "env specific info" point was valid. But `KClient.Namespace` already refers that hence this is valid. That's what I understood. :smile:

**Comment by girishramnani** [comment]
Unit test failed @adisky 
The CI would fight again and again so once unit test is resolved. I will reapprove
/approve cancel

**Comment by adisky** [comment]
> Unit test failed @adisky
> The CI would fight again and again so once unit test is resolved. I will reapprove
> /approve cancel

It was failing due to some network error.

**Comment by adisky** [comment]
captured logs
```
020/06/08 12:37:06 Build src succeeded after 4m21s
2020/06/08 12:37:06 Acquiring lease for "aws-quota-slice"
2020/06/08 14:37:07 No custom metadata found and prow metadata already exists. Not updating the metadata.
2020/06/08 14:37:08 Ran for 2h6m23s
error: some steps failed:
  * could not run steps: step integration-e2e failed: failed to acquire lease: resources not found
```
/retest

**Comment by adisky** [comment]
/retest
```
level=info msg="Cluster operator operator-lifecycle-manager-packageserver Available is False with : "
level=info msg="Cluster operator operator-lifecycle-manager-packageserver Progressing is True with : Working toward 0.15.1"
level=info msg="Pulling debug logs from the bootstrap machine"
level=info msg="Bootstrap gather logs captured here \"/tmp/artifacts/installer/log-bundle-20200608174605.tar.gz\""
level=fatal msg="Bootstrap failed to complete: failed to wait for bootstrapping to complete: timed out waiting for the condition"
---
