### PR TITLE
Default vol mount path to vol name if absent

### LINKED ISSUE #4005: component volumeMount path validation error
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:** master

## How did you run odo exactly?
odo push

## Actual behavior
```
Maysuns-MacBook-Pro:springboot-ex maysun$ odo push

Validation
 ✓  Validating the devfile [53446ns]

Creating Kubernetes resources for component myjava
 ✗  Failed to start component with name myjava. Error: Failed to create the component: unable to create or update component: unable to create Deployment myjava: Deployment.apps "myjava" is invalid: spec.template.spec.containers[0].volumeMounts[2].mountPath: Required value
```

## Expected behavior
should default as per https://github.com/openshift/odo/blob/master/docs/file-reference/index.md#volumemountsobject?

## Any logs, error output, etc?

This was my devfile:
```
components:
  - name: tools
    container:
      image: quay.io/eclipse/che-java11-maven:nightly
      memoryLimit: 768Mi
      mountSources: true
      endpoints:
      - name: '8080-tcp'
        targetPort: 8080
      volumeMounts:
        - name: m2
          # path: /home/user/.m2
  - name: m2
    volume:
      size: 2Gi
```

I am not sure if we ever defaulted to `name`. So idk if this is a regression

### PR DESCRIPTION
**Pull request by maysunfaisal**
Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>

**What type of PR is this?**
/kind bug

**What does does this PR do / why we need it**:
If vol mount path is absent, it defaults to vol mount name acc to the devfile schema https://devfile.github.io/devfile/api-reference.html

**Which issue(s) this PR fixes**:

Fixes #4005 

**PR acceptance criteria**:

- [x] Unit test 

- [x] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
- Comment out the vol mount path in a devfile and push
- Confirm the volume mount path by `oc/kubectl describe pod`

### CODE REVIEW

File: pkg/devfile/adapters/common/utils.go [hunk 1]
```diff
@@ -175,9 +176,15 @@ func GetVolumes(devfileObj devfileParser.DevfileObj) map[string][]DevfileVolume
 				}
 			}
 
+			// if there is no volume mount path, default to volume mount name as per devfile schema
+			mountPath := filepath.Join(string(os.PathSeparator), volumeMount.Name)
```
Comment (mik-dass) [inline pkg/devfile/adapters/common/utils.go:180]: Since most openshift containers are linux machines, wont this create create `\<volume-name>` when running odo from a windows machine?

Comment (adisky) [reply pkg/devfile/adapters/common/utils.go:180]: `os.PathSeparator` would take care about underlying OS

File: pkg/devfile/adapters/common/utils.go [hunk 2]
```diff
@@ -175,9 +176,15 @@ func GetVolumes(devfileObj devfileParser.DevfileObj) map[string][]DevfileVolume
...
+			if len(volumeMount.Path) > 0 {
+				mountPath = volumeMount.Path
+			}
```
Comment (adisky) [inline pkg/devfile/adapters/common/utils.go:183]: nit could be simplified to
```
if len(volumeMount.Path) <=0 {
       volumeMount.Path = filepath.Join(string(os.PathSeparator), volumeMount.Name)
}
```

File: pkg/devfile/adapters/common/utils.go (hunk 1 above)
Comment (mik-dass) [reply pkg/devfile/adapters/common/utils.go:180]: Yes and that would create`\<volume-name`on windows, which seems invalid to me

Comment (adisky) [reply pkg/devfile/adapters/common/utils.go:180]: ya right, we should default use `/` as separator.

Comment (maysunfaisal) [reply pkg/devfile/adapters/common/utils.go]: updated, pls help re-review the PR, thx!

File: pkg/devfile/adapters/common/utils.go (hunk 2 above)
Comment (maysunfaisal) [reply pkg/devfile/adapters/common/utils.go:185]: updated

**Comment by prietyc123** [comment]
We are hitting real failure on windows platform
```
--- FAIL: TestGetVolumes (0.00s)
    --- FAIL: TestGetVolumes/Case_5:_Valid_devfile_with_container_referencing_no_volume_mount_path (0.00s)
        utils_test.go:246: TestGetVolumes error - got map[mycontainer:[{myvolume1 \myvolume1 4Gi}]] wanted map[mycontainer:[{myvolume1 /myvolume1 4Gi}]]
FAIL
FAIL	github.com/openshift/odo/pkg/devfile/adapters/common	
```
@maysunfaisal Could you please address this. Till then I am holding this pr.

/hold

File: pkg/devfile/adapters/common/utils.go [hunk 3]
```diff
@@ -61,6 +61,9 @@ const (
 	// BinBash The path to sh executable
 	BinBash = "/bin/sh"
 
+	// FwdSlash is the path separator in linux containers
+	FwdSlash = "/"
```
Comment (mik-dass) [inline pkg/devfile/adapters/common/utils.go:65]: I don't think we need to store this in a variable as it is used in only one place and is only one character

Comment (maysunfaisal) [reply pkg/devfile/adapters/common/utils.go:65]: I did it because if you search for `"/"` in the odo repo, its all over the place. Some place has var defined, some are using direct strings. So I thought if I did it this way, it'd be at least consistent going forward. But I can remove it, if you think otherwise.

Comment (mik-dass) [reply pkg/devfile/adapters/common/utils.go:65]: I found only a few places where a variable has been created mostly in the URL package for URL paths. I would suggest using it directly as it is a single character string and probably won't change in the future or moving this variable to a general util package like /pkg/util/util.go for use across odo.

Comment (maysunfaisal) [reply pkg/devfile/adapters/common/utils.go]: updated. :)

**Comment by dharmit** [comment]
Works for me. Tried with `java-quarkus` component by commenting the volume from it.

/approve

**Comment by mik-dass** [comment]
```
[mrinaldas@localhost project]$ odo storage list 
The component 'nodejs' has the following storage attached:
NAME            SIZE     PATH             CONTAINER     STATE
nodejs-flhk     1Gi                       runtime       Not Pushed
nodejs-flhk     1Gi      /nodejs-flhk     runtime       Locally Deleted
```
`storage list` doesn't work properly when the path is not provided. We need to modify `GetLocalDevfileStorage` to use the default path too in such a case.

File: tests/integration/devfile/cmd_devfile_storage_test.go [hunk 4]
```diff
@@ -158,17 +159,17 @@ var _ = Describe("odo devfile storage command tests", func() {
 			helper.CopyExampleDevFile(filepath.Join("source", "devfiles", "nodejs", "devfile-with-volume-components.yaml"), filepath.Join(commonVar.Context, "devfile.yaml"))
 
 			stdOut := helper.CmdShouldPass("odo", "storage", "list", "--context", commonVar.Context)
-			helper.MatchAllInOutput(stdOut, []string{"firstvol", "secondvol", "Not Pushed", "CONTAINER", "runtime", "runtime2"})
+			helper.MatchAllInOutput(stdOut, []string{"firstvol", "secondvol", "/secondvol", "Not Pushed", "CONTAINER", "runtime", "runtime2"})
```
Comment (mik-dass) [inline tests/integration/devfile/cmd_devfile_storage_test.go:162]: since we are now checking for the path `/secondvol`, it might be a good idea to also check that the other paths (`/data`, `/data2`) are being displayed too

Comment (maysunfaisal) [reply tests/integration/devfile/cmd_devfile_storage_test.go]: Updated, I've also added a new commit for storage commit changes

**Comment by mik-dass** [comment]
```
[odo]  ✗  Waiting for component to start [5m]
[odo]  ✗  Failed to start component with name rlfwai. Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for rlfwai deployment roll out
Deleting project: thadwbtxdc
Running odo with args [odo project delete thadwbtxdc -f]
[odo] I1009 22:12:24.572511   68164 util.go:730] HTTPGetRequest: https://raw.githubusercontent.com/openshift/odo/master/build/VERSION
[odo] I1009 22:12:24.572651   68164 util.go:751] Response will be cached in /tmp/odohttpcache for 1h0m0s
[odo]  ✓  Deleted project : thadwbtxdc
[odo]  ⚠  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project may still exist on a different node.
[odo] I1009 22:12:24.668278   68164 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
Setting current dir to: /go/src/github.com/openshift/odo/tests/integration/operatorhub
Deleting dir: /tmp/672223586
------------------------------
• Failure [362.648 seconds]
odo service command tests for OperatorHub
/go/src/github.com/openshift/odo/tests/integration/operatorhub/
```
/retest

**Review by mik-dass — APPROVED** [review]
Works for me
/lgtm
