### PR TITLE
Fix clusterwide permission issues with odo link and run K8s tests with a developer user

### LINKED ISSUE #4965: odo can't create link using  client-side service binding library if user doesn't have permissions to list cluster wide resources
Original epic: https://github.com/openshift/odo/issues/4543

It looks like service binding library is trying to get cluster-wide resources.
This is especially problematic on OpenShift as normal cluster users usually don't have permissions to do so.
If the code base is supposed to be useful as a library it should avoid calls that require special privileges.

Issue reported to SBO: https://github.com/redhat-developer/service-binding-operator/issues/1003

/priority high
/kind bug

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this?**
/kind bug

**What does this PR do / why we need it**:
This PR attempts at fixing the permission issues caused while linking without the SBO.

**Which issue(s) this PR fixes**:

Fixes #4965 

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
1. Login as a non-admin user or someone who doesn't have permission to access CRD.
2. Create a comp and push it.
3. Create another comp and push it.
4. Link comp1 to comp2 and push it: the push should be done successfully.

TODO: Have to test this with service.

### CODE REVIEW

**Comment by dharmit** [comment]
> * Login as a non-admin user or someone who doesn't have permission to access CRD.
> 
> * Create a comp and push it.
> 
> * Create another comp and push it.
> 
> * Link comp1 to comp2 and push it: the push should be done successfully.

I see the Secret getting created after `odo link` as well as the env vars with info about Service belonging to c2 in c1's pod. But I think odo unlink doesn't delete the Secret. Please verify that part.

**Comment by feloy** [comment]
I have made some tests on a fresh new minikube, as a User1 bound to this role (so, without access to CRD resource):

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odo-user
rules:
- apiGroups: [""] # “” indicates the core API group
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["operators.coreos.com"]
  resources: ["clusterserviceversions"]
  verbs: ["*"]
- apiGroups: ["redis.redis.opstreelabs.in"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: ["route.openshift.io"]
  resources: ["*"]
  verbs: ["*"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odo-user-binding
subjects:
- kind: User
  name: user1 # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: odo-user
  apiGroup: rbac.authorization.k8s.io
```

All seems to work correctly. I can create and push a Redis service, link to it and push, unlink and push.

The secret attached to the link is deleted when unlinked.

**Comment by valaparthvi** [comment]
@baijum @pedjak If any of you have time, can  you take a look at this implementation? I think I could use an opinion on this one. I haven't implemented our own `Context` to override the `CustomResourcesDefinition()` method because I think it might be a little more work than it is worth. But if you think overriding the `CustomResourcesDefinition()` method  might be a better option, I would like to know more about it.

**Comment by valaparthvi** [comment]
/retest-required

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/5032/pull-ci-openshift-odo-main-psi-kubernetes-integration-e2e/1433687869737668608

**Comment by valaparthvi** [comment]
/test psi-kubernetes-integration-e2e

Reason - it did not run the commands I expected it to run, which is creating a developer user.

**Comment by valaparthvi** [comment]
/test psi-kubernetes-integration-e2e

For some reason, the k8s tests are not taking the latest changes into account.

File: scripts/minikube-minishift-setup-env.sh [hunk 1]
```diff
@@ -39,6 +39,62 @@ setup_kubeconfig() {
...
+  verbs: ["*"]
+- apiGroups: ["networking.k8s.io", "extensions"]
+  resources: ["ingresses"]
+  verbs: ["*"]
+- apiGroups: ["route.openshift.io"]
+  resources: ["*"]
+  verbs: ["*"]
+- apiGroups: ["apps.openshift.io"]
+  resources: ["*"]
+  verbs: ["*"]
```
Comment (valaparthvi) [inline scripts/minikube-minishift-setup-env.sh:78]: Does it make sense to add OpenShift resources to a minikube user? In a real world scenario, I think no minikube user will be concerned about OCP resources, but some of our tests rely on the user having access to these resources, and they might show a different output depending on which resource the user has access to.

File: scripts/minikube-minishift-setup-env.sh [hunk 2]
```diff
@@ -39,6 +39,62 @@ setup_kubeconfig() {
...
+    cd $certdir
+    shout "Starting to create minikube developer"
+    openssl genrsa -out developer.key 2048
+    openssl req -new -key developer.key -out developer.csr -subj "/CN=developer/O=minikube"
+    openssl x509 -req -in developer.csr -CA ~/.minikube/ca.crt -CAkey ~/.minikube/ca.key -CAcreateserial -out developer.crt -days 500
+    kubectl config set-credentials developer --client-certificate=developer.crt --client-key=developer.key
+    kubectl config set-context developer-minikube --cluster=minikube --user=developer
+    kubectl create -f - <<EOF
+kind: ClusterRole
+apiVersion: rbac.authorization.k8s.io/v1
```
Comment (feloy) [inline scripts/minikube-minishift-setup-env.sh:54]: Please comment that the intent of this role is to remove access to the CRD resource

File: scripts/minikube-minishift-setup-env.sh (hunk 1 above)
Comment (feloy) [reply scripts/minikube-minishift-setup-env.sh:78]: odo fails if it does not have access to these openshift resources, even in minikube. It could be interesting to open an issue, to make odo ignore resources that it cannot access, instead of failing

File: scripts/minikube-minishift-setup-env.sh [hunk 3]
```diff
@@ -81,6 +138,13 @@ case ${1} in
 
         # Create Operators for Operator tests
         sh $SETUP_OPERATORS
+
+        # Create a developer user if it is not created already and change the context to use it after the setup is done
+        kubectl config get-contexts developer-minikube
```
Comment (feloy) [inline scripts/minikube-minishift-setup-env.sh:143]: You could write it like:
```
kubectl config get-contexts developer-minikube || setup_minikube_developer
```

File: pkg/service/service_binding_builder.go [hunk 4]
```diff
@@ -0,0 +1,198 @@
+package service
```
Comment (feloy) [inline pkg/service/service_binding_builder.go:1]: Please indicate that this code is a fork from the Service Binding Operator, and what are the conditions to start using the upstream library again (an issue number?)

File: scripts/minikube-minishift-setup-env.sh (hunk 1 above)
Comment (prietyc123) [reply scripts/minikube-minishift-setup-env.sh:78]: > Does it make sense to add OpenShift resources to a minikube user? In a real world scenario, I think no minikube user will be concerned about OCP resources, but some of our tests rely on the user having access to these resources, and they might show a different output depending on which resource the user has access to.

I think its fine if we add permission for user to access those resources, as tests are relying on that. However I would like here from Team on this. @kadel @feloy @mohammedzee1000 Could you please share your thoughts. I have just pointed out to few people, however it would be great if any one of our team can share their thoughts.

File: scripts/minikube-minishift-setup-env.sh [hunk 5]
```diff
@@ -81,6 +138,13 @@ case ${1} in
...
+        if [ $? -ne 0 ]; then
+          setup_minikube_developer
+        fi
+        kubectl config use-context developer-minikube
```
Comment (prietyc123) [inline scripts/minikube-minishift-setup-env.sh:147]: What is it confirming `developer` user already exits?

**Review by prietyc123 — CHANGES_REQUESTED** [review]

File: scripts/minikube-minishift-setup-env.sh (hunk 1 above)
Comment (prietyc123) [reply scripts/minikube-minishift-setup-env.sh:78]: @valaparthvi Could you please confirm if its a problem with odo or just odo test?

File: scripts/minikube-minishift-setup-env.sh (hunk 5 above)
Comment (valaparthvi) [reply scripts/minikube-minishift-setup-env.sh:145]: Yeah, in case there is a running minikube cluster, we check if the context is created, if not, we create the context, user, and everything else, and then use the context.

File: scripts/minikube-minishift-setup-env.sh (hunk 1 above)
Comment (valaparthvi) [reply scripts/minikube-minishift-setup-env.sh:79]: It is a problem with odo. See #5042 for example.

File: scripts/minikube-minishift-setup-env.sh [hunk 6]
```diff
@@ -39,6 +39,63 @@ setup_kubeconfig() {
...
+    pwd=`pwd`
+    certdir=`mktemp -d`
+    cd $certdir
+    shout "Creating a minikube developer user"
+    openssl genrsa -out developer.key 2048
+    openssl req -new -key developer.key -out developer.csr -subj "/CN=developer/O=minikube"
+    openssl x509 -req -in developer.csr -CA ~/.minikube/ca.crt -CAkey ~/.minikube/ca.key -CAcreateserial -out developer.crt -days 500
+    kubectl config set-credentials developer --client-certificate=developer.crt --client-key=developer.key
+    kubectl config set-context developer-minikube --cluster=minikube --user=developer
+    # Create role and rolebinding to allow the user admin access to the cluster; this does not include access to CRD
```
Comment (feloy) [inline scripts/minikube-minishift-setup-env.sh:52]:
```suggestion
    # Create role and rolebinding to allow the user necessary access to the cluster; this does not include access to CRD
```

**Review by feloy — APPROVED** [review]

**Comment by valaparthvi** [comment]
@feloy Can you add the lgtm label again?
Reason - https://github.com/openshift/odo/pull/5032/commits/94184a21af5dd357153ee9135e7b5908e7571cbe

**Comment by pedjak** [comment]
@valaparthvi the change looks good

File: scripts/minikube-minishift-setup-env.sh (hunk 1 above)
Comment (valaparthvi) [reply scripts/minikube-minishift-setup-env.sh:79]: > It could be interesting to open an issue, to make odo ignore resources that it cannot access, instead of failing

https://github.com/openshift/odo/issues/5043

Comment (dharmit) [reply scripts/minikube-minishift-setup-env.sh:79]: I don't understand why we would want access to OpenShift specific apiGroups for a user being created on minikube. But, it's not going to hurt, so I won't request a change.

File: pkg/service/service_binding_builder.go [hunk 7]
```diff
@@ -0,0 +1,207 @@
...
+			}
+		} else {
+			crd, err := service.CustomResourceDefinition()
+			if err != nil {
+				// If the user does not have permission to access CRD, ignore
+				if !kerrors.IsForbidden(err) {
+					requestRetry(ctx, collect.ErrorReadingCRD, err)
+					return
+				} else {
+					klog.V(4).Infof("Skipping the check for CRD, user does not have access")
```
Comment (kadel) [inline pkg/service/service_binding_builder.go:80]: Can we make this user normal facing message? Ideally a warning?
odo user should know that something like this was skipped without running odo with increased log level.

**Review by kadel — CHANGES_REQUESTED** [review]

**Comment by kadel** [comment]
It looks like the warning is showing twice

```
Creating Kubernetes resources for component java-springboot
 ✓  Waiting for component to start [1ms]
 ⚠  Skipping the check for CRD, user does not have access
 ⚠  Skipping the check for CRD, user does not have access
```

But we can fix this in a separate PR.  For now this will make sure that user really notices this :-D

File: scripts/minikube-minishift-setup-env.sh (hunk 1 above)
Comment (valaparthvi) [reply scripts/minikube-minishift-setup-env.sh:79]: That is my concern as well. But if we don't allow access to these apiGroups, we see a different output from that of a kubeadmin user,

**Comment by valaparthvi** [comment]
> It looks like the warning is showing twice
> 
> ```
> Creating Kubernetes resources for component java-springboot
>  ✓  Waiting for component to start [1ms]
>  ⚠  Skipping the check for CRD, user does not have access
>  ⚠  Skipping the check for CRD, user does not have access
> ```
> 
> But we can fix this in a separate PR. For now this will make sure that user really notices this :-D

That's not a bug per se. Since we added the warning in both the overridden handler functions, it prints the warning when they are called.

**Comment by kadel** [comment]
> That's not a bug per se. Since we added the warning in both the overridden handler functions, it prints the warning when they are called.

From user point of view this is bug!
