### PR TITLE
Fix #3838: Component is left in broken state after redeployment of the pod 

### LINKED ISSUE #3838: component is left in broken state after redeployment of the pod
/kind bug

## What versions of software are you using?

**Operating System:**
macOS

**Output of `odo version`:**
▶ odo version
odo v1.2.5 (552aad7ea)

## How did you run odo exactly?
```
▶ odo create  java-maven
Experimental mode is enabled, use at your own risk

Validation
 ✓  Checking devfile existence [39413ns]
 ✓  Checking devfile compatibility [84734ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [89449ns]
 ✓  Validating devfile component [247861ns]

Please use `odo push` command to create the component with source deployed

▶ odo push

Validation
 ✓  Validating the devfile [188307ns]

Creating Kubernetes resources for component java-maven
 ✓  Waiting for component to start [2m]

Applying URL changes
 ✓  URL http-8080: http://http-8080-java-maven-tkral-test.apps.testocp4x.psiodo.net/ created

Syncing to component java-maven
 ✓  Checking files for pushing [5ms]
 ✓  Syncing files to the component [25s]

Executing devfile commands for component java-maven
 ✓  Executing mvn-package command "mvn package", if not running [1m]
 ✓  Executing run command "java -jar target/*.jar", if not running [2s]

Pushing devfile component java-maven
 ✓  Changes successfully pushed to component

▶ curl http://http-8080-java-maven-tkral-test.apps.testocp4x.psiodo.net/
Greetings from Spring Boot!%

▶ odo storage create mystorage --path=/data --size=1Gi
 ✓  Added storage mystorage to java-maven

Please use `odo push` command to make the storage accessible to the component

▶ odo push

Validation
 ✓  Validating the devfile [124117ns]

Creating Kubernetes resources for component java-maven
 ✓  Waiting for component to start [4m]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component java-maven
 ✓  Checking file changes for pushing [3ms]
 ✓  Syncing files to the component [2s]

Executing devfile commands for component java-maven
 ✗  Executing mvn-package command "mvn package", if not running [3s]
 ✗  Failed to start component with name java-maven. Error: Failed to create the component: command execution failed: unable to execute the run command: unable to exec command [/bin/sh -c mvn package]:
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.089 s
[INFO] Finished at: 2020-08-26T09:42:09Z
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/projects). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
: error while streaming command: command terminated with exit code 1

```

## Expected behavior
source code should be present in container and my application  should be running after `odo push`

## Any logs, error output, etc?

build command while running `odo push` fails because the directory where the application source is supposed to be is empty.

```
▶ oc exec java-maven-748556d67-kmk7x  -- ls /projects
?
devfile.yaml
```

### LINKED ISSUE #3841: odo watch redeploys component during first push
/kind bug

## How did you run odo exactly?

`odo push`
`odo watch`

## Actual behavior

The component is redeployed during the first push triggered by watch.

## Expected behavior

The component shouldn't be redeployed.

## Any logs, error output, etc?

```

Executing devfile commands for component nodejs
 ✓  Executing install command "npm install" [8s]
 ✓  Executing run command "npm start" [5s]

Pushing devfile component nodejs
 ✓  Changes successfully pushed to component
[mrinaldas@localhost project]$ odo watch
Waiting for something to change in /home/mrinaldas/project
File /home/mrinaldas/project/check.sh changed
Pushing files...

Validation
 ✓  Validating the devfile [61668ns]

Creating Kubernetes resources for component nodejs
 ✓  Waiting for component to start [6s]        // redeployed

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component nodejs
 ✓  Checking file changes for pushing [1ms]
...
```

### PR DESCRIPTION
**Pull request by jgwest**
**What type of PR is this?**
/kind bug

**What does does this PR do / why we need it**:

See https://github.com/openshift/odo/issues/3838#issuecomment-682259193

**Which issue(s) this PR fixes**:

Fixes #3838

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [X] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

See https://github.com/openshift/odo/issues/3838 for test reproduction steps.

### CODE REVIEW

File: tests/integration/devfile/cmd_devfile_push_test.go [hunk 1]
```diff
@@ -548,6 +547,43 @@ var _ = Describe("odo devfile push command tests", func() {
...
+			helper.ReplaceString("devfile.yaml", "memoryLimit: 768Mi", "memoryLimit: 769Mi")
+			commands := []string{"push", "-v", "4", "--namespace", namespace}
+			if shouldForcePush {
+				// Test both w/ and w/o '-f'
+				commands = append(commands, "-f")
+			}
+
+			// 3) Ensure the build passes, indicating that all files were correctly synced to the new pod
+			output = helper.CmdShouldPass("odo", commands...)
+			Expect(output).To(ContainSubstring("BUILD SUCCESS"))
```
Comment (mik-dass) [inline tests/integration/devfile/cmd_devfile_push_test.go:573]: We should also check that all the files are present in the pod after the successful push.

Comment (johnmcollier) [reply tests/integration/devfile/cmd_devfile_push_test.go:573]: @mik-dass Agreed, since we found that some of the devfiles didn't report a failed build or run command when this issue hit

File: tests/integration/devfile/cmd_devfile_push_test.go [hunk 2]
```diff
@@ -548,6 +549,92 @@ var _ = Describe("odo devfile push command tests", func() {
...
+			Expect(err).ToNot(HaveOccurred())
+
+			// 6) Sort and compare the local and remote files; they should match
+			sort.Strings(localFiles)
+			sort.Strings(remoteFiles)
+
+			equal := reflect.DeepEqual(localFiles, remoteFiles)
+			if !equal {
+				fmt.Fprintf(GinkgoWriter, "Files mismatched between local and remote. local: {%v} remote: {%v}", localFiles, remoteFiles)
+				Fail("Mismatching files between local and remote")
```
Comment (mik-dass) [inline tests/integration/devfile/cmd_devfile_push_test.go:624]: We can directly use `Expect(ACTUAL).Should(Equal(EXPECTED))`. According to https://onsi.github.io/gomega/, it uses reflect.DeepEqual() underneath.

File: tests/integration/devfile/cmd_devfile_push_test.go (hunk 1 above)
Comment (jgwest) [reply tests/integration/devfile/cmd_devfile_push_test.go:574]: Done.

File: tests/integration/devfile/cmd_devfile_push_test.go (hunk 2 above)
Comment (jgwest) [reply tests/integration/devfile/cmd_devfile_push_test.go]: Done.

File: pkg/sync/adapter.go [hunk 3]
```diff
@@ -108,7 +108,16 @@ func (a Adapter) SyncFiles(syncParameters common.SyncParameters) (isPushRequired
 			}
 		}
 
-		// run the indexer and find the modified/added/deleted/renamed files
+		// If the pod changed, reset the index, which will cause the indexer to walk the directory
```
Comment (cdrage) [inline pkg/sync/adapter.go:111]: Big :+1:
