### PR TITLE
Fix odo hang when cluster is unreachable 

### LINKED ISSUE #4046: odo 'hangs' after using a cluster that's no longer accessible
/kind bug

## What versions of software are you using?

**Operating System:**
MacBook Pro with Catalina

**Output of `odo version`:**
odo v2.0.0 (6fbb9d9bf)

## How did you run odo exactly?
I was using odo successfully, then installed CRC, used it for a bit, and then stopped the CRC cluster.

## Actual behavior
Tried to use odo again and every command (even ones I would have thought are 'local') takes >1min to respond. No errors, but every time you think it's hung and not going to return, then finally does. Even things that should fail fast (e.g. current dir is not a component) hang for a while.

## Expected behavior
I realize it's likely something underlying that is still trying to connect to my stopped cluster, but I didn't intentionally connect odo to it, nor is there any indication that's what the problem is: it just looks like odo performance is awful and it's my experience with odo that I associate with the problem.

There should be:
 - a shorter timeout
 - when there is a long delay, there should be some indication that the command is trying to connect (so I don't think it's hung)
 - when there's a timeout, there should be something that tells me how to stop trying to connect to that cluster

### PR DESCRIPTION
**Pull request by adisky**
**What type of PR is this?**
 /kind bug

**What does does this PR do / why we need it**:
Remove isResourceSupported call from command intialization

**Which issue(s) this PR fixes**:

Fixes #4046 

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
- Disconnect with the openshift/k8s cluster
- Run any odo command without changes 
- Run any odo command with  applying this PR
Observe the significant time difference between the output returned by odo

### CODE REVIEW

File: pkg/kclient/kclient.go [hunk 1]
```diff
@@ -200,6 +200,8 @@ func (c *Client) SetDiscoveryInterface(client discovery.DiscoveryInterface) {
 }
 
 func (c *Client) IsResourceSupported(apiGroup, apiVersion, resourceName string) (bool, error) {
+	klog.V(4).Infof("Checking is %s resource supported", resourceName)
```
Comment (dharmit) [inline pkg/kclient/kclient.go:203]: `Checking if %s resource is supported`

Also, I'd suggest `%q` instead of `%s`.

**Review by dharmit — CHANGES_REQUESTED** [review]
One small change request. Looks good otherwise.

**Review by dharmit — APPROVED** [review]
/lgtm
