### PR TITLE
Wait for pods to come up before running 'odo unlink' to avoid race condition

### LINKED ISSUE #4301: Failing "odo link" tests are blocking CI system
/kind bug
/area linking

odo doesn't fail if at the time of doing `odo link <cr-name>/<cr-instance-name>`, it fails to create a Secret on the cluster. Creation of this Secret is a task performed by Service Binding Operator. But if odo doesn't fail when such a Secret doesn't get created, it can cause user confusion as well as CI issues as we're seeing in our environment.

_Originally posted by @dharmit in https://github.com/openshift/odo/issues/3256#issuecomment-742480657_

### PR DESCRIPTION
**Pull request by dharmit**
**What type of PR is this?**
/kind failing-test

**What does this PR do / why we need it**:
$subject
We need this since it's become an annoyance in getting CI to pass for PRs.

**Which issue(s) this PR fixes**:

Fixes #4301

**PR acceptance criteria**:

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
CI should be green. Especially CI shouldn't fail due to #4301.

### CODE REVIEW

**Comment by dharmit** [comment]
```
[ssh:Fedora 32] • Failure [301.546 seconds]
[ssh:Fedora 32] odo devfile supported tests
[ssh:Fedora 32] /home/fedora/amqp_ci_rcv_odo-pr-build_PR_4428/repo/tests/e2escenarios/e2e_devfile_test.go:23
[ssh:Fedora 32]   odo debug support for devfile components
[ssh:Fedora 32]   /home/fedora/amqp_ci_rcv_odo-pr-build_PR_4428/repo/tests/e2escenarios/e2e_devfile_test.go:65
[ssh:Fedora 32]     Verify output debug information for java-openliberty debug works [It]
[ssh:Fedora 32] 
[ssh:Fedora 32] [Fail] odo devfile supported tests odo debug support for devfile components [It] Verify output debug information for java-openliberty debug works 
[ssh:Fedora 32] /home/fedora/amqp_ci_rcv_odo-pr-build_PR_4428/repo/tests/helper/helper_run.go:34
[ssh:Fedora 32] 
[ssh:Fedora 32] Ran 30 of 30 Specs in 836.482 seconds
[ssh:Fedora 32] FAIL! -- 29 Passed | 1 Failed | 0 Pending | 0 Skipped 
```
/retest

**Comment by dharmit** [comment]
```
[ssh:Fedora 32] • Failure [301.783 seconds]
[ssh:Fedora 32] odo devfile supported tests
[ssh:Fedora 32] /home/fedora/amqp_ci_rcv_odo-pr-build_PR_4428/repo/tests/e2escenarios/e2e_devfile_test.go:23
[ssh:Fedora 32]   odo debug support for devfile components
[ssh:Fedora 32]   /home/fedora/amqp_ci_rcv_odo-pr-build_PR_4428/repo/tests/e2escenarios/e2e_devfile_test.go:65
[ssh:Fedora 32] [Fail] odo devfile supported tests odo debug support for devfile components [It] Verify output debug information for java-openliberty debug works 
[ssh:Fedora 32] /home/fedora/amqp_ci_rcv_odo-pr-build_PR_4428/repo/tests/helper/helper_run.go:34
[ssh:Fedora 32] 
[ssh:Fedora 32] Ran 30 of 30 Specs in 918.405 seconds
[ssh:Fedora 32] FAIL! -- 29 Passed | 1 Failed | 0 Pending | 0 Skipped 
```
Same error as previous CI run
/retest

File: tests/integration/operatorhub/cmd_service_test.go [hunk 1]
```diff
@@ -449,7 +449,9 @@ spec:
 			stdOut = helper.CmdShouldFail("odo", "link", "EtcdCluster/example")
 			Expect(stdOut).To(ContainSubstring("already linked with the service"))
 
-			stdOut = helper.CmdShouldPass("odo", "unlink", "EtcdCluster/example")
+			// Running unlink command with timeout because at times unlink happens (which deletes underlying Kubernetes
+			// Secret) too fast and (seems to) mess the Pod created as a part of earlier odo push
+			stdOut = helper.CmdShouldRunWithTimeout(1*time.Minute, "odo", "unlink", "EtcdCluster/example")
```
Comment (valaparthvi) [inline tests/integration/operatorhub/cmd_service_test.go:454]: Looking at [your comment here](https://github.com/openshift/odo/issues/4301#issuecomment-776664917), wouldn't it make more sense to wait for the pod to be in a running state before this un-linking, instead of adding a static wait period?

File: go.mod [hunk 2]
```diff
@@ -95,4 +95,4 @@ replace (
 	k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.17.1
 	vbom.ml/util => github.com/fvbommel/util v0.0.0-20180919145318-efcd4e0f9787
 
-)
\ No newline at end of file
+)
```
Comment (valaparthvi) [inline go.mod:98]: Thank you! I thought I was the only one getting this annoying change :roll_eyes:

File: tests/integration/operatorhub/cmd_service_test.go (hunk 1 above)
Comment (kadel) [reply tests/integration/operatorhub/cmd_service_test.go:454]: I agree with @valaparthvi that instead of introducing static sleep, we should properly wait for whatever is needed to make the operation successful. 

As I understand this is essentially a race condition. Should this be solved inside odo code? To me, it seems that we are fixing this in the test, but the actual problem is how odo handles this situation. 


Did you really mean to use `CmdShouldRunWithTimeout` ? This function just makes sure that the command is killed after a given timeout. It is not introducing any sleep before executing the command.

Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go:454]: Sure it kills the command but it also returns the stdout. And that's what we're interested in along with a sleep. However, I agree with what @valaparthvi has mentioned and am trying to change accordingly.

I think the race condition is happening because link and unlink operations are being executed fast in CI environment. This problem has not surfaced yet when someone does things manually. So I'm not sure if this needs to be fixed in the odo code.

Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go]: @valaparthvi @kadel I've made the requested changes. Can one of you PTAL?

File: tests/integration/operatorhub/cmd_service_test.go [hunk 3]
```diff
@@ -449,6 +449,15 @@ spec:
 			stdOut = helper.CmdShouldFail("odo", "link", "EtcdCluster/example")
 			Expect(stdOut).To(ContainSubstring("already linked with the service"))
 
+			// Before running "odo unlink" checks, wait for the pod to come up from "odo push" done after "odo link"
+			pods = oc.GetAllPodsInNs(project)
```
Comment (kadel) [inline tests/integration/operatorhub/cmd_service_test.go:453]: Listing all pods in not a namespace is not nice.
If you need pods for the given component you can do the equivalent of `kubectl get deployment --selector component=<componentname>` 

It looks like we already have a function that might be  doing what you are trying to do 
https://github.com/openshift/odo/blob/2180507a4850dfac98559cc94aa9d55441007c0b/tests/helper/helper_kubectl.go#L69

Comment (kadel) [reply tests/integration/operatorhub/cmd_service_test.go:453]: this function might be also usefull for you https://github.com/openshift/odo/blob/2180507a4850dfac98559cc94aa9d55441007c0b/tests/helper/helper_kubectl.go#L110

Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go:453]: > GetRunningPodNameByComponent

This one looks useful. It does help me get the exact pod name that was finding through regex.

> WaitAndCheckForExistence

Looking at this function's comment and implementation, I think it's going to check if the resource type has ceased to exist. Whereas what I'm looking for is the pod to be in `Running` state.

I am going to use `GetRunningPodNameByComponent` and run it a few times against CRC before pushing a commit.

Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go]: I changed the code to use `GetRunningPodNameByComponent` method. Although I don't think it has anything to do with changing the way we wait for pods to come up, the test failed once during the 10 runs I tried it out for. With the `GetAllPodsInNS` implementation, it didn't fail. I think it's unrelated and probably indicates that we're still missing something to fix this particular flake.

At this point, I can't think of anything else and would need someone else taking a look at things if #4301 becomes an annoyance again.

**Comment by dharmit** [comment]
The irony. Below failure is the exact thing this PR is trying to fix (https://github.com/openshift/odo/pull/4428#discussion_r578989948):
```
 [odo] 
 ✗  Waiting for component to start [5m] [WARNING x7: Failed]
[odo]  ✗  Failed to start component with name eyvodd. Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for eyvodd deployment roll out\nFor more information to help determine the cause of the error, re-run with '-v'.
[odo] See below for a list of failed events that occured more than 5 times during deployment:
[odo] 
[odo]  NAME                                      COUNT  REASON  MESSAGE                        
[odo] 
[odo]  eyvodd-7cbd48b669-7zpxw.16651d420a71b7c8  7      Failed  Error: secret                  
[odo]                                                           "eyvodd-etcdcluster-example"   
[odo]                                                           not found                      
[odo] 
[odo] 
Deleting project: peswyzkths
Running odo with args [odo project delete peswyzkths -f] 
```

File: tests/integration/operatorhub/cmd_service_test.go (hunk 3 above)
Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go]: I'm going to roll back to using `oc.GetAllPodsInNs(project)`. I'm doing this because:
1. https://github.com/openshift/odo/pull/4428#issuecomment-782079225
2. I am going to need some help if this failure becomes a severe annoyance again. I can't really find what's going wrong. Very likely I'm missing something.

File: tests/integration/operatorhub/cmd_service_test.go [hunk 4]
```diff
@@ -449,6 +449,15 @@ spec:
...
+			componentPod := regexp.MustCompile(fmt.Sprintf(`%s-.[a-z0-9]*-.[a-z0-9]*`, componentName)).FindString(pods)
+			ocArgs = []string{"get", "pods", componentPod, "-o", "template=\"{{.status.phase}}\"", "-n", project}
+			helper.WaitForCmdOut("oc", ocArgs, 1, true, func(output string) bool {
+				return strings.Contains(output, "Running")
+			})
+
+			// stdOut = helper.CmdShouldRunWithTimeout(1*time.Minute, "odo", "unlink", "EtcdCluster/example")
```
Comment (prietyc123) [inline tests/integration/operatorhub/cmd_service_test.go:460]: commented code found

**Review by prietyc123 — CHANGES_REQUESTED** [review]

**Comment by kadel** [comment]
> @dharmit: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> ci/prow/v4.6-e2e-4x-psi	[416bc6f](https://github.com/openshift/odo/commit/416bc6f0abb6db7ba9a87373c414517591507588)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4428/pull-ci-openshift-odo-master-v4.6-e2e-4x-psi/1362758334473572352)	`/test v4.6-e2e-4x-psi`
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=odo&pr=4428). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:dharmit).

It looks like the problem is still present :-( 

```
I0219 13:45:59.806280 2675524 events.go:52] Warning Event: Count: 6, Reason: Failed, Message: Error: secret "jxqesj-etcdcluster-example" not found
[ssh:Fedora 32] [odo] 
I0219 13:46:13.595252 2675524 events.go:52] Warning Event: Count: 7, Reason: Failed, Message: Error: secret "jxqesj-etcdcluster-example" not found
[ssh:Fedora 32] [odo]  ✗  Waiting for component to start [5m] [WARNING x7: Failed]
[ssh:Fedora 32] [odo]  ✗  Failed to start component with name jxqesj. Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for jxqesj deployment roll out\nFor more information to help determine the cause of the error, re-run with '-v'.
[ssh:Fedora 32] [odo] See below for a list of failed events that occured more than 5 times during deployment:
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] [odo]  NAME                                     COUNT  REASON  MESSAGE                        
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] [odo]  jxqesj-c8df4fd78-42k4r.16652a06959602c9  7      Failed  Error: secret                  
[ssh:Fedora 32] [odo]                                                          "jxqesj-etcdcluster-example"   
[ssh:Fedora 32] [odo]                                                          not found                      
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] Deleting project: kmsirtuuwn
[ssh:Fedora 32] Running odo with args [odo project delete kmsirtuuwn -f]

```

File: tests/integration/operatorhub/cmd_service_test.go (hunk 4 above)
Comment (girishramnani) [reply tests/integration/operatorhub/cmd_service_test.go:460]: please remove this commented code @dharmit , else all looks good
