### PR TITLE
Deleting a component also unlinks it from components it might be linked to

### LINKED ISSUE #2355: odo delete Fails to Delete Linked Component When Secret Not Found
[kind/bug]

After linking two components, if you delete the component that shared its information with the other component as part of the linking, `odo` won't let you delete the remaining component.

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`: `odo v1.0.0 (4e3175e6)`

## How did you run odo exactly?
Create Java component
```
odo create java:8 backend --binary target/jarfile
odo push
```

Create Node.js component
```
odo create nodejs frontend
odo url create frontend
odo push
```

Link components
(In directory of node app)
`odo link backend`

Delete Java component
`odo delete backend`

Delete Node Component
`odo delete fronted`

## Actual behavior
```
✗  secrets "backend-app-8080" not found
```

## Expected behavior
Able to delete Node.js component

### PR DESCRIPTION
**Pull request by dharmit**
**What kind of PR is this?**

/kind bug

**What does does this PR do / why we need it**:
This PR unlinks a component requested for deletion from all the components it might be linked to in the OpenShift cluster

**Which issue(s) this PR fixes**:

Fixes #2355 

**How to test changes / Special notes to the reviewer**:
1. `odo create nodejs node`
2. `odo create java java`
3. From component `node`'s context directory do `odo link java --port 8080`
4. From component `java`'s context directory do `odo delete -f`
5. From component `node`'s context directory do `odo delete -f`

### CODE REVIEW

**Comment by dharmit** [comment]
@amitkrout @kadel do you think I should add integration tests here? The scenario I can think of is same as what I've described in the "How to test changes" section of this PR.

@amitkrout if yes, which file do you recommend I add it to?

File: pkg/odo/cli/component/delete.go [hunk 1]
```diff
@@ -81,7 +81,33 @@ func (do *DeleteOptions) Run() (err error) {
...
+			parentComponent, err := component.GetComponent(do.Client, do.componentName, do.Context.Application, do.Context.Project)
+			if err != nil {
+				return err
+			}
+
+			componentSecrets := component.UnlinkComponents(parentComponent, compoList)
+
+			for component, secret := range componentSecrets {
+				for _, secretName := range secret {
+					err = do.Client.UnlinkSecret(secretName, component, do.Context.Application)
```
Comment (mik-dass) [inline pkg/odo/cli/component/delete.go]: Please add a spinner here indicating that unlinking action is happening

**Comment by kadel** [comment]
> @amitkrout @kadel do you think I should add integration tests here? The scenario I can think of is same as what I've described in the "How to test changes" section of this PR.

yes that would be great!



> @amitkrout if yes, which file do you recommend I add it to?

I would categorize it as link test.

**Comment by dharmit** [comment]
@mik-dass Thanks for the tip! It makes sense. But I'll need some help. Can you see if you can help me?

Here's the `git diff`:
```sh
$ git diff
diff --git a/pkg/odo/cli/component/delete.go b/pkg/odo/cli/component/delete.go
index 932df0f3e..9a0fdadae 100644
--- a/pkg/odo/cli/component/delete.go
+++ b/pkg/odo/cli/component/delete.go
@@ -99,13 +99,18 @@ func (do *DeleteOptions) Run() (err error) {
                        componentSecrets := component.UnlinkComponents(parentComponent, compoList)
 
                        for component, secret := range componentSecrets {
+                               spinner := log.NewStatus(log.GetStdout())
+                               defer spinner.End(true)
                                for _, secretName := range secret {
+                                       spinner.Start(fmt.Sprintf("Unlinking component %q from component %q for secret %q\n", parentComponent.Name, component, secretName), false)
                                        err = do.Client.UnlinkSecret(secretName, component, do.Context.Application)
                                        if err != nil {
+                                               log.Errorf("Unlinking failed")
                                                return err
                                        }
-                                       log.Successf("Unlinked component %q from component %q for secret %q", parentComponent.Name, component, secretName)
+                                       log.Successf("Unlink successful")
                                }
+                               spinner.End(true)
                        }
                        err = component.Delete(do.Client, do.componentName, do.Application)
                        if err != nil {
```

And here's the output which is clearly messed up!
```sh
 odo delete -f
 ◐  Unlinking component "backend" from component "frontend" for secret "backend-app-8778"
 ◓  Unlinking component "backend" from component "frontend" for secret "backend-app-8778"
 ◑  Unlinking component "backend" from component "frontend" for secret "backend-app-8778"
 ✓  Unlink successful
 ✓  Unlinking component "backend" from component "frontend" for secret "backend-app-8778"
 [614ms]
 ◐  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
 ◓  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
 ◑  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
 ◒  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
 ◐  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
 ◓  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
 ◑  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
 ✓  Unlink successful
 ✓  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
 [2s]
 ◐  Unlinking component "backend" from component "node" for secret "backend-app-8080"
 ◓  Unlinking component "backend" from component "node" for secret "backend-app-8080"
 ◑  Unlinking component "backend" from component "node" for secret "backend-app-8080"
 ◒  Unlinking component "backend" from component "node" for secret "backend-app-8080"
 ✓  Unlink successful
 ✓  Unlinking component "backend" from component "node" for secret "backend-app-8080"
 [921ms]
 ◐  Unlinking component "backend" from component "node" for secret "backend-app-8778"
 ◓  Unlinking component "backend" from component "node" for secret "backend-app-8778"
 ◑  Unlinking component "backend" from component "node" for secret "backend-app-8778"
 ✓  Unlink successful
 ✓  Unlinking component "backend" from component "node" for secret "backend-app-8778"
 [2s]
 ✓  Deleting component backend [920ms]
 ✓  Component backend from application app has been deleted
```
Do you think you can suggest where I can improve here?

**Comment by dharmit** [comment]
> @mik-dass Thanks for the tip! It makes sense. But I'll need some help. Can you see if you can help me?
> 
> Here's the `git diff`:
> 
> ```shell
> $ git diff
> diff --git a/pkg/odo/cli/component/delete.go b/pkg/odo/cli/component/delete.go
> index 932df0f3e..9a0fdadae 100644
> --- a/pkg/odo/cli/component/delete.go
> +++ b/pkg/odo/cli/component/delete.go
> @@ -99,13 +99,18 @@ func (do *DeleteOptions) Run() (err error) {
>                         componentSecrets := component.UnlinkComponents(parentComponent, compoList)
>  
>                         for component, secret := range componentSecrets {
> +                               spinner := log.NewStatus(log.GetStdout())
> +                               defer spinner.End(true)
>                                 for _, secretName := range secret {
> +                                       spinner.Start(fmt.Sprintf("Unlinking component %q from component %q for secret %q\n", parentComponent.Name, component, secretName), false)
>                                         err = do.Client.UnlinkSecret(secretName, component, do.Context.Application)
>                                         if err != nil {
> +                                               log.Errorf("Unlinking failed")
>                                                 return err
>                                         }
> -                                       log.Successf("Unlinked component %q from component %q for secret %q", parentComponent.Name, component, secretName)
> +                                       log.Successf("Unlink successful")
>                                 }
> +                               spinner.End(true)
>                         }
>                         err = component.Delete(do.Client, do.componentName, do.Application)
>                         if err != nil {
> ```
> 
> And here's the output which is clearly messed up!
> 
> ```shell
>  odo delete -f
>  ◐  Unlinking component "backend" from component "frontend" for secret "backend-app-8778"
>  ◓  Unlinking component "backend" from component "frontend" for secret "backend-app-8778"
>  ◑  Unlinking component "backend" from component "frontend" for secret "backend-app-8778"
>  ✓  Unlink successful
>  ✓  Unlinking component "backend" from component "frontend" for secret "backend-app-8778"
>  [614ms]
>  ◐  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
>  ◓  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
>  ◑  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
>  ◒  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
>  ◐  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
>  ◓  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
>  ◑  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
>  ✓  Unlink successful
>  ✓  Unlinking component "backend" from component "frontend" for secret "backend-app-8080"
>  [2s]
>  ◐  Unlinking component "backend" from component "node" for secret "backend-app-8080"
>  ◓  Unlinking component "backend" from component "node" for secret "backend-app-8080"
>  ◑  Unlinking component "backend" from component "node" for secret "backend-app-8080"
>  ◒  Unlinking component "backend" from component "node" for secret "backend-app-8080"
>  ✓  Unlink successful
>  ✓  Unlinking component "backend" from component "node" for secret "backend-app-8080"
>  [921ms]
>  ◐  Unlinking component "backend" from component "node" for secret "backend-app-8778"
>  ◓  Unlinking component "backend" from component "node" for secret "backend-app-8778"
>  ◑  Unlinking component "backend" from component "node" for secret "backend-app-8778"
>  ✓  Unlink successful
>  ✓  Unlinking component "backend" from component "node" for secret "backend-app-8778"
>  [2s]
>  ✓  Deleting component backend [920ms]
>  ✓  Component backend from application app has been deleted
> ```
> 
> Do you think you can suggest where I can improve here?

Think I managed to have a sane output:
```sh
odo delete -f
 ✓  Unlinking components [614ms]
 ✓  Unlinking component "backend" from component "node" for secret "backend-app-8080"

 ✓  Unlinking component "backend" from component "node" for secret "backend-app-8778"

 ✓  Deleting component backend [1s]
 ✓  Component backend from application app has been deleted
```
with this `git diff`:
```sh
$ git diff
diff --git a/pkg/odo/cli/component/delete.go b/pkg/odo/cli/component/delete.go
index 932df0f3e..617d98c92 100644
--- a/pkg/odo/cli/component/delete.go
+++ b/pkg/odo/cli/component/delete.go
@@ -99,12 +99,19 @@ func (do *DeleteOptions) Run() (err error) {
                        componentSecrets := component.UnlinkComponents(parentComponent, compoList)
 
                        for component, secret := range componentSecrets {
+                               spinner := log.Spinner("Unlinking components")
                                for _, secretName := range secret {
+
+                                       defer spinner.End(false)
+
                                        err = do.Client.UnlinkSecret(secretName, component, do.Context.Application)
                                        if err != nil {
+                                               log.Errorf("Unlinking failed")
                                                return err
                                        }
-                                       log.Successf("Unlinked component %q from component %q for secret %q", parentComponent.Name, component, secretName)
+
+                                       spinner.End(true)
+                                       log.Successf(fmt.Sprintf("Unlinking component %q from component %q for secret %q\n", parentComponent.Name, component, secretName))
                                }
                        }
                        err = component.Delete(do.Client, do.componentName, do.Application)
```

File: pkg/odo/cli/component/delete.go (hunk 1 above)
Comment (dharmit) [reply pkg/odo/cli/component/delete.go]: Fixed

**Comment by mik-dass** [comment]
> Think I managed to have a sane output:

@dharmit The new output looks good to me :+1:

**Comment by dharmit** [comment]
> > @amitkrout if yes, which file do you recommend I add it to?
> 
> I would categorize it as link test.

Done. PR's ready for another round of review @kadel @mik-dass @cdrage.

File: tests/integration/cmd_link_unlink_test.go [hunk 2]
```diff
@@ -133,5 +133,23 @@ var _ = Describe("odo link and unlink command tests", func() {
...
+			helper.CmdShouldPass("odo", "push", "--context", frontendContext)
+			helper.CopyExample(filepath.Join("source", "nodejs"), backendContext)
+			helper.CmdShouldPass("odo", "create", "nodejs", "backend", "--context", backendContext, "--project", project)
+			helper.CmdShouldPass("odo", "push", "--context", backendContext)
+
+			// now link frontend to the backend component
+			helper.CmdShouldPass("odo", "link", "backend", "--port", "8080", "--context", frontendContext)
+
+			// now delete the backend component and then the frontend component
+			// this didn't work earlier: https://github.com/openshift/odo/issues/2355
```
Comment (mik-dass) [inline tests/integration/cmd_link_unlink_test.go]: do we need this comment?

File: tests/integration/cmd_link_unlink_test.go [hunk 3]
```diff
@@ -133,5 +133,23 @@ var _ = Describe("odo link and unlink command tests", func() {
 
 			helper.CmdShouldPass("odo", "unlink", "backend", "--app", appName, "--port", "8080", "--context", frontendContext)
 		})
+
+		It("should successfully delete component after linked component is deleted", func() {
+			// first create the two components
+			helper.CopyExample(filepath.Join("source", "nodejs"), frontendContext)
+			helper.CmdShouldPass("odo", "create", "nodejs", "frontend", "--context", frontendContext, "--project", project)
+			helper.CmdShouldPass("odo", "push", "--context", frontendContext)
+			helper.CopyExample(filepath.Join("source", "nodejs"), backendContext)
```
Comment (mik-dass) [inline tests/integration/cmd_link_unlink_test.go]: Maybe use some other component type like java?

File: tests/integration/cmd_link_unlink_test.go (hunk 2 above)
Comment (dharmit) [reply tests/integration/cmd_link_unlink_test.go]: not really. have mentioned this just to have the context. If some time down the line someone wonders why this has been added, they can take a look at the issue.

File: tests/integration/cmd_link_unlink_test.go (hunk 3 above)
Comment (dharmit) [reply tests/integration/cmd_link_unlink_test.go]: I used two nodejs components for tests to be faster. For the purpose of this test, it doesn't matter which components are started.
