### PR TITLE
Wait for component deletion, Add `--wait` flag to `odo delete`

### LINKED ISSUE #2682: `odo delete` should wait until all component related resources are gone before exit
/kind bug

## What versions of software are you using?

**Operating System:**
Windows 10 Pro
**Output of `odo version`:**
`odo v1.1.0 (86c7e2c9)`

## How did you run odo exactly?
Deleting component while in context folder with
`odo delete`

Then pushing component to cluster right away
`odo push`

## Actual behavior
`odo push` fails with:
```
c:\Temp\nodejs-ex>"c:\p\vscode-openshift-tools\out\tools\win32\odo.exe" push -v 4
I0304 22:15:10.393157   14816 common_push.go:117] SourceLocation: ./
I0304 22:15:10.394157   14816 common_push.go:125] Source Path: c:\Temp\nodejs-ex
Validation
 -  Checking component  ...
I0304 22:15:10.443158   14816 occlient.go:2549] Getting DeploymentConfig: nodejs-ex-app1
I0304 22:15:10.466161   14816 component.go:506] Checking source location: ./
 V  Checking component [26ms]

Configuration changes
 V  Initializing component
 -  Creating component  ...
I0304 22:15:10.485159   14816 occlient.go:747] Found exact image tag match for nodejs:8
 X  Creating component [88ms]
 X  Failed to create component with name nodejs-ex. Please use `odo config view` to view settings used to create component. Error: failed to create component with args {Name:nodejs-ex SourcePath:./ SourceRef: SourceType:local ImageName:nodejs:8 EnvVars:[DEBUG_PORT=5858] Ports:[8080/TCP 5858/TCP]  Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},} ApplicationName:app1 Wait:false StorageToBeMounted:map[] StdOut:<nil>}: unable to create PVC for nodejs-ex-app1: unable to create PVC: object is being deleted: persistentvolumeclaims "nodejs-ex-app1-s2idata" already exists
```

## Expected behavior
`odo delete` exits when all components resources are gone.
`odo push` works as usual and deploys component.

## Any logs, error output, etc?
see **Actual behavior**.

### PR DESCRIPTION
**Pull request by adisky**
**What type of PR is this?**
/kind feature

**What does does this PR do / why we need it**:
It adds `--wait` flag in `odo component delete`, which waits for component and its dependents to get deleted. with `foregroundDeletionPolicy` kubernetes deletes the dependent first which are referring `dc` with `ownerReference`. Then it deletes the `dc` itself. we have added `watch` to `dc` so that it waits for deletion of `dc`

**Which issue(s) this PR fixes**:

Fixes #2682  

**How to test changes / Special notes to the reviewer**:
Run `odo delete -f -w` on a deployed component, 
Run `oc get pvc`, check th s2i pvc gets deleted
Run `oc get route`, check the route created via url gets deleted

### CODE REVIEW

**Comment by amitkrout** [comment]
> How to test changes / Special notes to the reviewer:
Run odo delete -f -w on a deployed component, Immediately run odo push, it should not fail now with alreadyexist error as odo delete -f -w would wait for deletion to get completed.

@adisky Are you verifying the steps or torturing the code 🗡  hahaha....
I would say add steps which are easy to understand, user facing and more importantly use these steps in integration spec.

**Comment by amitkrout** [comment]
@adisky Please cleanup ```What type of PR is this?```

File: tests/integration/component.go [hunk 1]
```diff
@@ -835,22 +835,21 @@ func componentTests(args ...string) {
...
+
+			// TODO: Add this When the issue #2710 gets fixed
+			// helper.CmdShouldPass("odo", "storage", "create", "storage-name", "--size", "1Gi", "--path", "/data", "--context", context)
 			helper.ValidateLocalCmpExist(context, "Type,nodejs", "Name,"+cmpName, "Application,"+appName, "URL,0,Name,example")
 			helper.CmdShouldPass("odo", append(args, "push", "--context", context)...)
 
-			helper.CmdShouldPass("odo", "url", "create", "example-1", "--context", context)
-			helper.CmdShouldPass("odo", "storage", "create", "storage-name-1", "--size", "1Gi", "--path", "/data-1", "--context", context)
-			helper.CmdShouldPass("odo", append(args, "push", "--context", context)...)
+			// delete with --wait flag
```
Comment (amitkrout) [inline tests/integration/component.go]: @adisky Deleting these lines may cause some real functionality validation miss. These lines were added due to some reason may be to catch any regression for specific scenario. IMO create a separate spec to verify your changes.

**Comment by adisky** [comment]
> > How to test changes / Special notes to the reviewer:
> > Run odo delete -f -w on a deployed component, Immediately run odo push, it should not fail now with alreadyexist error as odo delete -f -w would wait for deletion to get completed.
> 
> @adisky Are you verifying the steps or torturing the code  hahaha....
> I would say add steps which are easy to understand, user facing and more importantly use these steps in integration spec.

@amitkrout Please check the reported issue. it is signifying running `odo push` just after `odo delete`, however i have simplified

File: tests/integration/component.go (hunk 1 above)
Comment (adisky) [reply tests/integration/component.go]: @amitkrout this test was not catching any regression, This line would always be true.  https://github.com/openshift/odo/blob/master/tests/helper/helper_oc.go#L458
I have fixed the test case and removed not necessary checks. Please check the regression it missed
https://github.com/openshift/odo/issues/2710
https://github.com/openshift/odo/issues/2693

Comment (adisky) [reply tests/integration/component.go]: you can run the test case manually in verbose mode, and verify it is passing even if the pvc still exist, however it should fail here https://github.com/openshift/odo/blob/master/tests/integration/component.go#L846

Comment (amitkrout) [reply tests/integration/component.go]: @adisky Understood, but tbh you are destroying one existing scenario with your changes. Why i am saying because the scenario is
```
create component 
create url
Create storage
odo push
create url
create storage
odo push
normal delete component 
```
And you are skipping steps of url create, storage create and push. IIRC the steps of running url create,storage create and push twice was to catch some short failure. So don't skip those steps. Rest script changes looks good to me.

Comment (adisky) [reply tests/integration/component.go]: @amitkrout sure i would add it, but we cannot add storage as of now, due to  #2710

File: pkg/occlient/occlient.go [hunk 2]
```diff
@@ -2138,6 +2156,37 @@ func (c *Client) Delete(labels map[string]string) error {
...
+
+	for {
+		select {
+		case event, ok := <-eventCh:
+			_, typeOk := event.Object.(*appsv1.DeploymentConfig)
+			if !ok || !typeOk {
+				return errors.New("Unable to watch deployment config")
+			}
+			if event.Type == watch.Deleted {
+				fmt.Println("deleted")
```
Comment (mik-dass) [inline pkg/occlient/occlient.go]: please use glog here

**Comment by girishramnani** [comment]
@adisky any update on this?

**Comment by adisky** [comment]
> @adisky any update on this?

yes updated it.

File: tests/helper/helper_oc.go [hunk 3]
```diff
@@ -481,3 +481,12 @@ func (oc *OcRunner) GetServices(namespace string) string {
 	output := string(session.Wait().Out.Contents())
 	return output
 }
+
+// VerifyResourceDeleted verifies if the given resource is deleted from cluster
+func (oc *OcRunner) VerifyResourceDeleted(resourceType, resourceName, namespace string) {
+	session := CmdRunner(oc.path, "get", resourceType, "--namespace", namespace)
+	Eventually(session).Should(gexec.Exit(0))
+	output := string(session.Wait().Out.Contents())
```
Comment (mik-dass) [inline tests/helper/helper_oc.go:489]: I think this should be `Err.Contents()` because of https://github.com/kubernetes/kubectl/issues/847

Comment (adisky) [reply tests/helper/helper_oc.go:489]: I am checking for contents, so i guess its ok.

Comment (adisky) [reply tests/helper/helper_oc.go:489]: `Expect(output).NotTo(ContainSubstring(resourceName))`

File: tests/integration/component.go [hunk 4]
```diff
@@ -853,5 +854,28 @@ func componentTests(args ...string) {
...
+			helper.CmdShouldPass("odo", "storage", "create", "storage-2", "--size", "1Gi", "--path", "/data2", "--context", context)
+			helper.CmdShouldPass("odo", append(args, "push", "--context", context)...)
+
+			// delete with --wait flag
+			helper.CmdShouldPass("odo", append(args, "delete", "-f", "-w", "--context", context)...)
+
+			oc.VerifyResourceDeleted("routes", "example", project)
+			oc.VerifyResourceDeleted("service", cmpName, project)
+			// verify s2i pvc is delete
+			oc.VerifyResourceDeleted("pvc", "s2idata", project)
```
Comment (mik-dass) [inline tests/integration/component.go:877]: there are three PVCs, we need to check if all of them are deleted

```
Running oc with args [oc get pvc --namespace twmwqqprru]
[oc] NAME                  STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
[oc] mvfzn-hgfxb-s2idata   Bound     pvc-jdslkaj-9f92-ljajlds          1Gi        RWO            gp2-encrypted   1m
[oc] storage-1-hgfxb-pvc   Bound     pvc-dasjldj-9f92-dhfhd           1Gi        RWO            gp2-encrypted   1m
[oc] storage-2-hgfxb-pvc   Bound     pvc-jsalkjd-9f92-lksala           1Gi        RWO            gp2-encrypted   44s
```

File: tests/helper/helper_oc.go (hunk 3 above)
Comment (mik-dass) [reply tests/helper/helper_oc.go:489]: But I would suggest not using resource names for validation and instead checking if none of the resource type exist because if someone misses a resource name while writing a test, it could go unchecked like in https://github.com/openshift/odo/pull/2732/files#r405976748

File: tests/integration/component.go (hunk 4 above)
Comment (adisky) [reply tests/integration/component.go:877]: Thanks for reminding.

File: tests/helper/helper_oc.go (hunk 3 above)
Comment (adisky) [reply tests/helper/helper_oc.go:489]: I feel checking the resource name is less error name, as it is exactly pointing what needs to be checked.

Comment (mik-dass) [reply tests/helper/helper_oc.go:489]: yes but it can lead to the above mentioned scenarios

Comment (adisky) [reply tests/helper/helper_oc.go:489]: I dont think, it is problem, checking `none` lead to entirely missing the error of pvc deletion
https://github.com/openshift/odo/commit/5cb97bcd7dbfbc243e8405857fadea268c4e3db2
I feeld it is better approach.

Comment (mik-dass) [reply tests/helper/helper_oc.go:489]: > I dont think, it is problem, checking none lead to entirely missing the error of pvc deletion
5cb97bc

That problem occured due to https://github.com/kubernetes/kubectl/issues/847 and we already have a solution for now. And this approach can lead to https://github.com/openshift/odo/pull/2732/files#r405976748 (highly possible that someone will make this mistake)

Comment (adisky) [reply tests/helper/helper_oc.go:489]: I missed this, as it has been rebased several time, I am not saying your approach is not right but i have thoroughly tested with this one, there and found it better.

Comment (mik-dass) [reply tests/helper/helper_oc.go:489]: > I missed this, as it has been rebased several time, I am not saying your approach is not right but i have thoroughly tested with this one, and hence found it better.

I know you have fixed it and have thoroughly tested it. But my concern is someone else missing something while using this function.

Comment (adisky) [reply tests/helper/helper_oc.go:489]: and `VerifyResourceDeleted` is checking if that particular resource has been deleted or not, If someday we might not delete user created `pvc` with odo delete, then `No resource found` not work, my point here is in test cases absolute verification is better.

Comment (amitkrout) [reply tests/helper/helper_oc.go:489]: hang on. Let me check the usecase first.

Comment (mik-dass) [reply tests/helper/helper_oc.go:489]: > then No resource found not work, my point here is in test cases absolute verification is better.

I agree with this point and it will be useful later on but since this test scenario requires checking the existence of all the given resource type, I would like a function to check for the existence of all so we don't miss something by mistake.

File: tests/helper/helper_oc.go [hunk 5]
```diff
@@ -481,3 +481,11 @@ func (oc *OcRunner) GetServices(namespace string) string {
...
```
Comment (amitkrout) [inline tests/helper/helper_oc.go:489]: > I think this should be Err.Contents() because of kubernetes/kubectl#847
I am checking for contents, so i guess its ok.
Expect(output).NotTo(ContainSubstring(resourceName))

@adisky Perticularly in this case you should not use ```Out.Contents()``` because of the open issue kubernetes/kubectl#847 as mentioned by @mik-dass 

Actually you are verifying ```""``` with ```not to contains resourceName```. So the result comes always true because ```""``` never contains anything let say the resource name.  
```
func (oc *OcRunner) VerifyResourceDeleted(resourceType, resourceName, namespace string) {
	session := CmdRunner(oc.path, "get", resourceType, "--namespace", namespace)
	Eventually(session).Should(gexec.Exit(0))
	output := string(session.Wait().Err.Contents())
	fmt.Println("StdOut is :", output)
	Expect(output).NotTo(ContainSubstring(resourceName))
}

Terminal output:

Running oc with args [oc get routes --namespace zevxjfovay]
[oc] No resources found in zevxjfovay namespace.
StdOut is : 
```

However you can use ```Err.Contents()``` atm till the upstream issue is not resolved. You can see how the actual output channels to StdErr instead of StdOut though the exit code is ```0```. Then only your string validation will make sense.
```
func (oc *OcRunner) VerifyResourceDeleted(resourceType, resourceName, namespace string) {
	session := CmdRunner(oc.path, "get", resourceType, "--namespace", namespace)
	Eventually(session).Should(gexec.Exit(0))
	output := string(session.Wait().Err.Contents())
	fmt.Println("StdErr is :", output)
	Expect(output).NotTo(ContainSubstring(resourceName))
}

Terminal output:

Running oc with args [oc get routes --namespace mqdtjckwfe]
[oc] No resources found in mqdtjckwfe namespace.
StdErr is : No resources found in mqdtjckwfe namespace.
```

File: tests/helper/helper_oc.go (hunk 3 above)
Comment (amitkrout) [reply tests/helper/helper_oc.go:489]: @adisky https://github.com/openshift/odo/pull/2732#discussion_r406061981

File: tests/helper/helper_oc.go (hunk 5 above)
Comment (adisky) [reply tests/helper/helper_oc.go:489]: @amitkrout it does not output `""` if the resource exist, if the resource exist and not deleted it will list the resources in the content and 	`Expect(output).NotTo(ContainSubstring(resourceName))` would fail

Comment (amitkrout) [reply tests/helper/helper_oc.go:489]: > it does not output ""

Yes, it gives the output ```""```` in ```StdOut``` channel because of the upstream issue.

Pasting it again. Please check it.
```
func (oc *OcRunner) VerifyResourceDeleted(resourceType, resourceName, namespace string) {
	session := CmdRunner(oc.path, "get", resourceType, "--namespace", namespace)
	Eventually(session).Should(gexec.Exit(0))
	output := string(session.Wait().Out.Contents())
	fmt.Println("StdOut is :", output)
	Expect(output).NotTo(ContainSubstring(resourceName))
}

Terminal output:

Running oc with args [oc get routes --namespace zevxjfovay]
[oc] No resources found in zevxjfovay namespace.
StdOut is :
```

Check for more info - https://stackoverflow.com/questions/3385201/confused-about-stdin-stdout-and-stderr

Comment (adisky) [reply tests/helper/helper_oc.go:489]: **Test gets failed, when it found any resource is existed. I see nothing wrong in the test case.**

`odo sub component command tests
/home/adisky/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_sub_test.go:13
  odo component delete should clean owned resources
  /home/adisky/go/src/github.com/openshift/odo/tests/integration/component.go:823
    should delete the component and the owned resources with wait flag [It]
    /home/adisky/go/src/github.com/openshift/odo/tests/integration/component.go:858

    Expected
        <string>: NAME              HOST/PORT                                     PATH   SERVICES      PORT   TERMINATION   WILDCARD
        example-1-zgpbk   example-1-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None
        example-2-zgpbk   example-2-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None
        
    not to contain substring
        <string>: example

    /home/adisky/go/src/github.com/openshift/odo/tests/helper/helper_oc.go:491
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Summarizing 2 Failures:

[Fail] odo component command tests odo component delete should clean owned resources [It] should delete the component and the owned resources with wait flag 
/home/adisky/go/src/github.com/openshift/odo/tests/helper/helper_oc.go:491
`

Comment (adisky) [reply tests/helper/helper_oc.go:489]: > > it does not output ""
> 
> Yes, it gives the output `""` in `StdOut` channel because of the upstream issue.
> 
> Pasting it again. Please check it.
> 
> ```
> func (oc *OcRunner) VerifyResourceDeleted(resourceType, resourceName, namespace string) {
> 	session := CmdRunner(oc.path, "get", resourceType, "--namespace", namespace)
> 	Eventually(session).Should(gexec.Exit(0))
> 	output := string(session.Wait().Out.Contents())
> 	fmt.Println("StdOut is :", output)
> 	Expect(output).NotTo(ContainSubstring(resourceName))
> }
> 
> Terminal output:
> 
> Running oc with args [oc get routes --namespace zevxjfovay]
> [oc] No resources found in zevxjfovay namespace.
> StdOut is :
> ```
> 
> Check for more info - https://stackoverflow.com/questions/3385201/confused-about-stdin-stdout-and-stderr
It outputs the resource name when it exist.

**Comment by adisky** [comment]
@amitkrout raw test logs, in case resource exist, test should fail.
```
odo sub component command tests odo component delete should clean owned resources 
  should delete the component and the owned resources with wait flag
  /home/adisky/go/src/github.com/openshift/odo/tests/integration/component.go:858
Created dir: /tmp/234650130
Creating a new project: fgqbtmujjt
Running odo with args [odo project create fgqbtmujjt -w -v4]
[odo] I0409 14:46:20.352890   18863 preference.go:165] The path for preference file is /tmp/234650130/config.yaml
[odo]  •  Waiting for project to come up  ...
[odo] I0409 14:46:21.186053   18863 occlient.go:531] Status of creation of project fgqbtmujjt is Active
[odo] I0409 14:46:21.186128   18863 occlient.go:536] Project fgqbtmujjt now exists
[odo] I0409 14:46:21.192714   18863 occlient.go:571] Status of creation of service account &ServiceAccount{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:default,GenerateName:,Namespace:fgqbtmujjt,SelfLink:/api/v1/namespaces/fgqbtmujjt/serviceaccounts/default,UID:c6364f68-7a42-11ea-875c-52fdfc072182,ResourceVersion:993551,Generation:0,CreationTimestamp:2020-04-09 14:46:20 +0530 IST,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Secrets:[{  default-token-pcw66    } {  default-dockercfg-mctts    }],ImagePullSecrets:[{default-dockercfg-mctts}],AutomountServiceAccountToken:nil,} is ready
 ✓  Waiting for project to come up [812ms]
[odo]  ✓  Project 'fgqbtmujjt' is ready for use
[odo]  ✓  New project created and now using project: fgqbtmujjt
[odo] I0409 14:46:21.207444   18863 odo.go:80] Could not get the latest release information in time. Never mind, exiting gracefully :)
Running odo with args [odo component create nodejs lfhyf --app zgpbk --project fgqbtmujjt --context /tmp/234650130]
[odo]  •  Validating component  ...
 ✓  Validating component [7ms]
[odo] 
[odo] Please use `odo push` command to create the component with source deployed
Running odo with args [odo url create example-1 --context /tmp/234650130]
[odo]  ✓  URL example-1 created for component: lfhyf
[odo] 
[odo] To create URL on the OpenShift Cluster, please use `odo push`
Running odo with args [odo storage create storage-1 --size 1Gi --path /data1 --context /tmp/234650130]
[odo]  ✓  Added storage storage-1 to lfhyf
[odo] 
[odo] Please use `odo push` command to make the storage accessible to the component
Running odo with args [odo component push --context /tmp/234650130]
[odo] Validation
[odo]  •  Checking component  ...
 ✓  Checking component [11ms]
[odo] 
[odo] Configuration changes
[odo]  ✓  Added storage storage-1 to lfhyf
[odo]  ✓  Initializing component
[odo]  •  Creating component  ...
 ✓  Creating component [70ms]
[odo] 
[odo] Applying URL changes
[odo]  ✓  URL example-1: http://example-1-zgpbk-fgqbtmujjt.apps-crc.testing created
[odo] 
[odo] Pushing to component lfhyf of type local
[odo]  •  Checking files for pushing  ...
 ✓  Checking files for pushing [414035ns]
[odo]  •  Waiting for component to start  ...
 ✓  Waiting for component to start [20s]
[odo]  •  Syncing files to the component  ...
 ✓  Syncing files to the component [6s]
[odo]  •  Building component  ...
 ✓  Building component [7s]
[odo]  ✓  Changes successfully pushed to component
Running odo with args [odo url create example-2 --context /tmp/234650130]
[odo]  ✓  URL example-2 created for component: lfhyf
[odo] 
[odo] To create URL on the OpenShift Cluster, please use `odo push`
Running odo with args [odo storage create storage-2 --size 1Gi --path /data2 --context /tmp/234650130]
[odo]  ✓  Added storage storage-2 to lfhyf
[odo] 
[odo] Please use `odo push` command to make the storage accessible to the component
Running odo with args [odo component push --context /tmp/234650130]
[odo] Validation
[odo]  •  Checking component  ...
 ✓  Checking component [23ms]
[odo] 
[odo] Configuration changes
[odo]  •  Retrieving component data  ...
[odo]  ✓  Added storage storage-2 to lfhyf
 ✓  Retrieving component data [37ms]
[odo]  •  Applying configuration  ...
 ✓  Applying configuration [35s]
[odo] 
[odo] Applying URL changes
[odo]  ✓  URL example-1 already exists
[odo]  ✓  URL example-2: http://example-2-zgpbk-fgqbtmujjt.apps-crc.testing created
[odo] 
[odo] Pushing to component lfhyf of type local
[odo]  •  Checking file changes for pushing  ...
 ✓  Checking file changes for pushing [169169ns]
[odo]  ✓  No file changes detected, skipping build. Use the '-f' flag to force the build.
Running odo with args [odo component delete -f --context /tmp/234650130]
[odo] This component has following urls that will be deleted with component
[odo] URL named example-1 with host example-1-zgpbk-fgqbtmujjt.apps-crc.testing having protocol http at port 8080
[odo] URL named example-2 with host example-2-zgpbk-fgqbtmujjt.apps-crc.testing having protocol http at port 8080
[odo] This component has following storages which will be deleted with the component
[odo] Storage storage-1 of size 1Gi
[odo] Storage storage-2 of size 1Gi
[odo]  •  Deleting component lfhyf  ...
 ✓  Deleting component lfhyf [220ms]
[odo]  ✓  Component lfhyf from application zgpbk has been deleted
Running oc with args [oc get routes --namespace fgqbtmujjt]
[oc] NAME              HOST/PORT                                     PATH   SERVICES      PORT   TERMINATION   WILDCARD
[oc] example-1-zgpbk   example-1-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None
[oc] example-2-zgpbk   example-2-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None

NAME              HOST/PORT                                     PATH   SERVICES      PORT   TERMINATION   WILDCARD
example-1-zgpbk   example-1-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None
example-2-zgpbk   example-2-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None
Deleting project: fgqbtmujjt
Running odo with args [odo project delete fgqbtmujjt -f]
[odo]  •  Deleting project fgqbtmujjt  ...
 ✓  Deleting project fgqbtmujjt [28s]
[odo]  ✓  Deleted project : fgqbtmujjt
Deleting dir: /tmp/234650130

• Failure [99.383 seconds]
odo sub component command tests
/home/adisky/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_sub_test.go:13
  odo component delete should clean owned resources
  /home/adisky/go/src/github.com/openshift/odo/tests/integration/component.go:823
    should delete the component and the owned resources with wait flag [It]
    /home/adisky/go/src/github.com/openshift/odo/tests/integration/component.go:858

    Expected
        <string>: NAME              HOST/PORT                                     PATH   SERVICES      PORT   TERMINATION   WILDCARD
        example-1-zgpbk   example-1-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None
        example-2-zgpbk   example-2-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None
        
    not to contain substring
        <string>: example

    /home/adisky/go/src/github.com/openshift/odo/tests/helper/helper_oc.go:491
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Summarizing 2 Failures:

[Fail] odo component command tests odo component delete should clean owned resources [It] should delete the component and the owned resources with wait flag 
/home/adisky/go/src/github.com/openshift/odo/tests/helper/helper_oc.go:491

[Fail] odo sub component command tests odo component delete should clean owned resources [It] should delete the component and the owned resources with wait flag 
/home/adisky/go/src/github.com/openshift/odo/tests/helper/helper_oc.go:491

Ran 2 of 170 Specs in 223.129 seconds
FAIL! -- 0 Passed | 2 Failed | 0 Pending | 168 Skipped
--- FAIL: TestIntegration (223.13s)
FAIL

Ginkgo ran 1 suite in 3m44.768249387s
Test Suite Failed
```

File: tests/helper/helper_oc.go (hunk 5 above)
Comment (amitkrout) [reply tests/helper/helper_oc.go:489]: Yup, this is expected because of https://github.com/openshift/odo/blob/master/tests/helper/helper_run.go#L77

If fails it get the output from ```StdErr``` like mentioned in line https://github.com/openshift/odo/blob/master/tests/helper/helper_run.go#L80

**Comment by amitkrout** [comment]
> @amitkrout raw test logs, in case resource exist, test should fail.
> 
> ```
> odo sub component command tests odo component delete should clean owned resources 
>   should delete the component and the owned resources with wait flag
>   /home/adisky/go/src/github.com/openshift/odo/tests/integration/component.go:858
> Created dir: /tmp/234650130
> Creating a new project: fgqbtmujjt
> Running odo with args [odo project create fgqbtmujjt -w -v4]
> [odo] I0409 14:46:20.352890   18863 preference.go:165] The path for preference file is /tmp/234650130/config.yaml
> [odo]  •  Waiting for project to come up  ...
> [odo] I0409 14:46:21.186053   18863 occlient.go:531] Status of creation of project fgqbtmujjt is Active
> [odo] I0409 14:46:21.186128   18863 occlient.go:536] Project fgqbtmujjt now exists
> [odo] I0409 14:46:21.192714   18863 occlient.go:571] Status of creation of service account &ServiceAccount{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:default,GenerateName:,Namespace:fgqbtmujjt,SelfLink:/api/v1/namespaces/fgqbtmujjt/serviceaccounts/default,UID:c6364f68-7a42-11ea-875c-52fdfc072182,ResourceVersion:993551,Generation:0,CreationTimestamp:2020-04-09 14:46:20 +0530 IST,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Secrets:[{  default-token-pcw66    } {  default-dockercfg-mctts    }],ImagePullSecrets:[{default-dockercfg-mctts}],AutomountServiceAccountToken:nil,} is ready
>  ✓  Waiting for project to come up [812ms]
> [odo]  ✓  Project 'fgqbtmujjt' is ready for use
> [odo]  ✓  New project created and now using project: fgqbtmujjt
> [odo] I0409 14:46:21.207444   18863 odo.go:80] Could not get the latest release information in time. Never mind, exiting gracefully :)
> Running odo with args [odo component create nodejs lfhyf --app zgpbk --project fgqbtmujjt --context /tmp/234650130]
> [odo]  •  Validating component  ...
>  ✓  Validating component [7ms]
> [odo] 
> [odo] Please use `odo push` command to create the component with source deployed
> Running odo with args [odo url create example-1 --context /tmp/234650130]
> [odo]  ✓  URL example-1 created for component: lfhyf
> [odo] 
> [odo] To create URL on the OpenShift Cluster, please use `odo push`
> Running odo with args [odo storage create storage-1 --size 1Gi --path /data1 --context /tmp/234650130]
> [odo]  ✓  Added storage storage-1 to lfhyf
> [odo] 
> [odo] Please use `odo push` command to make the storage accessible to the component
> Running odo with args [odo component push --context /tmp/234650130]
> [odo] Validation
> [odo]  •  Checking component  ...
>  ✓  Checking component [11ms]
> [odo] 
> [odo] Configuration changes
> [odo]  ✓  Added storage storage-1 to lfhyf
> [odo]  ✓  Initializing component
> [odo]  •  Creating component  ...
>  ✓  Creating component [70ms]
> [odo] 
> [odo] Applying URL changes
> [odo]  ✓  URL example-1: http://example-1-zgpbk-fgqbtmujjt.apps-crc.testing created
> [odo] 
> [odo] Pushing to component lfhyf of type local
> [odo]  •  Checking files for pushing  ...
>  ✓  Checking files for pushing [414035ns]
> [odo]  •  Waiting for component to start  ...
>  ✓  Waiting for component to start [20s]
> [odo]  •  Syncing files to the component  ...
>  ✓  Syncing files to the component [6s]
> [odo]  •  Building component  ...
>  ✓  Building component [7s]
> [odo]  ✓  Changes successfully pushed to component
> Running odo with args [odo url create example-2 --context /tmp/234650130]
> [odo]  ✓  URL example-2 created for component: lfhyf
> [odo] 
> [odo] To create URL on the OpenShift Cluster, please use `odo push`
> Running odo with args [odo storage create storage-2 --size 1Gi --path /data2 --context /tmp/234650130]
> [odo]  ✓  Added storage storage-2 to lfhyf
> [odo] 
> [odo] Please use `odo push` command to make the storage accessible to the component
> Running odo with args [odo component push --context /tmp/234650130]
> [odo] Validation
> [odo]  •  Checking component  ...
>  ✓  Checking component [23ms]
> [odo] 
> [odo] Configuration changes
> [odo]  •  Retrieving component data  ...
> [odo]  ✓  Added storage storage-2 to lfhyf
>  ✓  Retrieving component data [37ms]
> [odo]  •  Applying configuration  ...
>  ✓  Applying configuration [35s]
> [odo] 
> [odo] Applying URL changes
> [odo]  ✓  URL example-1 already exists
> [odo]  ✓  URL example-2: http://example-2-zgpbk-fgqbtmujjt.apps-crc.testing created
> [odo] 
> [odo] Pushing to component lfhyf of type local
> [odo]  •  Checking file changes for pushing  ...
>  ✓  Checking file changes for pushing [169169ns]
> [odo]  ✓  No file changes detected, skipping build. Use the '-f' flag to force the build.
> Running odo with args [odo component delete -f --context /tmp/234650130]
> [odo] This component has following urls that will be deleted with component
> [odo] URL named example-1 with host example-1-zgpbk-fgqbtmujjt.apps-crc.testing having protocol http at port 8080
> [odo] URL named example-2 with host example-2-zgpbk-fgqbtmujjt.apps-crc.testing having protocol http at port 8080
> [odo] This component has following storages which will be deleted with the component
> [odo] Storage storage-1 of size 1Gi
> [odo] Storage storage-2 of size 1Gi
> [odo]  •  Deleting component lfhyf  ...
>  ✓  Deleting component lfhyf [220ms]
> [odo]  ✓  Component lfhyf from application zgpbk has been deleted
> Running oc with args [oc get routes --namespace fgqbtmujjt]
> [oc] NAME              HOST/PORT                                     PATH   SERVICES      PORT   TERMINATION   WILDCARD
> [oc] example-1-zgpbk   example-1-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None
> [oc] example-2-zgpbk   example-2-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None
> 
> NAME              HOST/PORT                                     PATH   SERVICES      PORT   TERMINATION   WILDCARD
> example-1-zgpbk   example-1-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None
> example-2-zgpbk   example-2-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None
> Deleting project: fgqbtmujjt
> Running odo with args [odo project delete fgqbtmujjt -f]
> [odo]  •  Deleting project fgqbtmujjt  ...
>  ✓  Deleting project fgqbtmujjt [28s]
> [odo]  ✓  Deleted project : fgqbtmujjt
> Deleting dir: /tmp/234650130
> 
> • Failure [99.383 seconds]
> odo sub component command tests
> /home/adisky/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_sub_test.go:13
>   odo component delete should clean owned resources
>   /home/adisky/go/src/github.com/openshift/odo/tests/integration/component.go:823
>     should delete the component and the owned resources with wait flag [It]
>     /home/adisky/go/src/github.com/openshift/odo/tests/integration/component.go:858
> 
>     Expected
>         <string>: NAME              HOST/PORT                                     PATH   SERVICES      PORT   TERMINATION   WILDCARD
>         example-1-zgpbk   example-1-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None
>         example-2-zgpbk   example-2-zgpbk-fgqbtmujjt.apps-crc.testing          lfhyf-zgpbk   8080                 None
>         
>     not to contain substring
>         <string>: example
> 
>     /home/adisky/go/src/github.com/openshift/odo/tests/helper/helper_oc.go:491
> ------------------------------
> SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
> 
> Summarizing 2 Failures:
> 
> [Fail] odo component command tests odo component delete should clean owned resources [It] should delete the component and the owned resources with wait flag 
> /home/adisky/go/src/github.com/openshift/odo/tests/helper/helper_oc.go:491
> 
> [Fail] odo sub component command tests odo component delete should clean owned resources [It] should delete the component and the owned resources with wait flag 
> /home/adisky/go/src/github.com/openshift/odo/tests/helper/helper_oc.go:491
> 
> Ran 2 of 170 Specs in 223.129 seconds
> FAIL! -- 0 Passed | 2 Failed | 0 Pending | 168 Skipped
> --- FAIL: TestIntegration (223.13s)
> FAIL
> 
> Ginkgo ran 1 suite in 3m44.768249387s
> Test Suite Failed
> ```

Thnaks @adisky for discussing it over BJN. As a discussion outcome what i found that, the validation is done for the storage sub string which is printed in StdOut (In this case it's ```""``` because resource deleted successfully) and ofcourse as you metioned in the call we should not bother about the ```StdErr``` message, i agree.

Thanks @adisky for the clarification

Test looks good to me.

Approvers can you please have a look @girishramnani @kadel @cdrage

**Comment by adisky** [comment]
@amitkrout Thanks for the discussion and your inputs :)

File: pkg/occlient/occlient.go [hunk 6]
```diff
@@ -2123,6 +2141,39 @@ func (c *Client) Delete(labels map[string]string) error {
...
+	glog.V(4).Infof("Waiting for component to get deleted")
+
+	watcher, err := c.appsClient.DeploymentConfigs(c.Namespace).Watch(metav1.ListOptions{LabelSelector: selector})
+	if err != nil {
+		return err
+	}
+	defer watcher.Stop()
+	eventCh := watcher.ResultChan()
+
+	for {
```
Comment (girishramnani) [inline pkg/occlient/occlient.go:2156]: Seems that all the case statements in the select are terminating which means we might not need the for loop?

Comment (adisky) [reply pkg/occlient/occlient.go:2156]: yes even i thought so, and removed the for loop but it did not work, since we get events on `eventCh` other than `error` `deleted`, case events gets selected and executes none of the if conditions, returns from the function.

Comment (girishramnani) [reply pkg/occlient/occlient.go:2156]: Gotcha, maybe an idea would be to just v4 log those events for debugging purposes?

Comment (adisky) [reply pkg/occlient/occlient.go:2156]: yup, sure will update for that.

Comment (girishramnani) [reply pkg/occlient/occlient.go:2156]: maybe lets do that in a follow up?

Comment (girishramnani) [reply pkg/occlient/occlient.go:2156]: created a follow up https://github.com/openshift/odo/issues/2879
