### PR TITLE
remove abrubt os.Exit calls

### LINKED ISSUE #4999: Telemetry does not catch all errors due to abrupt `os.Exit` calls
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 34
**Output of `odo version`:**
odo v2.2.4 (0c0aaa5ea)

## How did you run odo exactly?
1. `odo delete` out of a context directory.
2. The above command will fail.

## Actual behavior
No telemetry data received on Segment, because at one point during this command execution, `LogErrorAndExit` is called, which exits before the telemetry data request can be triggered.

I noticed this with `odo create` or basically any command where you don't have the permission to create comp in a project.

On tracking down, it seems that this is the case with all the command execution where `LogErrorAndExit` is called at some point, except in `runnable.go`.
See - https://github.com/openshift/odo/search?q=LogErrorAndExit

## Expected behavior
Telemetry data must be sent for these errors.

## Any logs, error output, etc?

I can think of 2 solutions, atm:
1. We could either practice a strict behaviour where `LogErrorAndExit` can only be called by the `runnable.go:GenericRun`
2. Or, we could put the Telemetry data trigger request inside `LogErrorAndExit`, which would mean modifying `LogErrorAndExit` and all of its usages to be able to pass data that is required for triggering the request.

### PR DESCRIPTION
**Pull request by anandrkskd**
Signed-off-by: anandrkskd <anandrkskd@gmail.com>

**What type of PR is this?**
/kind bug
**What does this PR do / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4999

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

File: pkg/odo/cli/component/common_push.go [hunk 1]
```diff
@@ -113,7 +113,7 @@ func (cpo *CommonPushOptions) createCmpIfNotExistsAndApplyCmpConfig(stdout io.Wr
 				cmpName,
 				err,
 			)
-			os.Exit(1)
+			return err
```
Comment (feloy) [inline pkg/odo/cli/component/common_push.go:116]: I think you should call `util.LogErrorAndExit(err, "")` here

File: pkg/odo/cli/preference/view.go [hunk 2]
```diff
@@ -46,7 +45,7 @@ func (o *ViewOptions) Run(cmd *cobra.Command) (err error) {
 	cfg, err := preference.New()
 
 	if err != nil {
-		util.LogErrorAndExit(err, "")
```
Comment (feloy) [inline pkg/odo/cli/preference/view.go:49]: I think we should keep this as is

File: pkg/odo/cli/component/common_push.go (hunk 1 above)
Comment (anandrkskd) [reply pkg/odo/cli/component/common_push.go:116]: I am not sure why we want to use `LogErrorAndExit` here we are already doing logging in the above statement. And the error which is returned it just check if it's empty or not, if it's empty then it just does `return`.

File: pkg/odo/cli/preference/view.go (hunk 2 above)
Comment (anandrkskd) [reply pkg/odo/cli/preference/view.go:49]: I think, we should add log before return. But not sure why we want to keep this `LogErrorAndExit`. Can you help me understand how this will be helpful

File: pkg/odo/cli/component/common_push.go (hunk 1 above)
Comment (valaparthvi) [reply pkg/odo/cli/component/common_push.go:116]: >I think you should call util.LogErrorAndExit(err, "") here

Why do you say that @feloy? I think the whole point of this PR is to avoid abrupt exit calls, and calling `LogErrorAndExit` defies that purpose in my opinion.

File: pkg/odo/util/cmdutils.go [hunk 3]
```diff
@@ -184,7 +187,10 @@ func PrintComponentInfo(client *occlient.Client, currentComponentName string, co
 
 			// Let's also get the secrets / environment variables that are being passed in.. (if there are any)
 			secrets, err := client.GetKubeClient().GetSecret(linkedService.SecretName, project)
-			LogErrorAndExit(err, "")
+			if err != nil {
+				log.Error(errors.Cause(err))
```
Comment (valaparthvi) [inline pkg/odo/util/cmdutils.go:191]: @anandrkskd Why have you added these `log.Error` calls?

File: pkg/odo/cli/component/common_push.go (hunk 1 above)
Comment (feloy) [reply pkg/odo/cli/component/common_push.go:116]: @valaparthvi my bad, I misunderstood this function. I understood there had an existing function to be called that were exiting gracefully, I probably misunderstood

File: pkg/odo/util/cmdutils.go (hunk 3 above)
Comment (anandrkskd) [reply pkg/odo/util/cmdutils.go:191]: To log the error we experienced, I will remove it, as I overlooked that in the end it is printed after call telemetry command. I will update it ASAP

Comment (anandrkskd) [reply pkg/odo/util/cmdutils.go]: Updated

**Review by valaparthvi — COMMENTED** [review]
Anand, the current changes lgtm, however I see a few functions where you can make similar changes, can you include them as well?
https://github.com/openshift/odo/blob/main/pkg/devfile/adapters/kubernetes/component/adapter.go#L268
https://github.com/openshift/odo/blob/main/pkg/odo/cli/component/common_push.go#L122

**Comment by valaparthvi** [comment]
/retest-required

Reason - abrupt failure of both the k8s tests
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/5087/pull-ci-openshift-odo-main-psi-k8s-ibmc-integration-e2e/1442418706570285056
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/5087/pull-ci-openshift-odo-main-psi-kubernetes-integration-e2e/1442418706629005312

**Comment by valaparthvi** [comment]
All the context related functions in context.go should return *Context, and error and this error should be returned in order to fix this telemetry error.
The following places should return an error to be bubbled up - 
1. internalCxt.resolveProject - https://github.com/openshift/odo/blob/main/pkg/odo/genericclioptions/resolve.go#L31
2. genericclioptions.GetContextFlagValue  - https://github.com/openshift/odo/blob/main/pkg/odo/genericclioptions/flag.go#L34 and https://github.com/openshift/odo/blob/main/pkg/odo/genericclioptions/flag.go#L38
3. internalCxt.resolveNamespace - https://github.com/openshift/odo/blob/main/pkg/odo/genericclioptions/resolve.go#L70
and checkProjectCreateOrDeleteOnlyOnInvalidNamespaceNoFmt - https://github.com/openshift/odo/blob/main/pkg/odo/genericclioptions/util.go#L47
4. CopyFile - https://github.com/openshift/odo/blob/main/pkg/sync/sync.go#L44
5.  genericclioptions.ApplyIgnore - https://github.com/openshift/odo/blob/main/pkg/odo/genericclioptions/util.go#L71
6. CheckMachineReadableOutputCommand - https://github.com/openshift/odo/blob/main/pkg/odo/genericclioptions/runnable.go#L191


Other simple and might require more work places that need fixing - 
1. IsSecure - https://github.com/openshift/odo/blob/main/pkg/odo/cli/registry/util/util.go#L23
2. ComponentAllowingEmpty - https://github.com/openshift/odo/blob/main/pkg/odo/genericclioptions/context.go#L373 & https://github.com/openshift/odo/blob/main/pkg/odo/genericclioptions/context.go#L381
3. checkComponentExistsOrFail - https://github.com/openshift/odo/blob/main/pkg/odo/genericclioptions/util.go#L61

Other not so straightforward places that need fixing - 
1. DevfilePush - https://github.com/openshift/odo/blob/main/pkg/odo/cli/component/devfile.go#L51
2. DisplayLog - https://github.com/openshift/odo/blob/main/pkg/util/util.go#L1281
3. HandleError - https://github.com/openshift/odo/blob/main/pkg/odo/cli/ui/common.go#L12; I am not sure whether we want to fix this or keep it as is.

**Comment by valaparthvi** [comment]
> Other not so straightforward places that need fixing -
1. DevfilePush - https://github.com/openshift/odo/blob/main/pkg/odo/cli/component/devfile.go#L51
2. DisplayLog - https://github.com/openshift/odo/blob/main/pkg/util/util.go#L1281
3. HandleError - https://github.com/openshift/odo/blob/main/pkg/odo/cli/ui/common.go#L12; I am not sure whether we want to fix this or keep it as is.

Hey @anandrkskd, @feloy suggested that we can make the following points an issue for Hacktoberfest and I think it's a good suggestion, these issues wouldn't be completely straightforward but still good enough. If you are okay with it, I will go ahead and create the issues.

**Comment by anandrkskd** [comment]
Yeah sure @valaparthvi, make sense

**Comment by anandrkskd** [comment]
Test failed due to timeout error. Retesting
/test psi-kubernetes-integration-e2e

**Comment by anandrkskd** [comment]
@valaparthvi can you review this PR, I have made all the changes.
Thanks.

**Review by valaparthvi — CHANGES_REQUESTED** [review]
There are still traces of LogAndError in https://github.com/anandrkskd/odo/blob/dev/telemetery-os-Exit-call/pkg/odo/genericclioptions/context.go, can you remove them as well?

File: pkg/odo/cli/registry/util/util_test.go [hunk 4]
```diff
@@ -62,7 +62,7 @@ func TestIsSecure(t *testing.T) {
 				t.Errorf("Unable to add registry to preference file with error: %v", err)
 			}
 
-			got := IsSecure(tt.registryName)
+			got, _ := IsSecure(tt.registryName)
```
[the remark this answers is not in the document]
Comment (anandrkskd) [reply pkg/odo/cli/registry/util/util_test.go:65]: Do we want to handle error in tests?

[the remark this answers is not in the document]
Comment (valaparthvi) [reply pkg/odo/cli/registry/util/util_test.go:65]: Yes, we have done it earlier, we can do it for this as well.

**Comment by anandrkskd** [comment]
@valaparthvi can you `/lgtm` this PR, I have updated all the change requested.

File: pkg/odo/genericclioptions/context.go [hunk 5]
```diff
@@ -352,34 +367,33 @@ func NewOfflineDevfileContext(command *cobra.Command) *Context {
...
-			log.Errorf("No component is set")
-			os.Exit(1)
+			return "", fmt.Errorf("No component is set")
 		}
 	case 1:
 		cmp := optionalComponent[0]
 		o.cmp = cmp
 	default:
 		// safeguard: fail if more than one optional string is passed because it would be a programming error
 		log.Errorf("ComponentAllowingEmpty function only accepts one optional argument, was given: %v", optionalComponent)
```
Comment (valaparthvi) [inline pkg/odo/genericclioptions/context.go:394]: Remove this.

File: pkg/odo/genericclioptions/util.go [hunk 6]
```diff
@@ -34,32 +31,40 @@ func getFirstChildOfCommand(command *cobra.Command) *cobra.Command {
...
 // errFormatForCommand must contain one %s
-func checkProjectCreateOrDeleteOnlyOnInvalidNamespace(command *cobra.Command, errFormatForCommand string) {
+func checkProjectCreateOrDeleteOnlyOnInvalidNamespace(command *cobra.Command, errFormatForCommand string) error {
 	// do not error out when its odo delete -a, so that we let users delete the local config on missing namespace
 	if command.HasParent() && command.Parent().Name() != "project" && (command.Name() == "create" || (command.Name() == "delete" && !command.Flags().Changed("all"))) {
 		err := fmt.Errorf(errFormatForCommand, command.Root().Name())
-		util.LogErrorAndExit(err, "")
+		if err != nil {
+			return err
+		}
```
Comment (valaparthvi) [inline pkg/odo/genericclioptions/util.go:40]: I think here you can simply do `return fmt.Errorf(errFormatForCommand, command.Root().Name())`.

File: pkg/odo/genericclioptions/util.go [hunk 7]
```diff
@@ -34,32 +31,40 @@ func getFirstChildOfCommand(command *cobra.Command) *cobra.Command {
...
 // compare to checkProjectCreateOrDeleteOnlyOnInvalidNamespace, no %s is needed
-func checkProjectCreateOrDeleteOnlyOnInvalidNamespaceNoFmt(command *cobra.Command, errFormatForCommand string) {
+func checkProjectCreateOrDeleteOnlyOnInvalidNamespaceNoFmt(command *cobra.Command, errFormatForCommand string) error {
 	// do not error out when its odo delete -a, so that we let users delete the local config on missing namespace
 	if command.HasParent() && command.Parent().Name() != "project" && (command.Name() == "create" || command.Name() == "push" || (command.Name() == "delete" && !command.Flags().Changed("all"))) {
 		err := fmt.Errorf(errFormatForCommand)
-		util.LogErrorAndExit(err, "")
+		if err != nil {
+			return err
+		}
```
Comment (valaparthvi) [inline pkg/odo/genericclioptions/util.go:53]: Same as above, perhaps you can simply do `return fmt.Errorf(errFormatForCommand)`.

**Review by valaparthvi — CHANGES_REQUESTED** [review]

File: pkg/odo/genericclioptions/util.go (hunk 6 above)
Comment (anandrkskd) [reply pkg/odo/genericclioptions/util.go:40]: But it's the same, right? err is defined in the above line in the same way we can just return err.

File: pkg/odo/genericclioptions/context.go (hunk 5 above)
Comment (anandrkskd) [reply pkg/odo/genericclioptions/context.go:394]: understood

File: pkg/odo/genericclioptions/util.go (hunk 7 above)
Comment (anandrkskd) [reply pkg/odo/genericclioptions/util.go:53]: Same as above [comment](https://github.com/openshift/odo/pull/5087#discussion_r721883486)

File: pkg/odo/genericclioptions/util.go (hunk 6 above)
Comment (valaparthvi) [reply pkg/odo/genericclioptions/util.go:40]: It is the same, but unnecessary.

Comment (anandrkskd) [reply pkg/odo/genericclioptions/util.go]: Understood! I have pushed the required change.

File: pkg/odo/genericclioptions/util.go [hunk 8]
```diff
@@ -34,32 +31,40 @@ func getFirstChildOfCommand(command *cobra.Command) *cobra.Command {
...
 	// do not error out when its odo delete -a, so that we let users delete the local config on missing namespace
 	if command.HasParent() && command.Parent().Name() != "project" && (command.Name() == "create" || (command.Name() == "delete" && !command.Flags().Changed("all"))) {
 		err := fmt.Errorf(errFormatForCommand, command.Root().Name())
-		util.LogErrorAndExit(err, "")
+		if err != nil {
+			return fmt.Errorf(errFormatForCommand, command.Root().Name())
+		}
 	}
+	return nil
 }
```
Comment (valaparthvi) [inline pkg/odo/genericclioptions/util.go:43]:
```suggestion
func checkProjectCreateOrDeleteOnlyOnInvalidNamespace(command *cobra.Command, errFormatForCommand string) error {
	// do not error out when its odo delete -a, so that we let users delete the local config on missing namespace
	if command.HasParent() && command.Parent().Name() != "project" && (command.Name() == "create" || (command.Name() == "delete" && !command.Flags().Changed("all"))) {
		return fmt.Errorf(errFormatForCommand, command.Root().Name())
	}
	return nil
}
```

File: pkg/odo/genericclioptions/util.go [hunk 9]
```diff
@@ -34,32 +31,40 @@ func getFirstChildOfCommand(command *cobra.Command) *cobra.Command {
...
 	// do not error out when its odo delete -a, so that we let users delete the local config on missing namespace
 	if command.HasParent() && command.Parent().Name() != "project" && (command.Name() == "create" || command.Name() == "push" || (command.Name() == "delete" && !command.Flags().Changed("all"))) {
 		err := fmt.Errorf(errFormatForCommand)
-		util.LogErrorAndExit(err, "")
+		if err != nil {
+			return fmt.Errorf(errFormatForCommand)
+		}
 	}
+	return nil
 }
```
Comment (valaparthvi) [inline pkg/odo/genericclioptions/util.go:56]:
```suggestion
func checkProjectCreateOrDeleteOnlyOnInvalidNamespaceNoFmt(command *cobra.Command, errFormatForCommand string) error {
	// do not error out when its odo delete -a, so that we let users delete the local config on missing namespace
	if command.HasParent() && command.Parent().Name() != "project" && (command.Name() == "create" || command.Name() == "push" || (command.Name() == "delete" && !command.Flags().Changed("all"))) {
		return fmt.Errorf(errFormatForCommand)
	}
	return nil
}
```

**Review by valaparthvi — CHANGES_REQUESTED** [review]

**Review by valaparthvi — APPROVED** [review]
