### PR TITLE
Make sure that desired operators are installed in CI

### LINKED ISSUE #2924: [FLAKE] List operators installed in the namespace
/kind bug

## What versions of software are you using?

**Operating System:**
supported
**Output of `odo version`:**
master
## How did you run odo exactly?
https://github.com/openshift/odo/blob/master/tests/integration/operatorhub/cmd_service_test.go#L26

### LINKED ISSUE #2943: Test flake comming due no check is added for operator (etcd) responsiveness
/kind bug

## What versions of software are you using?

**Operating System:**
supported
**Output of `odo version`:**
master
## How did you run odo exactly?
```
make configure-installer-tests-cluster
make test-operator-hub
```

## Actual behavior
```
Running odo with args [odo project set ci-operator-hub-project]
[odo] Switched to project : ci-operator-hub-project
Running odo with args [odo catalog list services]
[odo] Operators available in the cluster
[odo] NAME                          CRDs
[odo] mongodb-enterprise.v1.4.5     MongoDB, MongoDBUser, MongoDBOpsManager



Running odo with args [odo service create  --crd EtcdCluster]
[odo]  ✗  Could not find specified operator 
```
etcd operator does not come up properly or failed to install after apply it through ```oc create...``` command. For example
```
oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: etcd
  namespace: ${OPERATOR_HUB_PROJECT}
spec:
  channel: singlenamespace-alpha
  installPlanApproval: Automatic
  name: etcd
  source: community-operators
  sourceNamespace: openshift-marketplace
EOF
``` 
That is why etcd operator is not listed in the catalog list. 

## Expected behavior
So from our end we can write some check to confirm even after applying it through oc create etcd is now responsive and ready for use.

### PR DESCRIPTION
**Pull request by dharmit**
**What type of PR is this?**
/kind flake

**What does does this PR do / why we need it**:
The flake we're seeing is not entirely reproducible so I've added a while loop
which will make sure that the operators we're interested in are installed. The
yaml definition works fine so there's no issue on that front.

**Which issue(s) this PR fixes**:

Fixes #2924
Fixes #2943 

**How to test changes / Special notes to the reviewer**:
```sh
$ make configure-installer-tests-cluster
$ make test-operator-hub
```

### CODE REVIEW

File: scripts/setup-operators.sh [hunk 1]
```diff
@@ -2,21 +2,53 @@
...
+    channel: singlenamespace-alpha
+    installPlanApproval: Automatic
+    name: etcd
+    source: community-operators
+    sourceNamespace: openshift-marketplace
 EOF
+}
+
+# install mongo operator
+while :
```
Comment (amitkrout) [inline scripts/setup-operators.sh:42]: We should limit this, for example try max of 3 times otherwise there is a high chance of infinite loop or consume a lots of time until it finds the proper grep line.

File: scripts/setup-operators-41.sh [hunk 2]
```diff
@@ -2,6 +2,47 @@
 set -x
 
 CI_OPERATOR_HUB_PROJECT=ci-operator-hub-project
+
+install_mongo_operator() {
```
Comment (amitkrout) [inline scripts/setup-operators-41.sh:6]: Good to have those, but tish will be dead code atm as 4.1 cluster has been disabled. You can remove any new changes making for 4.1 cluster.

**Comment by amitkrout** [comment]
@dharmit Thanks for a quick pr

/lgtm

**Comment by dharmit** [comment]
Travis failure seems to be related to [k8s tests](https://travis-ci.com/github/openshift/odo/jobs/321580647#L571-L586). Triggering again.

```
Failure in Spec Setup (BeforeEach) [1.101 seconds]
odo devfile catalog command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_catalog_test.go:13
  When executing catalog list components with -a flag [BeforeEach]
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_catalog_test.go:51
    should list all supported and unsupported devfile components
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_catalog_test.go:52
    No future change is possible.  Bailing out early after 0.299s.
    Running kubectl with args [kubectl config set-context /tmp/500087485 --namespace ktfasjlell]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
    /home/travis/gopath/src/github.com/openshift/odo/tests/helper/helper_run.go:34

```
Do you want me to open an issue for this @amitkrout ?

**Comment by amitkrout** [comment]
> Travis failure seems to be related to [k8s tests](https://travis-ci.com/github/openshift/odo/jobs/321580647#L571-L586). Triggering again.
> 
> ```
> Failure in Spec Setup (BeforeEach) [1.101 seconds]
> odo devfile catalog command tests
> /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_catalog_test.go:13
>   When executing catalog list components with -a flag [BeforeEach]
>   /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_catalog_test.go:51
>     should list all supported and unsupported devfile components
>     /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_catalog_test.go:52
>     No future change is possible.  Bailing out early after 0.299s.
>     Running kubectl with args [kubectl config set-context /tmp/500087485 --namespace ktfasjlell]
>     Expected
>         <int>: 1
>     to match exit code:
>         <int>: 0
>     /home/travis/gopath/src/github.com/openshift/odo/tests/helper/helper_run.go:34
> ```
> 
> Do you want me to open an issue for this @amitkrout ?

@dharmit  Actually the above log only gives the ginkgo failure format and the actual failure log unfortunately you missed. No issue, if its a flake the we are 100% going to hit it. Lets wait for next time same scenario failure.

**Comment by dharmit** [comment]
Maybe GitHub connectivity issue?
```
 • Failure [39.970 seconds]
odo devfile push command tests
/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:16
  When devfile push command is executed
  /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:93
    should delete the files from the container if its removed locally [It]
    /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:150
    No future change is possible.  Bailing out early after 32.618s.
      
    Running git with args [git clone https://github.com/che-samples/web-nodejs-sample.git /tmp/230477414/projectDir]
    Expected
        <int>: 128
    to match exit code:
        <int>: 0
    /go/src/github.com/openshift/odo/tests/helper/helper_run.go:34 
```
/test v4.2-integration-e2e-benchmark

**Comment by dharmit** [comment]
Travis failures.

**generic login, component command integration tests**
Probably a flake. WDYT @amitkrout ?
```
[odo]  ✓  Changes successfully pushed to component
Running odo with args [odo delete --context /tmp/753695717 -f]
[odo]  ✗  invalid configuration: [context was not found for specified context: qhhnzpnvmg/127-0-0-1:8443/developer, cluster has no server defined]
```

**service, link, component sub-commands command integration tests**
This failure happened because even after 1 minute of doing `odo app delete`, the underlying service in that app was not deleted. I'm not sure if we can add timeout for a longer period.
```
Failure [106.843 seconds]
odo service command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:15
  When the application is deleted
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:439
    should delete the service(s) in the application as well [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/servicecatalog/cmd_service_test.go:444
    Timeout out after 1 minutes
```
**devfile catalog, watch command integration tests on kubernetes cluster**
Not sure what blew up here. @amitkrout maybe you could tell/look?
```
Created dir: /tmp/483916658
Creating a new project: bmlfjlszob
Running kubectl with args [kubectl create namespace bmlfjlszob]
[kubectl] namespace "bmlfjlszob" created
Running kubectl with args [kubectl config set-context /tmp/483916658 --namespace bmlfjlszob]
[kubectl] error: open /home/travis/.kube/config.lock: file exists
Deleting project: 
Running kubectl with args [kubectl delete namespaces ]
[kubectl] error: resource name may not be empty
• Failure in Spec Setup (BeforeEach) [1.766 seconds]
odo devfile watch command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:14
  when executing watch without a valid devfile [BeforeEach]
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:71
    should fail
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:72
    No future change is possible.  Bailing out early after 0.626s.
    Running kubectl with args [kubectl config set-context /tmp/483916658 --namespace bmlfjlszob]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
    /home/travis/gopath/src/github.com/openshift/odo/tests/helper/helper_run.go:34
------------------------------
SSS•••
Summarizing 1 Failure:
[Fail] odo devfile watch command tests [BeforeEach] when executing watch without a valid devfile should fail 
/home/travis/gopath/src/github.com/openshift/odo/tests/helper/helper_run.go:34
Ran 4 of 35 Specs in 3.813 seconds
FAIL! -- 3 Passed | 1 Failed | 0 Pending | 31 Skipped

```

**Comment by dharmit** [comment]
Once again travis failure.
**service, link, component sub-commands command integration tests**
Doesn't look related to our code to me. 
```
Collecting pip==19.3.1
[odo]   Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
[odo] Installing collected packages: pip
[odo]   Found existing installation: pip 9.0.1
[odo]     Uninstalling pip-9.0.1:
[odo]       Successfully uninstalled pip-9.0.1
[odo] Successfully installed pip-19.3.1
[odo] ---> Installing dependencies ...
[odo] Collecting gunicorn
[odo]   Downloading https://files.pythonhosted.org/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77kB)
[odo] Collecting numpy
[odo]   Downloading https://files.pythonhosted.org/packages/3d/fc/4763e5f17ac6e7e7d55f377cde859ca1c5d5ac624441ab45315bc578aa9e/numpy-1.18.3-cp36-cp36m-manylinux1_x86_64.whl (20.2MB)
[odo] ERROR: Exception:
[odo] Traceback (most recent call last):
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
[odo]     yield
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
[odo]     data = self._fp.read(amt) if not fp_closed else b""
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 459, in read
[odo]     n = self.readinto(b)
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 503, in readinto
[odo]     n = self.fp.readinto(b)
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/socket.py", line 586, in readinto
[odo]     return self._sock.recv_into(b)
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 1012, in recv_into
[odo]     return self.read(nbytes, buffer)
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 874, in read
[odo]     return self._sslobj.read(len, buffer)
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 631, in read
[odo]     v = self._sslobj.read(len, buffer)
[odo] ConnectionResetError: [Errno 104] Connection reset by peer
[odo] 
[odo] During handling of the above exception, another exception occurred:
[odo] 
[odo] Traceback (most recent call last):
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
[odo]     status = self.run(options, args)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 382, in run
[odo]     resolver.resolve(requirement_set)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
[odo]     self._resolve_one(requirement_set, req)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
[odo]     abstract_dist = self._get_abstract_dist_for(req_to_install)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
[odo]     req, self.session, self.finder, self.require_hashes
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
[odo]     progress_bar=self.progress_bar
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/download.py", line 465, in unpack_url
[odo]     progress_bar=progress_bar
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/download.py", line 316, in unpack_http_url
[odo]     progress_bar)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/download.py", line 551, in _download_http_url
[odo]     _download_url(resp, link, content_file, hashes, progress_bar)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/download.py", line 253, in _download_url
[odo]     hashes.check_against_chunks(downloaded_chunks)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 80, in check_against_chunks
[odo]     for chunk in chunks:
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/download.py", line 223, in written_chunks
[odo]     for chunk in chunks:
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/utils/ui.py", line 160, in iter
[odo]     for x in it:
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_internal/download.py", line 212, in resp_read
[odo]     decode_content=False):
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
[odo]     data = self.read(amt=amt, decode_content=decode_content)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
[odo]     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
[odo]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
[odo]     self.gen.throw(type, value, traceback)
[odo]   File "/opt/app-root/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
[odo]     raise ProtocolError("Connection broken: %r" % e, e)
[odo] pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
[odo] WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
[odo] You should consider upgrading via the 'pip install --upgrade pip' command.
[odo] 
[odo]  ✗  command terminated with exit code 2
Deleting dir: /tmp/624345455
Deleting dir: /tmp/489211394
Deleting project: liajoweoqm
Running odo with args [odo project delete liajoweoqm -f]
[odo] This project contains the following applications, which will be deleted
[odo] Application app
[odo] This application has following components that will be deleted
[odo] component named backend
[odo] component named frontend
[odo]  •  Deleting project liajoweoqm  ...
 ✓  Deleting project liajoweoqm [7s]
[odo]  ✓  Deleted project : liajoweoqm
Deleting dir: /tmp/034198608
• Failure [67.153 seconds]
odo link and unlink command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:14
  When link between components using wrong port
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:55
    should fail [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:64
    No future change is possible.  Bailing out early after 22.976s.
    Running odo with args [odo push --context /tmp/489211394]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
```

4.2 integration test failure link. Looks like connection time-out while fetching devfile from the registry. 
```
 [odo] Experimental mode is enabled, use at your own risk
[odo] 
[odo]  ✗  Get https://che-devfile-registry.openshift.io//devfiles/index.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Deleting project: ccwwfcdjgd
Running odo with args [odo project delete ccwwfcdjgd -f]
[odo]  •  Deleting project ccwwfcdjgd  ...
[odo] 
 ✓  Deleting project ccwwfcdjgd [6s]
[odo]  ✓  Deleted project : ccwwfcdjgd
Setting current dir to: /go/src/github.com/openshift/odo/tests/integration/devfile
Deleting dir: /tmp/487127622
• Failure [18.255 seconds]
odo devfile push command tests
/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:16
  When devfile push command is executed
  /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:93
    should create pvc and reuse if it shares the same devfile volume name [It]
    /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:279 
```
/test v4.2-integration-e2e-benchmark

**Comment by dharmit** [comment]
Travis failure continues.
**service, link, component sub-commands command integration tests**
```
Running odo with args [odo component list --app app --project vhbtrcozvq]
[odo]  ✗  invalid configuration: no configuration has been provided
Setting current dir to: /home/travis/gopath/src/github.com/openshift/odo/tests/integration
Deleting project: vhbtrcozvq
Running odo with args [odo project delete vhbtrcozvq -f]
[odo]  •  Deleting project vhbtrcozvq  ...
 ✓  Deleting project vhbtrcozvq [7s]
[odo]  ✓  Deleted project : vhbtrcozvq
Deleting dir: /tmp/244880333
• Failure [42.418 seconds]
odo sub component command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/cmd_cmp_sub_test.go:13
  when component is in the current directory and --project flag is used
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/component.go:512
    creates a local python component, pushes it and then deletes it using --all flag in local directory [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/component.go:560
    No future change is possible.  Bailing out early after 0.204s.
    Running odo with args [odo component list --app app --project vhbtrcozvq]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
```

**Comment by prietyc123** [comment]
> Travis failure seems to be related to [k8s tests](https://travis-ci.com/github/openshift/odo/jobs/321580647#L571-L586). Triggering again.
> 
> ```
> Failure in Spec Setup (BeforeEach) [1.101 seconds]
> odo devfile catalog command tests
> /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_catalog_test.go:13
>   When executing catalog list components with -a flag [BeforeEach]
>   /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_catalog_test.go:51
>     should list all supported and unsupported devfile components
>     /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_catalog_test.go:52
>     No future change is possible.  Bailing out early after 0.299s.
>     Running kubectl with args [kubectl config set-context /tmp/500087485 --namespace ktfasjlell]
>     Expected
>         <int>: 1
>     to match exit code:
>         <int>: 0
>     /home/travis/gopath/src/github.com/openshift/odo/tests/helper/helper_run.go:34
> ```
> 
> Do you want me to open an issue for this @amitkrout ?

@dharmit Its a flake. We should open an issue for this.

**Comment by dharmit** [comment]
Travis failing with the error that I saw yesterday as well. It's failing in "devfile catalog, watch command integration tests on kubernetes cluster" testst:
```
$ make goget-tools
go get -u github.com/Masterminds/glide
go get -u github.com/frapposelli/wwhrd
go get -u github.com/onsi/ginkgo/ginkgo
go get -u github.com/securego/gosec/cmd/gosec
# It is not recomended to go get golangci-lint https://github.com/golangci/golangci-lint#go
curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /home/travis/gopath/bin v1.23.6
golangci/golangci-lint info checking GitHub for tag 'v1.23.6'
golangci/golangci-lint info found version: 1.23.6 for v1.23.6/linux/amd64
make: *** [goget-tools] Error 7
The command "make goget-tools" failed and exited with 2 during .
```

**Comment by amitkrout** [comment]
> @dharmit Thanks for a quick pr
> 
> /lgtm

/lgtm
