### PR TITLE
Refactor: fix s2i flag for odo create

### LINKED ISSUE #4048: odo create: --s2i flag is broken
/kind bug

1. If a devfile component already exists in the working file directory, `odo create <cmpType> --s2i` does not error out.

    image

2. Another bug has been introduced at https://github.com/openshift/odo/blame/master/pkg/odo/cli/component/create.go#L349 .
The `if !co.forceS2i { }` block has logic inside like https://github.com/openshift/odo/blame/master/pkg/odo/cli/component/create.go#L377  & https://github.com/openshift/odo/blame/master/pkg/odo/cli/component/create.go#L351 .. which requires `co.forceS2i == true`. This code will never execute since the outer blog requires `co.forceS2i == false` .  Therefore, conflicting flags are not being checked properly either.

### PR DESCRIPTION
**Pull request by dev-gaur**
**What type of PR is this?**

/kind bug
/kind code-refactoring

**Which issue(s) this PR fixes**:
Fixes #4048 , #4018 

**How to test changes / Special notes to the reviewer**:

Please try out the `odo create` command using all the possible combinations and flags.

### CODE REVIEW

**Comment by dev-gaur** [comment]
image

@prietyc123 satisfied with the message, when devfile does not exist?

File: pkg/odo/cli/component/create.go [hunk 1]
```diff
@@ -345,42 +345,45 @@ func (co *CreateOptions) Complete(name string, cmd *cobra.Command, args []string
 	// this populates the LocalConfigInfo as well
 	co.Context = genericclioptions.NewContextCreatingAppIfNeeded(cmd)
 
-	// If not using --s2i
-	if !co.forceS2i {
+	err = co.checkConflictingFlags()
+	if err != nil {
+		return
```
Comment (cdrage) [inline pkg/odo/cli/component/create.go:350]: return... what? This should be returning `err`

File: pkg/odo/cli/component/create.go [hunk 2]
```diff
@@ -542,7 +539,7 @@ func (co *CreateOptions) Complete(name string, cmd *cobra.Command, args []string
 
 		if util.CheckPathExists(co.DevfilePath) || co.devfileMetadata.devfilePath.value != "" {
 			// Categorize the sections
-			log.Info("Validation")
+			log.Info("Validation for Devfile component")
```
Comment (cdrage) [inline pkg/odo/cli/component/create.go:542]: Don't change this IMO, it should just stay as `Validation`. No need to specify Devfile. We're trying to avoid using the word Devfile anyways in the UI, since it's actually what's being used "under the hood" / engine, rather than what the user will be directly interacting with.

File: pkg/odo/cli/component/create.go [hunk 3]
```diff
@@ -567,70 +564,77 @@ func (co *CreateOptions) Complete(name string, cmd *cobra.Command, args []string
...
-			// supported by devfile, if it is supported we return and will download the corresponding devfile later,
-			// if it is not supported we still need to run all the codes related with s2i after devfile compatibility check
+		// Since we need to support both devfile and s2i, so we have to check if the component type is
+		// supported by devfile, if it is supported we return and will download the corresponding devfile later,
+		// if it is not supported we still need to run all the codes related with s2i after devfile compatibility check
 
-			hasComponent := false
-			devfileExistSpinner := log.Spinner("Checking devfile existence")
+		hasComponent := false
+		var devfileExistSpinner *log.Status
```
Comment (cdrage) [inline pkg/odo/cli/component/create.go:579]: As someone who wrote the `log` library and functionality, I'd suggest we avoid declaring a spinner like this.. 

You may run into issues in the future where the spinner will encounter a nil pointer.

File: pkg/odo/cli/component/create.go [hunk 4]
```diff
@@ -849,7 +855,7 @@ func (co *CreateOptions) Validate() (err error) {
 		return nil
 	}
 
-	log.Info("Validation")
+	log.Info("Validation for S2I component")
```
Comment (cdrage) [inline pkg/odo/cli/component/create.go:858]: Just keep it as `Validation`, I don't think we should declare that it's S2I.. As that would confuse the user.

**Review by cdrage — CHANGES_REQUESTED** [review]
Few changes, otherwise LGTM

File: pkg/odo/cli/component/create.go (hunk 2 above)
Comment (dev-gaur) [reply pkg/odo/cli/component/create.go:543]: Hi @cdrage , If we keep it just as `Validation` then the logs come out as following if an S2I component is created by default.

image

IMO, some verbosity could actually help in this case. Also, this verbosity will actually fix #4018 

@girishramnani @kadel @adisky @mik-dass you thoughts are welcome as well

Comment (dev-gaur) [reply pkg/odo/cli/component/create.go:543]: Currently it looks like this.

image

Comment (dev-gaur) [reply pkg/odo/cli/component/create.go:543]: Maybe we can revert back to just `Validation` after we get rid of S2I totally ?

File: pkg/odo/cli/component/create.go (hunk 1 above)
Comment (dev-gaur) [reply pkg/odo/cli/component/create.go:351]: Its defined here. https://github.com/openshift/odo/blob/ce72fb36681631b908ad7ca4731b2c4623db9823/pkg/odo/cli/component/create.go#L345 

That's a golang feature you can define the variable in the return block of function definition

File: pkg/odo/cli/component/create.go (hunk 2 above)
Comment (adisky) [reply pkg/odo/cli/component/create.go:543]: I think using only `Validation` is ok, explicitly specifying `Validation for devfile component`/ `Validation for S2I component` does not seem very user friendly. To solve the problem in better way  we should use a common spinner ` Validating the component` if one of the s2i or devfile component found just continue with it.
```
$ odo create java
Validation 
 ✓  Validating the component 
```

if no s2i or devfile component found
```
$ odo create java
Validation 
 ✗ No devfile or s2i component found, please run `odo catalog list components` for a list of supported components.
```

Comment (cdrage) [reply pkg/odo/cli/component/create.go:543]: I agree with @adisky we should keep it as `Validation`. We should not be outputting both s2i and devfile in the output either... 

Having both would indeed confused the user
