### PR TITLE
Fixes list output in odo directory when component is not pushed

### LINKED ISSUE #2028: `odo component list -o json` returns empty list for `not pushed` components
[kind/bug]

`odo component list` should display even components that are not pushed.

The same problem is with `odo component describe` It should show information even for components that are not pushed to the cluster.

## How did you run odo exactly?
`odo component list -o json | jq .`

## Actual behavior
```
▶ odo component list -o json | jq .
{
  "kind": "List",
  "apiVersion": "odo.openshift.io/v1alpha1",
  "metadata": {},
  "items": []
}
```
```
▶ odo component list
 ✗  There are no components deployed.
```

## Expected behavior
```
▶ odo component list -o json | jq .
{
  "kind": "List",
  "apiVersion": "odo.openshift.io/v1alpha1",
  "metadata": {},
  "items": [
    {
      "kind": "Component",
      "apiVersion": "odo.openshift.io/v1alpha1",
      "metadata": {
        "name": "java-spring-boot-addx",
        "namespace": "asdf",
        "creationTimestamp": null
      },
      "spec": {
        "app": "app",
        "type": "java",
        "source": "file://./",
        "url": [
          "java-spring-boot-addx-8080"
        ]
      },
      "status": {
        "state": "Not pushed"
      }
    }
  ]
}
```

```
▶ odo component list
APP     NAME                      TYPE     SOURCE        STATE
app     java-spring-boot-addx     java     file://./     Not pushed
```

### PR DESCRIPTION
**Pull request by mik-dass**
fixes #2028 

How to test:
1. Do `odo create <type>` and don't push on the cluster
2. Do `odo list`

The output should list the not pushed component

### CODE REVIEW

**Comment by mik-dass** [comment]
```
✗  Failed To Update Config To Component Deployed
[odo]  ✗  Applying configuration [1m]
```
/retest

File: pkg/component/component.go [hunk 1]
```diff
@@ -886,6 +886,36 @@ func List(client *occlient.Client, applicationName string) (ComponentList, error
 
 	}
 
+	if len(components) == 0 {
+		localConfig, err := config.New()
```
Comment (girishramnani) [inline pkg/component/component.go]: can we extract this out into a separate function? seems like its not dependent on other variables?

**Comment by mik-dass** [comment]
```
[odo]  ✗  Unable to connect to OpenShift cluster, is it down?
```
/retest

File: pkg/component/component.go (hunk 1 above)
Comment (mik-dass) [reply pkg/component/component.go]: done

File: tests/integration/servicecatalog/service_test.go [hunk 2]
```diff
@@ -84,11 +84,11 @@ var _ = Describe("odoServiceE2e", func() {
 			// Ping said URL
 			helper.HttpWaitFor(routeURL, "Spring Boot", 90, 1)
 
-			// Delete the component
```
Comment (amitkrout) [inline tests/integration/servicecatalog/service_test.go]: @mik-dass What is the need of removing ```helper.CmdShouldPass("odo", "delete", "sb-app", "-f")```

File: tests/integration/component.go [hunk 3]
```diff
@@ -111,6 +111,14 @@ func componentTests(args ...string) {
 			Expect(cmpAllList).To(ContainSubstring("cmp-git"))
 			helper.CmdShouldPass("odo", append(args, "delete", "cmp-git", "-f")...)
 		})
+
+		It("should list the component when it is not pushed", func() {
```
Comment (amitkrout) [inline tests/integration/component.go]: +1
It will work for comp and sub comp test.

File: tests/integration/servicecatalog/service_test.go (hunk 2 above)
Comment (mik-dass) [reply tests/integration/servicecatalog/service_test.go]: Because in 
```
JustAfterEach(func() {
			helper.DeleteProject(project)
```
we are deleting the project which internally calls list to display the info of the components. According to this PR, `component list` will show a component without the need for pushing. Thus the project delete call will error out. Thus I moved it after the service delete call as even the service call needs the config to figure out the project.

**Comment by mik-dass** [comment]
```
[odo]  ✗  unable to find tag latest for image wildfly
```
/retest

File: tests/integration/servicecatalog/service_test.go (hunk 2 above)
Comment (kadel) [reply tests/integration/servicecatalog/service_test.go]: I'm confused.  Are you saying that `odo project delete` will fail if there are no components in the project? That is not right.

**Comment by kadel** [comment]
Two components pushed to the same application in the same project
```
▶ odo list
APP     NAME                        TYPE       SOURCE        STATE
app     java-spring-boot-yelj       java       file://./     Pushed
app     nodejs-nodejs-rest-rhpo     nodejs     file://./     Pushed
```
Looks ok


Now when I delete one of them. (Current dir is nodejs component)
```
▶ odo delete
This component has following urls that will be deleted with component
URL named nodejs-nodejs-rest-rhpo-8080 with host nodejs-nodejs-rest-rhpo-8080-app-tkmyproject.apps.tkral.devcluster.openshift.com having protocol http at port 8080
? Are you sure you want to delete nodejs-nodejs-rest-rhpo from app? Yes
 ✓  Deleting component nodejs-nodejs-rest-rhpo [1s]
 ✓  Component nodejs-nodejs-rest-rhpo from application app has been deleted

▶ odo list
APP     NAME                      TYPE     SOURCE        STATE
app     java-spring-boot-yelj     java     file://./     Pushed
```

I see just the the java one, not the nodejs one even when I'm executing `odo list` from the nodejs direcory

The output should look like this
```
▶ odo list
APP     NAME                        TYPE       SOURCE        STATE
app     java-spring-boot-yelj       java       file://./     Pushed
app     nodejs-nodejs-rest-rhpo     nodejs     file://./     Not Pushed
```

Now when I delete the java component:
```
▶ odo delete java-spring-boot-yelj
This component has following urls that will be deleted with component
URL named java-spring-boot-yelj-8080 with host java-spring-boot-yelj-8080-app-tkmyproject.apps.tkral.devcluster.openshift.com having protocol http at port 8080
? Are you sure you want to delete java-spring-boot-yelj from app? Yes
 ✓  Deleting component java-spring-boot-yelj [1s]
 ✓  Component java-spring-boot-yelj from application app has been deleted
```

And I executed the `odo list` inside the nodejs component. I correctly see the nodejs in Not Pushed state. 
```
▶ odo list
APP     NAME                        TYPE       SOURCE     STATE
app     nodejs-nodejs-rest-rhpo     nodejs     ./         Not Pushed
```

**Comment by mik-dass** [comment]
@kadel Fixed. I have also added a integration test for the same.

File: tests/integration/servicecatalog/service_test.go (hunk 2 above)
Comment (mik-dass) [reply tests/integration/servicecatalog/service_test.go]: TBH I don't remember why I wrote the project delete thing, I was facing some error there though :D But the main reason is that service delete will list the components and since the list call will pick up the component from the config (It was getting deleted before the service delete) and try to find the deployment config accordingly and thus will fail.

**Comment by mik-dass** [comment]
```
2019/09/03 11:36:22 Container lease in pod benchmark completed successfully
2019/09/03 11:40:44 Container teardown in pod benchmark completed successfully
2019/09/03 11:40:44 Pod benchmark succeeded after 43m16s
2019/09/03 11:40:44 error: unable to signal to artifacts container to terminate in pod benchmark, triggering deletion: could not run remote command: container artifacts is not valid for pod benchmark
2019/09/03 11:40:44 error: unable to retrieve artifacts from pod benchmark: could not read gzipped artifacts: container artifacts is not valid for pod benchmark
2019/09/03 11:40:49 error: could not wait for pod 'benchmark': it is no longer present on the cluster (usually a result of a race or resource pressure. re-running the job should help)
2019/09/03 11:40:50 Ran for 47m21s
2019/09/03 11:40:50 Submitted failure event to sentry (id=eec045da685e4ed8a6aca4cf2f852812)
error: could not run steps: step benchmark failed: template pod "benchmark" failed: pod was deleted while ci-operator step was waiting for it
```
/retest

**Comment by mik-dass** [comment]
```
[odo]  ✗  Unable to connect to OpenShift cluster, is it down?
```
/retest

**Comment by mik-dass** [comment]
```
failed to acquire a resource: Post http://boskos.ci/acquire?dest=leased&owner=ci-op-ktlgdphk-1b2f4&request_id=5097988951133267392&state=free&type=aws-quota-slice: dial tcp: lookup boskos.ci on 10.142.15.242:53: no such host
```
/retest

**Comment by mik-dass** [comment]
```
[INFO] Releasing the lease on resouce e7615191-d54f-4e47-aa8f-7d9d83726a83...
failed to release resource "e7615191-d54f-4e47-aa8f-7d9d83726a83": status 401 Unauthorized, statusCode 401 releasing e7615191-d54f-4e47-aa8f-7d9d83726a83
```
/retest

File: pkg/component/component.go [hunk 4]
```diff
@@ -862,36 +862,95 @@ func GetComponentType(client *occlient.Client, componentName string, application
 }
 
 // List lists components in active application
-func List(client *occlient.Client, applicationName string) (ComponentList, error) {
+func List(client *occlient.Client, applicationName string, localConfigInfo ...config.LocalConfigInfo) (ComponentList, error) {
```
Comment (kadel) [inline pkg/component/component.go]: I guess the only reason why you have multiple `config.LocalConfigInfo` is to make it optional.

This is not a good approach. I think that it would be much better, to make `localConfigInfo` a pointer to the `config.LocalConfigInfo` and pass `nil` when it needs to be called without localConafigInfo.

**Comment by mik-dass** [comment]
```
Lease acquired, installing...
level=warning msg="Found override for ReleaseImage. Please be warned, this is not advised"
level=info msg="Consuming \"Install Config\" from target directory"
level=info msg="Creating infrastructure resources..."
level=error
level=error msg="Error: Error waiting for AMI (ami-00a5d52b114e5bd14) to be ready: timeout while waiting for state to become 'available' (last state: 'pending', timeout: 40m0s)"
level=error
level=error msg="  on ../tmp/openshift-install-332917876/main.tf line 91, in resource \"aws_ami_copy\" \"main\":"
level=error msg="  91: resource \"aws_ami_copy\" \"main\" {"
level=error
level=error
level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
---
Container test exited with code 1, reason Error
---
Another process exited
```
/retest

**Comment by mik-dass** [comment]
```
 I0916 06:54:32.486442   15762 cmdutils.go:48] Error:
[odo] invalid configuration: [context was not found for specified context: jucidpiemh/api-ci-op-mmwik55r-5db35-origin-ci-int-aws-dev-rhcloud-com:6443/developer, cluster has no server defined]
[odo] Please login to your server: 
[odo] 
[odo] odo login https://mycluster.mydomain.com
[odo]  ✗  invalid configuration: [context was not found for specified context: jucidpiemh/api-ci-op-mmwik55r-5db35-origin-ci-int-aws-dev-rhcloud-com:6443/developer, cluster has no server defined]
[odo] Please login to your server: 
[odo] 
[odo] odo login https://mycluster.mydomain.com
```
/retest
