### PR TITLE
Deploy fix

### LINKED ISSUE #1633: prevent unnecessary deployment triggers
Even if config has not been changed new deployment is triggered because odo changes the order of env variables in DC definition.

Screenshot 2019-04-18 at 17 39 06

### PR DESCRIPTION
**Pull request by mik-dass**
fixes #1633 

This PR prevents the unnecessary roll out of new deployment config.

### CODE REVIEW

File: pkg/occlient/occlient.go [hunk 1]
```diff
@@ -984,9 +985,19 @@ func uniqueAppendOrOverwriteEnvVars(existingEnvs []corev1.EnvVar, envVars ...cor
...
 
-	// Convert map to slice
-	for _, envVar := range mapExistingEnvs {
-		retVal = append(retVal, envVar)
+	// append the values to the final slice
+	// don't loop because we need them in order
+	for _, envVar := range existingEnvs {
+		if val, ok := mapExistingEnvs[envVar.Name]; ok {
+			retVal = append(retVal, val)
+			delete(mapExistingEnvs, envVar.Name)
```
Comment (girishramnani) [inline pkg/occlient/occlient.go]: would it be a better idea to just sort them instead of doing this?

File: pkg/occlient/templates.go [hunk 2]
```diff
@@ -139,6 +139,51 @@ func generateSupervisordDeploymentConfig(commonObjectMeta metav1.ObjectMeta, com
 	return dc
 }
 
+func updateSupervisorDeploymentConfig(existingDc *appsv1.DeploymentConfig, commonObjectMeta metav1.ObjectMeta, commonImageMeta CommonImageMeta,
+	envVar []corev1.EnvVar, envFrom []corev1.EnvFromSource, resourceRequirements *corev1.ResourceRequirements) appsv1.DeploymentConfig {
```
Comment (girishramnani) [inline pkg/occlient/templates.go]: too many function args

File: pkg/occlient/templates.go [hunk 3]
```diff
@@ -275,6 +320,44 @@ func generateGitDeploymentConfig(commonObjectMeta metav1.ObjectMeta, image strin
 	return dc
 }
 
+func updateGitDeploymentConfig(existingDc *appsv1.DeploymentConfig, commonObjectMeta metav1.ObjectMeta, image string, containerPorts []corev1.ContainerPort, envVars []corev1.EnvVar, resourceRequirements *corev1.ResourceRequirements) appsv1.DeploymentConfig {
```
Comment (girishramnani) [inline pkg/occlient/templates.go]: too many function args

File: pkg/occlient/occlient.go (hunk 1 above)
Comment (kadel) [reply pkg/occlient/occlient.go]: The order of the env variables is important if you start sorting, you will change the order.
This function is called `appendOrOvewrite` it shouldn't do any side effects like sorting

**Comment by kadel** [comment]
/test e2e-scenarios

```
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

File: pkg/occlient/occlient.go [hunk 4]
```diff
@@ -1290,22 +1303,26 @@ func (c *Client) PatchCurrentDC(name string, dc appsv1.DeploymentConfig, prePatc
...
 	// Update the current one that's deployed with the new Spec.
 	// despite the "patch" function name, we use update since `.Patch` requires
 	// use to define each and every object we must change. Updating makes it easier.
-	_, err := c.appsClient.DeploymentConfigs(c.Namespace).Update(currentDC)
+	updatedDc, err := c.appsClient.DeploymentConfigs(c.Namespace).Update(&modifiedDC)
 	if err != nil {
 		return errors.Wrapf(err, "unable to update DeploymentConfig %s", name)
 	}
 
+	if reflect.DeepEqual(updatedDc.Spec.Template, currentDC.Spec.Template) {
```
Comment (kadel) [inline pkg/occlient/occlient.go]: It might be worth to add a comment explaining what lead to this and why are we doing this. I'm sure that we will forget it after some time ;-)

File: pkg/occlient/occlient.go [hunk 5]
```diff
@@ -1387,7 +1404,12 @@ func (c *Client) UpdateDCToGit(ucp UpdateComponentParams, isDeleteSupervisordVol
 		return errors.New("UpdateDCToGit imageName cannot be blank")
 	}
 
-	dc := generateGitDeploymentConfig(ucp.CommonObjectMeta, ucp.ImageMeta.Name, ucp.ImageMeta.Ports, ucp.EnvVars, &ucp.ResourceLimits)
+	var dc appsv1.DeploymentConfig
+	if isDeleteSupervisordVolumes {
```
Comment (kadel) [inline pkg/occlient/occlient.go]: the same `if` condition is below, why not combine it?

File: pkg/occlient/occlient.go [hunk 6]
```diff
@@ -1502,20 +1524,30 @@ func (c *Client) UpdateDCToSupervisor(ucp UpdateComponentParams, isToLocal bool,
...
-	// Generate the SupervisorD Config
-	dc := generateSupervisordDeploymentConfig(
-		ucp.CommonObjectMeta,
-		ucp.ImageMeta,
-		inputEnvs,
-		cmpContainer.EnvFrom,
-		&ucp.ResourceLimits,
-	)
+	var dc appsv1.DeploymentConfig
+	if isCreatePVC {
```
Comment (kadel) [inline pkg/occlient/occlient.go]: again, the same if the statement is below

File: pkg/occlient/utils.go [hunk 7]
```diff
@@ -84,3 +84,20 @@ func IsDCRolledOut(config *appsv1.DeploymentConfig, desiredRevision int64) bool
 	}
 	return false
 }
+
+func hasUpdatedImages(oldDC *appsv1.DeploymentConfig, newDC *appsv1.DeploymentConfig) bool {
```
Comment (kadel) [inline pkg/occlient/utils.go]: it looks like this function is never used

File: pkg/occlient/templates.go [hunk 8]
```diff
@@ -139,6 +139,51 @@ func generateSupervisordDeploymentConfig(commonObjectMeta metav1.ObjectMeta, com
 	return dc
 }
 
+func updateSupervisorDeploymentConfig(existingDc *appsv1.DeploymentConfig, commonObjectMeta metav1.ObjectMeta, commonImageMeta CommonImageMeta,
+	envVar []corev1.EnvVar, envFrom []corev1.EnvFromSource, resourceRequirements *corev1.ResourceRequirements) appsv1.DeploymentConfig {
+
+	dc := *existingDc
+
+	dc.ObjectMeta = commonObjectMeta
+	dc.Spec.Strategy.Type = appsv1.DeploymentStrategyTypeRecreate
```
Comment (kadel) [inline pkg/occlient/templates.go]: this should be already set, we should overwrite it again

File: pkg/occlient/templates.go [hunk 9]
```diff
@@ -139,6 +139,51 @@ func generateSupervisordDeploymentConfig(commonObjectMeta metav1.ObjectMeta, com
...
+		"deploymentconfig": commonObjectMeta.Name,
+	}
+
+	dc.Spec.Template.ObjectMeta = metav1.ObjectMeta{
+		Labels: map[string]string{
+			"deploymentconfig": commonObjectMeta.Name,
+		},
+		// https://github.com/openshift/odo/pull/622#issuecomment-413410736
+		Annotations: map[string]string{
+			"alpha.image.policy.openshift.io/resolve-names": "*",
```
Comment (kadel) [inline pkg/occlient/templates.go]: this looks like a duplication of what is already in `occlient.generateSupervisordDeploymentConfig` (templates.go)

File: pkg/occlient/templates.go [hunk 10]
```diff
@@ -139,6 +139,51 @@ func generateSupervisordDeploymentConfig(commonObjectMeta metav1.ObjectMeta, com
...
+		},
+	}
+
+	for i := range dc.Spec.Template.Spec.Containers {
```
Comment (kadel) [inline pkg/occlient/templates.go]: all the containers would be the same?

File: pkg/occlient/templates.go [hunk 11]
```diff
@@ -139,6 +139,51 @@ func generateSupervisordDeploymentConfig(commonObjectMeta metav1.ObjectMeta, com
...
+
+	dc.ObjectMeta = commonObjectMeta
+	dc.Spec.Strategy.Type = appsv1.DeploymentStrategyTypeRecreate
+
+	dc.Spec.Selector = map[string]string{
+		"deploymentconfig": commonObjectMeta.Name,
+	}
+
+	dc.Spec.Template.ObjectMeta = metav1.ObjectMeta{
+		Labels: map[string]string{
```
Comment (kadel) [inline pkg/occlient/templates.go]: what about already existing labels?

File: pkg/occlient/templates.go (hunk 10 above)
Comment (mik-dass) [reply pkg/occlient/templates.go]: We have only one container support so I guess we can keep them same for now

**Comment by mik-dass** [comment]
@girishramnani @kadel Fixed. Please have a look again

**Comment by mik-dass** [comment]
> https://travis-ci.org/openshift/odo/jobs/529622044

Let me find a fix for this, marking this as WIP again

**Comment by mik-dass** [comment]
The unit test failed looking into it

**Comment by kadel** [comment]
@mik-dass 

```
gofmt ERROR - These files are not formated by gofmt:
./pkg/occlient/occlient_test.go
```

**Comment by kadel** [comment]
/retest

```
error: You must be logged in to the server (the server has asked for the client to provide credentials)

```

File: pkg/occlient/occlient.go [hunk 12]
```diff
@@ -1290,22 +1302,42 @@ func (c *Client) PatchCurrentDC(name string, dc appsv1.DeploymentConfig, prePatc
...
+	// inspired from https://github.com/openshift/origin/blob/bb1b9b5223dd37e63790d99095eec04bfd52b848/pkg/apps/controller/deploymentconfig/deploymentconfig_controller.go#L609
+	if reflect.DeepEqual(updatedDc.Spec.Template, currentDC.Spec.Template) {
+		return nil
+	} else {
+		currentDCBytes, err := json.Marshal(currentDC.Spec.Template)
+		updatedDCBytes, err := json.Marshal(updatedDc.Spec.Template)
+		if err != nil {
+			return errors.Wrapf(err, "unable to unmarshal dc")
+		}
+		glog.V(4).Infof("updatedDc Spec.Template: %v, not matching currentDc Spec.Template: %v", string(updatedDCBytes), string(currentDCBytes))
```
Comment (kadel) [inline pkg/occlient/occlient.go]: it would be good to add a  little bit more info to that message, like what it means if this is not matching. If I would read just this message in logs and didn't know how this is working I would think that this means that something went wrong

File: pkg/occlient/templates.go (hunk 10 above)
Comment (kadel) [reply pkg/occlient/templates.go]: then why not directly go for the first container? This will make it really confusing when someones add another container. Going just for the first one would be much safer

**Comment by mik-dass** [comment]
@kadel Fixed. Also I have made changes for the git update strategy. I guess we shouldn't wait for the deployment as of now because the build after it will anyways trigger a new deployment. We can revisit it in https://github.com/openshift/odo/issues/1682

File: pkg/occlient/templates.go [hunk 13]
```diff
@@ -22,6 +22,23 @@ type CommonImageMeta struct {
...
+type SupervisorDUpdateParams struct {
+	existingDc           *appsv1.DeploymentConfig
+	commonObjectMeta     metav1.ObjectMeta
+	commonImageMeta      CommonImageMeta
+	envVar               []corev1.EnvVar
+	envFrom              []corev1.EnvFromSource
+	resourceRequirements *corev1.ResourceRequirements
+}
+
+type GitDeploymentConfigUpdateParams struct {
```
Comment (kadel) [inline pkg/occlient/templates.go]: looks like this is not used anywhere

File: pkg/occlient/occlient.go [hunk 14]
```diff
@@ -1290,22 +1302,42 @@ func (c *Client) PatchCurrentDC(name string, dc appsv1.DeploymentConfig, prePatc
...
 		return errors.Wrapf(err, "unable to update DeploymentConfig %s", name)
 	}
 
+	// till we find a better solution for git
+	// it is better, not to follow the logs as the build will anyways trigger a new deployment later
+	if !waitForDc {
+		return nil
+	}
+
+	// we check after the update that the template in the earlier and the new dc are same or not
```
Comment (kadel) [inline pkg/occlient/occlient.go]: 👍

**Comment by mik-dass** [comment]
@kadel Fixed

File: pkg/occlient/templates.go [hunk 15]
```diff
@@ -139,6 +148,35 @@ func generateSupervisordDeploymentConfig(commonObjectMeta metav1.ObjectMeta, com
...
+			}
+		}
+		if containerIndex != -1 {
+			dc.Spec.Template.Spec.Containers[containerIndex].Resources = *updateParams.resourceRequirements
+		}
+	}
+
+	return dc
+}
+
```
Comment (cdrage) [inline pkg/occlient/templates.go]: Can you please add comments to the above function of what's happening what why it's needed?

File: pkg/occlient/templates.go [hunk 16]
```diff
@@ -139,6 +148,35 @@ func generateSupervisordDeploymentConfig(commonObjectMeta metav1.ObjectMeta, com
...
+	dc.ObjectMeta = updateParams.commonObjectMeta
+
+	if len(dc.Spec.Template.Spec.Containers) > 0 {
+		dc.Spec.Template.Spec.Containers[0].Name = updateParams.commonObjectMeta.Name
+		dc.Spec.Template.Spec.Containers[0].Ports = updateParams.commonImageMeta.Ports
+		dc.Spec.Template.Spec.Containers[0].Env = updateParams.envVar
+		dc.Spec.Template.Spec.Containers[0].EnvFrom = updateParams.envFrom
+	}
+
+	containerIndex := -1
```
Comment (cdrage) [inline pkg/occlient/templates.go]: Never really seen a `-1` been used.. Mind explaining in a comment why?

File: pkg/occlient/occlient.go [hunk 17]
```diff
@@ -1502,27 +1541,38 @@ func (c *Client) UpdateDCToSupervisor(ucp UpdateComponentParams, isToLocal bool,
...
-	// Generate the SupervisorD Config
-	dc := generateSupervisordDeploymentConfig(
-		ucp.CommonObjectMeta,
-		ucp.ImageMeta,
-		inputEnvs,
-		cmpContainer.EnvFrom,
-		&ucp.ResourceLimits,
-	)
+	var dc appsv1.DeploymentConfig
+	if isCreatePVC {
```
Comment (cdrage) [inline pkg/occlient/occlient.go]: what happens if `isCreatePVC` isn't true? Would it be correct in saying that supervisord won't be added at all?

File: pkg/occlient/templates.go [hunk 18]
```diff
@@ -139,6 +148,35 @@ func generateSupervisordDeploymentConfig(commonObjectMeta metav1.ObjectMeta, com
...
+	if updateParams.resourceRequirements != nil {
+		for index, container := range dc.Spec.Template.Spec.Containers {
```
Comment (kadel) [inline pkg/occlient/templates.go]: similarly as done above, we don't need to loop over all containers

File: pkg/occlient/occlient.go (hunk 17 above)
Comment (kadel) [reply pkg/occlient/occlient.go]: If I'm not mistaken it is an indicator that we are updating from git component to local or binary component and that PVC to hold source code/binary needs to be created. Am I right @mik-dass?

Not a good name variable, but that is something that is probably outside of the scope of this PR.

Comment (mik-dass) [reply pkg/occlient/occlient.go]: Yes it is used to indicate if a new supervisorD PVC should be created during the update or not e.g during the update from local/binary to git component. I have added a comment regarding this variable.

File: pkg/occlient/templates.go (hunk 16 above)
Comment (mik-dass) [reply pkg/occlient/templates.go]: I used it as the container index cannot be -1 and since we can store the container index in the same variable. But I am removing this logic due to https://github.com/openshift/odo/pull/1684#discussion_r282535213

**Comment by mik-dass** [comment]
@cdrage @kadel Fixed

**Comment by girishramnani** [comment]
maybe an integration test would be helpful here if possible @mik-dass

**Comment by mik-dass** [comment]
> maybe an integration test would be helpful here if possible @mik-dass

I have already a added a unit test for the same :)

File: pkg/occlient/occlient.go [hunk 19]
```diff
@@ -1502,27 +1542,38 @@ func (c *Client) UpdateDCToSupervisor(ucp UpdateComponentParams, isToLocal bool,
...
```
Comment (cdrage) [inline pkg/occlient/occlient.go]: We should rename this function before the PR gets merged in. :+1:

**Comment by mik-dass** [comment]
@cdrage Fixed

**Comment by surajnarwade** [comment]
```
level=warning msg="Found override for ReleaseImage. Please be warned, this is not advised"
level=info msg="Consuming \"Install Config\" from target directory"
level=info msg="Creating infrastructure resources..."
level=error
level=error msg="Error: Error applying plan:"
level=error
level=error msg="2 errors occurred:"
level=error msg="\t* module.vpc.aws_route_table_association.route_net[1]: 1 error occurred:"
level=error msg="\t* aws_route_table_association.route_net.1: timeout while waiting for state to become 'success' (timeout: 5m0s)"
level=error
level=error
level=error msg="\t* module.vpc.aws_internet_gateway.igw: 1 error occurred:"
level=error msg="\t* aws_internet_gateway.igw: error attaching EC2 Internet Gateway (igw-05564ebe4b83158c0): timeout while waiting for state to become 'success' (timeout: 2m0s)"
level=error
level=error
level=error
level=error
level=error
level=error msg="Terraform does not automatically rollback in the face of errors."
level=error msg="Instead, your Terraform state file has been partially updated with"
level=error msg="any resources that successfully completed. Please address the error"
level=error msg="above and apply again to incrementally change your infrastructure."
level=error
level=error
level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
```

/retest
