### PR TITLE
Fix parallel test run failure for devfile integration test 

### LINKED ISSUE #2954: Travis failures in "devfile catalog, watch command integration tests on kubernetes cluster"
I observed following Travis flake in **devfile catalog, watch command integration tests on kubernetes cluster** test.
```
Created dir: /tmp/483916658
Creating a new project: bmlfjlszob
Running kubectl with args [kubectl create namespace bmlfjlszob]
[kubectl] namespace "bmlfjlszob" created
Running kubectl with args [kubectl config set-context /tmp/483916658 --namespace bmlfjlszob]
[kubectl] error: open /home/travis/.kube/config.lock: file exists
Deleting project: 
Running kubectl with args [kubectl delete namespaces ]
[kubectl] error: resource name may not be empty
• Failure in Spec Setup (BeforeEach) [1.766 seconds]
odo devfile watch command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:14
  when executing watch without a valid devfile [BeforeEach]
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:71
    should fail
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:72
    No future change is possible.  Bailing out early after 0.626s.
    Running kubectl with args [kubectl config set-context /tmp/483916658 --namespace bmlfjlszob]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
    /home/travis/gopath/src/github.com/openshift/odo/tests/helper/helper_run.go:34
------------------------------
SSS•••
Summarizing 1 Failure:
[Fail] odo devfile watch command tests [BeforeEach] when executing watch without a valid devfile should fail 
/home/travis/gopath/src/github.com/openshift/odo/tests/helper/helper_run.go:34
Ran 4 of 35 Specs in 3.813 seconds
FAIL! -- 3 Passed | 1 Failed | 0 Pending | 31 Skipped

```
/kind flake
_Originally posted by @dharmit in https://github.com/openshift/odo/pull/2944#issuecomment-617552849_

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind bug

**What does does this PR do / why we need it**:

It supports parallel test run on kubernetes cluster.

**Which issue(s) this PR fixes**:

Fixes #2954 

**How to test changes / Special notes to the reviewer**:
Kubernetes job should pass on travis.

### CODE REVIEW

**Comment by prietyc123** [comment]
prow failure

/retest

File: tests/helper/kubernetes_utils.go [hunk 1]
```diff
@@ -8,11 +8,11 @@ import (
 )
 
 // CreateRandNamespace create new project with random name in kubernetes cluster (10 letters)
-func CreateRandNamespace(context string) string {
+func CreateRandNamespace() string {
 	projectName := RandString(10)
 	fmt.Fprintf(GinkgoWriter, "Creating a new project: %s\n", projectName)
 	CmdShouldPass("kubectl", "create", "namespace", projectName)
-	CmdShouldPass("kubectl", "config", "set-context", context, "--namespace", projectName)
+	CmdShouldPass("kubectl", "config", "set-context", "--current", "--namespace", projectName)
```
Comment (jgwest) [inline tests/helper/kubernetes_utils.go:15]: `kubectl config set-context` is not safe to use when tests are running in parallel AFAICT (either with or without ``--current`) . 

For two reasons:
- `kubectl` will prevent multiple concurrent writes which to the configuration file; it uses a `.lock` file and if the lock exists then changes to the configuration file are prevented (a non-zero error code is returned and the test will fail).
- Changing the current kube context of one automated test will affect any other tests that are running in parallel (for example, a different namespace then expected).

This use of `set-context` is failing tests for me on my local machine.

Comment (prietyc123) [reply tests/helper/kubernetes_utils.go:15]: Thanks a lot for you suggestion. I was also looking for the same kind of solution but was unable to find out from any other sources.

I will try it out for sure 👍

Comment (amitkrout) [reply tests/helper/kubernetes_utils.go:15]: @prietyc123 Please use the doc [1] along for more understanding along with @jgwest suggestion and create a separate pr that fixes this issue only.

[1] https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable

Comment (prietyc123) [reply tests/helper/kubernetes_utils.go]: Yes, It works for me. Thanks @amitkrout for making me understand more clearly over bjn.

File: .travis.yml [hunk 2]
```diff
@@ -153,7 +153,6 @@ jobs:
         - travis_wait make test-cmd-docker-devfile-push
         - travis_wait make test-cmd-docker-devfile-url
 
-
```
Comment (amitkrout) [inline .travis.yml:156]: Keep the travis file like it was. Adding a space or removing new line does make any sense. I guess it has been made accidentally, please revert it back.

File: tests/helper/helper_filesystem.go [hunk 3]
```diff
@@ -247,3 +247,29 @@ func ReplaceDevfileField(devfileLocation, field, newValue string) error {
 	}
 	return nil
 }
+
+// CopyFile copies the file from source to destination
```
Comment (amitkrout) [inline tests/helper/helper_filesystem.go:251]: Add more details. For example - what is source and destination argument

Comment (prietyc123) [reply tests/helper/helper_filesystem.go:251]: > Add more details. For example - what is source and destination argument

I think specifying the source and destination directory will conserve the ```CopyFile``` function for specific case. But it should be global so that anyone can use this function anywhere. So this function basically copies the files present in source directory to the destination directory. IMO comment explain it more accurately. Let me know if you still feel we should some comment.

File: .travis.yml (hunk 2 above)
Comment (prietyc123) [reply .travis.yml]: Yes, I got removed accidently. Good catch 👍

File: tests/integration/devfile/cmd_devfile_catalog_test.go [hunk 4]
```diff
@@ -22,7 +23,12 @@ var _ = Describe("odo devfile catalog command tests", func() {
 		os.Setenv("GLOBALODOCONFIG", filepath.Join(context, "config.yaml"))
 		helper.CmdShouldPass("odo", "preference", "set", "Experimental", "true")
 		if os.Getenv("KUBERNETES") == "true" {
-			project = helper.CreateRandNamespace(context)
+			err := helper.CopyFile(os.Getenv("KUBECONFIG"), filepath.Join(context, "config"))
+			if err != nil {
```
Comment (amitkrout) [inline tests/integration/devfile/cmd_devfile_catalog_test.go:27]: No need to handle ```err``` here. Just check https://github.com/openshift/odo/blob/master/tests/helper/helper_filesystem.go#L144 how it has been implemented in other places.

File: tests/helper/helper_filesystem.go (hunk 3 above)
Comment (amitkrout) [reply tests/helper/helper_filesystem.go:251]: Can please check how https://github.com/openshift/odo/blob/master/tests/helper/helper_filesystem.go#L144 has been implemented in other places. I am sure this will gives you a better picture and instead of writing the function again just re use it. See how it has been done in - https://github.com/openshift/odo/blob/master/tests/helper/helper_filesystem.go#L92

File: tests/integration/devfile/cmd_devfile_catalog_test.go [hunk 5]
```diff
@@ -22,7 +23,12 @@ var _ = Describe("odo devfile catalog command tests", func() {
...
+				fmt.Println("Source file does not copied to the target with error", err)
```
Comment (amitkrout) [inline tests/integration/devfile/cmd_devfile_catalog_test.go:28]: This need to be asserted instead of just printing. For example - https://github.com/openshift/odo/blob/master/tests/helper/helper_filesystem.go#L92.

File: tests/integration/devfile/cmd_devfile_catalog_test.go [hunk 6]
```diff
@@ -22,7 +23,12 @@ var _ = Describe("odo devfile catalog command tests", func() {
...
+			}
+			os.Setenv("KUBECONFIG", filepath.Join(context, "config"))
```
Comment (amitkrout) [inline tests/integration/devfile/cmd_devfile_catalog_test.go:30]: +1

File: tests/integration/devfile/cmd_devfile_catalog_test.go [hunk 7]
```diff
@@ -34,11 +40,13 @@ var _ = Describe("odo devfile catalog command tests", func() {
 	var _ = AfterEach(func() {
 		if os.Getenv("KUBERNETES") == "true" {
 			helper.DeleteNamespace(project)
+			os.Unsetenv("KUBECONFIG")
 		} else {
 			helper.DeleteProject(project)
 		}
 		helper.Chdir(currentWorkingDirectory)
 		helper.DeleteDir(context)
+		os.Unsetenv("GLOBALODOCONFIG")
```
Comment (amitkrout) [inline tests/integration/devfile/cmd_devfile_catalog_test.go:49]: +1, Ahh...It was a miss.

**Comment by amitkrout** [comment]
prow failure
/retest

File: tests/helper/helper_filesystem.go (hunk 3 above)
Comment (prietyc123) [reply tests/helper/helper_filesystem.go:251]: Ahh, I just missed it. Thanks for the info, I will definitely use this 👍

**Comment by prietyc123** [comment]
Created issue for the error https://travis-ci.com/github/openshift/odo/jobs/323318598#L1078 in https://github.com/openshift/odo/issues/2997

**Comment by prietyc123** [comment]
Tracked the failure in https://github.com/openshift/odo/issues/2998

/retest

File: tests/helper/helper_filesystem.go [hunk 8]
```diff
@@ -137,11 +137,11 @@ func copyDir(src string, dst string, info os.FileInfo) error {
...
 	}
 
-	return copyFile(src, dst, info)
+	return CopyFile(src, dst, info)
 }
 
-// copyFile copy one file to another location
-func copyFile(src, dst string, info os.FileInfo) error {
+// CopyFile copy one file to another location
+func CopyFile(src, dst string, info os.FileInfo) error {
```
Comment (amitkrout) [inline tests/helper/helper_filesystem.go:144]: This function is being used as a library for function in the same package. So caps in the function name is not required. revert it as it was. For example ```CopyFile``` -> ```copyFile```

File: tests/helper/kubernetes_utils.go [hunk 9]
```diff
@@ -2,11 +2,20 @@ package helper
...
 	"fmt"
+	"os"
 
 	. "github.com/onsi/ginkgo"
 	. "github.com/onsi/gomega"
 )
 
+// CopyKubeConfigFile copies default kubeconfig file into current context config file
+func CopyKubeConfigFile(kubeConfigFile, tempConfigFile string, info os.FileInfo) string {
+	err := CopyFile(kubeConfigFile, tempConfigFile, info)
```
Comment (amitkrout) [inline tests/helper/kubernetes_utils.go:13]: change it as per https://github.com/openshift/odo/pull/2965/files#r415551858

File: tests/helper/helper_filesystem.go (hunk 8 above)
Comment (prietyc123) [reply tests/helper/helper_filesystem.go:144]: I have changed it to ```CopyFile``` so that anyone can use this function anywhere as required. Because it is the basic function which can be required in other files.

File: tests/helper/kubernetes_utils.go (hunk 9 above)
Comment (prietyc123) [reply tests/helper/kubernetes_utils.go:13]: https://github.com/openshift/odo/pull/2965#discussion_r415560462

File: tests/helper/helper_filesystem.go (hunk 8 above)
Comment (amitkrout) [reply tests/helper/helper_filesystem.go:144]: We should not change the working test code until unless there is a hard requirement to do so. In your case you are not using ```CopyFile``` function out side of the same package, then it is not needed at all to open the function for other packages for your changes.

**Comment by prietyc123** [comment]
Error : 
```
[odo]  ✗  Waiting for component to start [4m]
[odo]  ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=nodejs-701733464-idsm-app'
Deleting project: juehwrzamz
Running odo with args [odo project delete juehwrzamz -f]
[odo] This project contains the following applications, which will be deleted
[odo] Application app
[odo] This application has following components that will be deleted
[odo] component named nodejs-701733464-idsm
[odo] No services / could not get services
[odo]  •  Deleting project juehwrzamz  ...
[odo] 
 ✓  Deleting project juehwrzamz [6s]
[odo]  ✓  Deleted project : juehwrzamz
Deleting dir: /tmp/701733464
• Failure [251.976 seconds]
odo debug command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_debug_test.go:17
  odo debug on a nodejs:latest component
  /go/src/github.com/openshift/odo/tests/integration/cmd_debug_test.go:40
    should expect a ws connection when tried to connect on different debug port locally and remotely [It]
    /go/src/github.com/openshift/odo/tests/integration/cmd_debug_test.go:41
    No future change is possible.  Bailing out early after 241.601s.
      
    Running odo with args [odo push --context /tmp/701733464]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
```

Issue already tracked in https://github.com/openshift/odo/issues/2877

/retest

**Comment by prietyc123** [comment]
prow failure.

retest

**Comment by girishramnani** [comment]
```
level=error msg="Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get https://api.ci-op-v7c54631-34074.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusteroperators: dial tcp 54.70.71.68:6443: connect: connection refused"
level=info msg="Pulling debug logs from the bootstrap machine"
```
