### PR TITLE
Makes it possible to list services outside a component directory

### LINKED ISSUE #1838: service list does not work outside of component dir
[kind/bug]

## What versions of software are you using?
- Operating System: All supported platform
- Output of `odo version`: master

## How did you run odo exactly?
```
$ oc --request-timeout 5m import-image java --namespace=myproject --from=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.5 --confirm

$ oc annotate istag/java:latest --namespace=myproject tags=builder --overwrite

$ odo create java sb-app

$ odo service create dh-postgresql-apb --plan dev -p postgresql_user=luke -p postgresql_password=secret -p postgresql_database=my_data -p postgresql_version=9.6

$ cd .. && odo service list
```
## Actual behavior
```
$ cd .. && odo service list
 ✗  the current directory does not represent an odo component.
Maybe use 'odo create' to create component here or switch to directory with a component

$ odo service list --project myproject
 ✗  the current directory does not represent an odo component.
```

## Expected behavior
```
$ odo service list
NAME                  TYPE                  STATUS
dh-postgresql-apb     dh-postgresql-apb     ProvisionedAndBound
```

### PR DESCRIPTION
**Pull request by dharmit**
User needs to provide the `app` and `project` for which they would like to list the
services.

## What is the purpose of this change? What does it change?

Listing services (`odo service list`) was not possible unless one's working from a component directory. This PR fixes that issue as long as `--app` field is provided. 

## Was the change discussed in an issue?
fixes #1838 

## How to test changes?

1. Build the binary
2. Create a service from a component directory (#1810).
3. `cd` into a non-component directory
4. Execute `odo service list --app <app-name> --project <project-name>` where `<app-name>` and `<project-name>` should be same as the used in the component directory mentioned in Step 2.

### CODE REVIEW

**Comment by amitkrout** [comment]
#1832 
/test integration

**Comment by surajnarwade** [comment]
code LGTM, I'll wait for CI to become :green_heart: 

travis shows weird error `imagestream java not found`, please look into it

**Comment by surajnarwade** [comment]
worked for me:

```
$ odo service list --app app
NAME                      TYPE                      STATUS
dh-es-apb                 dh-es-apb                 DeprovisionBlockedByExistingCredentials
postgresql-persistent     postgresql-persistent     ProvisionedAndBound

$ odo service list --app app --project myproject
NAME                      TYPE                      STATUS
dh-es-apb                 dh-es-apb                 DeprovisionBlockedByExistingCredentials
postgresql-persistent     postgresql-persistent     ProvisionedAndBound
```

**Comment by dharmit** [comment]
> worked for me:
> 
> ```
> $ odo service list --app app
> NAME                      TYPE                      STATUS
> dh-es-apb                 dh-es-apb                 DeprovisionBlockedByExistingCredentials
> postgresql-persistent     postgresql-persistent     ProvisionedAndBound
> 
> $ odo service list --app app --project myproject
> NAME                      TYPE                      STATUS
> dh-es-apb                 dh-es-apb                 DeprovisionBlockedByExistingCredentials
> postgresql-persistent     postgresql-persistent     ProvisionedAndBound
> ```

My concern with this is that `odo` defaults to `myproject` if project is not mentioned. Same behaviour can be seen with `odo component list` if executed from outside a component dir, i.e., `odo component list --app app` would, by default, list components for the app `app` in the project `myproject`.

Is this by design or is it a flaw we should fix?

cc @kadel

**Comment by surajnarwade** [comment]
@dharmit , it's normal behaviour, if you dont mention the project, odo should pick whatever current project is set in kubeconfig file

**Comment by dharmit** [comment]
> @dharmit , it's normal behaviour, if you dont mention the project, odo should pick whatever current project is set in kubeconfig file

Ah, didn't know that! Thanks for the info. :+1:

**Comment by dharmit** [comment]
@amitkrout I agree with your concern and, tbh, I had the same concern before I wrote this in separate spec. But I kept it separate because if we combine two checks in single test and something fails, it might become a bit of a pain to figure out where exactly things are breaking.

If you & @kadel still think that it makes sense to combine the two, I'll do what you recommended. :+1:

**Comment by amitkrout** [comment]
> @amitkrout I agree with your concern and, tbh, I had the same concern before I wrote this in separate spec. But I kept it separate because if we combine two checks in single test and something fails, it might become a bit of a pain to figure out where exactly things are breaking.
> 
> If you & @kadel still think that it makes sense to combine the two, I'll do what you recommended. 👍

@dharmit Right, Thanks for the clarification.
However you can create a new service (except the existing one) and ofcourse with the new component. Then this approach will really add weightage/more coverage to the test file.

Anyway i am going to add some change for request in your test scenario.

File: tests/integration/service_test.go [hunk 1]
```diff
@@ -101,4 +102,39 @@ var _ = Describe("odoServiceE2e", func() {
...
+		})
+		JustAfterEach(func() {
+			helper.DeleteProject(project)
+			helper.DeleteDir(context)
+			helper.Chdir(originalDir)
+		})
+		It("should be able to list services in a given app and project combination", func() {
+			// create a component by copying the example
+			helper.CopyExample(filepath.Join("source", "nodejs"), context)
+			helper.CmdShouldPass("odo", "create", "nodejs", "--app", app, "--project", project)
```
Comment (amitkrout) [inline tests/integration/service_test.go]: +1

File: tests/integration/service_test.go [hunk 2]
```diff
@@ -101,4 +102,39 @@ var _ = Describe("odoServiceE2e", func() {
...
+
+			// create a service from within a component directory
+			helper.CmdShouldPass("odo", "service", "create", "dh-postgresql-apb", "--plan", "dev",
```
Comment (amitkrout) [inline tests/integration/service_test.go]: Create a new service instead of ```dh-postgresql```. Just to improve the odo service coverage

File: tests/integration/service_test.go [hunk 3]
```diff
@@ -101,4 +102,39 @@ var _ = Describe("odoServiceE2e", func() {
...
+				"-p", "postgresql_user=luke", "-p", "postgresql_password=secret",
+				"-p", "postgresql_database=my_data", "-p", "postgresql_version=9.6",
+				"--app", app, "--project", project,
+			)
+			ocArgs := []string{"get", "serviceinstance", "-o", "name"}
+			helper.WaitForCmdOut("oc", ocArgs, 1, true, func(output string) bool {
+				return strings.Contains(output, "dh-postgresql-apb")
+			})
+
```
Comment (amitkrout) [inline tests/integration/service_test.go]: Add the steps for listing out the service in the component dir to make sure it works form component dir too.

**Comment by amitkrout** [comment]
Blocked due to pr #1912 because flake hit by this pr is fixed in pr #1912

**Comment by dharmit** [comment]
@kadel I don't think the CI failures are related to the PR. :unamused:

**Comment by kadel** [comment]
```
error: could not run steps: step benchmark failed: template pod "benchmark" failed: the pod ci-op-pjxdwwcj/benchmark failed after 35m40s (failed containers: test): ContainerFailed one or more containers exited
```
/retest

File: tests/integration/service_test.go [hunk 4]
```diff
@@ -101,4 +102,42 @@ var _ = Describe("odoServiceE2e", func() {
 	// 	})
 	// })
 
+	Context("When working from outside a component dir", func() {
```
Comment (kadel) [inline tests/integration/service_test.go]: the context says "when working **outside** a component dir" but then "JustBeforeEach" switches the current dir to the context dir  :-/

File: tests/integration/service_test.go [hunk 5]
```diff
@@ -101,4 +102,42 @@ var _ = Describe("odoServiceE2e", func() {
...
+		It("should be able to list services in a given app and project combination", func() {
+			// create a component by copying the example
+			helper.CopyExample(filepath.Join("source", "nodejs"), context)
+			helper.CmdShouldPass("odo", "create", "nodejs", "--app", app, "--project", project)
+
+			// create a service from within a component directory
+			helper.CmdShouldPass("odo", "service", "create", "dh-prometheus-apb", "--plan", "ephemeral",
+				"--app", app, "--project", project,
+			)
+			ocArgs := []string{"get", "serviceinstance", "-o", "name"}
```
Comment (kadel) [inline tests/integration/service_test.go]: this should specify namespace `"-n", "project"`

/approve cancel

File: tests/integration/service_test.go (hunk 4 above)
Comment (dharmit) [reply tests/integration/service_test.go]: That is for the sake of copying the nodejs example and creating a component from it. But for the test, we have made sure that we cd to `originalDir` https://github.com/openshift/odo/pull/1920/files#diff-2bf31fdcc572d1ff24f1215e18667e08R137-R140

File: tests/integration/service_test.go (hunk 5 above)
Comment (dharmit) [reply tests/integration/service_test.go]: Done.

Comment (amitkrout) [reply tests/integration/service_test.go]: @dharmit You need to add the name space in the same occurrence of step in other scenario of this test file

Comment (amitkrout) [reply tests/integration/service_test.go]: https://github.com/openshift/odo/pull/1920/files#diff-2bf31fdcc572d1ff24f1215e18667e08R58 and

**Comment by dharmit** [comment]
```
 • Failure [250.748 seconds]
odo generic
/go/src/github.com/openshift/odo/tests/integration/generic_test.go:14
  deploying a component with a specific image name
  /go/src/github.com/openshift/odo/tests/integration/generic_test.go:112
    should deploy the component [It]
```
/test integration

**Comment by amitkrout** [comment]
> ```
>  • Failure [250.748 seconds]
> odo generic
> /go/src/github.com/openshift/odo/tests/integration/generic_test.go:14
>   deploying a component with a specific image name
>   /go/src/github.com/openshift/odo/tests/integration/generic_test.go:112
>     should deploy the component [It]
> ```
> 
> /test integration

@dharmit Thanks for re- triggering the test.
From the message above it's hard to find out the failure reason. I would suggest quote the exact failure log form the console. It helps to point out test flaky behaviour in first look.

**Comment by dharmit** [comment]
@amitkrout does this help or is it still not the exact error message?

```
[91m[1m• Failure [368.994 seconds][0m
odoCmpSubE2e
[90m/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_sub_test.go:13[0m
  when running odo push multiple times, check for existence of environment variables
  [90m/go/src/github.com/openshift/odo/tests/integration/component.go:477[0m
    [91m[1mshould should retain the same environment variable on multiple push [It][0m
    [90m/go/src/github.com/openshift/odo/tests/integration/component.go:490[0m

    [91mNo future change is possible.  Bailing out early after 300.524s.
    Running odo with args [odo push]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0[0m

    /go/src/github.com/openshift/odo/tests/helper/helper_run.go:32
[90m------------------------------[0m


[91m[1mSummarizing 1 Failure:[0m

[91m[1m[Fail] [0m[90modoCmpSubE2e [0m[0mwhen running odo push multiple times, check for existence of environment variables [0m[91m[1m[It] should should retain the same environment variable on multiple push [0m
[37m/go/src/github.com/openshift/odo/tests/helper/helper_run.go:32[0m

[1m[91mRan 21 of 106 Specs in 1017.591 seconds[0m
[1m[91mFAIL![0m -- [32m[1m20 Passed[0m | [91m[1m1 Failed[0m | [33m[1m0 Pending[0m | [36m[1m85 Skipped[0m
```

**Comment by amitkrout** [comment]
> @amitkrout does this help or is it still not the exact error message?
> 
> ```
> �[91m�[1m• Failure [368.994 seconds]�[0m
> odoCmpSubE2e
> �[90m/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_sub_test.go:13�[0m
>   when running odo push multiple times, check for existence of environment variables
>   �[90m/go/src/github.com/openshift/odo/tests/integration/component.go:477�[0m
>     �[91m�[1mshould should retain the same environment variable on multiple push [It]�[0m
>     �[90m/go/src/github.com/openshift/odo/tests/integration/component.go:490�[0m
> 
>     �[91mNo future change is possible.  Bailing out early after 300.524s.
>     Running odo with args [odo push]
>     Expected
>         <int>: 1
>     to match exit code:
>         <int>: 0�[0m
> 
>     /go/src/github.com/openshift/odo/tests/helper/helper_run.go:32
> �[90m------------------------------�[0m
> 
> 
> �[91m�[1mSummarizing 1 Failure:�[0m
> 
> �[91m�[1m[Fail] �[0m�[90modoCmpSubE2e �[0m�[0mwhen running odo push multiple times, check for existence of environment variables �[0m�[91m�[1m[It] should should retain the same environment variable on multiple push �[0m
> �[37m/go/src/github.com/openshift/odo/tests/helper/helper_run.go:32�[0m
> 
> �[1m�[91mRan 21 of 106 Specs in 1017.591 seconds�[0m
> �[1m�[91mFAIL!�[0m -- �[32m�[1m20 Passed�[0m | �[91m�[1m1 Failed�[0m | �[33m�[1m0 Pending�[0m | �[36m�[1m85 Skipped�[0m
> ```
@dharmit Above you pasted is the failure result, the reason is (copied from the same scenario - https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/1920/pull-ci-openshift-odo-master-integration/1126)
```
[odo] Configuration changes
[odo]  •  Applying configuration  ...
[odo]  ✗  Applying configuration [5m]
[odo]  ✗  Failed To Update Config To Component Deployed 
```
Seems a flake 
/test integration

**Comment by dharmit** [comment]
```
[odo]  •  Checking files for pushing  ...
[odo]  ✓  Checking files for pushing [460892ns]
[odo]  •  Waiting for component to start  ...
[odo]  ✗  Waiting for component to start [4m]
[odo]  ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=python-app-app'
Deleting project: dabkincvwo
```
@amitkrout have I picked the right reason this time? If yes, looks like a flake to me. But are so many flakes possible/normal?

**Comment by amitkrout** [comment]
> ```
> [odo]  •  Checking files for pushing  ...
> [odo]  ✓  Checking files for pushing [460892ns]
> [odo]  •  Waiting for component to start  ...
> [odo]  ✗  Waiting for component to start [4m]
> [odo]  ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=python-app-app'
> Deleting project: dabkincvwo
> ```
> 
> @amitkrout have I picked the right reason this time? If yes, looks like a flake to me. But are so many flakes possible/normal?

Yes, you pasted the exact failure message.

> But are so many flakes possible/normal?

IMO it's not normal. Something we should look into the code because the test script we are running is same as how enterprise user going to use odo. For example more than one user runs odo on same cluster in same time with different name space, context and etc.

Lets track the issue #1981 with high priority cc_ @kadel

**Comment by amitkrout** [comment]
ping @girishramnani @kadel @surajnarwade

**Comment by dharmit** [comment]
> ping @girishramnani @kadel @surajnarwade

I'd like @kadel to have a look since he had some feedback https://github.com/openshift/odo/pull/1920#pullrequestreview-270127113. @surajnarwade already found the stuff good to merge. I'll ping Tomas again.

File: tests/integration/service_test.go (hunk 4 above)
Comment (kadel) [reply tests/integration/service_test.go]: ok, I missed that. 
/lgtm
