### PR TITLE
Fixes wait for project creation

### LINKED ISSUE #2117: Project create doesn't wait properly
https://travis-ci.com/openshift/odo/jobs/233964101#L2793

```
Running odo with args [odo project list]
[odo] ACTIVE     NAME
[odo] *          kdiadkbatt
[odo]            myproject
Running odo with args [odo project list]
[odo] ACTIVE     NAME
[odo]            kbcwtnzrez
[odo] *          kdiadkbatt
[odo]            myproject
```
I had applied a sleep operation of 1 sec in between the two list operations and the create was performed with `-w` flag

### LINKED ISSUE #2284: flaky project list in tests
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`: CI

## How did you run odo exactly?

in the v4.2 integration test, odo project command tests, seems to have a flaky test on odo side - the project didn't show up in the list after creation.

```
Running odo with args [odo project delete ikiydcpzex -f]
[odo]  •  Deleting project ikiydcpzex  ...
[odo]  ✓  Deleting project ikiydcpzex [6s]
[odo]  ✓  Deleted project : ikiydcpzex
Deleting dir: /tmp/799583864

�[91m�[1m• Failure [7.997 seconds]�[0m
�[90m/go/src/github.com/openshift/odo/tests/integration/project/cmd_project_test.go:13�[0m
  when running project command app parameter in directory that doesn't contain .odo config directory
  �[90m/go/src/github.com/openshift/odo/tests/integration/project/cmd_project_test.go:41�[0m
    �[91m�[1mshould successfully execute list along with machine readable output [It]�[0m
    �[90m/go/src/github.com/openshift/odo/tests/integration/project/cmd_project_test.go:42�[0m

    �[91mExpected
        <string>: ACTIVE     NAME
                   drsbsxyaju
                   gmktltcicr
                   myproject
        
    to contain substring
        <string>: ikiydcpzex�[0m

```
link - https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2275/pull-ci-openshift-odo-master-v4.2-integration/519

observed in this PR first https://github.com/openshift/odo/pull/2275

### PR DESCRIPTION
**Pull request by mik-dass**
fixes #2117 
fixes #2284 

How to test:

- Run `odo project create <name> -w` and check if the command waits properly.
- `make test-cmd-project` should pass.

### CODE REVIEW

**Comment by girishramnani** [comment]
can we have a test for this?

**Comment by mik-dass** [comment]
> can we have a test for this?

There is an open issue regarding this #2319 . But I will write the test as part of this PR itself.

**Comment by mik-dass** [comment]
> There is an open issue regarding this #2319 . But I will write the test as part of this PR itself.

@girishramnani There is already a test for CreateNewProject() https://github.com/openshift/odo/blob/116728936e3ed26f25b51ae51218d4d0e11bb6ee/pkg/occlient/occlient_test.go#L2258
I have modified the test according to this PR.

**Comment by mik-dass** [comment]
```
Lease acquired, installing...
Installing from release registry.svc.ci.openshift.org/ci-op-i14rl3wc/release@sha256:567e8d426e6734f7211e87abe15c66b35ff365e604f913a912b4a3982a5f2d18
level=fatal msg="failed to fetch Terraform Variables: failed to fetch dependency of \"Terraform Variables\": failed to fetch dependency of \"Bootstrap Ignition Config\": failed to fetch dependency of \"Master Machines\": failed to generate asset \"Platform Credentials Check\": validate AWS credentials: mint credentials check: error simulating policy: Throttling: Rate exceeded\n\tstatus code: 400, request id: a25c8834-a2bc-4155-90b9-01789b284900"
---
```
/retest

**Comment by mik-dass** [comment]
weird that the `odo project list` and `odo project list -o json` don't match https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2330/pull-ci-openshift-odo-master-v4.1-integration/692#1:build-log.txt%3A18136

**Comment by mik-dass** [comment]
```

error: could not run steps: step [release:latest] failed: release "release-latest" failed: the pod ci-op-rv8vk0pl/release-latest failed after 13s (failed containers: release): ContainerFailed one or more containers exited
```
/retest

**Comment by amitkrout** [comment]
@mik-dass i have run this pr not less than 20times and none of the time it fails on listing out the project just after creating it. 

Looks like the fix works properly. However i would request somebody from the team please confirm the stability of the fix.

File: tests/integration/project/cmd_project_test.go [hunk 1]
```diff
@@ -26,6 +26,8 @@ var _ = Describe("odo project command tests", func() {
 	// Clean up after the test
 	// This is run after every Spec (It)
 	var _ = AfterEach(func() {
+		// remove later
+		helper.CmdRunner("odo", "project", "list", "-o", "json")
```
Comment (amitkrout) [inline tests/integration/project/cmd_project_test.go]: Remove it

Comment (mik-dass) [reply tests/integration/project/cmd_project_test.go]: this is for debugging, the tests are still failing

Comment (amitkrout) [reply tests/integration/project/cmd_project_test.go]: ok

Comment (kadel) [reply tests/integration/project/cmd_project_test.go]: @mik-dass pls mark this PR as work in progress if you plan to do any changes

File: pkg/occlient/occlient.go [hunk 2]
```diff
@@ -550,9 +550,19 @@ func (c *Client) CreateNewProject(projectName string, wait bool) error {
...
 				break
 			}
-			if e, ok := val.Object.(*projectv1.Project); ok {
-				glog.V(4).Infof("Project %s now exists", e.Name)
-				return nil
+			if prj, ok := val.Object.(*projectv1.Project); ok {
+				glog.V(4).Infof("Status of creation of project %s is %s", prj.Name, prj.Status.Phase)
+				switch prj.Status.Phase {
+				//prj.Status.Phase can only be "Terminating" or "Active" or ""
+				case "Active":
```
Comment (kadel) [inline pkg/occlient/occlient.go]: please use [`corev1.NamespaceActive`](https://github.com/openshift/odo/blob/3a2ca54ad9f93ec0659311c0cf4526aa783e5ef3/vendor/k8s.io/api/core/v1/types.go#L4177) instead of hardcored string

File: tests/integration/project/cmd_project_test.go (hunk 1 above)
Comment (mik-dass) [reply tests/integration/project/cmd_project_test.go]: Done

**Comment by mik-dass** [comment]
@kadel Fixed

**Comment by mik-dass** [comment]
```
2019/12/10 11:13:22 No custom metadata found and prow metadata already exists. Not updating the metadata.
```
/retest

**Comment by mik-dass** [comment]
```
{"component":"entrypoint","file":"prow/entrypoint/run.go:164","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 4h0m0s timeout","time":"2019-12-10T15:24:00Z"}
```
/retest

**Comment by kadel** [comment]
@mik-dass is this still WIP?

File: pkg/occlient/occlient.go [hunk 3]
```diff
@@ -533,16 +541,50 @@ func (c *Client) CreateNewProject(projectName string, wait bool) error {
...
+				}
 			}
 		}
 	}
 
 	return nil
 }
 
+func (c *Client) WaitForDefaultServiceAccountInNamespace(namespace, serviceAccountName string) error {
+	watcher, err := c.kubernetesCoreV1.ServiceAccounts(namespace).Watch(metav1.SingleObject(metav1.ObjectMeta{Name: serviceAccountName}))
```
Comment (kadel) [inline pkg/occlient/occlient.go]: Why not use existing `kubeClient` clientset?
```
c.kubeClient.Core().ServiceAccounts
```

File: pkg/occlient/occlient.go [hunk 4]
```diff
@@ -35,6 +35,7 @@ import (
 	projectclientset "github.com/openshift/client-go/project/clientset/versioned/typed/project/v1"
 	routeclientset "github.com/openshift/client-go/route/clientset/versioned/typed/route/v1"
 	userclientset "github.com/openshift/client-go/user/clientset/versioned/typed/user/v1"
+	KCorev1 "k8s.io/client-go/kubernetes/typed/core/v1"
```
Comment (kadel) [inline pkg/occlient/occlient.go]: Go package names should be lowercase one word. so `kcorev1` would be better.

You shouldn't need this import at all. See my comment in`WaitForDefaultServiceAccountInNamespace` function

File: pkg/occlient/occlient.go [hunk 5]
```diff
@@ -533,16 +541,50 @@ func (c *Client) CreateNewProject(projectName string, wait bool) error {
...
+					}
+				}
 			}
 		}
 	}
 
 	return nil
 }
 
+func (c *Client) WaitForDefaultServiceAccountInNamespace(namespace, serviceAccountName string) error {
```
Comment (kadel) [inline pkg/occlient/occlient.go]: The function name is a little bit confusing.  It is not waiting for default service account, but for the service account specified by `serviceAccountName` argument.

You can just call it `WaitForServiceAccount`. 
There should also be a  comment describing what is this function doing. like for example that it will block

File: pkg/occlient/occlient.go [hunk 6]
```diff
@@ -533,16 +541,50 @@ func (c *Client) CreateNewProject(projectName string, wait bool) error {
...
+	watcher, err := c.kubernetesCoreV1.ServiceAccounts(namespace).Watch(metav1.SingleObject(metav1.ObjectMeta{Name: serviceAccountName}))
+	if err != nil {
+		return err
+	}
+	defer watcher.Stop()
+
+	if watcher != nil {
+		for {
```
Comment (kadel) [inline pkg/occlient/occlient.go]: This could wait forever, no?
There probably should be a timeout.

Comment (mik-dass) [reply pkg/occlient/occlient.go]: Fixed

**Comment by mik-dass** [comment]
@kadel Fixed

**Comment by mik-dass** [comment]
```
2020/01/09 09:30:32 Build root succeeded after 2m49s
2020/01/09 09:30:33 Building src
2020/01/09 09:32:25 Build src succeeded after 1m52s
2020/01/09 09:32:25 No custom metadata found and prow metadata already exists. Not updating the metadata.
2020/01/09 09:32:28 Ran for 4m45s
2020/01/09 09:32:29 Submitted failure event to sentry (id=730b66c4d5764f17b5b2ad298ed6fc6b)
error: could not run steps: step [release:latest] failed: release "release-latest" failed: the pod ci-op-6p1psidw/release-latest failed after 49s (failed containers: release): ContainerFailed one or more containers exited
```
/retest

File: pkg/occlient/occlient.go [hunk 7]
```diff
@@ -533,16 +533,59 @@ func (c *Client) CreateNewProject(projectName string, wait bool) error {
...
+	if namespace == "" || serviceAccountName == "" {
+		return errors.New("namespace and serviceAccountName cannot be empty")
+	}
+	watcher, err := c.kubeClient.CoreV1().ServiceAccounts(namespace).Watch(metav1.SingleObject(metav1.ObjectMeta{Name: serviceAccountName}))
+	if err != nil {
+		return err
+	}
+	defer watcher.Stop()
+
+	timeout := time.After(1 * time.Minute)
```
Comment (girishramnani) [inline pkg/occlient/occlient.go]: can we make this timeout a constant at the top?

Comment (girishramnani) [reply pkg/occlient/occlient.go]: and please document this value in the `--help`

File: pkg/occlient/occlient.go [hunk 8]
```diff
@@ -533,16 +533,59 @@ func (c *Client) CreateNewProject(projectName string, wait bool) error {
...
+	if watcher != nil {
```
Comment (girishramnani) [inline pkg/occlient/occlient.go]: shouldn't this be above https://github.com/openshift/odo/pull/2330/files#diff-6025e9b620e9321c03c11bf29e5c4dbdR565
because else we are calling `Stop()` on a `nil` watcher?

Comment (girishramnani) [reply pkg/occlient/occlient.go]: or is this check even necessary?

**Comment by girishramnani** [comment]
@mik-dass please address the comments that I have added.

**Comment by mik-dass** [comment]
@girishramnani Fixed

**Comment by mik-dass** [comment]
```

    Expected
      
        <string>: ACTIVE     NAME
                   myproject
                   pjvfjaxjmh
                   urfctwhneu
        
    to contain substring
        <string>: ezbishpehz
```
The changes still don't fix the issue

**Comment by kadel** [comment]
@mik-dass what is the situation with this PR? Should we close this:

**Comment by mik-dass** [comment]
> @mik-dass what is the situation with this PR? Should we close this:

Let me push the latest changes

**Comment by mik-dass** [comment]
```
[odo]  ✓  Changes successfully pushed to component
Checking http://nodejs-app-8080-app-rnkocvqnrl.apps.ci-op-qi85281i-18180.origin-ci-int-aws.dev.rhcloud.com, for Hello nodejs UPDATED
try 0 of 90
Running curl with args [curl http://nodejs-app-8080-app-rnkocvqnrl.apps.ci-op-qi85281i-18180.origin-ci-int-aws.dev.rhcloud.com]
Deleting dir: /tmp/601832666/abcd
Replacing "Hello" with "Hello odo" in /tmp/601832666/server.js
[curl]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[curl]                                  Dload  Upload   Total   Spent    Left  Speed
[curl] 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    42    0    42    0     0    226      0 --:--:-- --:--:-- --:--:--   228
```
/retest
