### PR TITLE
Fixes odo watch when delay is set to 0

### LINKED ISSUE #3439: flag --delay 0 in watch command panic out
/kind bug

## What versions of software are you using?

**Operating System:**
supported
**Output of `odo version`:**
master
## How did you run odo exactly?
```
$ odo project create test123

$ oc --request-timeout 5m import-image nodejs --namespace=test123 --from=registry.access.redhat.com/rhscl/nodejs-10-rhel7:latest --confirm

$ oc annotate istag/nodejs:latest --namespace=test123 tags=builder --overwrite

$ odo create nodejs nodejs-app --project test123 --context tests/examples/source/nodejs/

$ odo push --context tests/examples/source/nodejs/

go to another terminal and run the watch command along with flag --delay 0

$ odo watch nodejs-app --context tests/examples/source/nodejs/ --delay 0
panic: non-positive interval for NewTicker

goroutine 1 [running]:
time.NewTicker(0x0, 0xc0006d4b40)
        /usr/local/Cellar/go/1.13.7/libexec/src/time/tick.go:23 +0x147
github.com/openshift/odo/pkg/watch.WatchAndPush(0xc000238f00, 0x2b3d5c0, 0xc0000d4008, 0xc0005f1c70, 0xa, 0xc0005f1c30, 0x3, 0xc0006d4b40, 0x48, 0xc0007bee60, ...)
        /Users/amit/go/src/github.com/openshift/odo/pkg/watch/watch.go:285 +0x48a
github.com/openshift/odo/pkg/odo/cli/component.(*WatchOptions).Run(0xc000182380, 0x0, 0x0)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/cli/component/watch.go:235 +0x22f
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x2b71080, 0xc000182380, 0xc000496500, 0xc0003941e0, 0x1, 0x5)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:31 +0x13c
github.com/openshift/odo/pkg/odo/cli/component.NewCmdWatch.func1(0xc000496500, 0xc0003941e0, 0x1, 0x5)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/cli/component/watch.go:276 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc000496500, 0xc000394190, 0x5, 0x5, 0xc000496500, 0xc000394190)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00044a500, 0x296ab78, 0xc0000b3980, 0x6)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:864
main.main()
        /Users/amit/go/src/github.com/openshift/odo/cmd/odo/odo.go:67 +0x32a
```

## Actual behavior
panic out

## Expected behavior
As per the UX it says with delay 0 should work with performance issue but it does not panic out.  
```
--delay int        Time in seconds between a detection of code change and push.delay=0 means changes will be pushed as soon as they are detected which can cause performance issues (default 1)
``

## Any logs, error output, etc?

### PR DESCRIPTION
**Pull request by mik-dass**
**What type of PR is this?**

/kind bug

**What does does this PR do / why we need it**:

Disables the watch ticker when delay is set to 0.

**Which issue(s) this PR fixes**:

Fixes #3439 

**PR acceptance criteria**:

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer**:

- Execute `odo watch --delay 0` on a odo component.

### CODE REVIEW

**Comment by girishramnani** [comment]
@mik-dass fixes https://github.com/openshift/odo/issues/3439

**Comment by mik-dass** [comment]
> @mik-dass fixes #3439

I missed it. Updated the description.

**Comment by dharmit** [comment]
When I set `--delay=0`, it pushes even when I have only opened some file in vim (made no changes whatsoever). I'm guessing it's considered as a change to the repo because opening a file in vim creates a `.swp` file.

Should this behaviour be addressed at some point (post v2, maybe?) to ignore `.swp` file by default?

**Comment by mik-dass** [comment]
> I'm guessing it's considered as a change to the repo because opening a file in vim creates a .swp file.

Yes this is the due to the .swp files created by vim.

> Should this behaviour be addressed at some point (post v2, maybe?) to ignore .swp file by default?

We already have the capabilities of detecting files to be ignored from the .odoignore/.gitignore file. There is even a flag in watch to filter out these files.

File: tests/helper/helper_generic.go [hunk 1]
```diff
@@ -147,8 +147,13 @@ func WatchNonRetCmdStdOut(cmdStr string, timeout time.Duration, check func(outpu
 	for {
 		select {
 		case <-timeoutCh:
+			if buf.String() != "" {
+				fmt.Println("Output from stdout:")
```
Comment (kadel) [inline tests/helper/helper_generic.go:151]: ❤️

**Comment by mik-dass** [comment]
/hold
The integration test for `--delay 0` is failing on the CI though locally and even on a slow network it is passing.

**Comment by mik-dass** [comment]
```
[odo]  ✗  Get https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/devfile.yaml: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
/retest

File: pkg/watch/watch.go [hunk 2]
```diff
@@ -281,10 +281,15 @@ func WatchAndPush(client *occlient.Client, out io.Writer, parameters WatchParame
 		parameters.StartChan <- true
 	}
 
+	var ticker *time.Ticker
 	delay := time.Duration(parameters.PushDiffDelay) * time.Second
-	ticker := time.NewTicker(delay)
+
+	// don't create a ticker if delay is 0 as it will trigger panic
```
Comment (cdrage) [inline pkg/watch/watch.go:287]: `Don't`

File: tests/integration/devfile/utils/utils.go [hunk 3]
```diff
@@ -379,6 +379,11 @@ func OdoWatch(odoV1Watch OdoV1Watch, odoV2Watch OdoV2Watch, project, context, fl
 		("odo watch " + flag + " --context " + context),
 		time.Duration(5)*time.Minute,
 		func(output string) bool {
+			// the test hangs up on the CI when the delay is set to 0
```
Comment (cdrage) [inline tests/integration/devfile/utils/utils.go:382]: `The`
