### PR TITLE
Reset index when force pushed

### LINKED ISSUE #3479: odo watch deletes all files
/kind bug

## What versions of software are you using?

**Operating System:**
MacOS 

**Output of `odo version`:**
built from source.
odo v1.2.3 (33a73e351)
 

## How did you run odo exactly?

I am using https://github.com/gorkem/odo-devfile/tree/master/python-example to do python debugging 

```sh
odo create
odo push --debug
## At this point, application is running and I can attach my debugger
odo watch
```
Modify `app.py` and observe that build fails with missing `requirements.txt`.
I have opened a terminal and noticed that other than the modified file all other files are 
deleted. Doing another `odo push` restores them.

### PR DESCRIPTION
**Pull request by gorkem**
**What type of PR is this?**

/kind bug

**What does does this PR do / why we need it**:
It resets the index for synced files to ensure that all files are synced when a pod is started/restarted or it is force pushed.

**Which issue(s) this PR fixes**:

Fixes #3479

**How to test changes / Special notes to the reviewer**:

Instructions are provided on #3479

### CODE REVIEW

File: pkg/sync/adapter.go [hunk 1]
```diff
@@ -76,6 +81,10 @@ func (a Adapter) SyncFiles(syncParameters common.SyncParameters) (isPushRequired
 			}
 		}
 
+		if isForcePush {
+			//reset the index
+			util.DeleteIndexFile(pushParameters.Path)
```
Comment (mik-dass) [inline pkg/sync/adapter.go:86]: please handle the returned error

File: pkg/sync/adapter.go [hunk 2]
```diff
@@ -45,16 +45,21 @@ func (a Adapter) SyncFiles(syncParameters common.SyncParameters) (isPushRequired
...
 	compInfo := syncParameters.CompInfo
 	globExps := util.GetAbsGlobExps(pushParameters.Path, pushParameters.IgnoredFiles)
+	isWatch := len(pushParameters.WatchFiles) > 0 || len(pushParameters.WatchDeletedFiles) > 0
 
 	// Sync source code to the component
 	// If syncing for the first time, sync the entire source directory
 	// If syncing to an already running component, sync the deltas
 	// If syncing from an odo watch process, skip this step, as we already have the list of changed and deleted files.
-	if !syncParameters.PodChanged && !pushParameters.ForceBuild && len(pushParameters.WatchFiles) == 0 && len(pushParameters.WatchDeletedFiles) == 0 {
+	if isWatch && !isForcePush {
```
Comment (mik-dass) [inline pkg/sync/adapter.go:58]: please update the comments above regarding force pushing with watch

**Comment by mik-dass** [comment]
Can we include a integration test for testing push against restarted pods?

File: pkg/sync/adapter.go [hunk 3]
```diff
@@ -88,35 +100,25 @@ func (a Adapter) SyncFiles(syncParameters common.SyncParameters) (isPushRequired
 			forceWrite = true
 		}
 
-		// If the component already exists, sync only the files that changed
-		if syncParameters.ComponentExists {
-			// apply the glob rules from the .gitignore/.odo file
-			// and ignore the files on which the rules apply and filter them out
-			filesChangedFiltered, filesDeletedFiltered := util.FilterIgnores(ret.FilesChanged, ret.FilesDeleted, absIgnoreRules)
+		// apply the glob rules from the .gitignore/.odo file
```
Comment (mik-dass) [inline pkg/sync/adapter.go:103]: `.odoignore`

Comment (girishramnani) [reply pkg/sync/adapter.go:103]: we will resolve this in a follow up PR, for now I am merging this.

Comment (girishramnani) [reply pkg/sync/adapter.go:103]: addressed this in this PR https://github.com/openshift/odo/pull/3614
if there is nothing else wrong them can you please lgtm @mik-dass ?

Comment (mik-dass) [reply pkg/sync/adapter.go:103]: :+1:
