### PR TITLE
Fixes project wait flag

### LINKED ISSUE #2117: Project create doesn't wait properly
https://travis-ci.com/openshift/odo/jobs/233964101#L2793

```
Running odo with args [odo project list]
[odo] ACTIVE     NAME
[odo] *          kdiadkbatt
[odo]            myproject
Running odo with args [odo project list]
[odo] ACTIVE     NAME
[odo]            kbcwtnzrez
[odo] *          kdiadkbatt
[odo]            myproject
```
I had applied a sleep operation of 1 sec in between the two list operations and the create was performed with `-w` flag

### PR DESCRIPTION
**Pull request by mik-dass**
fixes #2117 

How to test:
Check if the `odo project create <project-name> -w` works and it waits properly for the project to be ready.

### CODE REVIEW

File: tests/integration/cmd_project_test.go [hunk 1]
```diff
@@ -41,13 +41,12 @@ var _ = Describe("odo project command tests", func() {
...
 		It("should successfully execute list along with machine readable output", func() {
 			helper.CmdRunner("odo", "project", "list")
-			time.Sleep(1 * time.Second)
 			listOutput := helper.CmdShouldPass("odo", "project", "list")
 			Expect(listOutput).To(ContainSubstring(project))
 
 			// project deletion doesn't happen immediately, so we test subset of the string
 			listOutputJson := helper.CmdShouldPass("odo", "project", "list", "-o", "json")
-			Expect(listOutputJson).To(ContainSubstring(`{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"` + project + `","namespace":"` + project + `","creationTimestamp":null},"spec":{},"status":{"active":false}}`))
+			Expect(listOutputJson).To(ContainSubstring(`{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"` + project + `","namespace":"` + project + `","creationTimestamp":null},"spec":{},"status":{"active":true}}`))
```
Comment (amitkrout) [inline tests/integration/cmd_project_test.go]: In parallel run validating the projects status ```"status":{"active":true}}``` or ```"status":{"active":true}}``` could lead to a flaky behavior.  Instead of matching the full json can you match some major key value pair.

For now see how this is being done in one of our test cases - https://github.com/openshift/odo/blob/master/tests/integration/component.go#L197

File: tests/integration/cmd_project_test.go [hunk 2]
```diff
@@ -41,13 +41,12 @@ var _ = Describe("odo project command tests", func() {
 	Context("when running project command app parameter in directory that doesn't contain .odo config directory", func() {
 		It("should successfully execute list along with machine readable output", func() {
 			helper.CmdRunner("odo", "project", "list")
-			time.Sleep(1 * time.Second)
```
Comment (amitkrout) [inline tests/integration/cmd_project_test.go]: Cool!!!

Comment (amitkrout) [inline tests/integration/cmd_project_test.go]: Also remove ```helper.CmdRunner("odo", "project", "list")```. In the next line it is being duplicated.

**Comment by mik-dass** [comment]
```
✗  Waiting for component to start [4m]
[odo]  ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=mycomponent-myapp'
```
/retest

**Comment by mik-dass** [comment]
@amitkrout Done

File: tests/integration/cmd_project_test.go [hunk 3]
```diff
@@ -40,14 +40,12 @@ var _ = Describe("odo project command tests", func() {
...
 		It("should successfully execute list along with machine readable output", func() {
-			helper.CmdRunner("odo", "project", "list")
-			time.Sleep(1 * time.Second)
 			listOutput := helper.CmdShouldPass("odo", "project", "list")
 			Expect(listOutput).To(ContainSubstring(project))
 
 			// project deletion doesn't happen immediately, so we test subset of the string
 			listOutputJson := helper.CmdShouldPass("odo", "project", "list", "-o", "json")
-			Expect(listOutputJson).To(ContainSubstring(`{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"` + project + `","namespace":"` + project + `","creationTimestamp":null},"spec":{},"status":{"active":false}}`))
+			Expect(listOutputJson).To(ContainSubstring(`{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"` + project + `","namespace":"` + project + `","creationTimestamp":null},"spec":{},`))
```
Comment (cdrage) [inline tests/integration/cmd_project_test.go]: Shouldn't this be status: active? Why was it removed? This is obvious that the test is failing.. In this test scenario, you can modify the `beforeEach` to add `-w` to wait for the project to come up.

Comment (amitkrout) [reply tests/integration/cmd_project_test.go]: > Shouldn't this be status: active? Why was it removed? This is obvious that the test is failing..

@cdrage https://github.com/openshift/odo/pull/2221#discussion_r330991328

Think a case where you have more scenarios are running for example ```make test-integration``` then in two node you cannot be sure that the current scenario project is active throughout the scenario. May be in the same time some different project scenario is created and become active.

> In this test scenario, you can modify the beforeEach to add -w to wait for the project to come up

In the test script we have already made this behavior as default to avoid flakes. see - https://github.com/openshift/odo/blob/master/tests/helper/odo_utils.go#L79. The failure was happening due to the step ```CmdRunner(...)``` which does not wait for command output.

Comment (mik-dass) [reply tests/integration/cmd_project_test.go]: As @amitkrout pointed due to parallel tests we can't be sure of the activeness of the test throughout the scenario so I removed the status. @cdrage @kadel WDYT?

Comment (cdrage) [reply tests/integration/cmd_project_test.go]: Ah, but that defeats the whole purpose of the test though, to make sure that it's the active project.

Comment (amitkrout) [reply tests/integration/cmd_project_test.go]: yup, there is an option of sequential run. In a long run it would be hard to even manage ```get``` and ```set``` command in parallel run. @mik-dass Please do the change to run it on single node test.

For reference check - https://github.com/openshift/odo/tree/master/tests/integration/loginlogout.

**Comment by mik-dass** [comment]
@cdrage @amitkrout Done please have a look

**Comment by amitkrout** [comment]
> @cdrage @amitkrout Done please have a look

Looks good to me.

**Comment by mik-dass** [comment]
```
[oc] Error in configuration: 
[oc] * context was not found for specified context: yfkoarskib/api-ci-op-r1xy5kvm-1b2f4-origin-ci-int-aws-dev-rhcloud-com:6443/developer
[oc] * cluster has no server defined
```
/retest
