### PR TITLE
Avoid racing condition between set and unset KUBECONFIG

### LINKED ISSUE #3032: Race condition causes failure in devfile watch test parallel run
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**
master
## Any logs, error output, etc?
```
------------------------------
Created dir: /tmp/952158957
Deleting project: qygbrftitg
Running kubectl with args [kubectl delete namespaces qygbrftitg]
[kubectl] Error from server (Conflict): Operation cannot be fulfilled on namespaces "qygbrftitg": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
• Failure in Spec Setup (BeforeEach) [0.304 seconds]
odo devfile watch command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:14
  when executing watch without pushing a devfile component [BeforeEach]
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:62
    should fail
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:63
    Unexpected error:
        <*os.PathError | 0xc0002230b0>: {Op: "stat", Path: "", Err: 0x2}
        stat : no such file or directory
    occurred
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:28
```

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind bug

**What does does this PR do / why we need it**:

Avoid racing condition between set and unset KUBECONFIG while running test in parallel.

**Which issue(s) this PR fixes**:

Fixes #3032 

**How to test changes / Special notes to the reviewer**:

```make test-cmd-devfile-watch``` should pass on kubernetes cluster

### CODE REVIEW

**Comment by prietyc123** [comment]
Thanks @amitkrout for the input.

File: tests/integration/devfile/cmd_devfile_catalog_test.go [hunk 1]
```diff
@@ -22,9 +22,8 @@ var _ = Describe("odo devfile catalog command tests", func() {
 		os.Setenv("GLOBALODOCONFIG", filepath.Join(context, "config.yaml"))
 		helper.CmdShouldPass("odo", "preference", "set", "Experimental", "true")
 		if os.Getenv("KUBERNETES") == "true" {
-			info, err := os.Stat(os.Getenv("KUBECONFIG"))
-			Expect(err).NotTo(HaveOccurred())
-			kubeConfigFile := helper.CopyKubeConfigFile(os.Getenv("KUBECONFIG"), filepath.Join(context, "config"), info)
+			homeDir, _ := os.UserHomeDir()
```
Comment (mik-dass) [inline tests/integration/devfile/cmd_devfile_catalog_test.go:25]: please handle the error here

File: tests/integration/devfile/cmd_devfile_watch_test.go [hunk 2]
```diff
@@ -24,9 +24,8 @@ var _ = Describe("odo devfile watch command tests", func() {
 		context = helper.CreateNewContext()
 		os.Setenv("GLOBALODOCONFIG", filepath.Join(context, "config.yaml"))
 		if os.Getenv("KUBERNETES") == "true" {
-			info, err := os.Stat(os.Getenv("KUBECONFIG"))
-			Expect(err).NotTo(HaveOccurred())
-			kubeConfigFile := helper.CopyKubeConfigFile(os.Getenv("KUBECONFIG"), filepath.Join(context, "config"), info)
+			homeDir, _ := os.UserHomeDir()
```
Comment (mik-dass) [inline tests/integration/devfile/cmd_devfile_watch_test.go:27]: same as https://github.com/openshift/odo/pull/3040/files#r417108839

**Comment by mik-dass** [comment]
```
2020/04/29 07:31:01 Build root succeeded after 1m40s
2020/04/29 07:31:01 Building src
2020/04/29 07:32:27 Build src succeeded after 1m25s
2020/04/29 07:32:27 Acquiring lease for "aws-quota-slice"
2020/04/29 07:32:27 Acquired lease "b5fe26a8-682c-4d3f-86c3-f6fbe610b1a3" for "aws-quota-slice"
2020/04/29 07:32:27 Executing template integration-e2e-benchmark
2020/04/29 07:32:27 Creating or restarting template instance
2020/04/29 07:32:27 Template instance integration-e2e-benchmark already deleted, do not need to wait any longer
```
/retest

File: tests/integration/devfile/cmd_devfile_catalog_test.go (hunk 1 above)
Comment (prietyc123) [reply tests/integration/devfile/cmd_devfile_catalog_test.go]: Done

**Comment by amitkrout** [comment]
Change works fine, hence travis job is passing. Ideally Openshift CI won't be affected by this change. So applying lgtm label. Thanks @prietyc123 
/lgtm
