### PR TITLE
Watch command should better handle file synchronization/error reporting when push command is invoked before/after the watch

### LINKED ISSUE #3371: On windows platform teardown steps fails to delete context because files are still in use
/kind bug

## What versions of software are you using?

**Operating System:**
Win10

**Output of `odo version`:**
master

## How did you run odo exactly?

Running `make test-cmd-devfile-watch` on windows powershell terminal.

## Actual behavior

```
> make test-cmd-devfile-watch
ginkgo  -randomizeAllSpecs -slowSpecThreshold=120 -timeout 7200s -nodes=1 -focus="odo devfile watch command tests" tests/integration/devfile/
Running Suite: Devfile Suite
============================
Random Seed: 1592388378 - Will randomize all specs
Will run 6 of 60 specs
SSSSSSSSSS+SSS+SSSSSSSSSSSSSSSSSSSSSSSS+SSSSS+SSSSSSSSRunning command:  [odo watch  --context C:\Users\Admin\AppData\Local\Temp\647821543]
Created dir: C:\Users\Admin\AppData\Local\Temp\647821543
Setting KUBECONFIG=C:\Users\Admin\AppData\Local\Temp\647821543\config
Creating a new project: dzqnphrivh
Running odo.exe with args [odo project create dzqnphrivh -w -v4]
[odo]  -  Waiting for project to come up  ...
[odo] I0617 10:06:37.483866    7540 occlient.go:543] Status of creation of project dzqnphrivh is Active
[...]
[odo]  V  Project 'dzqnphrivh' is ready for use
[odo]  V  New project created and now using project: dzqnphrivh
[odo] I0617 10:06:37.562831    7540 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
Current working dir: C:\Users\Admin\go\src\github.com\openshift\odo\tests\integration\devfile
Setting current dir to: C:\Users\Admin\AppData\Local\Temp\647821543
Running odo.exe with args [odo preference set Experimental true]
[odo] I0617 10:06:37.670415    2920 preference.go:188] The path for preference file is C:\Users\Admin\AppData\Local\Temp\647821543\config.yaml
[odo] Global preference was successfully updated
[...]
Running odo.exe with args [odo create nodejs --project dzqnphrivh lkvpwi]
[odo] I0617 10:06:37.838760   11028 preference.go:188] The path for preference file is C:\Users\Admin\AppData\Local\Temp\647821543\config.yaml
[odo] Experimental mode is enabled, use at your own risk
[odo]
[odo] I0617 10:06:37.880608   11028 util.go:399] path ./.odo/config.yaml doesn't exist, skipping it
[odo] I0617 10:06:37.880608   11028 preference.go:188] The path for preference file is C:\Users\Admin\AppData\Local\Temp\647821543\config.yaml
[odo] I0617 10:06:37.883330   11028 preference.go:188] The path for preference file is C:\Users\Admin\AppData\Local\Temp\647821543\config.yaml
[odo] I0617 10:06:39.471178   11028 util.go:399] path devfile.yaml doesn't exist, skipping it
[odo] I0617 10:06:39.471178   11028 preference.go:188] The path for preference file is C:\Users\Admin\AppData\Local\Temp\647821543\config.yaml
[odo] I0617 10:06:39.471178   11028 util.go:399] path devfile.yaml doesn't exist, skipping it
[odo] Validation
[odo]  -  Checking devfile compatibility  ...
[odo]  -  Creating a devfile component from registry: DefaultDevfileRegistry  ...
I0617 10:06:39.471178   11028 preference.go:188] The path for preference file is C:\Users\Admin\AppData\Local\Temp\647821543\config.yaml
 V  Checking devfile compatibility [0ns]
 V  Creating a devfile component from registry: DefaultDevfileRegistry [0ns]
[odo]  -  Validating devfile component  ...
[odo] I0617 10:06:39.472269   11028 util.go:399] path .odo\env\env.yaml doesn't exist, skipping it
[odo] I0617 10:06:39.472269   11028 preference.go:188] The path for preference file is C:\Users\Admin\AppData\Local\Temp\647821543\config.yaml
 V  Validating devfile component [1ms]
[odo] I0617 10:06:39.472269   11028 preference.go:188] The path for preference file is C:\Users\Admin\AppData\Local\Temp\647821543\config.yaml
[odo] I0617 10:06:39.472269   11028 util.go:399] path devfile.yaml doesn't exist, skipping it
[odo]
[odo] Please use `odo push` command to create the component with source deployed
[odo] I0617 10:06:39.542637   11028 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
Running odo.exe with args [odo push --devfile devfile.yaml --project dzqnphrivh]
[odo] I0617 10:06:39.677232    5916 preference.go:188] The path for preference file is C:\Users\Admin\AppData\Local\Temp\647821543\config.yaml
[odo] I0617 10:06:39.720051    5916 preference.go:188] The path for preference file is C:\Users\Admin\AppData\Local\Temp\647821543\config.yaml
[...]
[odo]  V  Changes successfully pushed to component
[odo] I0617 10:06:50.421320    5916 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
Deleting dir: C:\Users\Admin\AppData\Local\Temp\647821543\abcd
Replacing "Hello" with "Hello odo" in C:\Users\Admin\AppData\Local\Temp\647821543\app\app.js
Running oc.exe with args [oc get pods --namespace dzqnphrivh --show-labels]
[oc] NAME                     READY   STATUS    RESTARTS   AGE   LABELS
[oc] lkvpwi-576f7f6dc-p4h9m   1/1     Running   0          31s   component=lkvpwi,pod-template-hash=576f7f6dc
Running oc.exe with args [oc exec lkvpwi-576f7f6dc-p4h9m --namespace dzqnphrivh -- ls -lai /projects/nodejs-web-app]
[oc] total 44
[oc] 281176798 drwxrwsrwx.  6 1000910000 1000910000   190 Jun 17 10:07 .
[oc] 188767190 drwxrwsrwx.  3 root       1000910000    28 Jun 17 10:06 ..
[oc] 140611490 drwxrwsrwx.  2 1000910000 1000910000     6 Jun 17 10:07 .abc
[oc] 281176799 -rw-rw-rw-.  1 1000910000 1000910000    25 Jun 17 10:06 .gitignore
[oc] 283235153 drwxrwsrwx.  3 1000910000 1000910000    44 Jun 17 10:06 .odo
[oc] 281176809 -rw-rw-rw-.  1 1000910000 1000910000     0 Jun 17 10:07 a.txt
[oc] 287485128 drwxrwsrwx.  2 1000910000 1000910000    20 Jun 17 10:07 app
[oc] 281176800 -rw-rw-rw-.  1 1000910000 1000910000  5369 Jun 17 10:06 config
[oc] 281176801 -rw-rw-rw-.  1 1000910000 1000910000    80 Jun 17 10:06 config.yaml
[oc] 281176802 -rw-rw-rw-.  1 1000910000 1000910000  1162 Jun 17 10:06 devfile.yaml
[oc] 310393695 drwxrwsrwx. 52 1000910000 1000910000  4096 Jun 17 10:06 node_modules
[oc] 281176808 -rw-rw-rw-.  1 1000910000 1000910000 14663 Jun 17 10:06 package-lock.json
[oc] 281176803 -rw-rw-rw-.  1 1000910000 1000910000   279 Jun 17 10:06 package.json
Deleting project: dzqnphrivh
Running odo.exe with args [odo project delete dzqnphrivh -f]
[odo] I0617 10:07:12.157937    9372 application.go:49] Unable to list Service Catalog instances: unable to list ServiceInstances: the server could not find 
the requested resource (get serviceinstances.servicecatalog.k8s.io)
[odo]  !  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project 
may still exist on a different node.
[odo] I0617 10:07:12.231407    9372 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
[odo]  V  Deleted project : dzqnphrivh
Setting current dir to: C:\Users\Admin\go\src\github.com\openshift\odo\tests\integration\devfile
Deleting dir: C:\Users\Admin\AppData\Local\Temp\647821543
------------------------------
+ Failure in Spec Teardown (AfterEach) [36.450 seconds]
odo devfile watch command tests
C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:15
  when executing odo watch after odo push [AfterEach]
  C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:83
    should listen for file changes
    C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:84
    Unexpected error:
        <*os.PathError | 0xc000405860>: {
            Op: "remove",
            Path: "C:\\Users\\Admin\\AppData\\Local\\Temp\\647821543\\a.txt",
            Err: 0x20,
        }
        remove C:\Users\Admin\AppData\Local\Temp\647821543\a.txt: The process cannot access the file because it is being used by another process.
    occurred
    C:/Users/Admin/go/src/github.com/openshift/odo/tests/helper/helper_filesystem.go:28
```

## Expected behavior

Running [devfile watch file](https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_watch_test.go#L82) on windows but [teardown step](https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_watch_test.go#L46) throws error due to file is being used by another process .

### LINKED ISSUE #3435: odo watch does not tell me the err on devfile validation failure
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:** master

## How did you run odo exactly?
`odo watch` but I had two default commands. It errors out but doesn't tell me what the error is and if I am newbie I wouldn't be able to figure out what the issue was

## Any logs, error output, etc?
```
$ odo watch
Waiting for something to change in /Users/maysun/dev/redhat/resources/springboot-ex
File /Users/maysun/dev/redhat/resources/springboot-ex/src/main/java/application/rest/v1/Example.java changed
Pushing files...

Validation
 ✗  Validating the devfile [54323ns]
Waiting for something to change in /Users/maysun/dev/redhat/resources/springboot-ex
File /Users/maysun/dev/redhat/resources/springboot-ex/src/main/java/application/rest/v1/Example.java changed
Pushing files...

Validation
 ✗  Validating the devfile [61381ns]
Waiting for something to change in /Users/maysun/dev/redhat/resources/springboot-ex
```

### LINKED ISSUE #3540: test-cmd-devfile-log teardown steps throws error while accessing projectDir on windows platform
/kind bug

## What versions of software are you using?

**Operating System:**
Win10

**Output of `odo version`:**
master

## How did you run odo exactly?

Run `make test-cmd-devfile-log` on windows

## Actual behavior

```
> make test-cmd-devfile-log
Running Suite: Devfile Suite
============================
Random Seed: 1594377900
Will run 1 of 95 specs

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSCreated dir: C:\Users\Admin\AppData\Local\Temp\203208851
Running odo.exe with args [odo preference set Experimental true]
[odo] Global preference was successfully updated
Setting KUBECONFIG=C:\Users\Admin\AppData\Local\Temp\203208851\config
Creating a new project: ebxzlgtift
Running odo.exe with args [odo project create ebxzlgtift -w -v4]
[odo]  -  Waiting for project to come up  ...
[odo] I0710 10:45:13.247354   10808 occlient.go:542] Status of creation of project ebxzlgtift is Active
[odo] I0710 10:45:13.301183   10808 occlient.go:547] Project ebxzlgtift now exists
[odo] I0710 10:45:13.303540   10808 occlient.go:582] Status of creation of service account &ServiceAccount{ObjectMeta:{default  ebxzlgtift /api/v1/namespaces/ebxzlgtift/serviceaccounts/default a31009da-c299-11ea-a594-fa163e9b6334 19441694 0 2020-07-10 10:39:30 +0000 GMT <nil> <nil> map[] map[] [] []  []},Secrets:[]ObjectReference{ObjectReference{Kind:,Namespace:,Name:default-token-qr8sk,UID:,APIVersion:,ResourceVersion:,FieldPath:,},ObjectReference{Kind:,Namespace:,Name:default-dockercfg-jj7xv,UID:,APIVersion:,ResourceVersion:,FieldPath:,},},ImagePullSecrets:[]LocalObjectReference{LocalObjectReference{Name:default-dockercfg-jj7xv,},},AutomountServiceAccountToken:nil,} is ready
 V  Waiting for project to come up [998ms]
[odo]  V  Project 'ebxzlgtift' is ready for use
[odo]  V  New project created and now using project: ebxzlgtift
[odo] I0710 10:45:13.331457   10808 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
Current working dir: C:\Users\Admin\go\src\github.com\openshift\odo\tests\integration\devfile
Setting current dir to: C:\Users\Admin\AppData\Local\Temp\203208851
Setting current dir to: C:\Users\Admin\AppData\Local\Temp\203208851/projectDir
Running odo.exe with args [odo create nodejs --project ebxzlgtift fjkkqn]
[odo] Experimental mode is enabled, use at your own risk
[odo]
[odo] Validation
 V  Checking devfile existence [0ns]
 V  Checking devfile compatibility [337900ns]
 V  Creating a devfile component from registry: DefaultDevfileRegistry [337900ns]
 V  Validating devfile component [1ms]
[odo]
[odo] Please use `odo push` command to create the component with source deployed
Running odo.exe with args [odo push --project ebxzlgtift]
[odo]
[odo] Validation
 V  Validating the devfile [0ns]
[odo]
[odo] Creating Kubernetes resources for component fjkkqn
 V  Waiting for component to start [6s]
[odo]
[odo] Applying URL changes
[odo]  V  URLs are synced with the cluster, no changes are required.
[odo]
[odo] Syncing to component fjkkqn
 V  Checking files for pushing [19ms]
 V  Syncing files to the component [213ms]
[odo]
[odo] Executing devfile commands for component fjkkqn
 V  Executing install command "npm install" [2s]
 V  Executing run command "npm start" [1s]
[odo]
[odo] Pushing devfile component fjkkqn
[odo]  V  Changes successfully pushed to component
Running odo.exe with args [odo log]
[odo] time="2020-07-10T10:40:02Z" level=info msg="create process:devrun"
[odo] time="2020-07-10T10:40:02Z" level=info msg="create process:debugrun"
[odo] time="2020-07-10T10:40:05Z" level=debug msg="no auth required"
[odo] time="2020-07-10T10:40:05Z" level=info msg="stop the program" program=debugrun
[odo] time="2020-07-10T10:40:05Z" level=info msg="stop the program" program=devrun
[odo] time="2020-07-10T10:40:05Z" level=info msg="force to kill the program" program=debugrun
[odo] time="2020-07-10T10:40:05Z" level=info msg="force to kill the program" program=devrun
[odo] time="2020-07-10T10:40:05Z" level=debug msg="no auth required"
[odo] time="2020-07-10T10:40:05Z" level=debug msg="succeed to find process:devrun"
[odo] time="2020-07-10T10:40:05Z" level=info msg="try to start program" program=devrun
[odo] time="2020-07-10T10:40:05Z" level=info msg="success to start program" program=devrun
[odo] ODO_COMMAND_RUN is npm start
[odo] Changing directory to ${CHE_PROJECTS_ROOT}/nodejs-starter
[odo] Executing command cd ${CHE_PROJECTS_ROOT}/nodejs-starter && npm start
[odo] > nodejs-starter@1.0.0 start /projects/nodejs-starter
[odo] > node server.js
[odo] App started on PORT 3000
[odo] time="2020-07-10T10:40:06Z" level=debug msg="wait program exit" program=devrun
Running odo.exe with args [odo log -f]
[odo] time="2020-07-10T10:40:06Z" level=debug msg="wait program exit" program=devrun
Deleting project: ebxzlgtift
Running odo.exe with args [odo project delete ebxzlgtift -f]
[odo]  V  Deleted project : ebxzlgtift
[odo]  !  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project 
may still exist on a different node.
Setting current dir to: C:\Users\Admin\go\src\github.com\openshift\odo\tests\integration\devfile
Deleting dir: C:\Users\Admin\AppData\Local\Temp\203208851

------------------------------
+ Failure in Spec Teardown (AfterEach) [13.654 seconds]
odo devfile log command tests
C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_log_test.go:14
  Verify odo log for devfile works [AfterEach]
  C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_log_test.go:49
    should log run command output
    C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_log_test.go:55

    Unexpected error:
        <*os.PathError | 0xc000074270>: {
            Op: "remove",
            Path: "C:\\Users\\Admin\\AppData\\Local\\Temp\\203208851\\projectDir",
            Err: 0x20,
        }
        remove C:\Users\Admin\AppData\Local\Temp\203208851\projectDir: The process cannot access the file because it is being used by another process.
    occurred

    C:/Users/Admin/go/src/github.com/openshift/odo/tests/helper/helper_filesystem.go:28
SSSSSSSSSSSSSSS

Summarizing 1 Failure:

[Fail] odo devfile log command tests [AfterEach] Verify odo log for devfile works should log run command output 
C:/Users/Admin/go/src/github.com/openshift/odo/tests/helper/helper_filesystem.go:28
```

## Expected behavior

We should handle the `C:\Users\Admin\AppData\Local\Temp\203208851\projectDir` smartly in the spec. As it is expected behaviour on windows.

### LINKED ISSUE #3585: Watch command should better handle file synchronization when push command is invoked before/after the watch
The current behaviour of the watch command assumes that the state of the filesystem is synchronized with the state of the pod. This assumption is not correct, as this may not be true in all cases (depending on user behaviour and when push was invoked).

Likewise, the current behaviour of the push command assumes that the index data under `.odo` is synchronized with the state of the pod. This may not be the case if the watch command is bypassing the index data update logic.

### Scenario A - On launch, `odo watch` assumes that the current filesystem is synchronized to the pod:
1) odo push a generic project
2) Change some source file A
3) odo watch that project
4) Change some other source file B

After step 4's `odo watch` push operation completes:
- Expected behaviour: The k8s pod _should_ include the change made in step 2
- Actual behaviour: The k8s pod _does not_ include the change made in step 2

### Scenario B - `odo watch` doesn't update index data
1) odo push a generic project
2) Start watch command
3) Update some source file A and wait for deploy
4) Terminate watch command
5) odo push the project

- Expected behaviour: Source file A is not synchronized to the pod, because it has not been updated since step 3.
- Actual behaviour: Source file A _is_ synchronized to the pod, because the index file still represents the old version of the file. (Note: this is our expected actual behaviour, I need to verify this is true.)

Related issues/PRs:
https://github.com/openshift/odo/issues/3345
https://github.com/openshift/odo/pull/3536

/kind bug

### PR DESCRIPTION
**Pull request by jgwest**
**What type of PR is this?**
> /kind bug

**What does this PR do / why we need it**:
- Fix the `odo watch` logic such that if you edit a devfile after watch has started, the changes to the devfile will now be picked up.
- Fix the `odo watch` logic such that it now updates the `.odo/odo-file-index.json` file, allowing it to play well with `odo push` if push is called immediately after watch
- Fix the `odo watch` logic to regenerate and use the file index to detect changes when `odo watch` is first invoked (in a particular session), with all subsequent updates during the session using the watched file list for changes
- Adds integration tests that test the behaviours that were failing in the linked issues
- Adds directory delete retry, with exponential backoff, to the `DeleteDir` test utility function, to fix Windows-issues seen by myself and others

**Which issue(s) this PR fixes**:
Fixes #3435
Fixes #3585

Windows test fixes:
Fixes #3371
Fixes #3540

**PR acceptance criteria**:

- [ ] Unit test 

- [X] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer**:

To test #3435:
- Create and push a generic odo project
- Run `odo watch`
- Make a change that invalidates the devfile (for example, replace all instances of `"kind: build"` with `"kind: run"` in the file)
- `odo watch` will now report the same error as `odo push` would, against that devfile

To test #3585:
- Create and `odo push` a generic project
- Change some source file A
- `odo watch` that project
- Change some other source file B
- The k8s pod should include the both changes (source file A and B), and the index file (`.odo/odo-file-index.json`) should include both files
(See #3585 for another scenario you can test, if desired)

### CODE REVIEW

**Comment by prietyc123** [comment]
@jgwest Can you please add issue #3540 also in the description of the pr.

**Comment by prietyc123** [comment]
@jgwest PR needs rebase

File: tests/integration/devfile/cmd_devfile_watch_test.go [hunk 1]
```diff
@@ -103,6 +109,68 @@ var _ = Describe("odo devfile watch command tests", func() {
...
+			helper.CmdShouldPass("odo", "create", "nodejs", "--project", namespace, cmpName)
+
+			helper.CopyExample(filepath.Join("source", "devfiles", "nodejs", "project"), context)
+			helper.CopyExampleDevFile(filepath.Join("source", "devfiles", "nodejs", "devfile.yaml"), filepath.Join(context, "devfile.yaml"))
+
+			output := helper.CmdShouldPass("odo", "push", "--project", namespace)
+			Expect(output).To(ContainSubstring("Changes successfully pushed to component"))
+
+			session := helper.CmdRunner("odo", "watch", "--context", context)
+			defer session.Kill()
```
Comment (johnmcollier) [inline tests/integration/devfile/cmd_devfile_watch_test.go:123]: Do we need the `dever session.Kill()` here if we're calling `session.Kill()` down below?

File: tests/integration/devfile/cmd_devfile_watch_test.go [hunk 2]
```diff
@@ -103,6 +109,68 @@ var _ = Describe("odo devfile watch command tests", func() {
...
+			// 1) Push a generic project
+			output := helper.CmdShouldPass("odo", "push", "--project", namespace)
+			Expect(output).To(ContainSubstring("Changes successfully pushed to component"))
+
+			// 2) Create a new file A
+			fileAPath, fileAText := createSimpleFile(context)
+
+			// 3) Odo watch that project
+			session := helper.CmdRunner("odo", "watch", "--context", context)
+			defer session.Kill()
```
Comment (johnmcollier) [inline tests/integration/devfile/cmd_devfile_watch_test.go:154]: Do we need the `dever session.Kill()` here if we're calling `session.Kill()` down below?

File: pkg/odo/cli/component/watch.go [hunk 3]
```diff
@@ -292,3 +298,38 @@ func NewCmdWatch(name, fullName string) *cobra.Command {
...
 }
+
+// regenerateAdapterAndPush is used as a DevfileWatchHandler in WatchParameters; it is a wrapper around adapter.Push()
+// that first regenerates the component adapter before calling push. This ensures that it has picked up the latest
+// devfile.yaml changes
+func regenerateAdapterAndPush(pushParams common.PushParameters, watchParams watch.WatchParameters) error {
+	var adapter common.ComponentAdapter
+	adapter, err := regenerateComponentAdapterFromWatchParams(watchParams)
+	if err == nil {
+		err = adapter.Push(pushParams)
```
Comment (johnmcollier) [inline pkg/odo/cli/component/watch.go:309]: Could we check for an error and if present, wrap the error with a message?

File: pkg/watch/watch.go [hunk 4]
```diff
@@ -48,7 +53,9 @@ type WatchParameters struct {
 	// DevfileBuildCmd takes the build command through the command line and overwrites devfile build command
 	DevfileBuildCmd string
 	// DevfileRunCmd takes the run command through the command line and overwrites devfile run command
-	DevfileRunCmd string
+	DevfileRunCmd    string
```
Comment (johnmcollier) [inline pkg/watch/watch.go:56]: Thinking aloud here...

Could we make `regenerateAdapterAndPush` and `regenerateComponentAdapterFromWatchParams` methods on the `WatchOptions` type? Then I don't think we'd need to add `DevfileRunCmd`, `DevfilePath` and `DevfileNamespace` to the WatchParameters struct, no?

File: pkg/odo/cli/component/watch.go [hunk 5]
```diff
@@ -292,3 +298,38 @@ func NewCmdWatch(name, fullName string) *cobra.Command {
...
+	return err
+}
+
+// regenerateComponentAdapterFromWatchParams (re)generates a component adapter from the given watch parameters.
+func regenerateComponentAdapterFromWatchParams(parameters watch.WatchParameters) (common.ComponentAdapter, error) {
+
+	// Parse devfile and validate
+	devObj, err := devfile.ParseAndValidate(parameters.DevfilePath)
+	if err != nil {
+		return nil, err
```
Comment (johnmcollier) [inline pkg/odo/cli/component/watch.go:321]: Should we wrap this error with a message?

File: pkg/sync/adapter.go [hunk 6]
```diff
@@ -235,6 +265,65 @@ func getSyncFolder(projects []versionsCommon.DevfileProject) (string, error) {
 
 }
 
+// updateIndexWithWatchChanges uses the pushParameters.WatchDeletedFiles and pushParamters.WatchFiles to update
+// the existing index file; the index file is required to exist when this function is called.
+func updateIndexWithWatchChanges(pushParameters common.PushParameters) error {
```
Comment (johnmcollier) [inline pkg/sync/adapter.go:270]: Could you add unit tests for this function if possible?

File: pkg/util/file_indexer.go [hunk 7]
```diff
@@ -247,6 +244,39 @@ func RunIndexer(directory string, ignoreRules []string) (ret IndexerRet, err err
 	return ret, nil
 }
 
+// CalculateFileDataKeyFromPath converts an absolute path to relative (and converts to OS-specific paths) for use
+// as a map key in IndexerRet and FileIndex
+func CalculateFileDataKeyFromPath(absolutePath string, rootDirectory string) (string, error) {
```
Comment (johnmcollier) [inline pkg/util/file_indexer.go:249]: Unit tests for `CalculateFileDataKeyFromPath` and `GenerateNewFileDataEntry`?

File: pkg/odo/cli/component/watch.go [hunk 8]
```diff
@@ -292,3 +298,38 @@ func NewCmdWatch(name, fullName string) *cobra.Command {
 
 	return watchCmd
 }
+
+// regenerateAdapterAndPush is used as a DevfileWatchHandler in WatchParameters; it is a wrapper around adapter.Push()
+// that first regenerates the component adapter before calling push. This ensures that it has picked up the latest
+// devfile.yaml changes
+func regenerateAdapterAndPush(pushParams common.PushParameters, watchParams watch.WatchParameters) error {
```
[the remark this answers is not in the document]
Comment (jgwest) [reply pkg/odo/cli/component/watch.go:305]: Done.

File: tests/integration/devfile/cmd_devfile_watch_test.go (hunk 1 above)
Comment (jgwest) [reply tests/integration/devfile/cmd_devfile_watch_test.go:122]: We don't need the session kill below, I've removed it in the appropriate spots.

File: tests/integration/devfile/cmd_devfile_watch_test.go (hunk 2 above)
Comment (jgwest) [reply tests/integration/devfile/cmd_devfile_watch_test.go:149]: Done.

File: pkg/odo/cli/component/watch.go (hunk 3 above)
Comment (jgwest) [reply pkg/odo/cli/component/watch.go]: Done.

File: pkg/odo/cli/component/watch.go (hunk 5 above)
Comment (jgwest) [reply pkg/odo/cli/component/watch.go]: Done.

File: pkg/sync/adapter.go (hunk 6 above)
Comment (jgwest) [reply pkg/sync/adapter.go:270]: Done.

File: pkg/util/file_indexer.go (hunk 7 above)
Comment (jgwest) [reply pkg/util/file_indexer.go:249]: Done.

File: pkg/watch/watch.go (hunk 4 above)
Comment (jgwest) [reply pkg/watch/watch.go]: Yep, that works, done.

**Comment by dharmit** [comment]
> To test #3435:
> 
>     * Create and push a generic odo project
> 
>     * Run `odo watch`
> 
>     * Make a change that invalidates the devfile (for example, replace all instances of `"kind: build"` with `"kind: run"` in the file)
> 
>     * `odo watch` will now report the same error as `odo push` would, against that devfile

I tried above steps for the project https://github.com/akashshinde/node-todo with this devfile:
<details>

```yaml
schemaVersion: 2.0.0                                                                                                                                                                          
metadata:                                                                                                                                                                                     
  name: nodejs                                                                                                                                                                                
  version: 1.0.0                                                                                                                                                                              
  alpha.build-dockerfile: "https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/build/Dockerfile"                                                                   
  alpha.deployment-manifest: "https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/deploy/deployment-manifest.yaml"
projects:                                      
  - name: nodejs-starter
    git:                                       
      location: "https://github.com/odo-devfiles/nodejs-ex.git"                                
components:                                    
  - container:                                 
      name: runtime                            
      image: registry.access.redhat.com/ubi8/nodejs-12:1-45                                    
      memoryLimit: 1024Mi
      mountSources: true
      sourceMapping: /project
      endpoints:                               
        - name: http-8080
          targetPort: 8080
commands:                                      
  - exec:                                      
      id: install                              
      component: runtime
      commandLine: npm install
      workingDir: /project
      group:                                   
        kind: build                            
        isDefault: true
  - exec:                                      
      id: run                                  
      component: runtime
      commandLine: npm start
      workingDir: /project
      group:                                   
        kind: run                              
        isDefault: true
  - exec:
      id: debug
      component: runtime
      commandLine: npm run debug
      workingDir: /project
      group:
        kind: debug
        isDefault: true
  - exec:
      id: test
      component: runtime
      commandLine: npm test
      workingDir: /project
      group:
        kind: test
        isDefault: true
```

</details>

I modified `kind: build` to `kind: run` and it rightly failed because it found both `kind: run` to be set `isDefault:true`. Then I undid that change to make it a valid devfile once again. All the time, `odo watch` has been running in a different terminal.

What I'm observing is that `odo watch` has gone into an infinite loop of pushing because it detects that there's change in `.odo/odo-file-index.json`. I have not made any changes beyond what I mentioned above. I'm trying on the latest CRC box. Is this behaviour expected? Am I doing something wrong?

**Comment by johnmcollier** [comment]
@jgwest Can you rebase?

@dharmit I'm not able to reproduce with your steps on Jonathan's branch. Can you share the .gitignore file? Odo should've added .odo/odo-file-index.json to it, right?
