### PR TITLE
Separate out openshift specific tests

### LINKED ISSUE #4577: Separate out tests to avoid running s2i command on minikube
/kind failing-test

## What versions of software are you using?

**Operating System:**
fedora 32

**Output of `odo version`:**
master

## How did you run odo exactly?

Running test on kubernetes cluster fedora vm

## Actual behavior

```
$ kubectl create namespace blah
namespace/blah created

$ kubectl config set-context --current --namespace blah
Context "minikube" modified.

$ odo create nodejs
Devfile Object Validation
 ✓  Creating a devfile component from devfile path: /Users/pkumari/go/src/github.com/openshift/odo/testim/devfile.yaml [80871ns]
Validation
 ✓  Validating if devfile name is correct [42845ns]

Please use `odo push` command to create the component with source deployed

$ odo create nodejs
 ✗  this directory already contains a component

$ odo create nodejs --s2i
 ✗  unable to list imagestreams: the server could not find the requested resource (get imagestreams.image.openshift.io).
unable to list imagestreams: the server could not find the requested resource (get imagestreams.image.openshift.io)
```
Tests failing on https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_create_test.go#L195

Console log:
```
[ssh:Fedora 32] Running kubectl with args [kubectl create namespace cmd-devfile-create-test190hal]

[ssh:Fedora 32] [kubectl] namespace/cmd-devfile-create-test190hal created

[ssh:Fedora 32] Running kubectl with args [kubectl config set-context --current --namespace cmd-devfile-create-test190hal]

[ssh:Fedora 32] [kubectl] Context "minikube" modified.

[ssh:Fedora 32] Running kubectl with args [kubectl get namespaces]
[...]
[ssh:Fedora 32] Running odo with args [odo create nodejs]

[ssh:Fedora 32] [odo] I0401 07:41:26.029644   60845 util.go:422] path .odo/config.yaml doesn't exist, skipping it
[...]
[ssh:Fedora 32] Running odo with args [odo create nodejs]

[ssh:Fedora 32] [odo] I0401 07:41:26.128875   60853 util.go:727] HTTPGetRequest: https://raw.githubusercontent.com/openshift/odo/master/build/VERSION

[ssh:Fedora 32] [odo] I0401 07:41:26.128944   60853 util.go:422] path .odo/config.yaml doesn't exist, skipping it

[ssh:Fedora 32] [odo]  ���  this directory already contains a component

[ssh:Fedora 32] Running odo with args [odo create nodejs --s2i]

[ssh:Fedora 32] [odo] I0401 07:41:26.220830   60861 util.go:727] HTTPGetRequest: https://raw.githubusercontent.com/openshift/odo/master/build/VERSION

[ssh:Fedora 32] [odo] I0401 07:41:26.221071   60861 util.go:748] Response will be cached in /tmp/odohttpcache for 1h0m0s

[ssh:Fedora 32] [odo] I0401 07:41:26.221224   60861 util.go:761] Cached response used.

[ssh:Fedora 32] [odo] I0401 07:41:26.237764   60861 catalog.go:408] Unable to get Image Streams from namespace openshift. Error unable to list imagestreams: the server could not find the requested resource (get imagestreams.image.openshift.io)
```
## Expected behavior

`--s2i` tests should be separated out, so that it only runs on openshift cluster.

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind failing-test

**What does does this PR do / why we need it**:

This will resolve test failure on kubernetes cluster

**Which issue(s) this PR fixes**:

Fixes #4577 

**PR acceptance criteria**:

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
`make test-cmd-devfile-create` should run successfully on openshift and kubernetes both.

### CODE REVIEW

**Comment by prietyc123** [comment]
We are getting false logs for PSI jobs. For ex https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4578/pull-ci-openshift-odo-master-psi-kubernetes-integration-e2e/1377582757776986112#1:build-log.txt%3A32 I don't see any jobs running for build no. 990 🙁 
I think there is something wrong on jenkins front, that we need to look into.

**Comment by rnapoles-rh** [comment]
> We are getting false logs for PSI jobs. For ex https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4578/pull-ci-openshift-odo-master-psi-kubernetes-integration-e2e/1377582757776986112#1:build-log.txt%3A32 I don't see any jobs running for build no. 990 🙁
> I think there is something wrong on jenkins front, that we need to look into.

It could be that the logs were deleted as we recycle them as the last 15 are displayed, the job number also goes away

File: tests/integration/devfile/cmd_devfile_create_test.go [hunk 1]
```diff
@@ -191,9 +191,21 @@ var _ = Describe("odo devfile create command tests", func() {
...
+				if os.Getenv("KUBERNETES") == "true" {
+					Skip("This is a OpenShift specific scenario, skipping")
+				}
+			})
 
+			It("should fail when we create the devfile or s2i component multiple times", func() {
+				helper.CopyExampleDevFile(filepath.Join("source", "devfiles", "nodejs", devfile), filepath.Join(commonVar.Context, devfile))
+				helper.CmdShouldPass("odo", "create", "nodejs")
+				output := helper.CmdShouldFail("odo", "create", "nodejs", "--s2i")
+				Expect(output).To(ContainSubstring("this directory already contains a component"))
```
Comment (rnapoles-rh) [inline tests/integration/devfile/cmd_devfile_create_test.go:208]: This tests say "should fail when we create the devfile or s2i component multiple times", however here only create devfile component once then try to create a s2i component.
To fully cover the possible paths we should:
1. Create devfile component (should pass) then try to create again a devfile component (should fail), try to create a s21 component (should fail)
2. Create a s2i component  (should pass) then try to create again a s21 component (should fail), try to create a devfile component (should fail)
With this then we can get rid of test in lines 190-193

Comment (prietyc123) [reply tests/integration/devfile/cmd_devfile_create_test.go:208]: > With this then we can get rid of test in lines 190-193

Line number 190-193 is for both openshift and kubernetes scenario I separated out s2i from there because s2i images won't be available for kubernetes. 
Lines 204-208 is only openshift specific scenario. So in brief for openshift we are testing two scenario:

1. Create devfile component (should pass) then create devfile component again (should fail).
2. Create devfile component (should pass) then create s2i component (should fail). As we have already tested with twice devfile creation, checking it again will duplicate the things.

**Review by mohammedzee1000 — APPROVED** [review]
looks good to me
/lgtm
