### PR TITLE
Skiping s2iItem check on kubernetes cluster

### LINKED ISSUE #3713: Skip s2i items check on "odo catalog list components -o json" for kubernetes cluster
/kind bug

## What versions of software are you using?

**Operating System:**

All supported

**Output of `odo version`:**

master

## How did you run odo exactly?

Running `odo catalog list components -o json` on kubernetes cluster failing the test.

## Actual behavior

```
Created dir: /tmp/095615081
Running odo with args [odo preference set Experimental true]
[odo] I0806 09:02:50.155529   17148 preference.go:209] The path for preference file is /tmp/095615081/config.yaml
[odo] Global preference was successfully updated
[odo] I0806 09:02:50.155819   17148 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
Setting KUBECONFIG=/tmp/095615081/config
Creating a new project: noehvakeio
Running kubectl with args [kubectl create namespace noehvakeio]
[kubectl] namespace/noehvakeio created
Running kubectl with args [kubectl config set-context --current --namespace noehvakeio]
[kubectl] Context "minikube" modified.
Running kubectl with args [kubectl get namespaces]
[kubectl] NAME              STATUS   AGE
[kubectl] bsumixzjbl        Active   0s
[kubectl] default           Active   2m51s
[kubectl] kube-node-lease   Active   2m52s
[kubectl] kube-public       Active   2m52s
[kubectl] kube-system       Active   2m52s
[kubectl] noehvakeio        Active   0s
Current working dir: /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile
Setting current dir to: /tmp/095615081
Running odo with args [odo catalog list components -o json]
[odo] I0806 09:02:50.743562   17217 cert_rotation.go:137] Starting client certificate rotation controller
[odo] {
[odo] 	"kind": "List",
[odo] 	"apiVersion": "odo.dev/v1alpha1",
[odo] 	"metadata": {
[odo] 		"creationTimestamp": null
[odo] 	},
[odo] 	"devfileItems": [
[odo] 		{
[odo] 			"Name": "java-maven",
[odo] 			"DisplayName": "Maven Java",
[odo] 			"Description": "Upstream Maven and OpenJDK 11",
[odo] 			"Link": "/devfiles/java-maven/devfile.yaml",
[odo] 			"Registry": {
[odo] 				"Name": "DefaultDevfileRegistry",
[odo] 				"URL": "https://raw.githubusercontent.com/odo-devfiles/registry/master"
[odo] 			}
[odo] 		},
[odo] 		{
[odo] 			"Name": "java-openliberty",
[odo] 			"DisplayName": "Open Liberty",
[odo] 			"Description": "Open Liberty microservice in Java",
[odo] 			"Link": "/devfiles/java-openliberty/devfile.yaml",
[odo] 			"Registry": {
[odo] 				"Name": "DefaultDevfileRegistry",
[odo] 				"URL": "https://raw.githubusercontent.com/odo-devfiles/registry/master"
[odo] 			}
[odo] 		},
[odo] 		{
[odo] 			"Name": "java-quarkus",
[odo] 			"DisplayName": "Quarkus Java",
[odo] 			"Description": "Upstream Quarkus with Java+GraalVM",
[odo] 			"Link": "/devfiles/java-quarkus/devfile.yaml",
[odo] 			"Registry": {
[odo] 				"Name": "DefaultDevfileRegistry",
[odo] 				"URL": "https://raw.githubusercontent.com/odo-devfiles/registry/master"
[odo] 			}
[odo] 		},
[odo] 		{
[odo] 			"Name": "java-springboot",
[odo] 			"DisplayName": "Spring Boot®",
[odo] 			"Description": "Spring Boot® using Java",
[odo] 			"Link": "/devfiles/java-springboot/devfile.yaml",
[odo] 			"Registry": {
[odo] 				"Name": "DefaultDevfileRegistry",
[odo] 				"URL": "https://raw.githubusercontent.com/odo-devfiles/registry/master"
[odo] 			}
[odo] 		},
[odo] 		{
[odo] 			"Name": "nodejs",
[odo] 			"DisplayName": "NodeJS Runtime",
[odo] 			"Description": "Stack with NodeJS 12",
[odo] 			"Link": "/devfiles/nodejs/devfile.yaml",
[odo] 			"Registry": {
[odo] 				"Name": "DefaultDevfileRegistry",
[odo] 				"URL": "https://raw.githubusercontent.com/odo-devfiles/registry/master"
[odo] 			}
[odo] 		}
[odo] 	]
[odo] }
Deleting project: noehvakeio
Running kubectl with args [kubectl delete namespaces noehvakeio]
[kubectl] namespace "noehvakeio" deleted
Setting current dir to: /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile
Deleting dir: /tmp/095615081
• Failure [6.129 seconds]
odo devfile catalog command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_catalog_test.go:14
  When executing catalog list components with experimental mode set to true
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_catalog_test.go:130
    should prove that nodejs is present in both S2I Component list and Devfile Component list [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_catalog_test.go:134
    Expected
        <string>: null
    to contain substring
        <string>: nodejs
```

## Expected behavior

`s2iItems` should be check only for openshift cluster here - https://github.com/openshift/odo/blob/master/tests/integration/devfile/cmd_devfile_catalog_test.go#L149

## Any logs, error output, etc?

https://travis-ci.com/github/openshift/odo/jobs/369244976#L450

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind bug
/kind cleanup
/kind failing-test
/kind code-refactoring

**What does does this PR do / why we need it**:

PR skin s2i image check for kubernetes clusters due to the fact that imagestreams are not there with k8s.
Also code clean up.

**Which issue(s) this PR fixes**:

Fixes #3713 

**PR acceptance criteria**:

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer**:

`make test-cmd-devfile-catalog` should run on both openshift and kubernetes cluster

### CODE REVIEW

File: tests/integration/devfile/utils/utils.go [hunk 1]
```diff
@@ -585,3 +586,32 @@ func DeleteLocalConfig(args ...string) {
 	}
 	helper.MatchAllInOutput(output, expectedOutput)
 }
+
+// VerifyCatalogListComponent verifies component exists in both S2I Component list and Devfile Component list
+func VerifyCatalogListComponent(output string) error {
+
+	componentName := "nodejs"
```
Comment (amitkrout) [inline tests/integration/devfile/utils/utils.go:593]: pass it as a argument in the calling function.

Comment (prietyc123) [reply tests/integration/devfile/utils/utils.go:593]: `componentName` is not connecting to the spec anywhere https://github.com/openshift/odo/pull/3715/files#diff-318517042700080474192fc7dc04e456R133 and we can check for any component inside the json. So I think its better to have it inside function inspite of unnecessarily adding it to the test.

Comment (amitkrout) [reply tests/integration/devfile/utils/utils.go:593]: https://github.com/openshift/odo/pull/3715/files#diff-318517042700080474192fc7dc04e456R133 and more importantly is not a good idea to hardcode things in a library function.

Comment (prietyc123) [reply tests/integration/devfile/utils/utils.go:593]: Yes, its checking the component inside the spec and that's what `VerifyCatalogListComponent()` is doing. So separate function has meant for that purpose only thats why componentName lies there. AFA hardcoding things are concerned so its just a variable name thats needs to be assigned some value right?

Comment (amitkrout) [reply tests/integration/devfile/utils/utils.go:593]: Think in a generic way, for example tomorrow i want java component name to be verified the then the library function should be flexible to verify it.

Comment (amitkrout) [reply tests/integration/devfile/utils/utils.go:593]: Verifies the catalog list output along with the component name
```
func VerifyCatalogListComponent(output, componentName string) error {
}
```

File: tests/integration/devfile/cmd_devfile_catalog_test.go [hunk 2]
```diff
@@ -130,35 +130,10 @@ var _ = Describe("odo devfile catalog command tests", func() {
...
-
-			helper.MatchAllInOutput(output, wantOutput)
-
-			outputBytes, err = json.Marshal(data["devfileItems"])
-			if err == nil {
-				output = string(outputBytes)
-			}
-
-			helper.MatchAllInOutput(output, wantOutput)
+			err := utils.VerifyCatalogListComponent(output)
```
Comment (amitkrout) [inline tests/integration/devfile/cmd_devfile_catalog_test.go:135]: Pass the component name too as an argument to avoid hardcoding in the library function
```
err := utils.VerifyCatalogListComponent(output, componentName)
```

File: tests/integration/devfile/utils/utils.go [hunk 3]
```diff
@@ -585,3 +586,28 @@ func DeleteLocalConfig(args ...string) {
...
+
+	for _, items := range listItems {
+		outputBytes, err := json.Marshal(data[items])
+		if err != nil {
+			return err
+		}
+		output = string(outputBytes)
+		helper.MatchAllInOutput(output, componentName)
+	}
+	return err
```
Comment (amitkrout) [inline tests/integration/devfile/utils/utils.go:612]: ```return nil```

File: tests/integration/devfile/utils/utils.go [hunk 4]
```diff
@@ -585,3 +586,28 @@ func DeleteLocalConfig(args ...string) {
 	}
 	helper.MatchAllInOutput(output, expectedOutput)
 }
+
+// VerifyCatalogListComponent verifies component exists in both S2I Component list and Devfile Component list
+func VerifyCatalogListComponent(output string, componentName []string) error {
+	var data map[string]interface{}
+	listItems := []string{"devfileItems"}
+
+	err := json.Unmarshal([]byte(output), &data)
```
Comment (amitkrout) [inline tests/integration/devfile/utils/utils.go:595]: keep error in the block scope, for example 

if err := json.Unmarshal([]byte(output), &data); err != nil {
    return err
}
```

File: tests/integration/devfile/utils/utils.go (hunk 3 above)
Comment (prietyc123) [reply tests/integration/devfile/utils/utils.go:617]: It will be same 👍

File: tests/integration/devfile/utils/utils.go (hunk 4 above)
Comment (prietyc123) [reply tests/integration/devfile/utils/utils.go:596]: Just maintaining the contiguous pattern like everywhere you will see https://github.com/openshift/odo/blob/master/tests/helper/helper_generic.go#L82 and thats fine both are same and it will give you better glace view.

File: tests/integration/devfile/utils/utils.go (hunk 3 above)
Comment (amitkrout) [reply tests/integration/devfile/utils/utils.go]: Nope it not same. err is returned in the block level itself when it is hit for first time. 

All the time the function will return the error of the statment ```err := json.Unmarshal([]byte(output), &data)```

**Comment by amitkrout** [comment]
Due to wrong env setup i was able to reproduce it locally. sorry for the confusion. look good
/hold cancel
