### PR TITLE
Mount persistent volumes for S2I images

### LINKED ISSUE #4623: converted wildfly and dotnet application error out with permission denied
/kind bug

## What versions of software are you using?

**Operating System:** MacOS

**Output of `odo version`:**

## How did you run odo exactly?
`"odo", "create", "--s2i", "wildfly", "wildfly-app"`
"odo", "create", "--s2i", "dotnet:2.0"

## Actual behavior
```
 + PV_MNT_PT=/opt/app-root              
INFO[2021-04-14T23:04:26Z] [odo] + ODO_UTILS_DIR=/opt/odo               
INFO[2021-04-14T23:04:26Z] [odo] + '[' '!' -f /opt/app-root/conf/supervisor.conf ']' 
INFO[2021-04-14T23:04:26Z] [odo] + cp -rp /opt/odo/conf /opt/app-root   
INFO[2021-04-14T23:04:26Z] [odo] cp: cannot create directory '/opt/app-root/conf': Permission denied 
INFO[2021-04-14T23:04:26Z] [odo]  ✗  Executing s2i-assemble command "/opt/odo/bin/s2i-setup && /opt/odo/bin/assemble-and-restart" [179ms] 
INFO[2021-04-14T23:04:26Z] [odo]  ✗  Failed to start component with name wildfly-app. Error: Failed to create the component: command execution failed: unable to execute the run command: unable to exec command [/bin/sh -c /opt/odo/bin/s2i-setup && /opt/odo/bin/assemble-and-restart]:  
INFO[2021-04-14T23:04:26Z] [odo] + set -eo pipefail                     
INFO[2021-04-14T23:04:26Z] [odo] + PV_MNT_PT=/opt/app-root              
INFO[2021-04-14T23:04:26Z] [odo] + ODO_UTILS_DIR=/opt/odo               
INFO[2021-04-14T23:04:26Z] [odo] + '[' '!' -f /opt/app-root/conf/supervisor.conf ']' 
INFO[2021-04-14T23:04:26Z] [odo] + cp -rp /opt/odo/conf /opt/app-root   
INFO[2021-04-14T23:04:26Z] [odo] cp: cannot create directory '/opt/app-root/conf': Permission denied 
INFO[2021-04-14T23:04:26Z] [odo] : error while streaming command: command terminated with exit code 1 
INFO[2021-04-14T23:04:26Z] Deleting project: e2e-source-test36ipy       
INFO[2021-04-14T23:04:26Z] Running odo with args [odo project delete e2e-source-test36ipy -f] `
```

```
   Generating MSBuild file /opt/app-root/src/obj/asp-net-hello-world.csproj.nuget.g.targets.
[odo]   Restore completed in 4.99 sec for /opt/app-root/src/asp-net-hello-world.csproj.
[odo] ---> Publishing application...
[odo] Microsoft (R) Build Engine version 15.4.8.50081 for .NET Core
[odo] Copyright (C) Microsoft Corporation. All rights reserved.
[odo] 
[odo]   asp-net-hello-world -> /opt/app-root/src/bin/Release/netcoreapp2.0/asp-net-hello-world.dll
[odo]   asp-net-hello-world -> /opt/app-root/app/
[odo] chmod: changing permissions of '/opt/app-root/app/default-cmd.sh': Operation not permitted
[odo] : error while streaming command: command terminated with exit code 1
```

## Expected behavior
Component should be working

- [ ] Persistent volumes should be mounted into `/opt/app-root` and in `$DEPLOYMENTS_DIR`
- [ ] `$DEPLOYMENTS_DIR` can be inside `/opt/app-root`, in this case mount only one PV in `/opt/app-root`
- [ ] An init container should copy the content of the original `/opt/app-root` into the persistent volume mounted on this endpoint
- [ ] Declare a `preStart` event in the devfile to run this init container (blocked by #4901)

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this?**

/kind bug

**What does this PR do / why we need it**:

This PR:
- mounts persistent volumes in /opt/app-root and the deployments directory 
- adds a preStart event to the devfile, to create an initContainer that copies original files in /opt/app-root into the persistent volume

**Which issue(s) this PR fixes**:

Fixes #4623 

**PR acceptance criteria**:

- [x] Unit test 

- [ ] Integration test 

- [x] Documentation 

- [ ] Update changelog

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

```
# install the wildfly image stream:

$ oc apply -n openshift -f https://raw.githubusercontent.com/openshift/library/master/arch/x86_64/community/wildfly/imagestreams/wildfly-centos7.json

# get wildfly sources from `tests/examples/source/wildfly/`

$ odo create --s2i wildfly

# check that the devfile contains `events/prestart` section

$ odo push

# check that component is running correctly
```

or

```
# get nodejs sources from tests/examples/source/nodejs/

$ odo create --s2i nodejs

# check that the devfile contains `events/prestart` section

$ odo push

# check that component is running correctly
```

### CODE REVIEW

**Comment by prietyc123** [comment]
@feloy I feel there is some real failures with services on kubernetes. I have just overlooked the logs and suspect most of the failures with linking while doing `odo push`

```
[ssh:Fedora-32-minikube] [odo] I0723 06:37:05.559229 2095016 pods.go:79] Container Status: {"name":"runtime","state":{"running":{"startedAt":"2021-07-23T06:37:04Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"registry.access.redhat.com/ubi8/nodejs-14:latest","imageID":"docker-pullable://registry.access.redhat.com/ubi8/nodejs-14@sha256:bd40a2c6ad864e848d86ec519c665b6b042b9fa2bd88de6b93946b1055f7ab0b","containerID":"docker://4dcc0c33075505031d05617ab48dea5b63dba1804b0219950537473532e6d82e","started":true}
[ssh:Fedora-32-minikube] [odo] I0723 06:37:05.559254 2095016 pods.go:83] Pod cmp-hxwtvx-app-5b448f6c65-mrn94 is Running
[ssh:Fedora-32-minikube] [odo] I0723 06:37:05.561523 2095016 operators.go:36] Fetching list of operators installed in cluster
[ssh:Fedora-32-minikube] [odo]  ✗  Failed to start component with name "cmp-hxwtvx". Error: Failed to create the component: admission webhook "vservicebinding.kb.io" denied the request: cannot update Service Binding if 'Ready' condition is True. If you want to rebind to another service/application, remove this binding and create a new one.
```
Could you please have a look.

**Comment by feloy** [comment]
/test psi-kubernetes-integration-e2e
Retry with SBO v0.9.1

**Comment by feloy** [comment]
/test psi-unit-test-windows

```
[ssh:Windows 10] panic: test timed out after 10m0s
[ssh:Windows 10] 
[ssh:Windows 10] goroutine 10 [running]:
[ssh:Windows 10] testing.(*M).startAlarm.func1()
[ssh:Windows 10] 	c:/go/src/testing/testing.go:1628 +0xe6
skipped 142 lines unfold_more
[ssh:Windows 10] github.com/openshift/odo/pkg/watch.WatchAndPush.func1(0xc0005cf3f0, 0xc0005fc1f8, 0xc00036dfd0, 0xc0005e1ec0, 0xc00049f000, 0xc00049efc0, 0xc0005fc200, 0xc00049efe0)
[ssh:Windows 10] 	C:/Users/Admin/amqp_ci_rcv_odo-windows-unit-pr-build_PR_4918/wTSdF/repo/pkg/watch/watch.go:198 +0xf05
[ssh:Windows 10] created by github.com/openshift/odo/pkg/watch.WatchAndPush
[ssh:Windows 10] 	C:/Users/Admin/amqp_ci_rcv_odo-windows-unit-pr-build_PR_4918/wTSdF/repo/pkg/watch/watch.go:187 +0x3da
[ssh:Windows 10] FAIL	github.com/openshift/odo/pkg/watch	600.556s
```

**Comment by feloy** [comment]
/test psi-kubernetes-integration-e2e

```
 • Failure [611.580 seconds]
 odo devfile push command tests
 /home/fedora/amqp_ci_rcv_odo-minikube-pr-build_PR_4918/KdFfu/repo/tests/integration/devfile/cmd_devfile_push_test.go:18
   verify files are correctly synced
   /home/fedora/amqp_ci_rcv_odo-minikube-pr-build_PR_4918/KdFfu/repo/tests/integration/devfile/cmd_devfile_push_test.go:134
     when project and clonePath is present
     /home/fedora/amqp_ci_rcv_odo-minikube-pr-build_PR_4918/KdFfu/repo/tests/integration/devfile/cmd_devfile_push_test.go:301
       should sync to the correct dir in container [It]
       /home/fedora/amqp_ci_rcv_odo-minikube-pr-build_PR_4918/KdFfu/repo/tests/integration/devfile/cmd_devfile_push_test.go:302
 
       Timed out after 600.000s.
      
       Running odo with args [odo push --v 5]
       Expected process to exit.  It did not.
```

**Comment by feloy** [comment]
/test v4.8-integration-e2e

(passes locally)

```
• Failure [28.241 seconds]
odo push command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_push_test.go:15
  when push command is executed
  /go/src/github.com/openshift/odo/tests/integration/cmd_push_test.go:76
    should build when a file and a folder is renamed in the directory [It]
    /go/src/github.com/openshift/odo/tests/integration/cmd_push_test.go:114
    No future change is possible.  Bailing out early after 0.539s.
      
    Running odo with args [odo push --context /tmp/592045329]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
```

**Comment by feloy** [comment]
PVC errors

/test v4.8-integration-e2e

**Comment by dharmit** [comment]
@feloy did you import some builder image for `odo create --s2i wildfly` to work? I'm asking because it's not available by default:
```sh
$ odo catalog list components
Odo Devfile Components:
....
....

Odo S2I Components:
NAME       PROJECT       TAGS                                                      SUPPORTED
java       openshift     latest,openjdk-11-el7,openjdk-11-ubi8,openjdk-8-el7       YES
nodejs     openshift     12-ubi8,14-ubi8,latest                                    YES
dotnet     openshift     2.1-el7,2.1-ubi8,3.1-el7,3.1-ubi8,5.0-ubi8                NO
golang     openshift     1.13.4-ubi7,1.14.7-ubi8,latest                            NO
httpd      openshift     2.4-el7,2.4-el8,latest                                    NO
java       openshift     openjdk-8-ubi8                                            NO
nginx      openshift     1.14-el8,1.16-el7,1.16-el8,1.18-ubi7,1.18-ubi8,latest     NO
nodejs     openshift     10-ubi8,12-ubi7,14-ubi7                                   NO
perl       openshift     5.26-ubi8,5.30-el7,5.30-ubi8,latest                       NO
php        openshift     7.2-ubi8,7.3-ubi7,7.3-ubi8,7.4-ubi8,latest                NO
python     openshift     2.7-ubi7,2.7-ubi8,3.6-ubi8,3.8-ubi7,3.8-ubi8,latest       NO
ruby       openshift     2.5-ubi8,2.6-ubi7,2.6-ubi8,2.7-ubi7,2.7-ubi8,latest       NO
```

**Comment by dharmit** [comment]
> @feloy did you import some builder image for `odo create --s2i wildfly` to work? I'm asking because it's not available by default:

For the time being, I'm doing `odo create --s2i java`.

**Comment by dharmit** [comment]
> For the time being, I'm doing `odo create --s2i java`.

I'm hitting a different error than the one you mentioned on Slack.
```sh
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
ERROR Neither $JAVA_MAIN_CLASS nor $JAVA_APP_JAR is set and 0 JARs found in /deployments (1 expected)
INFO exec  java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=5858,suspend=n -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -cp "." -jar   
Error: -jar requires jar file specification
Listening for transport dt_socket at address: 5858
Usage: java [options] <mainclass> [args...]
```
But could that be because I'm using `java` instead of `wildfly` with `odo create`?

**Comment by feloy** [comment]
> @feloy did you import some builder image for `odo create --s2i wildfly` to work? I'm asking because it's not available by default:
> 

Yes, right, I have found the image to install on the tests scripts (scripts/configure-installer-tests-cluster.sh):
```
oc apply -n openshift -f https://raw.githubusercontent.com/openshift/library/master/arch/x86_64/community/wildfly/imagestreams/wildfly-centos7.json
```

**Comment by feloy** [comment]
> > For the time being, I'm doing `odo create --s2i java`.
> 
> I'm hitting a different error than the one you mentioned on Slack.
> 
> ```shell
> Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
> ERROR Neither $JAVA_MAIN_CLASS nor $JAVA_APP_JAR is set and 0 JARs found in /deployments (1 expected)
> INFO exec  java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=5858,suspend=n -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -cp "." -jar   
> Error: -jar requires jar file specification
> Listening for transport dt_socket at address: 5858
> Usage: java [options] <mainclass> [args...]
> ```
> 
> But could that be because I'm using `java` instead of `wildfly` with `odo create`?

Yes. You can also test with a nodejs project, see the updated **How to test changes / Special notes to the reviewer**

**Comment by feloy** [comment]
PVC errors

/test v4.8-integration-e2e

**Comment by feloy** [comment]
/test v4.8-integration-e2e

flaky?
```
[Fail] odo project command tests [It] should list current empty project in json format 
```

**Comment by feloy** [comment]
/test psi-kubernetes-integration-e2e

```
INFO[2021-08-19T17:42:34Z] error: Process interrupted with signal interrupt, cancelling execution... 
INFO[2021-08-19T17:42:34Z] Step kubernetes-integration-e2e-kubernetes-integration-e2e-steps failed after 3h57m19s. 
```

**Comment by feloy** [comment]
/test psi-kubernetes-integration-e2e
```
INFO[2021-08-20T11:32:31Z] error: Process interrupted with signal interrupt, cancelling execution... 
INFO[2021-08-20T11:32:31Z] Step kubernetes-integration-e2e-kubernetes-integration-e2e-steps failed after 3h57m7s. 
```

**Comment by feloy** [comment]
/test psi-kubernetes-integration-e2e

```
exec: "odo": executable file not found in $PATH
```

**Comment by dharmit** [comment]
> > @feloy What was the verdict on this PR? I remember you brought up that this PR might not be relevant with the removal of S2I comp. Are we still bringing this in? Is it RFR?
> 
> We are waiting for Tomas' opinion if `odo create --s2i` should also be removed immediately, or later

@kadel can you PTAL?

**Comment by kadel** [comment]
> We are waiting for Tomas' opinion if `odo create --s2i` should also be removed immediately, or later

Not in this PR. This PR should be just about fixing the issues with volumes and file permissions

File: pkg/devfile/validate/events.go [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+}
+
+func validateEvents(events v1alpha2.Events) (err error) {
+
+	if err := validatePreStart(events.PreStart); err != nil {
+		return err
+	}
+
+	return nil
+}
```
Comment (valaparthvi) [inline pkg/devfile/validate/events.go:16]: I don't understand the use of these functions? Or do you plan on using them later on?

File: pkg/devfile/convert/convert.go [hunk 2]
```diff
@@ -278,6 +330,57 @@ func setDevfileComponentsForS2I(d data.DevfileData, s2iImage string, localConfig
...
+	volumeAppRoot := devfilev1.Component{
+		Name: "app-root-volume",
+		ComponentUnion: devfilev1.ComponentUnion{
+			Volume: &devfilev1.VolumeComponent{
+				Volume: devfilev1.Volume{
+					Size: "1Gi",
+				},
+			},
+		},
+	}
```
Comment (valaparthvi) [inline pkg/devfile/convert/convert.go:356]: I might be nitpicking, but do you think we can move the following piece of code into a local function that accepts the `Name`? I see the same code is used if `separateDeploymentsMount` is true.
```go
devfilev1.Component{
		Name: "app-root-volume",
		ComponentUnion: devfilev1.ComponentUnion{
			Volume: &devfilev1.VolumeComponent{
				Volume: devfilev1.Volume{
					Size: "1Gi",
				},
			},
		},
	}
```

File: pkg/devfile/validate/events.go (hunk 1 above)
Comment (feloy) [reply pkg/devfile/validate/events.go:16]: I forgot to remove them, they are unused now

File: pkg/devfile/convert/convert.go (hunk 2 above)
Comment (feloy) [reply pkg/devfile/convert/convert.go:356]: It would be nice to have some high-level functions on top of the devfile library for these creations of ComponentUnion, but it would be better to make the changes in the whole sources

**Comment by feloy** [comment]
/test v4.8-integration-e2e

Test passes locally

```
odo service command tests for OperatorHub
/go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:18
  Operators are installed in the cluster
  /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:31
    a specific operator is installed
    /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:129
      when a nodejs component is created
      /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:181
        when an Redis instance is created with no name
        /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:269
          when odo push is executed
          /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:289
            when the service is deleted [BeforeEach]
            /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:341
              should delete service definition from devfile.yaml
              /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:346
              No future change is possible.  Bailing out early after 13.761s.
      
              Running odo with args [odo push]
              Expected
                  <int>: 1
              to match exit code:
                  <int>: 0
```

**Comment by valaparthvi** [comment]
@feloy I was unable to push wildfly image to the cluster. Here is the error - 

```sh
➜  odo push --show-log

Validation
 ✓  Validating the devfile [159314ns]

Creating Services for component wildfly-wildfly-vyyz
 ✓  Services are in sync with the cluster, no changes are required

Creating Kubernetes resources for component wildfly-wildfly-vyyz
 ✓  Waiting for component to start [388ms]
 ✓  Links are in sync with the cluster, no changes are required
 ✓  Waiting for component to start [412ms]

Applying URL changes
 ✓  URL http-8778: http://http-8778-app-myproject.apps.ci-ln-glxhklt-f76d1.origin-ci-int-gce.dev.openshift.com/ created
 ✓  URL http-8080: http://http-8080-app-myproject.apps.ci-ln-glxhklt-f76d1.origin-ci-int-gce.dev.openshift.com/ created

Syncing to component wildfly-wildfly-vyyz
 ✓  Checking file changes for pushing [615818ns]
 ✓  Syncing files to the component [8s]

Executing devfile commands for component wildfly-wildfly-vyyz
 •  Executing s2i-assemble command "/opt/odo/bin/s2i-setup && /opt/odo/bin/assemble-and-restart"  ...
+ set -eo pipefail
+ PV_MNT_PT=/opt/app-root
+ ODO_UTILS_DIR=/opt/odo
+ '[' '!' -f /opt/app-root/conf/supervisor.conf ']'
+ cp -rp /opt/odo/conf /opt/app-root
+ mkdir -p /tmp
+ touch /tmp/.dummy
+ mkdir -p /tmp/src/
+ touch /tmp/src/.dummy
+ [[ /tmp != *\/\s\r\c* ]]
+ mkdir -p /tmp/src
+ touch /tmp/src/.dummy
+ mkdir -p /opt/app-root/src
+ '[' '!' -z true ']'
+ rsync -ar /tmp/projects/ /tmp/src
+ set -eo pipefail
+ export ODO_UTILS_DIR=/opt/odo
+ ODO_UTILS_DIR=/opt/odo
+ export ODO_IMAGE_MAPPINGS_FILE=/opt/odo/language-scripts/image-mappings.json
+ ODO_IMAGE_MAPPINGS_FILE=/opt/odo/language-scripts/image-mappings.json
++ /opt/odo/bin/getlanguage
+ IMAGE_LANG=
+ '[' '!' -z /home/jboss ']'
+ '[' /tmp '!=' /home/jboss ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' '!' -d /opt/app-root/src-backup ']'
+ mkdir -p /opt/app-root/src-backup/src
+ rsync -rlO /tmp/src/. /opt/app-root/src-backup/src/
+ b_IFS=' 	
'
+ b_OFS=
+ OIFS=' 	
'
+ IFS='
'
++ ls -A /tmp/src/
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /home/jboss/.dummy
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /home/jboss/.gitignore
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /home/jboss/devfile.yaml
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /home/jboss/pom.xml
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /home/jboss/src
+ OIFS=
+ IFS=' 	
'
+ '[' -n centos7/s2i-base-centos7 ']'
+ '[' centos7/s2i-base-centos7 == redhat-openjdk-18/openjdk18-openshift ']'
+ '[' -f /tmp/src/.s2i/bin/assemble ']'
+ '[' -n '' ']'
+ '[' -n /usr/local/s2i ']'
+ rm -rf /opt/app-root/src/.git
+ /usr/local/s2i/assemble
/opt/odo/bin/assemble-and-restart: line 63: /usr/local/s2i/assemble: No such file or directory
 ✗  Executing s2i-assemble command "/opt/odo/bin/s2i-setup && /opt/odo/bin/assemble-and-restart" [4s]
 ✗  Failed to start component with name "wildfly-wildfly-vyyz". Error: Failed to create the component: command execution failed: unable to execute the run command: unable to exec command [/bin/sh -c /opt/odo/bin/s2i-setup && /opt/odo/bin/assemble-and-restart]: 
+ set -eo pipefail
+ PV_MNT_PT=/opt/app-root
+ ODO_UTILS_DIR=/opt/odo
+ '[' '!' -f /opt/app-root/conf/supervisor.conf ']'
+ cp -rp /opt/odo/conf /opt/app-root
+ mkdir -p /tmp
+ touch /tmp/.dummy
+ mkdir -p /tmp/src/
+ touch /tmp/src/.dummy
+ [[ /tmp != *\/\s\r\c* ]]
+ mkdir -p /tmp/src
+ touch /tmp/src/.dummy
+ mkdir -p /opt/app-root/src
+ '[' '!' -z true ']'
+ rsync -ar /tmp/projects/ /tmp/src
+ set -eo pipefail
+ export ODO_UTILS_DIR=/opt/odo
+ ODO_UTILS_DIR=/opt/odo
+ export ODO_IMAGE_MAPPINGS_FILE=/opt/odo/language-scripts/image-mappings.json
+ ODO_IMAGE_MAPPINGS_FILE=/opt/odo/language-scripts/image-mappings.json
++ /opt/odo/bin/getlanguage
+ IMAGE_LANG=
+ '[' '!' -z /home/jboss ']'
+ '[' /tmp '!=' /home/jboss ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' '!' -d /opt/app-root/src-backup ']'
+ mkdir -p /opt/app-root/src-backup/src
+ rsync -rlO /tmp/src/. /opt/app-root/src-backup/src/
+ b_IFS=' 	
'
+ b_OFS=
+ OIFS=' 	
'
+ IFS='
'
++ ls -A /tmp/src/
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /home/jboss/.dummy
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /home/jboss/.gitignore
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /home/jboss/devfile.yaml
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /home/jboss/pom.xml
+ for file in '`ls -A ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ rm -fr /home/jboss/src
+ OIFS=
+ IFS=' 	
'
+ '[' -n centos7/s2i-base-centos7 ']'
+ '[' centos7/s2i-base-centos7 == redhat-openjdk-18/openjdk18-openshift ']'
+ '[' -f /tmp/src/.s2i/bin/assemble ']'
+ '[' -n '' ']'
+ '[' -n /usr/local/s2i ']'
+ rm -rf /opt/app-root/src/.git
+ /usr/local/s2i/assemble
/opt/odo/bin/assemble-and-restart: line 63: /usr/local/s2i/assemble: No such file or directory
: error while streaming command: command terminated with exit code 1

```

Do you think I am missing something or does this seem unrelated to your changes?

**Comment by feloy** [comment]
> @feloy I was unable to push wildfly image to the cluster. Here is the error -
> 
> ```shell
> ➜  odo push --show-log
> 
> Validation
>  ✓  Validating the devfile [159314ns]
> 
> Creating Services for component wildfly-wildfly-vyyz
>  ✓  Services are in sync with the cluster, no changes are required
> 
> Creating Kubernetes resources for component wildfly-wildfly-vyyz
>  ✓  Waiting for component to start [388ms]
>  ✓  Links are in sync with the cluster, no changes are required
>  ✓  Waiting for component to start [412ms]
> 
> Applying URL changes
>  ✓  URL http-8778: http://http-8778-app-myproject.apps.ci-ln-glxhklt-f76d1.origin-ci-int-gce.dev.openshift.com/ created
>  ✓  URL http-8080: http://http-8080-app-myproject.apps.ci-ln-glxhklt-f76d1.origin-ci-int-gce.dev.openshift.com/ created
> 
> Syncing to component wildfly-wildfly-vyyz
>  ✓  Checking file changes for pushing [615818ns]
>  ✓  Syncing files to the component [8s]
> 
> Executing devfile commands for component wildfly-wildfly-vyyz
>  •  Executing s2i-assemble command "/opt/odo/bin/s2i-setup && /opt/odo/bin/assemble-and-restart"  ...

[...]

> + /usr/local/s2i/assemble
> /opt/odo/bin/assemble-and-restart: line 63: /usr/local/s2i/assemble: No such file or directory
> : error while streaming command: command terminated with exit code 1
> ```
> 
> Do you think I am missing something or does this seem unrelated to your changes?

You need to replace `/usr/local/s2i` in the generated devfile with `/usr/libexec/s2i`

Not sure if the problem is specific to the wildfly s2i information or if we can fix this in odo

File: pkg/devfile/convert/convert.go [hunk 3]
```diff
@@ -278,6 +330,57 @@ func setDevfileComponentsForS2I(d data.DevfileData, s2iImage string, localConfig
...
+
+	var deploymentDir string
+	for _, env := range s2iEnv {
+		if env.Name == "ODO_S2I_DEPLOYMENT_DIR" {
+			deploymentDir = env.Value
+			break
+		}
+	}
+
+	separateDeploymentsMount := len(deploymentDir) > 0 && !strings.HasPrefix(deploymentDir, occlient.DefaultAppRootDir)
```
Comment (valaparthvi) [inline pkg/devfile/convert/convert.go:345]: Can you move this code to L356 ? I think it will make it easier to understand the code.

**Review by valaparthvi — COMMENTED** [review]
The code lgtm but do we need 1 or 2 more integration tests to verify these changes or do we already have enough tests? Also, do you think we need to modify unit tests(storage/kubernetes_test.go) to accommodate the new changes?

File: pkg/devfile/convert/convert.go [hunk 4]
```diff
@@ -236,6 +242,52 @@ func setDevfileCommandsForS2I(d data.DevfileData) {
...
+					VolumeMounts: []devfilev1.VolumeMount{
+						{
+							Name: "app-root-volume",
+							Path: "/mnt/app-root",
+						},
+					},
+					Command: []string{
+						"/bin/sh",
+						"-c",
+						"[ -d /opt/app-root ] && cp -R /opt/app-root /mnt/ || true",
```
[the remark this answers is not in the document]
Comment (feloy) [reply pkg/devfile/convert/convert.go:282]: Yes, the script will always return true, even if some error occurs during copying the files. This is to prevent the initContainer to finish as Error, that would terminate the pod immediately

**Comment by feloy** [comment]
> The code lgtm but do we need 1 or 2 more integration tests to verify these changes or do we already have enough tests? Also, do you think we need to modify unit tests(storage/kubernetes_test.go) to accommodate the new changes?

I will work on adding some integration and/or unit tests

File: tests/integration/cmd_create_s2i_test.go [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+	// Clean up after the test
+	// This is run after every Spec (It)
+	var _ = AfterEach(func() {
+		helper.CommonAfterEach(commonVar)
+	})
+
+	When("creating a component from s2i wildfly", func() {
+
+		BeforeEach(func() {
+			helper.Cmd("odo", "component", "create", "--s2i", "wildfly", "--project", commonVar.Project).ShouldPass()
```
Comment (valaparthvi) [inline tests/integration/cmd_create_s2i_test.go:29]: Do we need to add that imagestream or does it work as is?

**Review by valaparthvi — APPROVED** [review]
Thanks for working on all the requested changes, Philippe.

File: tests/integration/cmd_create_s2i_test.go (hunk 5 above)
Comment (feloy) [reply tests/integration/cmd_create_s2i_test.go:29]: I think the imagestream is installed from this script: scripts/configure-installer-tests-cluster.sh (https://github.com/openshift/odo/blob/main/scripts/configure-installer-tests-cluster.sh#L43)
