### PR TITLE
Decide GVR based on underlying cluster

### LINKED ISSUE #4431: Exception encountered when running odo link on minikube
/kind bug

## What versions of software are you using?

**Operating System:**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

Kubernetes v1.20.2 on Docker 20.10.2

**Output of `odo version`:**
odo v2.0.4 (5544b25ec)

## How did you run odo exactly?
After listing an available service:
```
root@unwisest1:~/odoprojects/application-stack-samples/jpa# odo service list
NAME                   AGE
Database/database3     6m35s
```

I then attempted  to link to that service:
`root@unwisest1:~/odoprojects/application-stack-samples/jpa# odo link Database/database3`

## Actual behavior
Exception is raised when issuing the odo link.

## Expected behavior
odo link is successful

## Any logs, error output, etc?
Exception raised:
```
root@unwisest1:~/odoprojects/application-stack-samples/jpa# odo link Database/database3
panic: runtime error: index out of range [2] with length 1
goroutine 1 [running]:
github.com/openshift/odo/pkg/odo/cli/component.(*commonLinkOptions).complete(0xc000305680, 0xc0006a0510, 0x4, 0xc00019b180, 0xc00076e290, 0x1, 0x1, 0x1682b9a, 0xc0006a0510)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_link.go:138 +0xfe6
github.com/openshift/odo/pkg/odo/cli/component.(*LinkOptions).Complete(0xc0006b35c0, 0xc0006a0510, 0x4, 0xc00019b180, 0xc00076e290, 0x1, 0x1, 0xc000140800, 0x1e66f93)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/link.go:100 +0x121
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x2208960, 0xc0006b35c0, 0xc00019b180, 0xc00076e290, 0x1, 0x1)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:29 +0xb8
github.com/openshift/odo/pkg/odo/cli/component.NewCmdLink.func1(0xc00019b180, 0xc00076e290, 0x1, 0x1)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/link.go:158 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc00019b180, 0xc00076e270, 0x1, 0x1, 0xc00019b180, 0xc00076e270)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003a6280, 0x1fac418, 0xc00010efc0, 0x2)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:67 +0x32a
root@unwisest1:~/odoprojects/application-stack-samples/jpa#
```

### PR DESCRIPTION
**Pull request by dharmit**
**What type of PR is this?**
/kind api-change
/kind bug

**What does this PR do / why we need it**:
Gets rid of the deprecated `SelfLink` attribute of a deployment and uses information available from the underlying cluster instead.

**Which issue(s) this PR fixes**:

Fixes #4431

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
Along with OCP 4.6 and 4.7, `odo link` should work fine on OCP 4.8 and minikube started with `minikube start --kubernetes-version=v1.20.2`

### CODE REVIEW

File: pkg/kclient/deployments.go [hunk 1]
```diff
@@ -364,3 +364,31 @@ func (c *Client) GetDeploymentConfigsFromSelector(selector string) ([]appsv1.Dep
 	}
 	return dcList.Items, nil
 }
+
+// GetDeploymentAPIVersion returns a map with Group, Version, Resource information of Deployment objects
+// depending on the GVR supported by the cluster
+func (c *Client) GetDeploymentAPIVersion() (map[string]string, error) {
```
Comment (kadel) [inline pkg/kclient/deployments.go:370]: Would it be better to use `metav1.GroupVersionResource` as a return type, instead of `map`?

Comment (dharmit) [reply pkg/kclient/deployments.go]: Makes sense to me. Pushed the change. Haven't tested it, however.

File: pkg/odo/cli/component/common_link.go [hunk 2]
```diff
@@ -128,20 +128,18 @@ func (o *commonLinkOptions) complete(name string, cmd *cobra.Command, args []str
...
 			return err
 		}
 
-		// This is a really hacky way to get group, version and resource info but I couldn't find better one.
-		// A sample "deploymentSelfLinkSplit" looks like: [ apis apps v1 namespaces myproject deployments nodejs ]
-		deploymentSelfLinkSplit := strings.Split(deployment.SelfLink, "/")
-
 		// Populate the application selector field in service binding request
 		o.serviceBinding.Spec.Application = &servicebinding.Application{
 			GroupVersionResource: metav1.GroupVersionResource{
```
Comment (kadel) [inline pkg/odo/cli/component/common_link.go:139]: the original reason why I suggested using `metav1.GroupVersionResource` as the return type for `GetDeploymentAPIVersion`  is that you could use it here directly  like this
```
GroupVersionResource: deploymentGVR
```

**Comment by dharmit** [comment]
> New changes are detected. LGTM label has been removed.

Did a force push to rebase on top of #4569
