### PR TITLE
Modify operator hub tests to run in separate namespaces

### LINKED ISSUE #3193: Frequent failures in odo service command tests for OperatorHub
/kind failing-test

[odo test statistics dashboard](https://gist.github.com/jgwest/5b28687514970ae6baa5942ee82d5755) is reporting quite a few failures for `odo service command tests for OperatorHub When operator backed services are created`.

When we delete `example3` service using `oc delete EtcdCluster/example3`, it succeeds. Next we check if `odo service list` returns the message `No operator backed services found in the namesapce` but it doesn't. From the logs, it seems like `example2` service started before `example3` test is not getting deleted.

### PR DESCRIPTION
**Pull request by dharmit**
**What type of PR is this?**
/kind cleanup
/kind failing-test

**What does does this PR do / why we need it**:
This PR ensures that each test spec for operator hub is run in a
separate namespace. This is needed because these tests were written in a
stringent fashion which tied the hands while writing additional tests
for the feature.

This PR should help take the tests out of the "odo test statistics"
dashboard.

**Which issue(s) this PR fixes**:

Fixes #3193

**How to test changes / Special notes to the reviewer**:
* CI should pass. Specially for Operator Hub tests under
`tests/integration/operatorhub`.
* Looks at the review comments I've made for clarification

### CODE REVIEW

File: scripts/setup-operators.sh [hunk 1]
```diff
@@ -28,9 +28,9 @@ install_etcd_operator(){
   kind: Subscription
   metadata:
     name: etcd
-    namespace: ${OPERATOR_HUB_PROJECT}
+    namespace: openshift-operators
```
Comment (dharmit) [inline scripts/setup-operators.sh:31]: Earlier, etcd operator was being installed in `CI_OPERATOR_HUB_PROJECT` and mongodb operator in `openshift-operators`. The way this was done made etcd operator available only in the `CI_OPERATOR_HUB_PROJECT` namespace while mongodb operator was available across the cluster.

Now, I have modified the code to install etcd operator in across the cluster as well. The way this works is, we install it in `openshift-operators` namespace using `clusterwide-alpha` channel. This makes sure that the installed operator is available across all the namespaces on the cluster. Serves the purpose of both installing an operator in single namespce as well as across the cluster.

File: tests/integration/operatorhub/cmd_service_test.go [hunk 2]
```diff
@@ -14,21 +14,68 @@ import (
...
 
+	preSetup := func() {
+		project = helper.CreateRandProject()
+		helper.CmdShouldPass("odo", "project", "set", project)
+
+		// wait till oc can see the all operators installed by setup script in the namespace
+		ocArgs := []string{"get", "csv"}
+		helper.WaitForCmdOut("oc", ocArgs, 1, true, func(output string) bool {
+			return strings.Contains(output, "NAME")
+		}, true)
```
Comment (dharmit) [inline tests/integration/operatorhub/cmd_service_test.go:36]: This is required because every time a user creates a new project, it takes OpenShift a few seconds before it can make the clusterwide operators available to the newly created namespace.

File: tests/integration/operatorhub/cmd_service_test.go [hunk 3]
```diff
@@ -14,21 +14,68 @@ import (
...
+
+		ocArgs = []string{"get", "csv"}
+		helper.WaitForCmdOut("oc", ocArgs, 1, true, func(output string) bool {
+			return strings.Contains(output, "etcd")
+		}, true)
```
Comment (dharmit) [inline tests/integration/operatorhub/cmd_service_test.go:41]: Same as https://github.com/openshift/odo/pull/3239/files#r429151204.

File: tests/integration/operatorhub/cmd_service_test.go [hunk 4]
```diff
@@ -14,21 +14,68 @@ import (
...
+
+		ocArgs = []string{"get", "csv"}
+		helper.WaitForCmdOut("oc", ocArgs, 1, true, func(output string) bool {
+			return strings.Contains(output, "mongo")
+		}, true)
```
Comment (dharmit) [inline tests/integration/operatorhub/cmd_service_test.go:46]: Same as https://github.com/openshift/odo/pull/3239/files#r429151204

File: tests/integration/operatorhub/cmd_service_test.go [hunk 5]
```diff
@@ -62,10 +105,19 @@ var _ = Describe("odo service command tests for OperatorHub", func() {
...
+
+		JustAfterEach(func() {
+			cleanPreSetup()
+		})
+
 		It("should only output the definition of the CR that will be used to start service", func() {
 			// First let's grab the etcd operator's name from "odo catalog list services" output
 			operators := helper.CmdShouldPass("odo", "catalog", "list", "services")
-			etcdOperator := regexp.MustCompile(`etcdoperator\.*[a-z][0-9]\.[0-9]\.[0-9]`).FindString(operators)
+			etcdOperator := regexp.MustCompile(`etcdoperator\.*[a-z][0-9]\.[0-9]\.[0-9]-clusterwide`).FindString(operators)
```
Comment (dharmit) [inline tests/integration/operatorhub/cmd_service_test.go:120]: This modification is done because earlier when etcd operator was installed in a single namespace, output of `odo catalog list services` would be as below:
```sh
odo catalog list services
Operators available in the cluster
NAME                                CRDs
etcdoperator.v0.9.4     EtcdCluster, EtcdBackup, EtcdRestore
```
But since it's now being installed from clusterwide channel, it looks like:
```sh
odo catalog list services
Operators available in the cluster
NAME                                CRDs
etcdoperator.v0.9.4-clusterwide     EtcdCluster, EtcdBackup, EtcdRestore

```

File: scripts/setup-operators.sh (hunk 1 above)
Comment (prietyc123) [inline scripts/setup-operators.sh:31]: Now operators in the namespace `openshift-operators` will be available globally to any namespace, right?

File: scripts/setup-operators.sh [hunk 6]
```diff
@@ -51,25 +51,11 @@ do
     fi
 done
 
-# Now onto namespace bound operator
-# Create OperatorGroup
-oc create -f - <<EOF
```
Comment (prietyc123) [inline scripts/setup-operators.sh:56]: You are removing this because now you are using the default operator namespace `openshift-operators`, right?

Comment (dharmit) [reply scripts/setup-operators.sh:56]: Not "default" really. The `openshift-operators` namespce already has an Operator Group when the OpenShift cluster comes up. So, we don't need to create one ourselves.

File: scripts/setup-operators.sh (hunk 1 above)
Comment (dharmit) [reply scripts/setup-operators.sh:31]: Yes, indeed. :+1:

File: tests/integration/operatorhub/cmd_service_test.go [hunk 7]
```diff
@@ -14,21 +14,68 @@ import (
...
+		project = helper.CreateRandProject()
+		helper.CmdShouldPass("odo", "project", "set", project)
+
+		// wait till oc can see the all operators installed by setup script in the namespace
+		ocArgs := []string{"get", "csv"}
+		helper.WaitForCmdOut("oc", ocArgs, 1, true, func(output string) bool {
+			return strings.Contains(output, "NAME")
+		}, true)
+
+		ocArgs = []string{"get", "csv"}
```
Comment (prietyc123) [inline tests/integration/operatorhub/cmd_service_test.go:38]: Duplicate line

File: scripts/setup-operators.sh (hunk 6 above)
Comment (dharmit) [reply scripts/setup-operators.sh:56]:
```sh
$ oc get og -n openshift-operators
NAME               AGE
global-operators   20d
```

File: tests/integration/operatorhub/cmd_service_test.go [hunk 8]
```diff
@@ -14,21 +14,68 @@ import (
...
+		helper.WaitForCmdOut("oc", ocArgs, 1, true, func(output string) bool {
+			return strings.Contains(output, "etcd")
+		}, true)
+
+		ocArgs = []string{"get", "csv"}
```
Comment (prietyc123) [inline tests/integration/operatorhub/cmd_service_test.go:43]: Duplicate line

File: tests/integration/operatorhub/cmd_service_test.go [hunk 9]
```diff
@@ -14,21 +14,68 @@ import (
...
 	})
 
+	preSetup := func() {
+		project = helper.CreateRandProject()
+		helper.CmdShouldPass("odo", "project", "set", project)
+
+		// wait till oc can see the all operators installed by setup script in the namespace
+		ocArgs := []string{"get", "csv"}
+		helper.WaitForCmdOut("oc", ocArgs, 1, true, func(output string) bool {
+			return strings.Contains(output, "NAME")
```
Comment (prietyc123) [inline tests/integration/operatorhub/cmd_service_test.go:35]: Does the `NAME` make any significance to validate the operators we are looking for up and running? AFAIU operator `etcd` and `mongo` would be enough to be validated for the text search.

File: scripts/setup-operators.sh (hunk 6 above)
Comment (prietyc123) [reply scripts/setup-operators.sh:56]: cool!!!

File: tests/integration/operatorhub/cmd_service_test.go [hunk 10]
```diff
@@ -14,21 +14,68 @@ import (
...
+		}, true)
+
+		ocArgs = []string{"get", "csv"}
+		helper.WaitForCmdOut("oc", ocArgs, 1, true, func(output string) bool {
```
Comment (prietyc123) [inline tests/integration/operatorhub/cmd_service_test.go:39]: How if you execute this `helper.waitForCmdOut` in a loop because only one arg is getting changed? And yes the loop style implementation will look programmatically smart.

File: tests/integration/operatorhub/cmd_service_test.go [hunk 11]
```diff
@@ -74,22 +126,22 @@ var _ = Describe("odo service command tests for OperatorHub", func() {
...
-			for i, line := range lines {
-				if strings.Contains(line, "name: example") {
-					lines[i] = strings.Replace(lines[i], "example", "example2", 1)
-				}
-			}
-			stdOut = strings.Join(lines, "\n")
-
 			// stdOut contains the yaml specification. Store it to a file
 			randomFileName := helper.RandString(6) + ".yaml"
 			fileName := filepath.Join("/tmp", randomFileName)
```
Comment (prietyc123) [inline tests/integration/operatorhub/cmd_service_test.go:147]: This won't work on windows. Please use context instead.

Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go:147]: This is not a part of the PR.

File: tests/integration/operatorhub/cmd_service_test.go (hunk 9 above)
Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go:35]: Makes sense.

File: tests/integration/operatorhub/cmd_service_test.go (hunk 10 above)
Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go:39]: It's two things now - etcd and mongodb. IMO, it's OK to not use loop for it.

File: tests/integration/operatorhub/cmd_service_test.go [hunk 12]
```diff
@@ -101,19 +153,19 @@ var _ = Describe("odo service command tests for OperatorHub", func() {
 			helper.CmdShouldPass("odo", "service", "create", "--from-file", fileName)
 
 			// now verify if the pods for the operator have started
-			pods := helper.CmdShouldPass("oc", "get", "pods", "-n", CI_OPERATOR_HUB_PROJECT)
+			pods := helper.CmdShouldPass("oc", "get", "pods", "-n", project)
```
Comment (prietyc123) [inline tests/integration/operatorhub/cmd_service_test.go:156]: As we are already setting project using odo command, There is no use of explicitly mentioning `-n` flag here. So I did just a check to confirm how `odo project set` sets active projects for `oc` too.

```
$ odo project create xya
 ✓  Project 'xya' is ready for use
 ✓  New project created and now using project: xya
$ odo project list
ACTIVE     NAME
           default
           [...]
           viraj
*          xya
$ oc projects
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    [...]
    viraj
  * xya
$ odo project set viraj
Switched to project : viraj
$ odo project list
ACTIVE     NAME
           default
           [...]
*          viraj
           xya
$ oc projects
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    [...]
  * viraj
    xya
```

File: tests/integration/operatorhub/cmd_service_test.go [hunk 13]
```diff
@@ -101,19 +153,19 @@ var _ = Describe("odo service command tests for OperatorHub", func() {
...
+			ocArgs := []string{"get", "pods", etcdPod, "-o", "template=\"{{.status.phase}}\"", "-n", project}
 			helper.WaitForCmdOut("oc", ocArgs, 1, true, func(output string) bool {
 				return strings.Contains(output, "Running")
 			})
 
 			// Delete the pods created. This should idealy be done by `odo
 			// service delete` but that's not implemented for operator backed
 			// services yet.
-			helper.CmdShouldPass("oc", "delete", "EtcdCluster", "example2")
+			helper.CmdShouldPass("oc", "delete", "EtcdCluster", "example")
```
Comment (prietyc123) [inline tests/integration/operatorhub/cmd_service_test.go:168]: +1

File: tests/integration/operatorhub/cmd_service_test.go [hunk 14]
```diff
@@ -167,58 +228,34 @@ spec:
...
 			// Delete the pods created. This should idealy be done by `odo
 			// service delete` but that's not implemented for operator backed
 			// services yet.
-			helper.CmdShouldPass("oc", "delete", "EtcdCluster", "example3")
+			helper.CmdShouldPass("oc", "delete", "EtcdCluster", "example")
 
 			// Now let's check the output again to ensure expected behaviour
-			stdOut = helper.CmdShouldFail("odo", "service", "list")
-			jsonOut = helper.CmdShouldFail("odo", "service", "list", "-o", "json")
+			stdOut = helper.CmdShouldFail("odo", "service", "list", "--project", project)
```
Comment (prietyc123) [inline tests/integration/operatorhub/cmd_service_test.go:257]: Project has been set in preSetup, So calling it here through `--project` makes no sense to me. Please check the similar occurence throughout the changes.

File: tests/integration/operatorhub/cmd_service_test.go (hunk 7 above)
Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go]: Addressed

File: tests/integration/operatorhub/cmd_service_test.go (hunk 8 above)
Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go]: Addressed

File: tests/integration/operatorhub/cmd_service_test.go (hunk 9 above)
Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go]: Addressed

**Comment by prietyc123** [comment]
Thanks @amitkrout for providing few inputs.

File: tests/integration/operatorhub/cmd_service_test.go [hunk 15]
```diff
@@ -167,58 +222,34 @@ spec:
...
+			jsonOut = helper.CmdShouldFail("odo", "service", "list", "-o", "json", "--project", project)
```
Comment (prietyc123) [inline tests/integration/operatorhub/cmd_service_test.go:252]: https://github.com/openshift/odo/pull/3239#discussion_r429185881

File: tests/integration/operatorhub/cmd_service_test.go (hunk 12 above)
Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go:150]: I'm just being explicit here. Besides, in this comment https://github.com/openshift/odo/issues/3193#issuecomment-632524803 you have mentioned to provide the project name for better user experience. So can you please decide if you want to use `--project` or not?

File: tests/integration/operatorhub/cmd_service_test.go (hunk 14 above)
Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go:251]: https://github.com/openshift/odo/pull/3239#discussion_r429188003

File: tests/integration/operatorhub/cmd_service_test.go (hunk 15 above)
Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go:252]: https://github.com/openshift/odo/pull/3239#discussion_r429188003

File: tests/integration/operatorhub/cmd_service_test.go (hunk 11 above)
Comment (prietyc123) [reply tests/integration/operatorhub/cmd_service_test.go:141]: Yes, I understood but It can be fixed right? It's not a big change that we can go for a new pr and review process. Anyway in the commit message you can mention the fix so that we can find out what this pr fixes.

Comment (prietyc123) [reply tests/integration/operatorhub/cmd_service_test.go:141]: Yes, I understood but It can be fixed right? It's not a big change that we can go for a new pr and review process. Anyway in the commit message you can mention the fix so that we can find out what this pr fixes.

File: tests/integration/operatorhub/cmd_service_test.go [hunk 16]
```diff
@@ -167,58 +222,34 @@ spec:
...
-			helper.WaitForCmdOut("oc", ocArgs, 1, true, func(output string) bool {
-				return strings.Contains(output, "Running")
-			})
+		It("should list the services if they exist", func() {
+			createEtcdClusterService()
 
-			stdOut = helper.CmdShouldPass("odo", "service", "list")
+			stdOut := helper.CmdShouldPass("odo", "service", "list")
 			Expect(stdOut).To(ContainSubstring("example"))
 			Expect(stdOut).To(ContainSubstring("EtcdCluster"))
```
Comment (prietyc123) [inline tests/integration/operatorhub/cmd_service_test.go:239]: Make it in a single check as you have done in https://github.com/openshift/odo/pull/3239/files#diff-49f09fb5341717455c0421b3c592e685R243

File: tests/integration/operatorhub/cmd_service_test.go (hunk 11 above)
Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go:141]: I have not checked if it's a big change or a small one. Last time I tried to fix something in my PR that had not been touched in my PR, it ended up going for a really long time. So, if you think that this line of code is problematic, I humbly request you to open a new issue. But I'm not addressing it in this PR.

File: tests/integration/operatorhub/cmd_service_test.go (hunk 16 above)
Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go:239]: Not touched in this PR. Please open a separate issue for this to be addressed. I can't have double standards between this and https://github.com/openshift/odo/pull/3239#discussion_r429256479 even if I'm aware of the change that needs to be made. I'm sorry.

Comment (prietyc123) [reply tests/integration/operatorhub/cmd_service_test.go:239]: @dharmit Do you need a separate issue for this?

**Comment by dharmit** [comment]
CI's failing in the Operator Hub tests. Looking into it. It works just fine locally. Not sure what's going wrong in the CI. :disappointed:

File: tests/integration/operatorhub/cmd_service_test.go (hunk 12 above)
Comment (prietyc123) [reply tests/integration/operatorhub/cmd_service_test.go:150]: It seems you misunderstood my comment. NP, I have put the details in the [issue](https://github.com/openshift/odo/issues/3241) what was trying to say.

File: tests/integration/operatorhub/cmd_service_test.go (hunk 10 above)
Comment (prietyc123) [reply tests/integration/operatorhub/cmd_service_test.go]: Atm its fine but what if we expand the number of operators in that, then loop will really matters a lot. So lets do it from now to avoid the refactor/cleanup for someone else.

Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go]: Makes sense. Addressed.

File: tests/integration/operatorhub/cmd_service_test.go (hunk 12 above)
Comment (dharmit) [reply tests/integration/operatorhub/cmd_service_test.go:144]: > It seems you misunderstood my comment. NP, I have put the details in the [issue](https://github.com/openshift/odo/issues/3241) what was trying to say.

This comment thread which started from https://github.com/openshift/odo/pull/3239#discussion_r429184825 is about "not using the `-n` flag in tests", whereas that issue is about "project name not showing up in the output". How are the two things similar? How did I misunderstand what you were trying to say? What am I missing here? :thinking: 

> As part of the `--project` flag is concerned TBH it depends on how you are going to use this. Here you have already setting the active project through `odo project set...` that too in `justBeforeEach`. So it really does not make sense to pass the `--project` flag in the spec implementation.
> 
> If you want to use the `--project` flag then don't use set command. Either way implementation will work fine.

This part of your comment is about what you started out with in https://github.com/openshift/odo/pull/3239#discussion_r429184825. But the issue and this comment thread don't seem to have anything in common !

**Comment by dharmit** [comment]
@amitkrout We're running all test spec in separate namespaces in this PR. I'm not sure why the CI is reporting below error. How did the service `example` exist before it was created? I'm likely missing something:
```
 [odo] I0522 12:57:46.421581    9777 preference.go:188] The path for preference file is /tmp/artifacts/.odo/preference.yaml
[odo] apiVersion: etcd.database.coreos.com/v1beta2
[odo] kind: EtcdCluster
[odo] metadata:
[odo]   annotations:
[odo]     etcd.database.coreos.com/scope: clusterwide
[odo]   name: example
[odo] spec:
[odo]   size: 3
[odo]   version: 3.2.13
[odo] 
Running odo with args [odo service create --from-file /tmp/gtlxka.yaml]
[odo] I0522 12:57:46.631585    9800 preference.go:188] The path for preference file is /tmp/artifacts/.odo/preference.yaml
[odo] I0522 12:57:46.631782    9800 preference.go:188] The path for preference file is /tmp/artifacts/.odo/preference.yaml
[odo] I0522 12:57:46.631990    9800 operators.go:17] Fetching list of operators installed in cluster
[odo] I0522 12:57:46.695813    9800 preference.go:188] The path for preference file is /tmp/artifacts/.odo/preference.yaml
[odo] Deploying service of type: EtcdCluster
[odo]  •  Deploying service  ...
[odo] I0522 12:57:46.696082    9800 preference.go:188] The path for preference file is /tmp/artifacts/.odo/preference.yaml
[odo]  ✗  Deploying service [32ms]
[odo]  ✗  etcdclusters.etcd.database.coreos.com "example" already exists
Deleting project: jcewwlhjsd
Running odo with args [odo project delete jcewwlhjsd -f]
[odo] I0522 12:57:47.038910    9818 application.go:49] Unable to list Service Catalog instances: unable to list ServiceInstances: serviceinstances.servicecatalog.k8s.io is forbidden: User "developer" cannot list resource "serviceinstances" in API group "servicecatalog.k8s.io" in the namespace "jcewwlhjsd"
[odo]  ⚠  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project may still exist on a different node.
[odo]  ✓  Deleted project : jcewwlhjsd
• Failure [15.530 seconds]
odo service command tests for OperatorHub
/go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:17
  When using from-file option
  /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:122
    should be able to create a service [It]
    /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:132
    No future change is possible.  Bailing out early after 0.305s.
      
    Running odo with args [odo service create --from-file /tmp/gtlxka.yaml]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
    /go/src/github.com/openshift/odo/tests/helper/helper_run.go:34 
```

**Comment by amitkrout** [comment]
> How did the service example exist before it was created? I'm likely missing something:

Checking

File: tests/integration/operatorhub/cmd_service_test.go [hunk 17]
```diff
@@ -14,21 +13,45 @@ import (
...
 
+	var project string
+
 	BeforeEach(func() {
 		SetDefaultEventuallyTimeout(10 * time.Minute)
 		SetDefaultConsistentlyDuration(30 * time.Second)
-		helper.CmdShouldPass("odo", "project", "set", CI_OPERATOR_HUB_PROJECT)
 		// TODO: remove this when OperatorHub integration is fully baked into odo
-		os.Setenv("ODO_EXPERIMENTAL", "true")
+		helper.CmdShouldPass("odo", "preference", "set", "Experimental", "true")
```
Comment (amitkrout) [inline tests/integration/operatorhub/cmd_service_test.go:24]: Preference will clash for each spec. SO you need to overwrite the preference path each time the spec is called. For example 
```
context = helper.CreateNewContext()
os.Setenv("GLOBALODOCONFIG", filepath.Join(context, "config.yaml"))
helper.CmdShouldPass("odo", "preference", "set", "Experimental", "true")
```

Comment (amitkrout) [reply tests/integration/operatorhub/cmd_service_test.go:24]: Make sure you are un setting the environment variable ```GLOBALODOCONFIG``` in ```AfterEach``` teardown step too

File: tests/integration/operatorhub/cmd_service_test.go (hunk 16 above)
Comment (prietyc123) [reply tests/integration/operatorhub/cmd_service_test.go:256]: Issue https://github.com/openshift/odo/issues/3245

File: tests/integration/operatorhub/cmd_service_test.go (hunk 11 above)
Comment (prietyc123) [reply tests/integration/operatorhub/cmd_service_test.go:135]: Issue has been tracked in https://github.com/openshift/odo/issues/3246

**Comment by amitkrout** [comment]
@dharmit As pre our last discussion over slack, can you please revert back the changes and make the spec run in series. Also create another issue for test failure while running operator hub test cases in parallel. 

Or i am also fine if you want to keep the refactor you made in this pr, but make sure that these test should run sequentially.

**Comment by dharmit** [comment]
> @dharmit As pre our last discussion over slack, can you please revert back the changes and make the spec run in series. Also create another issue for test failure while running operator hub test cases in parallel.
> 
> Or i am also fine if you want to keep the refactor you made in this pr, but make sure that these test should run sequentially and ofcourse a separate issue for test failure while running operator hub test cases in parallel.

I'm going with the second one - keeping the changes in this refactor since that ensures that all specs are run in a separate namespace/project and make the tests run sequentially. And I created the issue #3244 yesterday to track this. :+1:

**Comment by dharmit** [comment]
Travis failure in `generic, login and component command integration tests` looks related to issue in connecting with [registry.access.redhat.com](https://registry.access.redhat.com):
```
[oc] 'Running oc with args [oc --request-timeout 5m import-image java:8 --namespace=hrclrkttrn --from=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.5 --confirm]
[oc] error: tag 1.5 failed: Internal error occurred: received unexpected HTTP status: 503 Service Unavailable
[oc] imagestream.image.openshift.io/java imported with errors
[oc] 
[oc] Name:			java
[oc] Namespace:		hrclrkttrn
[oc] Created:		Less than a second ago
[oc] Labels:			<none>
[oc] Annotations:		openshift.io/image.dockerRepositoryCheck=2020-05-26T15:08:52Z
[oc] Docker Pull Spec:	172.30.1.1:5000/hrclrkttrn/java
[oc] Image Lookup:		local=false
[oc] Unique Images:		0
[oc] Tags:			1
[oc] 
[oc] 8
[oc]   tagged from registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.5
[oc] 
[oc]   ! error: Import failed (InternalError): Internal error occurred: received unexpected HTTP status: 503 Service Unavailable
[oc]       Less than a second ago
[oc] 
[oc] 
Running oc with args [oc annotate istag/java:8 --namespace=hrclrkttrn tags=builder --overwrite]
[oc] Error from server (NotFound): imagestreamtags.image.openshift.io "java:8" not found
Deleting project: hrclrkttrn
Running odo with args [odo project delete hrclrkttrn -f]
[odo] I0526 15:08:53.106541    1730 application.go:49] Unable to list Service Catalog instances: unable to list ServiceInstances: serviceinstances.servicecatalog.k8s.io is forbidden: User "developer" cannot list serviceinstances.servicecatalog.k8s.io in the namespace "hrclrkttrn": no RBAC policy matched
[odo]  ✓  Deleted project : hrclrkttrn
[odo]  ⚠  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project may still exist on a different node.
[odo] I0526 15:08:53.120594    1730 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
Setting current dir to: /home/travis/gopath/src/github.com/openshift/odo/tests/integration
Deleting dir: /tmp/327560218
• Failure [2.306 seconds]
odo component command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/cmd_cmp_test.go:13
  Creating component using symlink
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/component.go:782
    Should be able to deploy a spring boot uberjar file using symlinks in all odo commands [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/component.go:806
    No future change is possible.  Bailing out early after 0.268s.
    Running oc with args [oc annotate istag/java:8 --namespace=hrclrkttrn tags=builder --overwrite]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
    /home/travis/gopath/src/github.com/openshift/odo/tests/helper/helper_run.go:34
```

Travis failure in ` devfile catalog, create, push, delete, registry and docker devfile url command integration tests ` looks related to issue in executing the devrun command:
```
✓  Executing devbuild command "/artifacts/bin/build-container-full.sh" [53s]
[odo] I0526 15:16:34.369462    7091 adapter.go:354] Executing devfile command devrun
[odo]  •  Executing devrun command "/artifacts/bin/start-server.sh"  ...
[odo] I0526 15:16:34.369549    7091 exec.go:24] Executing command [/opt/odo/bin/supervisord ctl stop all] for pod: obopol-6fdf64bcc9-zx6tt in container: runtime
[odo]  ✗  
[odo] Unable to exec command [/opt/odo/bin/supervisord ctl stop all]: 
[odo] 
[odo]  ✗  Executing devrun command "/artifacts/bin/start-server.sh" [7ms]
[odo]  ✗  Failed to start component with name obopol.
[odo] Error: Failed to create the component: unable to execute the run command: error while streaming command: error sending request: Post https://127.0.0.1:8443/api/v1/namespaces/fdwuwerrac/pods/obopol-6fdf64bcc9-zx6tt/exec?command=%2Fopt%2Fodo%2Fbin%2Fsupervisord&command=ctl&command=stop&command=all&container=runtime&stderr=true&stdout=true: read tcp 127.0.0.1:45876->127.0.0.1:8443: read: connection reset by peer
Deleting project: fdwuwerrac
Running odo with args [odo project delete fdwuwerrac -f]
[odo]  ✗  The project fdwuwerrac does not exist. Please check the list of projects using `odo project list`
• Failure [65.081 seconds]
odo devfile push command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:16
  Verify devfile push works
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:49
    should execute the default devbuild and devrun commands if present [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_push_test.go:167
    No future change is possible.  Bailing out early after 60.602s.
    Running odo with args [odo push --devfile devfile.yaml --project fdwuwerrac]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
```

4.2 and 4.5 integration test failures seem like a flake that's being tracked in #2641.

**Comment by amitkrout** [comment]
Applying on basis of https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_odo/3239/pull-ci-openshift-odo-master-v4.4-integration-e2e/699/artifacts/integration-e2e/container-logs/test.log
/lgtm
