### PR TITLE
Wait for rollout

### LINKED ISSUE #2661: odo push doesn't wait for running pod
/kind bug
/area devfile
/priority medium

`odo push` should wait for the Pod to be in running state before exits.
Currently, it does that only for first invocation (when resources are created). But any additional `odo push` doesn't wait.

```
export ODO_EXPERIMENTAL=true

▶ odo push ; kubectl get pods
 •  Push devfile component odo-examples  ...
 ✓  Waiting for component to start [9s]
 ✓  Push devfile component odo-examples [10s]
NAME                           READY   STATUS    RESTARTS   AGE
odo-examples-8cb546c7b-sbmxd   1/1     Running   0          11s

# modify devfile.yaml

▶ odo push ; kubectl get pods
 •  Push devfile component odo-examples  ...
 ✓  Waiting for component to start [174ms]
 ✓  Push devfile component odo-examples [1s]
NAME                           READY   STATUS        RESTARTS   AGE
odo-examples-8cb546c7b-sbmxd   1/1     Terminating   0          71s
```

Also if edits to devfile.yaml caused Pod to get into CrashLoop state users doesn't know about it

### PR DESCRIPTION
**Pull request by kadel**
**What type of PR is this?**

/kind bug
/area devfile

**What does does this PR do / why we need it**:
fixes problem when `odo push` wouldn't wait for new Pod after there was a change in Deployment

**Which issue(s) this PR fixes**:

Fixes #2661

**How to test changes / Special notes to the reviewer**:
use devfile component
`odo push`
update devfile
`odo push`

second push used to fail

### CODE REVIEW

File: tests/integration/cmd_devfile_push_test.go [hunk 1]
```diff
@@ -48,8 +52,12 @@ var _ = Describe("odo devfile push command tests", func() {
 
 			helper.CopyExample(filepath.Join("source", "devfiles", "nodejs"), context)
 
-			output := helper.CmdShouldPass("odo", "push", "--devfile", "devfile.yaml", "--namespace", project)
+			output := helper.CmdShouldPass("odo", "push", "--devfile", "devfile.yaml", "--namespace", namespace)
 			Expect(output).To(ContainSubstring("Changes successfully pushed to component"))
+
+			// update devfile and push again
+			helper.ReplaceString("devfile.yaml", "name: FOO", "name: BAR")
+			helper.CmdShouldPass("odo", "push", "--devfile", "devfile.yaml", "--namespace", namespace)
```
Comment (kadel) [inline tests/integration/cmd_devfile_push_test.go]: This is a new important addition. It actually tests fix in this PR.

Comment (kadel) [inline tests/integration/cmd_devfile_push_test.go]: This is a new important addition. It actually tests fix in this PR.

Comment (kadel) [inline tests/integration/cmd_devfile_push_test.go]: This is a new important addition. It actually tests fix in this PR.

File: pkg/devfile/adapters/kubernetes/component/adapter.go [hunk 2]
```diff
@@ -51,6 +51,11 @@ func (a Adapter) Push(path string, ignoredFiles []string, forceBuild bool, globE
 		return errors.Wrap(err, "unable to create or update component")
 	}
 
+	_, err = a.Client.WaitForDeploymetRollout(a.ComponentName)
+	if err != nil {
+		return err
```
Comment (johnmcollier) [inline pkg/devfile/adapters/kubernetes/component/adapter.go]: Should we wrap this error like we do for the other errors we return from this function?

File: tests/integration/cmd_devfile_push_test.go (hunk 1 above)
Comment (johnmcollier) [reply tests/integration/cmd_devfile_push_test.go]: Good catch, I should have added this when I wrote the tests.

File: pkg/devfile/adapters/kubernetes/component/adapter.go (hunk 2 above)
Comment (kadel) [reply pkg/devfile/adapters/kubernetes/component/adapter.go]: fixed

File: pkg/kclient/deployments.go [hunk 3]
```diff
@@ -18,6 +22,76 @@ func (c *Client) GetDeploymentByName(name string) (*appsv1.Deployment, error) {
...
+	for i := range status.Conditions {
+		c := status.Conditions[i]
+		if c.Type == condType {
+			return &c
+		}
+	}
+	return nil
+}
+
+// WaitForRolllout waits for deployment to finish rollout. Returns the state of the deployment after rollout.
```
Comment (rajivnathan) [inline pkg/kclient/deployments.go]: typo: `WaitForRolllout` -> `WaitForDeploymentRollout`

File: pkg/devfile/adapters/kubernetes/component/adapter.go [hunk 4]
```diff
@@ -51,6 +51,11 @@ func (a Adapter) Push(path string, ignoredFiles []string, forceBuild bool, globE
 		return errors.Wrap(err, "unable to create or update component")
 	}
 
+	_, err = a.Client.WaitForDeploymetRollout(a.ComponentName)
```
Comment (rajivnathan) [inline pkg/devfile/adapters/kubernetes/component/adapter.go]: typo: missing the `n` in `WaitForDeploymetRollout`

File: pkg/kclient/deployments.go (hunk 3 above)
Comment (kadel) [reply pkg/kclient/deployments.go]: fixed

File: pkg/devfile/adapters/kubernetes/component/adapter.go (hunk 4 above)
Comment (kadel) [reply pkg/devfile/adapters/kubernetes/component/adapter.go]: 😇 ups.
Fixed. Thx

**Comment by girishramnani** [comment]
I can see 5 legitimate failures in the CI related to devfile @kadel .
```
• Failure [7.157 seconds]
odo devfile push command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_devfile_push_test.go:15
  when devfile push command is executed
  /go/src/github.com/openshift/odo/tests/integration/cmd_devfile_push_test.go:63
    should not build when no changes are detected in the directory and build when a file change is detected [It]
skipped 80 lines unfold_more
[odo]  ✓  Deleted project : mwcfllxvyl
Setting current dir to: /go/src/github.com/openshift/odo/tests/integration
Deleting dir: /tmp/551487786
• Failure [7.227 seconds]
odo devfile push command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_devfile_push_test.go:15
  when devfile push command is executed
  /go/src/github.com/openshift/odo/tests/integration/cmd_devfile_push_test.go:63
    should build when no changes are detected in the directory and force flag is enabled [It]
skipped 50 lines unfold_more
[odo]  ✓  Deleted project : ctdcckqsqe
Setting current dir to: /go/src/github.com/openshift/odo/tests/integration
Deleting dir: /tmp/958871729
• Failure [6.993 seconds]
odo devfile push command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_devfile_push_test.go:15
  Verify devfile push works
  /go/src/github.com/openshift/odo/tests/integration/cmd_devfile_push_test.go:45
    Check that odo push works with a devfile [It]
skipped 66 lines unfold_more
[odo]  ✓  Deleted project : eahsapgsib
Setting current dir to: /go/src/github.com/openshift/odo/tests/integration
Deleting dir: /tmp/631770455
• Failure [7.340 seconds]
odo devfile push command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_devfile_push_test.go:15
  when devfile push command is executed
  /go/src/github.com/openshift/odo/tests/integration/cmd_devfile_push_test.go:63
    should be able to create a file, push, delete, then push again propagating the deletions [It]
skipped 70 lines unfold_more
[odo]  ✓  Deleted project : aylyrhgjru
Setting current dir to: /go/src/github.com/openshift/odo/tests/integration
Deleting dir: /tmp/325446482
• Failure [7.431 seconds]
odo devfile push command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_devfile_push_test.go:15
  when devfile push command is executed
  /go/src/github.com/openshift/odo/tests/integration/cmd_devfile_push_test.go:63
    should delete the files from the container if its removed locally [It]
skipped 90 lines unfold_more
[Fail] odo devfile push command tests when devfile push command is executed [It] should delete the files from the container if its removed locally 
/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34
```

File: pkg/kclient/deployments.go [hunk 5]
```diff
@@ -18,6 +22,76 @@ func (c *Client) GetDeploymentByName(name string) (*appsv1.Deployment, error) {
...
+		c := status.Conditions[i]
+		if c.Type == condType {
+			return &c
+		}
+	}
+	return nil
+}
+
+// WaitForDeploymentRollout waits for deployment to finish rollout. Returns the state of the deployment after rollout.
+func (c *Client) WaitForDeploymentRollout(deploymentName string) (*appsv1.Deployment, error) {
```
Comment (girishramnani) [inline pkg/kclient/deployments.go]: can we get a unit test for this function?

File: pkg/kclient/deployments.go [hunk 6]
```diff
@@ -18,6 +22,76 @@ func (c *Client) GetDeploymentByName(name string) (*appsv1.Deployment, error) {
...
+		}
+	}()
+
+	select {
+	case val := <-success:
+		return val, nil
+	case err := <-failure:
+		return nil, err
+	case <-time.After(5 * time.Minute):
+		return nil, errors.Errorf("timeout while waiting for %s deployment roll out b", deploymentName)
```
Comment (girishramnani) [inline pkg/kclient/deployments.go]: `roll out b` typo?

File: pkg/kclient/deployments.go [hunk 7]
```diff
@@ -18,6 +22,76 @@ func (c *Client) GetDeploymentByName(name string) (*appsv1.Deployment, error) {
...
+				failure <- errors.New("watch channel was closed")
+				return
+			}
+			//based on https://github.com/kubernetes/kubectl/blob/9a3954bf653c874c8af6f855f2c754a8e1a44b9e/pkg/polymorphichelpers/rollout_status.go#L66-L91
+			if deployment, ok := val.Object.(*appsv1.Deployment); ok {
+				if deployment.Generation <= deployment.Status.ObservedGeneration {
+					cond := getDeploymentCondition(deployment.Status, appsv1.DeploymentProgressing)
+					if cond != nil && cond.Reason == "ProgressDeadlineExceeded" {
+						failure <- fmt.Errorf("deployment %q exceeded its progress deadline", deployment.Name)
+					} else if deployment.Spec.Replicas != nil && deployment.Status.UpdatedReplicas < *deployment.Spec.Replicas {
```
Comment (girishramnani) [inline pkg/kclient/deployments.go]: why do we have `Spec.Replicas` and `Status.Replicas`. is there any difference?

Comment (girishramnani) [reply pkg/kclient/deployments.go]: figured it out. np.

File: pkg/kclient/deployments.go [hunk 8]
```diff
@@ -18,6 +22,76 @@ func (c *Client) GetDeploymentByName(name string) (*appsv1.Deployment, error) {
...
+			val, ok := <-w.ResultChan()
+			if !ok {
+				failure <- errors.New("watch channel was closed")
+				return
+			}
+			//based on https://github.com/kubernetes/kubectl/blob/9a3954bf653c874c8af6f855f2c754a8e1a44b9e/pkg/polymorphichelpers/rollout_status.go#L66-L91
+			if deployment, ok := val.Object.(*appsv1.Deployment); ok {
+				if deployment.Generation <= deployment.Status.ObservedGeneration {
+					cond := getDeploymentCondition(deployment.Status, appsv1.DeploymentProgressing)
+					if cond != nil && cond.Reason == "ProgressDeadlineExceeded" {
```
Comment (girishramnani) [inline pkg/kclient/deployments.go]: `ProgressDeadlineExceeded` make this a constant maybe?

File: pkg/kclient/deployments.go (hunk 5 above)
Comment (kadel) [reply pkg/kclient/deployments.go]: > I can see 5 legitimate failures in the CI related to devfile @kadel .

ouch, messed something up after rebasing with latest master :-/

**Comment by kadel** [comment]
> I can see 5 legitimate failures in the CI related to devfile @kadel .

ouch, messed something up after rebasing with latest master :-/

File: pkg/kclient/deployments.go (hunk 8 above)
Comment (kadel) [reply pkg/kclient/deployments.go]: done

File: pkg/kclient/deployments.go (hunk 6 above)
Comment (kadel) [reply pkg/kclient/deployments.go]: fixed

File: tests/integration/cmd_devfile_push_test.go [hunk 9]
```diff
@@ -13,18 +13,20 @@ import (
...
 var _ = Describe("odo devfile push command tests", func() {
-	var project string
+	var namespace string
 	var context string
 	var currentWorkingDirectory string
 
 	var sourcePath = "/projects"
 
+	// TODO: all oc commands in all devfile related test should get replaced by kubectl
+	// TODO: to goal is not to use "oc"
```
Comment (amitkrout) [inline tests/integration/cmd_devfile_push_test.go]: Please create a github issue so that we won't loose eye on it

File: pkg/kclient/deployments.go (hunk 5 above)
Comment (amitkrout) [reply pkg/kclient/deployments.go]: Same question

**Comment by adisky** [comment]
Looks good to me, Second push is succeeded with this PR,  just wondering why `Push devfile component openlibertydevfile`  is getting printed two times.
````
adisky@localhost openLibertyDevfile]$ odo push 
 •  Push devfile component openlibertydevfile  ...
 ✓  Checking file changes for pushing [1ms]
 ✓  Waiting for component to start [35ms]
 ✓  Syncing files to the component [22s]
 ✓  Push devfile component openlibertydevfile [1m]
 ✓  Changes successfully pushed to component
```

File: tests/integration/cmd_devfile_push_test.go (hunk 9 above)
Comment (kadel) [reply tests/integration/cmd_devfile_push_test.go]: #2752
