### PR TITLE
Restart command when stopped on odo push

### LINKED ISSUE #4822: Applications in pods not starting on CodeReady Container restart
/kind bug

## What versions of software are you using?

**Operating System:**
Macos latest

**Output of `odo version`:**
odo v2.2.1 (17a078b67)

Server: https://api.crc.testing:6443
Kubernetes: v1.20.0+75370d3

# How did you run odo exactly?
Running latest CodeReady Container version of OpenShift on my Mac. I am able to push applications to the cluster and they are working fine. Using the "odo push" command. Scaling number of pods works fine, and they all start and run the node application.

When I stop the CodeReady Container (crc stop), and start it again (crc start) - the pods are starting and seems to run fine. But when I open the URL of any of them - I get "Application is not available". I get the same on all applications - even "Hello World" kind of applications.

So somehow shutting down CRC and starting it again creates some "strange status" on the pods. I have tried to delete the pods from OpenShift console and also to scale to 0 instances and then add instances, but they still do not work. So even if OpenShift removes the pods and start new instances - they fail. Logs do not give any info. They only way to "fix" the application is to do a "odo push -f" that forces rebuild and redeploy of the application in the OpenShift cluster.

I did some investigation, and it seems that when restarting CRC, the pods are started, but the "npm start" is not run to actually start the node application within the pod. So the pod is running, the code is deployed in /project, but the application is not started. If I open the pod terminal, I can see that sometimes the /project folder has data in it and if I run "npm start" manually from the /project folder, the application starts again, but scaling e.g. to 2 pods are not working - the second pod is not working - because it will have the /project folder empty for some reason. Sometimes on crc restart, I find that the /project folder is empty also.

This is pod log from a series of events:

* Initial odo push and 2 few test pages in browser - everything working fine:

```
time="2021-06-17T05:09:21Z" level=info msg="create process:devrun" 
time="2021-06-17T05:09:21Z" level=info msg="create process:debugrun" 
time="2021-06-17T05:09:32Z" level=debug msg="no auth required" 
time="2021-06-17T05:09:32Z" level=debug msg="succeed to find process:devrun" 
time="2021-06-17T05:09:32Z" level=info msg="try to start program" program=devrun 
time="2021-06-17T05:09:32Z" level=info msg="success to start program" program=devrun 
ODO_COMMAND_RUN is npm start
Changing directory to /project
Executing command cd /project && npm start

> nodejs-ex@0.0.1 start /project
> node server.js

Server running on http://0.0.0.0:8080
time="2021-06-17T05:09:33Z" level=debug msg="wait program exit" program=devrun 
time="2021-06-17T05:09:35Z" level=debug msg="no auth required" 
10.217.0.1 - - [17/Jun/2021:05:09:41 +0000] "GET / HTTP/1.1" 200 40430 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36"
10.217.0.1 - - [17/Jun/2021:05:14:56 +0000] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36"

```
* Running crc stop to shut down:

```
time="2021-06-17T05:15:17Z" level=info msg="receive a signal to stop all process & exit" signal=terminated 
time="2021-06-17T05:15:17Z" level=info msg="stop the program" program=devrun 
time="2021-06-17T05:15:17Z" level=info msg="force to kill the program" program=devrun 
time="2021-06-17T05:15:18Z" level=error msg="program stopped with error:signal: terminated" program=devrun 
time="2021-06-17T05:15:18Z" level=info msg="Stopped by user, don't start it again" program=devrun 
time="2021-06-17T05:15:19Z" level=info msg="stop the program" program=debugrun 
```

* Running crc start to start again - application is not started:

```
ime="2021-06-17T05:21:46Z" level=info msg="create process:devrun" 
time="2021-06-17T05:21:47Z" level=info msg="create process:debugrun" 

```

## Actual behavior
odo pushed applications are not running after CRC restart. The pods are running, but they are not started. Sometimes the application code has disappeared from the "/project" folder as well. "odo push -f" is only way to fix.

## Expected behavior
Running pods should have the application running as well.

## Any logs, error output, etc?
See above.

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this?**

/kind bug

**What does this PR do / why we need it**:

`odo push` checks that the component is running on the container. If not, it starts it

**Which issue(s) this PR fixes**:

Fixes #4822

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

File: pkg/devfile/adapters/kubernetes/component/adapter.go [hunk 1]
```diff
@@ -339,6 +340,24 @@ func (a Adapter) Push(parameters common.PushParameters) (err error) {
 	return nil
 }
 
+func (a Adapter) GetSupervisordCtlStatus(command devfilev1.Command) bool {
```
Comment (mik-dass) [inline pkg/devfile/adapters/kubernetes/component/adapter.go:343]: Please add some comments for the function. Since this function is quite similar to `CheckSupervisordCtlStatus`, it might be a good idea to modify and add the functionality to it.

**Review by dharmit — COMMENTED** [review]
/approve

Functionality is OK.

But I'm confused by the functions `CheckSupervisordCtlStatus` and `GetSupervisordCtlStatus`.
1. Of course, the name is causing most of the confusion.
2. But besides that, IIUC, they both are checking/getting the status of the devfile run/debug command and the not the status of supervisord command itself. The name kinda suggests as though we're checking if supervisord itself is running fine in the pod.

**Comment by feloy** [comment]
Also, please have a look at the second part of the resolution in this PR: https://github.com/openshift/odo-init-image/pull/93

**Comment by dharmit** [comment]
> But I'm confused by the functions `CheckSupervisordCtlStatus` and `GetSupervisordCtlStatus`.
> 
>   1. Of course, the name is causing most of the confusion.
> 
>   2. But besides that, IIUC, they both are checking/getting the status of the devfile run/debug command and the not the status of supervisord command itself. The name kinda suggests as though we're checking if supervisord itself is running fine in the pod.

@feloy do you think we can do something about this? I didn't LGTM because I found this a bit concerning.

**Comment by feloy** [comment]
> > But I'm confused by the functions `CheckSupervisordCtlStatus` and `GetSupervisordCtlStatus`.
> > 
> > 1. Of course, the name is causing most of the confusion.
> > 2. But besides that, IIUC, they both are checking/getting the status of the devfile run/debug command and the not the status of supervisord command itself. The name kinda suggests as though we're checking if supervisord itself is running fine in the pod.
> 
> @feloy do you think we can do something about this? I didn't LGTM because I found this a bit concerning.

Yes, I'll try to make this clearer

**Review by dharmit — APPROVED** [review]
@feloy thanks for the changes. Function names & comments are clearer now. 👍🏾

**Comment by feloy** [comment]
@dharmit I had to make some changes (renaming is not as easy as `F2` when interfaces are involved :( ) Can you please lgtm again if the tests pass?

File: pkg/devfile/adapters/kubernetes/component/adapter.go [hunk 2]
```diff
@@ -339,9 +343,10 @@ func (a Adapter) Push(parameters common.PushParameters) (err error) {
 	return nil
 }
 
-// CheckSupervisordCtlStatus checks the supervisord status according to the given command
-// if the command is not in a running state, we fetch the last 20 lines of the component's log and display it
-func (a Adapter) CheckSupervisordCtlStatus(command devfilev1.Command) error {
+// GetSupervisordCommandStatus returns true if the command is running
+// based on `supervisord ctl` output and returns an error if
+// the command is not known by supersisord
```
Comment (valaparthvi) [inline pkg/devfile/adapters/kubernetes/component/adapter.go:348]: supervisord*

**Comment by dharmit** [comment]
> @dharmit I had to make some changes (renaming is not as easy as `F2` when interfaces are involved :( ) Can you please lgtm again if the tests pass?

Oh. I'm sorry about that. Can I suggest you to try GoLand for such cases? I'm not sure about `.go` files, but I have been using it even when writing odo docs. When I try to delete a file, it does a sanity check in the repo if that file is being referenced anywhere. Out of curiosity, I tried the same on VS Code, but it didn't perform checks like that.

**Comment by dharmit** [comment]
/lgtm 

As the review feedback has been addressed.

**Comment by dharmit** [comment]
> I'm not sure about `.go` files, but I have been using it even when writing odo docs. When I try to delete a file, it does a sanity check in the repo if that file is being referenced anywhere. Out of curiosity, I tried the same on VS Code, but it didn't perform checks like that.

@feloy I can confirm that GoLand does indeed make renaming simpler. I renamed a method in the `pkg/odo/cli/service/interface.go` file just to play with things, and it renamed it across the code wherever it was being implemented. `Rename` option is under `Refactor` when you right-click on a method name. Or use `Shift+F6` shortcut.
