### PR TITLE
Fix windows incompatibility with /tmp

### LINKED ISSUE #3246: filepath.Join("/tmp", randomFileName) does not support on windows
/kind bug

## What versions of software are you using?

**Operating System:**
Windows

**Output of `odo version`:**
master

## How did you run odo exactly?
Running `filepath.Join("/tmp", randomFileName)` on windows.

## Actual behavior
`/tmp/randomFileName` throws error as `/tmp` won't be identified on windows.

## Expected behavior 
Defining `/tmp` in some context should work

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind bug

**What does does this PR do / why we need it**:
The purpose of the pr is to make `/tmp` compatible for All supported OS

**Which issue(s) this PR fixes**:

Fixes #3246 

**How to test changes / Special notes to the reviewer**:

The changes should work for all the platform.

### CODE REVIEW

**Comment by prietyc123** [comment]
Flake https://travis-ci.com/github/openshift/odo/jobs/340436251#L594 already covered in https://github.com/openshift/odo/issues/3122. 
Restarted the job

File: tests/integration/operatorhub/cmd_service_test.go [hunk 1]
```diff
@@ -92,7 +92,7 @@ var _ = Describe("odo service command tests for OperatorHub", func() {
 
 			// stdOut contains the yaml specification. Store it to a file
 			randomFileName := helper.RandString(6) + ".yaml"
-			fileName := filepath.Join("/tmp", randomFileName)
+			fileName := filepath.Join(os.TempDir(), randomFileName)
```
Comment (amitkrout) [inline tests/integration/operatorhub/cmd_service_test.go:95]: @prietyc123 +1, however i would suggest keep those lines that bring changes to the system in a teardown steps like ```justBeforeEach``` and ```JustAfterEach```. Because, consider a case where you created a file within a spec and did certain operation and an immediate ```oc``` or ```odo``` command fails, then the created file will be left behind for sure. So it's better to have those things in teardown steps, in case the spec command fails the teardown steps will anyway cleanup these files. 

I won't mind if you fix this in a separate pr. But for now atleast remove the created file at the end of the spec.

Comment (prietyc123) [reply tests/integration/operatorhub/cmd_service_test.go:95]: > however i would suggest keep those lines that bring changes to the system in a teardown steps like `justBeforeEach` and `JustAfterEach`.

+1 Good point, its better to accumulate all those such cases in our test suite and fix them in a single shoot, i will take a look and send another in pr as a refactor for sure.

Comment (amitkrout) [reply tests/integration/operatorhub/cmd_service_test.go:95]: /lgtm

**Comment by prietyc123** [comment]
Failure mentioned in [comment](https://github.com/openshift/odo/issues/2877#issuecomment-635105783)

/retest

**Comment by amitkrout** [comment]
prow failure
/retest

**Comment by dharmit** [comment]
Tests are failing with following error:
```
 Test Suite Passed
+ make test-operator-hub
ginkgo  -randomizeAllSpecs -slowSpecThreshold=120 -timeout 7200s -nodes=1 -focus="odo service command tests" tests/integration/operatorhub/
Failed to compile operatorhub:
# github.com/openshift/odo/tests/integration/operatorhub [github.com/openshift/odo/tests/integration/operatorhub.test]
tests/integration/operatorhub/cmd_service_test.go:132:30: undefined: os
Ginkgo ran 1 suite in 2.124275347s
Test Suite Failed
make: *** [test-operator-hub] Error 1
2020/06/01 06:30:04 Container test in pod integration-e2e failed, exit code 2, reason Error
2020/06/01 06:44:49 Copied 178.39MB of artifacts from integration-e2e to /logs/artifacts/integration-e2e
2020/06/01 06:44:49 Releasing lease for "aws-quota-slice"
2020/06/01 06:44:49 No custom metadata found and prow metadata already exists. Not updating the metadata.
2020/06/01 06:44:50 Ran for 2h0m22s 
```
The cause is:
```
tests/integration/operatorhub/cmd_service_test.go:132:30: undefined: os
```
This is happening in spite of `os` module being imported in the mentioned file.

Another thing I've observed is that this PR is based on somewhat old version of `master`. If it makes sense, can we rebase it so as to be sure that we're not debugging against the outdated code?

I'll remove the lgtm label so that re-test triggers are stopped.
