### PR TITLE
resolved panic on port set

### LINKED ISSUE #1523: Config set port panic out
[kind/bug]

## What versions of software are you using?
- Operating System: 
- Output of `odo version`: master

## How did you run odo exactly?
$ odo config set Ports 8080/TCP  - panic out
$ odo config set ports 8080/TCP - panic out
$ odo config set --ports 8080/TCP - unknown flag: --ports

## Actual behavior
Fails

## Expected behavior
Should set

## Any logs, error output, etc?
```
$ odo config set ports 8080/TCP
panic: interface conversion: interface {} is string, not []string

goroutine 1 [running]:
github.com/openshift/odo/pkg/config.(*LocalConfigInfo).SetConfiguration(0xc00013efd0, 0x7ffeefbffbcf, 0x5, 0x2296560, 0xc000af3410, 0x0, 0x2593d53)
        /Users/amit/go/src/github.com/openshift/odo/pkg/config/config.go:184 +0x103b
github.com/openshift/odo/pkg/odo/cli/config.(*SetOptions).Run(0xc0004ebe00, 0x0, 0x0)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/cli/config/set.go:106 +0x105
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x28182a0, 0xc0004ebe00, 0xc0007acb40, 0xc0006c0180, 0x2, 0x2)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:17 +0xf2
github.com/openshift/odo/pkg/odo/cli/config.NewCmdSet.func2(0xc0007acb40, 0xc0006c0180, 0x2, 0x2)
        /Users/amit/go/src/github.com/openshift/odo/pkg/odo/cli/config/set.go:142 +0x5e
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc0007acb40, 0xc0006c0120, 0x2, 0x2, 0xc0007acb40, 0xc0006c0120)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702 +0x289
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00059b440, 0x0, 0x0, 0x4)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783 +0x29f
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/amit/go/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
        /Users/amit/go/src/github.com/openshift/odo/cmd/odo/odo.go:73 +0x489
```
```
$ odo config set --ports 8080/TCP
Error: unknown flag: --ports
Usage:
  odo config set [flags]

Examples:

  # Set a configuration value in the local config
  odo config set Type java
  odo config set Name test
  odo config set MinMemory 50M
  odo config set MaxMemory 500M
  odo config set Memory 250M
  odo config set Ignore false
  odo config set MinCPU 0.5
  odo config set MaxCPU 2
  odo config set CPU 1
  
  # Set a env variable in the local config
  odo config set Type --env PORT=4000
  odo config set Name --env DB_USERNAME=postgres,DB_HOSTNAME=postgres
  odo config set MinMemory --env KAFKA_HOST=kafka --env KAFKA_PORT=6639

Flags:
  -e, --env stringSlice   Set the environment variables in config
  -f, --force             Don't ask for confirmation, set the config directly
  -h, --help              help for set

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files (default false)
      --skip-connection-check            Skip cluster check
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

 ✗  unknown flag: --ports
```

### PR DESCRIPTION
**Pull request by girishramnani**
## What is the purpose of this change? What does it change?
Resolves a panic while setting port config

## Was the change discussed in an issue?
fixes #1523 

## How to test changes?
```
$ odo config set Ports 8080/TCP - panic out
$ odo config set ports 8080/TCP - panic out
```
shouldn't panic

### CODE REVIEW

**Comment by girishramnani** [comment]
added regression in UT to make sure this doesn't occur again @amitkrout

File: pkg/config/config_test.go [hunk 1]
```diff
@@ -22,6 +22,7 @@ func TestSetLocalConfiguration(t *testing.T) {
 	maxCPUValue := "2"
 	minMemValue := "500M"
 	testValue := "test"
+	ports := "8080/TCP,45/UDP"
```
Comment (kadel) [inline pkg/config/config_test.go]: we should have tests for all the other options. The whole switch case in `SetConfiguration` needs to be covered

Comment (girishramnani) [reply pkg/config/config_test.go]: maybe in another PR?

File: pkg/config/config.go [hunk 2]
```diff
@@ -186,7 +186,7 @@ func (lci *LocalConfigInfo) SetConfiguration(parameter string, value interface{}
 		case "sourcelocation":
 			lci.componentSettings.SourceLocation = &strValue
 		case "ports":
-			arrValue := value.([]string)
+			arrValue := strings.Split(strValue, ",")
```
Comment (kadel) [inline pkg/config/config.go]: wouldn't it be better to convert this huge switch case to separate set functions to avoid using `interface{}` like we have with get*?

File: pkg/config/config_test.go (hunk 1 above)
Comment (girishramnani) [reply pkg/config/config_test.go]: the scope of this seems like to be resolving the panic

File: pkg/config/config.go (hunk 2 above)
Comment (girishramnani) [reply pkg/config/config.go]: sure, we can have an issue which scopes out all the issues with `SetConfiguration`

**Comment by amitkrout** [comment]
@girishramnani ```odo config set Ports 8080/TCP``` went fine but push stuck in ```✓  Creating project odo2-1553604360``` step.
```
$ odo push
 ✓  Checking component
 ✓  Checking component version
 ✓  Creating project odo2-1553604360
```

config.yaml
```
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: php
  SourceLocation: https://github.com/appuio/example-php-sti-helloworld
  SourceType: git
  Ports:
  - 8080/TCP
  Application: testing
  Project: odo2-1553604360
  Name: testcmp
```

Can you please check

File: pkg/config/config_test.go (hunk 1 above)
Comment (kadel) [reply pkg/config/config_test.go]: It is just resolving this one particular case.
It does nothing to prevent from happening this again with other option.

**Comment by girishramnani** [comment]
> @girishramnani `odo config set Ports 8080/TCP` went fine but push stuck in `✓ Creating project odo2-1553604360` step.
> 
> ```
> $ odo push
>  ✓  Checking component
>  ✓  Checking component version
>  ✓  Creating project odo2-1553604360
> ```
> config.yaml
> 
> ```
> kind: LocalConfig
> apiversion: odo.openshift.io/v1alpha1
> ComponentSettings:
>   Type: php
>   SourceLocation: https://github.com/appuio/example-php-sti-helloworld
>   SourceType: git
>   Ports:
>   - 8080/TCP
>   Application: testing
>   Project: odo2-1553604360
>   Name: testcmp
> ```
> Can you please check

@anmolbabu PTAL at this as well

**Comment by girishramnani** [comment]
I can add an e2e for this sure @anmolbabu

**Comment by anmolbabu** [comment]
> > @girishramnani `odo config set Ports 8080/TCP` went fine but push stuck in `✓ Creating project odo2-1553604360` step.
> > ```
> > $ odo push
> >  ✓  Checking component
> >  ✓  Checking component version
> >  ✓  Creating project odo2-1553604360
> > ```
> > config.yaml
> > ```
> > kind: LocalConfig
> > apiversion: odo.openshift.io/v1alpha1
> > ComponentSettings:
> >   Type: php
> >   SourceLocation: https://github.com/appuio/example-php-sti-helloworld
> >   SourceType: git
> >   Ports:
> >   - 8080/TCP
> >   Application: testing
> >   Project: odo2-1553604360
> >   Name: testcmp
> > ```
> > Can you please check
> 
> @anmolbabu PTAL at this as well

@girishramnani You might need to run it in verbose mode to get more logs

File: pkg/config/config.go (hunk 2 above)
Comment (kadel) [reply pkg/config/config.go]: I think that the sooner we fix this properly the better

**Comment by amitkrout** [comment]
> > > @girishramnani `odo config set Ports 8080/TCP` went fine but push stuck in `✓ Creating project odo2-1553604360` step.
> > > ```
> > > $ odo push
> > >  ✓  Checking component
> > >  ✓  Checking component version
> > >  ✓  Creating project odo2-1553604360
> > > ```
> > > config.yaml
> > > ```
> > > kind: LocalConfig
> > > apiversion: odo.openshift.io/v1alpha1
> > > ComponentSettings:
> > >   Type: php
> > >   SourceLocation: https://github.com/appuio/example-php-sti-helloworld
> > >   SourceType: git
> > >   Ports:
> > >   - 8080/TCP
> > >   Application: testing
> > >   Project: odo2-1553604360
> > >   Name: testcmp
> > > ```
> > > Can you please check
> > 
> > 
> > @anmolbabu PTAL at this as well
> 
> @girishramnani You might need to run it in verbose mode to get more logs Offcourse creating project being stuck is something weird and in my opinion un-related to ports in anyway
> 
> The only time ports come into picture is once it starts creating component i.e, after the message along the lines `Creating %s component with name %s` appears

Probably it was a glitch. Now i am able to push the changes and i can see ```Port``` is reflected in dc.

**Comment by anmolbabu** [comment]
> > > > @girishramnani `odo config set Ports 8080/TCP` went fine but push stuck in `✓ Creating project odo2-1553604360` step.
> > > > ```
> > > > $ odo push
> > > >  ✓  Checking component
> > > >  ✓  Checking component version
> > > >  ✓  Creating project odo2-1553604360
> > > > ```
> > > > config.yaml
> > > > ```
> > > > kind: LocalConfig
> > > > apiversion: odo.openshift.io/v1alpha1
> > > > ComponentSettings:
> > > >   Type: php
> > > >   SourceLocation: https://github.com/appuio/example-php-sti-helloworld
> > > >   SourceType: git
> > > >   Ports:
> > > >   - 8080/TCP
> > > >   Application: testing
> > > >   Project: odo2-1553604360
> > > >   Name: testcmp
> > > > ```
> > > > Can you please check
> > > 
> > > 
> > > @anmolbabu PTAL at this as well
> > 
> > 
> > @girishramnani You might need to run it in verbose mode to get more logs Offcourse creating project being stuck is something weird and in my opinion un-related to ports in anyway
> > The only time ports come into picture is once it starts creating component i.e, after the message along the lines `Creating %s component with name %s` appears
> 
> Probably it was a glitch. Now i am able to push the changes and i can see `Port` is reflected in dc.

Wow that's good news :) (It avoided us of a new bug ;) )

**Comment by anmolbabu** [comment]
> Add the e2e test scenario just after line https://github.com/openshift/odo/blob/master/tests/e2e/e2e_test.go#L365
> 
> ```
> runCmdShouldPass(odo config set Ports 8080/TCP)
> runCmdShouldPass("odo push")
> runCmdShouldPass("odo url create")
> ```

We should ideally also check it for update scenario

File: pkg/config/config.go (hunk 2 above)
Comment (girishramnani) [reply pkg/config/config.go]: a switch will always be there it will just be moved up in the set.go of the cli package

File: pkg/config/config_test.go (hunk 1 above)
Comment (girishramnani) [reply pkg/config/config_test.go]: done, added e2e test for each param

File: pkg/config/config.go (hunk 2 above)
Comment (girishramnani) [reply pkg/config/config.go]: lets record this in an issue

**Comment by girishramnani** [comment]
> > Add the e2e test scenario just after line https://github.com/openshift/odo/blob/master/tests/e2e/e2e_test.go#L365
> > ```
> > runCmdShouldPass(odo config set Ports 8080/TCP)
> > runCmdShouldPass("odo push")
> > runCmdShouldPass("odo url create")
> > ```
> 
> We should ideally also check it for update scenario

should we do this and what @amitkrout said as part of this PR or another?

**Comment by girishramnani** [comment]
blocked on https://github.com/openshift/odo/pull/1517

**Comment by girishramnani** [comment]
possibly unblocked

**Comment by mohammedzee1000** [comment]
Should merge once travis is green :)
