### PR TITLE
Fixes the symlink path for the binary flag

### LINKED ISSUE #2282: Component create fails with flag —context when —binary is located in temp folder
[kind/bug]

## What versions of software are you using?
- Operating System: **macOS**
- Output of `odo version`: master

## How did you run odo exactly?
```
$ odo component create wildfly --project test123 --binary /var/folders/c9/fb55pf_568dfd1fzj9w1v4n00000gn/T/test/ROOT.war --context /var/folders/c9/fb55pf_568dfd1fzj9w1v4n00000gn/T/test/ 
 ✗  Validating component [1s]
 ✗  ../../../../../../private/var/folders/c9/fb55pf_568dfd1fzj9w1v4n00000gn/T/test/ROOT.war binary needs to be inside of the context directory (/var/folders/c9/fb55pf_568dfd1fzj9w1v4n00000gn/T/test/)
```

## Actual behavior
Component creation fails on **macOS**. 
```
$ ls /var/folders/c9/fb55pf_568dfd1fzj9w1v4n00000gn/T/test
ROOT.war
$ ls /private/var/folders/c9/fb55pf_568dfd1fzj9w1v4n00000gn/T/test/
ROOT.war
```
odo confuses between which ```$TMPDIR``` to use in --context when binary is already located in temp folder.

This causing the test script failure in java test on macOS -  https://github.com/openshift/odo/blob/master/tests/e2escenarios/e2e_java_test.go#L60

On WIndows and linux system same test script it works 

## Expected behavior
Should work

### PR DESCRIPTION
**Pull request by mik-dass**
fixes #2282 

How to test:
* create a symlink and try odo create command using it

### CODE REVIEW

File: tests/integration/component.go [hunk 1]
```diff
@@ -693,4 +694,52 @@ func componentTests(args ...string) {
...
+
+		It("Should be able to deploy a spring boot uberjar file using openjdk", func() {
+			oc.ImportJavaIS(project)
+
+			// change to the parent of the context
+			helper.Chdir(filepath.Dir(context))
+
+			// create a symlink
+			symLinkName := "symLink"
+			helper.SymLink(filepath.Base(context), symLinkName)
```
Comment (kadel) [inline tests/integration/component.go]: Shouldn't the symlink creation be part of the test setup (in `JustBeforeEach`)?

File: tests/integration/component.go [hunk 2]
```diff
@@ -693,4 +694,52 @@ func componentTests(args ...string) {
...
+			symLinkPath = filepath.Join(filepath.Dir(context), symLinkName)
+
+			helper.CopyExample(filepath.Join("binary", "java", "openjdk"), context)
+
+			// create the component using symlink
+			helper.CmdShouldPass("odo", "create", "java:8", "sb-jar-test", "--project",
+				project, "--binary", filepath.Join(symLinkPath, "sb.jar"), "--context", symLinkPath)
+
+			// Create a URL and push without using the symlink
+			helper.CmdShouldPass("odo", "url", "create", "uberjaropenjdk", "--port", "8080", "--context", context)
```
Comment (kadel) [inline tests/integration/component.go]: we should test symlink with each command, so instead  of using `context` you should use `symLinkPath`

File: tests/integration/component.go [hunk 3]
```diff
@@ -693,4 +694,52 @@ func componentTests(args ...string) {
...
+			helper.CmdShouldPass("odo", "push", "--context", context)
```
Comment (kadel) [inline tests/integration/component.go]: `symLinkPath` instead of `context`

File: tests/integration/component.go [hunk 4]
```diff
@@ -693,4 +694,52 @@ func componentTests(args ...string) {
...
+			routeURL := helper.DetermineRouteURL(context)
+
+			// Ping said URL
+			helper.HttpWaitFor(routeURL, "HTTP Booster", 90, 1)
+
+			// Delete the component
+			helper.CmdShouldPass("odo", "delete", "sb-jar-test", "-f", "--context", context)
```
Comment (kadel) [inline tests/integration/component.go]: `symLinkPath` instead of `context`

File: tests/integration/component.go (hunk 1 above)
Comment (kadel) [reply tests/integration/component.go]: Wouldn't this create a symlink to context dir inside the context dir itself?

if the context is for example `/tmp/test` the symlink will be `/tmp/test/symLink` pointing to `/tmp/test`, is that what you want, or am I missing something?

Comment (kadel) [reply tests/integration/component.go]: Also, this doesn't look right at all. For example, if the context is `/tmp/test/1` this will call `symlink("1","symLink") in the `/tmp/test/1` directory and it will fail.

Comment (kadel) [reply tests/integration/component.go]: It would be better and cleaner to create a new tempory dir, and create symlink inside it

Comment (mik-dass) [reply tests/integration/component.go]: I did it because someone might want to add a similar test in the same context which will have a symlink to a file

File: tests/integration/component.go (hunk 2 above)
Comment (mik-dass) [reply tests/integration/component.go]: Just wanted to make sure that the other odo commands work seamlessly even if the component was created using a symlink

File: tests/integration/component.go (hunk 4 above)
Comment (mik-dass) [reply tests/integration/component.go]: https://github.com/openshift/odo/pull/2308#pullrequestreview-305012149

File: tests/integration/component.go (hunk 3 above)
Comment (mik-dass) [reply tests/integration/component.go]: https://github.com/openshift/odo/pull/2308#discussion_r337386705

File: tests/integration/component.go (hunk 1 above)
Comment (mik-dass) [reply tests/integration/component.go]: > Also, this doesn't look right at all. For example, if the context is /tmp/test/1 this will call symlink("1","symLink") in the /tmp/test/1` directory and it will fail.

I am switching to the parent directory which is `/tmp` before running the test and thus the symlink is created inside `tmp`

**Comment by amitkrout** [comment]
@mik-dass Can you please test it on Win setup.

File: tests/integration/component.go (hunk 1 above)
Comment (kadel) [reply tests/integration/component.go]: > I am switching to the parent directory which is `/tmp` before running the test and thus the symlink is created inside `tmp`

I missed that. But still this is not good. As you are switching from a randomly created directory to on elevel up. If two such tests are run at the same time it will fail on as they will both they to create the same symlink.
```
    Unexpected error:
        <*os.LinkError | 0xc0002d8400>: {Op: "symlink", Old: "145303116", New: "symLink", Err: 0x11}
        symlink 145303116 symLink: file exists
    occurred
```

Comment (kadel) [reply tests/integration/component.go]: > I did it because someone might want to add a similar test in the same context which will have a symlink to a file

if we need such a test we can always split it into nested context and break `JustBeforeEach` and `JustAfterEach` into two

File: tests/integration/component.go (hunk 2 above)
Comment (kadel) [reply tests/integration/component.go]: then this should be an additional test case.

**Comment by kadel** [comment]
The test is failing on MacOS for me :-( 
```
[odo]  ✗  ../../../../../../private/var/folders/0l/m50bc_nj27lf8pbd_sdv_7h40000gn/T/312706099/sb.jar binary needs to be inside of the context directory (/var/folders/0l/m50bc_nj27lf8pbd_sdv_7h40000gn/T/symLink)
```

**Comment by kadel** [comment]
> The test is failing on MacOS for me :-(
> 
> ```
> [odo]  ✗  ../../../../../../private/var/folders/0l/m50bc_nj27lf8pbd_sdv_7h40000gn/T/3127
> ```
 sorry, I have been running tests with old binary 😬 without the fix. With correct binary there is no such error.

**Comment by mik-dass** [comment]
@kadel Done

File: tests/integration/component.go [hunk 5]
```diff
@@ -712,4 +713,72 @@ func componentTests(args ...string) {
...
+			// Delete the component
+			helper.CmdShouldPass("odo", "delete", "sb-jar-test", "-f", "--context", symLinkPath)
+		})
+
+		It("Should be able to deploy a wildfly war file using symlinks in some odo commands", func() {
+			// create a symlink
+			symLinkName := helper.RandString(10)
+			helper.SymLink(filepath.Base(context), symLinkName)
+			symLinkPath := filepath.Join(filepath.Dir(context), symLinkName)
+			symLinkPaths = append(symLinkPaths, symLinkPath)
```
Comment (amitkrout) [inline tests/integration/component.go]: Same create symlink steps are being executed in both the spec. Move it to ```JustBeforeEach```. BTW symlink create is a pre setup for test to run, so keep it in ```JustBeforeEach```

+1 for removing symlink in ```JustAfterEach```

File: tests/integration/component.go [hunk 6]
```diff
@@ -712,4 +713,72 @@ func componentTests(args ...string) {
...
+
+	Context("Creating component using symlink", func() {
+		JustBeforeEach(func() {
+			project = helper.CreateRandProject()
+			originalDir = helper.Getwd()
+			helper.Chdir(filepath.Dir(context))
+		})
+		JustAfterEach(func() {
+			// remove the symlinks
+			for _, symLinkPath := range symLinkPaths {
```
Comment (amitkrout) [inline tests/integration/component.go]: Race condition will be hit In parallel run in case both the spec runs in same time. Instead of string slice use simple string type.

File: tests/integration/component.go [hunk 7]
```diff
@@ -712,4 +713,72 @@ func componentTests(args ...string) {
 			Expect(stdError).To(ContainSubstring("quantities must match the regular expression"))
 		})
 	})
+
+	Context("Creating component using symlink", func() {
+		JustBeforeEach(func() {
+			project = helper.CreateRandProject()
+			originalDir = helper.Getwd()
+			helper.Chdir(filepath.Dir(context))
```
Comment (amitkrout) [inline tests/integration/component.go]: Unnecessarily changing the dir, right ? Without changing the dir it should work.

File: tests/integration/component.go [hunk 8]
```diff
@@ -712,4 +713,72 @@ func componentTests(args ...string) {
...
+			// Create a URL and push without using the symlink
+			helper.CmdShouldPass("odo", "url", "create", "uberjaropenjdk", "--port", "8080", "--context", symLinkPath)
+			helper.CmdShouldPass("odo", "push", "--context", symLinkPath)
+			routeURL := helper.DetermineRouteURL(symLinkPath)
+
+			// Ping said URL
+			helper.HttpWaitFor(routeURL, "HTTP Booster", 90, 1)
+
+			// Delete the component
+			helper.CmdShouldPass("odo", "delete", "sb-jar-test", "-f", "--context", symLinkPath)
```
Comment (amitkrout) [inline tests/integration/component.go]: It would be great it you add one more validation steps 
```
helper.CmdShouldPass("odo", append(args, "delete", "-f", "--all", "--context", symLinkPath)...)
```

File: tests/integration/component.go [hunk 9]
```diff
@@ -712,4 +713,72 @@ func componentTests(args ...string) {
...
+			// create a symlink
+			symLinkName := helper.RandString(10)
+			helper.SymLink(filepath.Base(context), symLinkName)
+			symLinkPath := filepath.Join(filepath.Dir(context), symLinkName)
+			symLinkPaths = append(symLinkPaths, symLinkPath)
+
+			helper.CopyExample(filepath.Join("binary", "java", "openjdk"), context)
+
+			// create the component using symlink
+			helper.CmdShouldPass("odo", "create", "java:8", "sb-jar-test", "--project",
```
Comment (amitkrout) [inline tests/integration/component.go]: Can you please follow the format like
```
helper.CmdShouldPass("odo", append(args, "create", "java:8", "sb-jar-test", "--project", project, "--binary", filepath.Join(symLinkPath, "sb.jar"), "--context", symLinkPath)...)
```
and replace the same format in remaining occurrence

**Comment by mik-dass** [comment]
@amitkrout fixed

**Comment by mik-dass** [comment]
```
✗  Waiting for component to start [4m]
[odo]  ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=my-component-app'
```
/retest

**Comment by amitkrout** [comment]
On win10
```
+ Failure in Spec Setup (JustBeforeEach) [0.002 seconds]
odo component command tests
C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_test.go:13
  Creating component using symlink
  C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:717
    Should be able to deploy a wildfly war file using symlinks in some odo commands [JustBeforeEach]
    C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:759

    Unexpected error:
        <*os.LinkError | 0xc00004ab80>: {
            Op: "symlink",
            Old: "C:\\Users\\Admin\\AppData\\Local\\Temp\\951734598",
            New: "C:\\Users\\Admin\\AppData\\Local\\Temp\\gxvauchjzk",
            Err: 0x522,
        }
        symlink C:\Users\Admin\AppData\Local\Temp\951734598 C:\Users\Admin\AppData\Local\Temp\gxvauchjzk: A required privilege is not held by the client.   
    occurred

    C:/Users/Admin/go/src/github.com/openshift/odo/tests/helper/helper_filesystem.go:172
```
@mik-dass Can you please check what went wrong on win10 setup while creating symlink.

**Comment by mik-dass** [comment]
```
 containers exited
 Container setup exited with code 1, reason Error
---
Lease acquired, installing...
Installing from release registry.svc.ci.openshift.org/ci-op-hs9tcmzm/release@sha256:53b6c3df841449374c9d0e3a13ad2455bbc3b290307a448e49cc475f154b1a85
level=fatal msg="failed to fetch Terraform Variables: failed to fetch dependency of \"Terraform Variables\": failed to fetch dependency of \"Bootstrap Ignition Config\": failed to fetch dependency of \"Common Manifests\": failed to generate asset \"DNS Config\": getting public zone for \"origin-ci-int-aws.dev.rhcloud.com\": listing hosted zones: Throttling: Rate exceeded\n\tstatus code: 400, request id: ea489559-d988-4a3d-bfe6-9816524f2379"
---
```
/retest

**Comment by amitkrout** [comment]
> On win10
> 
> ```
> + Failure in Spec Setup (JustBeforeEach) [0.002 seconds]
> odo component command tests
> C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_test.go:13
>   Creating component using symlink
>   C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:717
>     Should be able to deploy a wildfly war file using symlinks in some odo commands [JustBeforeEach]
>     C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:759
> 
>     Unexpected error:
>         <*os.LinkError | 0xc00004ab80>: {
>             Op: "symlink",
>             Old: "C:\\Users\\Admin\\AppData\\Local\\Temp\\951734598",
>             New: "C:\\Users\\Admin\\AppData\\Local\\Temp\\gxvauchjzk",
>             Err: 0x522,
>         }
>         symlink C:\Users\Admin\AppData\Local\Temp\951734598 C:\Users\Admin\AppData\Local\Temp\gxvauchjzk: A required privilege is not held by the client.   
>     occurred
> 
>     C:/Users/Admin/go/src/github.com/openshift/odo/tests/helper/helper_filesystem.go:172
> ```
> 
> @mik-dass Can you please check what went wrong on win10 setup while creating symlink.

@mik-dass I have gone through the articles [1], [2] that you shared with me. To create symlink on platform like Windows, go library need elevated privileges to access the system file. Currently test script on windows fails to create symlink because of same reason. However these symlink scenario went fine when i run the test on PowerShell terminal having admin privilege. 

I guess there should be some flag in ginkgo to skip test scenario in ```Context``` level, if yes then we can use it (BTW i have created an issue in ginkgo - https://github.com/onsi/ginkgo/issues/615 asking the same question)

@mik-dass Do you have any suggestion until the proper solution comes ?

[1] https://social.technet.microsoft.com/Forums/windows/en-US/6097d64f-882d-4fa1-860e-8156b99bde16/how-can-i-get-permission-to-create-a-symbolic-link?forum=w8itprosecurity
[2] https://superuser.com/questions/839580/how-can-i-create-symbolic-links-in-windows-8-1-without-an-admin-command-prompt

**Comment by amitkrout** [comment]
> > On win10
> > ```
> > + Failure in Spec Setup (JustBeforeEach) [0.002 seconds]
> > odo component command tests
> > C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_test.go:13
> >   Creating component using symlink
> >   C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:717
> >     Should be able to deploy a wildfly war file using symlinks in some odo commands [JustBeforeEach]
> >     C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:759
> > 
> >     Unexpected error:
> >         <*os.LinkError | 0xc00004ab80>: {
> >             Op: "symlink",
> >             Old: "C:\\Users\\Admin\\AppData\\Local\\Temp\\951734598",
> >             New: "C:\\Users\\Admin\\AppData\\Local\\Temp\\gxvauchjzk",
> >             Err: 0x522,
> >         }
> >         symlink C:\Users\Admin\AppData\Local\Temp\951734598 C:\Users\Admin\AppData\Local\Temp\gxvauchjzk: A required privilege is not held by the client.   
> >     occurred
> > 
> >     C:/Users/Admin/go/src/github.com/openshift/odo/tests/helper/helper_filesystem.go:172
> > ```
> > 
> > 
> > @mik-dass Can you please check what went wrong on win10 setup while creating symlink.
> 
> @mik-dass I have gone through the articles [1], [2] that you shared with me. To create symlink on platform like Windows, go library need elevated privileges to access the system file. Currently test script on windows fails to create symlink because of same reason. However these symlink scenario went fine when i run the test on PowerShell terminal having admin privilege.
> 
> I guess there should be some flag in ginkgo to skip test scenario in `Context` level, if yes then we can use it (BTW i have created an issue in ginkgo - [onsi/ginkgo#615](https://github.com/onsi/ginkgo/issues/615) asking the same question)
> 
> @mik-dass Do you have any suggestion until the proper solution comes ?
> 
> [1] https://social.technet.microsoft.com/Forums/windows/en-US/6097d64f-882d-4fa1-860e-8156b99bde16/how-can-i-get-permission-to-create-a-symbolic-link?forum=w8itprosecurity
> [2] https://superuser.com/questions/839580/how-can-i-create-symbolic-links-in-windows-8-1-without-an-admin-command-prompt

@mik-dass https://github.com/onsi/ginkgo/issues/615#issuecomment-546284211

**Comment by mik-dass** [comment]
@amitkrout I have skipped the tests on windows for now

File: tests/integration/component.go [hunk 10]
```diff
@@ -712,4 +712,67 @@ func componentTests(args ...string) {
 			Expect(stdError).To(ContainSubstring("quantities must match the regular expression"))
 		})
 	})
+
+	Context("Creating component using symlink", func() {
+		var symLinkPath string
+
+		JustBeforeEach(func() {
+			if runtime.GOOS == "windows" {
```
Comment (amitkrout) [inline tests/integration/component.go]: PS C:\Users\Admin\go\src\github.com\openshift\odo> make test-cmd-cmp
The system cannot find the path specified.
'grep' is not recognized as an internal or external command,
operable program or batch file.
ginkgo -v -randomizeAllSpecs -slowSpecThreshold=120 -timeout 7200s -nodes=1 -focus="odo component command tests" tests/integration/
Running Suite: Integration Suite
================================
Random Seed: 1572342873 - Will randomize all specs
Will run 2 of 55 specs

SSSSSSSSSSSSSSSSSS
------------------------------
odo component command tests Creating component using symlink 
  Should be able to deploy a wildfly war file using symlinks in some odo commands
  C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:763
Created dir: C:\Users\Admin\AppData\Local\Temp\921376195
Deleting dir: C:\Users\Admin\AppData\Local\Temp\921376195

S [SKIPPING] in Spec Setup (JustBeforeEach) [0.004 seconds]
odo component command tests
C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_test.go:13
  Creating component using symlink
  C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:718
    Should be able to deploy a wildfly war file using symlinks in some odo commands [JustBeforeEach]
    C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:763

    skipping on windows because of admin issue in go library

    C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:723
------------------------------
SSSSSSSSSSSS
------------------------------
odo component command tests Creating component using symlink 
    C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:742

    skipping on windows because of admin issue in go library

    C:/Users/Admin/go/src/github.com/openshift/odo/tests/integration/component.go:723
------------------------------
SSSSSSSSSSSSSSSSSSSSSSS
Ran 0 of 55 Specs in 0.914 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 55 Skipped
PASS

Ginkgo ran 1 suite in 6.150263s
Test Suite Passed
PS C:\Users\Admin\go\src\github.com\openshift\odo>
/approve

File: tests/integration/component.go [hunk 11]
```diff
@@ -712,4 +712,67 @@ func componentTests(args ...string) {
...
+				Skip("skipping on windows because of admin issue in go library")
```
Comment (amitkrout) [inline tests/integration/component.go]: @mik-dass Can you please update the message to -  ```Skipping test because symlink creation on platform like Windows, go library need elevated privileges to access the system file.```

**Comment by mik-dass** [comment]
```
level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
```
/retest

File: tests/integration/component.go [hunk 12]
```diff
@@ -712,4 +712,67 @@ func componentTests(args ...string) {
 			Expect(stdError).To(ContainSubstring("quantities must match the regular expression"))
 		})
 	})
+
+	Context("Creating component using symlink", func() {
+		var symLinkPath string
+
+		JustBeforeEach(func() {
+			if runtime.GOOS == "windows" {
+				Skip("Skipping test because for symlink creation on platform like Windows, go library needs elevated privileges.")
```
Comment (amitkrout) [inline tests/integration/component.go]: +1

**Comment by mik-dass** [comment]
```
should show the version of odo major components including server login URL [It]
    /go/src/github.com/openshift/odo/tests/integration/generic_test.go:271
     Expected
      
        <bool>: false
    to be true
```
/retest

**Comment by amitkrout** [comment]
> ```
> should show the version of odo major components including server login URL [It]
>     /go/src/github.com/openshift/odo/tests/integration/generic_test.go:271
>      Expected
>       
>         <bool>: false
>     to be true
> ```
> 
> /retest

#2329

**Comment by mik-dass** [comment]
@amitkrout rebased

**Comment by mik-dass** [comment]
```
I1104 12:23:48.471984   18364 cmdutils.go:48] Error:
[odo] unable to set current project toclutgmvnfk: unable to switch to clutgmvnfk project: Error loading config file "/home/travis/.kube/config": v1.Config.AuthInfos: []v1.NamedAuthInfo: v1.NamedAuthInfo.AuthInfo: v1.AuthInfo.ClientCertificateData: decode base64: illegal base64 data at input byte 1440, error found in #10 byte of ...|ks1OUIxM2"}}]}|..., bigger context ...|Es0by93YWQ1UXFERThtWUxQTWFJaDMKOFRJRC8yYks1OUIxM2"}}]}|...
[odo]  ✗  Error loading config file "/home/travis/.kube/config": v1.Config.AuthInfos: []v1.NamedAuthInfo: v1.NamedAuthInfo.AuthInfo: v1.AuthInfo.ClientCertificateData: decode base64: illegal base64 data at input byte 1440, error found in #10 byte of ...|ks1OUIxM2"}}]}|..., bigger context
```
/retest

**Comment by mik-dass** [comment]
```
  Waiting for component to start [4m]
[odo]  ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=nodejs-push-atonce-nodejs-create-now-test'
```
/retest

**Comment by mik-dass** [comment]
```
✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=python-app'
[odo]  ✗  Waiting for component to start [4m]
```
/retest

**Comment by mik-dass** [comment]
```
level=fatal msg="Terraform destroy: failed to destroy using Terraform"
2019/11/12 17:28:33 Container setup in pod integration failed, exit code 1, reason Error
Another process exited
2019/11/12 17:28:43 Container test in pod integration failed, exit code 1, reason Error
2019/11/12 17:51:45 Copied 9.77Mi of artifacts from integration to /logs/artifacts/integration
2019/11/12 17:51:47 Ran for 50m8s
2019/11/12 17:51:48 Submitted failure event to sentry (id=da880703f572472784ba2511021c590e)
error: could not run steps: step integration failed: template pod "integration" failed: the pod ci-op-vz97j4gy/integration failed after 45m54s (failed containers: setup, test): ContainerFailed one or more containers exited
```
/retest
