### PR TITLE
repeated check for deleted dir in odo watch test

### LINKED ISSUE #5044: [ flake ] odo watch fails on IBMCloud
/kind failing-test
/area testing

## What versions of software are you using?

**Operating System:** fedora

**Output of `odo version`:** 
 odo version
odo v2.3.0 (8ad4b0921)

##How did you run odo exactly?
make test-integration-devfile fails for `odo watch` as it takes time for changes to take place.

##Actual behavior
Test fails for `odo watch` as it takes time for changes to take place in the container. 

##Expected behavior
Test should pass without failure

```
��� Failure [70.780 seconds]

odo devfile watch command tests
  when executing odo watch after odo push
    should listen for file changes [It]


    Expected
        <string>: total 72
        4849689 drwxrwsrwx.  6 root       1007960000  4096 Sep  6 06:50 .
        3704750 dr-xr-xr-x.  1 root       root        4096 Sep  6 06:49 ..
        4850623 drwxr-s---.  2 1007960000 1007960000  4096 Sep  6 06:49 .abc
        4849726 -rw-------.  1 1007960000 1007960000    34 Sep  6 06:49 .gitignore
        4850624 -rw-r--r--.  1 1007960000 1007960000     0 Sep  6 06:49 a.txt
        4850625 drwxr-s---.  2 1007960000 1007960000  4096 Sep  6 06:49 abcd
        4849727 -rw-------.  1 1007960000 1007960000  2701 Sep  6 06:49 config
        4849718 -rw-r--r--.  1 1007960000 1007960000  1088 Sep  6 06:49 devfile.yaml
        4849728 drwxr-sr-x. 67 1007960000 1007960000  4096 Sep  6 06:49 node_modules
        4849729 -rw-r--r--.  1 1007960000 1007960000 18992 Sep  6 06:49 package-lock.json
        4849719 -rw-r--r--.  1 1007960000 1007960000   395 Sep  6 06:49 package.json
        4849720 -rw-r--r--.  1 1007960000 1007960000   195 Sep  6 06:49 preference.yaml
        4849721 -rw-r--r--.  1 1007960000 1007960000  1911 Sep  6 06:49 server.js
        4849723 drwxr-sr-x.  2 1007960000 1007960000  4096 Sep  6 06:49 test

    not to contain substring

        <string>: abcd
```

### PR DESCRIPTION
**Pull request by anandrkskd**
Signed-off-by: anandrkskd <anandrkskd@gmail.com>

**What type of PR is this?**

/kind flake

**What does this PR do / why we need it**:
This Pr fixes flake for odo watch test 

**Which issue(s) this PR fixes**:

Fixes #5044

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by anandrkskd** [comment]
/test psi-unit-test-mac
unit test failed as it was disabled at that time.

File: tests/integration/devfile/utils/utils.go [hunk 1]
```diff
@@ -532,7 +532,12 @@ func validateContainerExecListDir(odoV1Watch OdoV1Watch, odoV2Watch OdoV2Watch,
 			}
 			cliRunner := runner.(helper.CliRunner)
 			podName := cliRunner.GetRunningPodNameByComponent(odoV2Watch.CmpName, project)
-			stdOut = cliRunner.ExecListDir(podName, project, folderToCheck)
+
+			Eventually(func() bool {
```
Comment (prietyc123) [inline tests/integration/devfile/utils/utils.go:536]: Can we use our predefined library for this repeated execution https://github.com/openshift/odo/blob/main/tests/helper/helper_generic.go#L41 . We have eventually inside that.

**Review by prietyc123 — CHANGES_REQUESTED** [review]

File: tests/integration/devfile/utils/utils.go [hunk 2]
```diff
@@ -532,7 +532,14 @@ func validateContainerExecListDir(odoV1Watch OdoV1Watch, odoV2Watch OdoV2Watch,
 			}
 			cliRunner := runner.(helper.CliRunner)
 			podName := cliRunner.GetRunningPodNameByComponent(odoV2Watch.CmpName, project)
+
+			helper.WaitForCmdOut("oc", []string{"exec", podName, "--namespace", project,
```
Comment (prietyc123) [inline tests/integration/devfile/utils/utils.go:536]: This will fail for `kubernetes`, no? We have `WaitForRunnerCmdOut` function for oc and kubernetes both.

**Review by prietyc123 — CHANGES_REQUESTED** [review]

File: tests/integration/devfile/utils/utils.go [hunk 3]
```diff
@@ -521,31 +521,34 @@ func OdoWatchWithIgnore(odoV2Watch OdoV2Watch, context, flag string) {
...
+	cliRunner := runner.(helper.CliRunner)
 	switch platform {
 	case "kube":
 		if isDevfileTest {
-			folderToCheck := "/projects"
+			folderToCheck = "/projects"
 			if odoV2Watch.FolderToCheck != "" {
 				folderToCheck = odoV2Watch.FolderToCheck
 			}
 			cliRunner := runner.(helper.CliRunner)
```
Comment (prietyc123) [inline tests/integration/devfile/utils/utils.go:533]: I think you missed removing `cliRunner` from here, no?

**Review by prietyc123 — CHANGES_REQUESTED** [review]

File: tests/integration/devfile/utils/utils.go (hunk 3 above)
Comment (anandrkskd) [reply tests/integration/devfile/utils/utils.go:533]: yes updating

Comment (anandrkskd) [reply tests/integration/devfile/utils/utils.go]: Updated
