### PR TITLE
Fixing e2e vs integration test naming

### LINKED ISSUE #1780: Cleanup test naming - e2e vs integration
There is still a lot of places (like Makefile, or names of Describe blocks) where integration tests are named as e2e or have e2e in the name.
This should be cleaned to make it clear that those are two different tests approaches.

/kind bug
/area testing
/priority medium
/project Sprint 168

### PR DESCRIPTION
**Pull request by amitkrout**
## Was the change discussed in an issue?
related to #1780

## How to test changes?

Review the change properly

### CODE REVIEW

**Comment by kadel** [comment]
ping @amitkrout

File: Makefile [hunk 1]
```diff
@@ -114,76 +114,81 @@ test-generic:
...
-test-e2e-scenarios:
+# Run all e2e test scenarios
+.PHONY: test-e2e-all
+test-e2e-all:
 	go test -v github.com/openshift/odo/tests/e2escenarios -ginkgo.slowSpecThreshold=$(SLOW_SPEC_THRESHOLD) -ginkgo.v -timeout $(TIMEOUT)
 
+# Run core beta flow e2e tests
+.PHONY: test-e2e-beta
+test-e2e-beta:
+	go test -v github.com/openshift/odo/tests/e2escenarios --ginkgo.focus="odo core beta flow" -ginkgo.slowSpecThreshold=$(SLOW_SPEC_THRESHOLD) -ginkgo.v -timeout $(TIMEOUT)
```
Comment (kadel) [inline Makefile]: why `go test` here but other commands use `ginkgo` ?

File: scripts/openshiftci-presubmit-e2etests.sh [hunk 2]
```diff
@@ -12,5 +12,7 @@ make bin
 export PATH="$PATH:$(pwd)"
 export CUSTOM_HOMEDIR="/tmp/artifacts"
 
-make test-e2e-scenarios
+make test-e2e-beta
```
Comment (kadel) [inline scripts/openshiftci-presubmit-e2etests.sh]: wouldn't it be better to use `make test-e2e-all` to make sure that new e2e scenarios are executed once added?

Comment (amitkrout) [reply scripts/openshiftci-presubmit-e2etests.sh]: +1

File: Makefile (hunk 1 above)
Comment (amitkrout) [reply Makefile]: Yup, will fix those.

File: tests/integration/json_test.go [hunk 3]
```diff
@@ -1,114 +0,0 @@
-package integration
```
Comment (kadel) [inline tests/integration/json_test.go]: why was this removed?

File: docs/development.adoc [hunk 4]
```diff
@@ -179,234 +179,159 @@ $ MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --extra-clusterup-flags "--ena
...
-----
+* Don’t create new test file for issues(bug) and try to add some scenario for each bug fix if applicable
 +
 
-Run generic integration tests
-+
-----
-$ TEST_EXEC_NODES=1 make test-generic
-----
+* Don’t use unnecessary text validation in `Expect` of certain command output.
```
Comment (kadel) [inline docs/development.adoc]: What do you mean by this?

**Comment by cdrage** [comment]
This looks good to me with the exception of the missing json tests :(

File: tests/integration/json_test.go (hunk 3 above)
Comment (amitkrout) [reply tests/integration/json_test.go]: @kadel @cdrage ```-o json``` is tested as a flag to supported command but should not be a test file. For example 

we have already a test file ```cmd_app_test``` where most of the app related command is validated. So it's better to test the ```-o json``` flag along with this test file instead of making the same scenario in a different file along with the ```-o json``` flag. See - https://github.com/openshift/odo/blob/master/tests/integration/cmd_app_test.go#L69 where it has been implemented.

Advantage - 
1. No duplicate scenario in separate file
2. Reduces total test time
3. Later it will be easy to manage and maintain json flag test along with the supported command

So i removed the file but not its scenario. I add all the ```-o json``` flag scenario in the respective test file.

**Comment by amitkrout** [comment]
> This looks good to me with the exception of the missing json tests :(

https://github.com/openshift/odo/pull/1878#discussion_r315534264

File: docs/development.adoc [hunk 5]
```diff
@@ -179,234 +179,169 @@ $ MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --extra-clusterup-flags "--ena
...
-----
+* Don’t create new test file for issues(bug) and try to add some scenario for each bug fix if applicable
 +
 
-Run generic integration tests
-+
-----
-$ TEST_EXEC_NODES=1 make test-generic
-----
+* Don’t use unnecessary text validation in `Expect` of certain command output. Only validation of key text specific to that scenario would be enough.
```
Comment (amitkrout) [inline docs/development.adoc]: @kadel Does it now make sense ?

File: docs/development.adoc (hunk 4 above)
Comment (amitkrout) [reply docs/development.adoc]: https://github.com/openshift/odo/pull/1878#discussion_r315548910

**Comment by boczkowska** [comment]
The docs themselves look good to me
/lgtm

File: tests/integration/json_test.go (hunk 3 above)
Comment (cdrage) [reply tests/integration/json_test.go]: IMO it's nice to have it in it's own machine-readable-output testing file... it's an essential part of `odo` and having to go through a bunch of other files just to find where to put `-o json` tests would be cumbersome. I agree with @kadel  that we should not be deleting this file.

Comment (amitkrout) [reply tests/integration/json_test.go]: > IMO it's nice to have it in it's own machine-readable-output testing file... it's an essential part of odo and having to go through a bunch of other files just to find where to put -o json tests would be cumbersome. I agree with @kadel that we should not be deleting this file.

Right now keeping the test in separate file looks good because only few command/subcommands support machine readable output. The size of the file and duplicate scenarios will be increased for sure once all the task of issue https://github.com/openshift/odo/issues/1739 is fixed

The way to handle it smartly without duplicating the scenario in separate file

cmd_app_test.go
```
Context("when running app command without app parameter in directory that contains .odo config directory", func() {
	It("should successfully execute list, describe and delete", func() {
	    helper.CopyExample(filepath.Join("source", "nodejs"), context)
		helper.CmdShouldPass("odo", "component", "create", "nodejs", cmpName, "--app", appName, "--project", project, "--context", context)
		helper.CmdShouldPass("odo", "push", "--context", context)

		appListOutput := helper.CmdShouldPass("odo", "app", "list")
		Expect(appListOutput).To(ContainSubstring(appName))
		
		helper.CmdShouldPass("odo", "app", "describe")
		
		helper.CmdShouldPass("odo", "app", "delete", "-f")
	})
})
```
Let see how the machine readable output will be add without hurting the core app test
```
Context("when running app command without app parameter in directory that contains .odo config directory", func() {
	It("should successfully execute list, describe and delete along with machine readable output", func() {
	    helper.CopyExample(filepath.Join("source", "nodejs"), context)
		helper.CmdShouldPass("odo", "component", "create", "nodejs", cmpName, "--app", appName, "--project", project, "--context", context)
		helper.CmdShouldPass("odo", "push", "--context", context)

		appListOutput := helper.CmdShouldPass("odo", "app", "list")
		Expect(appListOutput).To(ContainSubstring(appName))
		actualCompListJSON := helper.CmdShouldPass("odo", "list", "-o", "json")
		desiredCompListJSON := fmt.Sprintf(`{"kind":"List","apiVersion":"odo.openshift.io/v1alpha1","metadata":{},"items":[{"kind":"Component","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"nodejs","creationTimestamp":null, "namespace":"%s"},"spec":{"type":"nodejs","app":"app","source":"file://./"},"status":{"state":"Pushed"}}]}`, project)
		Expect(desiredCompListJSON).Should(MatchJSON(actualCompListJSON))

		helper.CmdShouldPass("odo", "app", "describe")
		desiredDesAppJSON := fmt.Sprintf(`{"kind":"app","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"myapp","namespace":"%s","creationTimestamp":null},"spec":{}}`, project)
		actualDesAppJSON := helper.CmdShouldPass("odo", "app", "describe", "myapp", "-o", "json")
		Expect(desiredDesAppJSON).Should(MatchJSON(actualDesAppJSON))

		helper.CmdShouldPass("odo", "app", "delete", "-f")
	})
})
```

Moreover it will be easy to test ```-o``` flag on those existing variety of scenarios of supported command.

**Comment by amitkrout** [comment]
> Just doing a "request changes" review so it doesn't get merged by accident. But I don't think we should be moving the machine readable output commands to different files (see my above comments)
> 
> /hold

https://github.com/openshift/odo/pull/1878#discussion_r316100540

**Comment by amitkrout** [comment]
> The docs themselves look good to me
> /lgtm

Thanks for doc side review.

File: tests/integration/json_test.go (hunk 3 above)
Comment (kadel) [reply tests/integration/json_test.go]: @amitkrout got a point there. It might be good to have the json output in a test together with the command. 
 - It will reduce the number of tests
 - It makes logical sense, you have only one test setup, and than just execute both commands (with `-o` and  without `-o`)
 - Json output doesn't need any special place, it is just a regular command with different output format.

File: docs/development.adoc (hunk 5 above)
Comment (kadel) [reply docs/development.adoc]: Still, don't know what you are trying to say :-(

Comment (amitkrout) [reply docs/development.adoc]: Don’t use unnecessary text validation in `Expect` of certain command output. In `Expect` only validation of key text specific of that scenario would be enough.
```
For example:
While running multiple push on same component without changing any source file.

// No text validation is required
helper.CmdShouldPass("odo", "push", "--context", context+"/nodejs-ex")
// only validating the particular text key to this scenario
output := helper.CmdShouldPass("odo", "push", "--context", context+"/nodejs-ex")
Expect(output).To(ContainSubstring("No file changes detected, skipping build"))
```

@kadel Please check, this could be helpful. You can suggest me a better phrase also

**Comment by kadel** [comment]
hey @cdrage does the discussion at https://github.com/openshift/odo/pull/1878#discussion_r316100540 answers your questions?

/approve

File: scripts/openshiftci-presubmit-e2etests.sh (hunk 2 above)
Comment (kadel) [reply scripts/openshiftci-presubmit-e2etests.sh]: shouldn't this use `test-e2e-all`?

**Comment by amitkrout** [comment]
```
2019/09/03 16:00:02 error: unable to retrieve artifacts from pod benchmark: could not read gzipped artifacts: container artifacts is not valid for pod benchmark
2019/09/03 16:00:07 error: could not wait for pod 'benchmark': it is no longer present on the cluster (usually a result of a race or resource pressure. re-running the job should help)
2019/09/03 16:00:08 Ran for 59m47s
2019/09/03 16:00:08 Submitted failure event to sentry (id=49dc56d846734b268dffbd0fdb8bd884)
error: could not run steps: step benchmark failed: template pod "benchmark" failed: pod was deleted while ci-operator step was waiting for it
```
/retest

**Comment by amitkrout** [comment]
```
[odo]  ✗  Failed To Update Config To Component Deployed
[odo]  ✗  Applying configuration [57s]
```
/test integration

**Comment by amitkrout** [comment]
```
odo sub component command tests when component is in the current directory and --project flag is used 
  creates and pushes local nodejs component and then deletes --all
  /go/src/github.com/openshift/odo/tests/integration/component.go:329
 Created dir: /tmp/724815433
Creating a new project: texjxuxufc
Running odo with args [odo project create texjxuxufc -w -v4]
[odo] I0904 13:18:24.552396   19818 preference.go:118] The path for preference file is /tmp/724815433/config.yaml
[odo] I0904 13:18:24.552472   19818 occlient.go:479] Trying to connect to server api.ci-op-d1whffy3-f09f4.origin-ci-int-aws.dev.rhcloud.com:6443
[odo] I0904 13:18:24.567450   19818 occlient.go:486] Server https://api.ci-op-d1whffy3-f09f4.origin-ci-int-aws.dev.rhcloud.com:6443 is up
[odo] I0904 13:18:24.631580   19818 occlient.go:409] isLoggedIn err:  <nil> 
[odo]  output: "developer"
[odo]  •  Waiting for project to come up  ...
[odo]  ✓  Waiting for project to come up [353ms]
[odo]  ✓  Project 'texjxuxufc' is ready for use
[odo]  ✓  New project created and now using project : texjxuxufc
[odo] I0904 13:18:25.006691   19818 odo.go:70] Could not get the latest release information in time. Never mind, exiting gracefully :)
Current working dir: /go/src/github.com/openshift/odo/tests/integration
Setting current dir to: /tmp/724815433
Running odo with args [odo component create nodejs my-component --app app --project texjxuxufc --env key=value,key1=value1]
[odo]  •  Validating component  ...
[odo]  ✓  Validating component [37ms]
[odo] Please use `odo push` command to create the component with source deployed



[odo] 
Running odo with args [odo component push --context /tmp/724815433]
[odo]  ✗  invalid configuration: [context was not found for specified context: jgjryhzmbp/api-ci-op-d1whffy3-f09f4-origin-ci-int-aws-dev-rhcloud-com:6443/developer, cluster has no server defined]
[odo] Please login to your server: 
[odo] 
[odo] odo login https://mycluster.mydomain.com



[odo] 
Setting current dir to: /go/src/github.com/openshift/odo/tests/integration
Deleting project: texjxuxufc
Running odo with args [odo project delete texjxuxufc -f]
[odo]  •  Deleting project texjxuxufc  ...
[odo]  ✓  Deleting project texjxuxufc [5s]
[odo]  ✓  Deleted project : texjxuxufc
Deleting dir: /tmp/724815433
 • Failure [6.659 seconds]
odo sub component command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_sub_test.go:13
  when component is in the current directory and --project flag is used
  /go/src/github.com/openshift/odo/tests/integration/component.go:306
    creates and pushes local nodejs component and then deletes --all [It]
    /go/src/github.com/openshift/odo/tests/integration/component.go:329
     No future change is possible.  Bailing out early after 0.102s.
      
    Running odo with args [odo component push --context /tmp/724815433]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
     /go/src/github.com/openshift/odo/tests/helper/helper_run.go:32
```
Could be a potential flake
/test integration

**Comment by amitkrout** [comment]
> ```
> odo sub component command tests when component is in the current directory and --project flag is used 
>   creates and pushes local nodejs component and then deletes --all
>   /go/src/github.com/openshift/odo/tests/integration/component.go:329
>  Created dir: /tmp/724815433
> Creating a new project: texjxuxufc
> Running odo with args [odo project create texjxuxufc -w -v4]
> [odo] I0904 13:18:24.552396   19818 preference.go:118] The path for preference file is /tmp/724815433/config.yaml
> [odo] I0904 13:18:24.552472   19818 occlient.go:479] Trying to connect to server api.ci-op-d1whffy3-f09f4.origin-ci-int-aws.dev.rhcloud.com:6443
> [odo] I0904 13:18:24.567450   19818 occlient.go:486] Server https://api.ci-op-d1whffy3-f09f4.origin-ci-int-aws.dev.rhcloud.com:6443 is up
> [odo] I0904 13:18:24.631580   19818 occlient.go:409] isLoggedIn err:  <nil> 
> [odo]  output: "developer"
> [odo]  •  Waiting for project to come up  ...
> [odo]  ✓  Waiting for project to come up [353ms]
> [odo]  ✓  Project 'texjxuxufc' is ready for use
> [odo]  ✓  New project created and now using project : texjxuxufc
> [odo] I0904 13:18:25.006691   19818 odo.go:70] Could not get the latest release information in time. Never mind, exiting gracefully :)
> Current working dir: /go/src/github.com/openshift/odo/tests/integration
> Setting current dir to: /tmp/724815433
> Running odo with args [odo component create nodejs my-component --app app --project texjxuxufc --env key=value,key1=value1]
> [odo]  •  Validating component  ...
> [odo]  ✓  Validating component [37ms]
> [odo] Please use `odo push` command to create the component with source deployed
> 
> 
> 
> [odo] 
> Running odo with args [odo component push --context /tmp/724815433]
> [odo]  ✗  invalid configuration: [context was not found for specified context: jgjryhzmbp/api-ci-op-d1whffy3-f09f4-origin-ci-int-aws-dev-rhcloud-com:6443/developer, cluster has no server defined]
> [odo] Please login to your server: 
> [odo] 
> [odo] odo login https://mycluster.mydomain.com
> 
> 
> 
> [odo] 
> Setting current dir to: /go/src/github.com/openshift/odo/tests/integration
> Deleting project: texjxuxufc
> Running odo with args [odo project delete texjxuxufc -f]
> [odo]  •  Deleting project texjxuxufc  ...
> [odo]  ✓  Deleting project texjxuxufc [5s]
> [odo]  ✓  Deleted project : texjxuxufc
> Deleting dir: /tmp/724815433
>  • Failure [6.659 seconds]
> odo sub component command tests
> /go/src/github.com/openshift/odo/tests/integration/cmd_cmp_sub_test.go:13
>   when component is in the current directory and --project flag is used
>   /go/src/github.com/openshift/odo/tests/integration/component.go:306
>     creates and pushes local nodejs component and then deletes --all [It]
>     /go/src/github.com/openshift/odo/tests/integration/component.go:329
>      No future change is possible.  Bailing out early after 0.102s.
>       
>     Running odo with args [odo component push --context /tmp/724815433]
>     Expected
>         <int>: 1
>     to match exit code:
>         <int>: 0
>      /go/src/github.com/openshift/odo/tests/helper/helper_run.go:32
> ```
> 
> Could be a potential flake
> /test integration

Issue created - #2088

**Comment by kadel** [comment]
After this gets merged you should open PR against release repo to stop using the old scripts 
- scripts/openshiftci-presubmit-e2e-scenarios.sh 
- scripts/openshiftci-presubmit-e2e.sh
